### ISSUE TITLE
Support BD menu

### ISSUE THREAD

**Issue by bitweng** [iina/iina#102]
选择盘片就能播放完整一张光盘，有菜单等选择。

**Comment by csujedihy** [comment]
This is not easy.

**Comment by HarukaMa** [comment]
This is a mpv issue, not IINA issue I'm afraid. mpv doesn't have bluray menu support at the moment.

iPhone$B$+$iAw?.(B

H29/01/08 15:23$B!"(BJedihy <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by lhc70000** [comment]
#55

**Comment by megabitsenmzq** [comment]
不支持menu也没关系的，只要能够按顺序播放，其实就足够了

**Comment by jelockwood** [comment]
VLC now supports playing Java Blu-Ray menus. Would the same library it uses be a help? As far as I can see VLC uses the standard libbluray

I have successfully used VLC (on Mac) to play various Blu-Ray discs and only those obviously older discs with presumably older style menus i.e. not Java did not work in terms of playing the menu.

**Comment by liyuxi** [comment]
> VLC now supports playing Java Blu-Ray menus. Would the same library it uses be a help? As far as I can see VLC uses the standard libbluray
> 
> I have successfully used VLC (on Mac) to play various Blu-Ray discs and only those obviously older discs with presumably older style menus i.e. not Java did not work in terms of playing the menu.

VLC now is playback bluray with BD-J ability

**Comment by liyuxi** [comment]
请将VLC的完整蓝光菜单（含BD-J）移植到IINA，VLC已经能全功能播放BD，蓝光中一些内容必须通过菜单调出，比如特别收录内容。

**Comment by HarukaMa** [comment]
I've failed to implement full libbluray functions into mpv. So either someone familiar with mpv contribute to us in a fork, or ask mpv to implement it directly. mpv states that they don't have enough interest in it, though.

(or better, contribute to them directly)
