### ISSUE TITLE
Support video recording

### ISSUE THREAD

**Issue by FezVrasta** [iina/iina#110]
A feature like the one provided by QuickTime to record your own screen or an area of it would be really nice.

Great player!

**Comment by lhc70000** [comment]
Thanks for feedback. Since actually screen recording has nothing to do with playback when it comes to development, we must do a lot of extra work if we want to support it.

QuickTime already has a perfect screen recording feature, so we're not going to reinvent the wheel, at least in next few releases. Why don't use QuickTime for screen recording and IINA for video playback? :p

**Comment by FezVrasta** [comment]
The idea was to replace QuickTime with INAA and forget that QuickTime ever existed 🙄

**Comment by joeynotjoe** [comment]
It's really easy to extract clips using [this script](https://github.com/Kagami/mpv_slicing/): 
It would be awesome to add that feature here. Also possible to add in extract to gif, possibly using [gifify](https://github.com/vvo/gifify) / [gifscicle](https://www.lcdf.org/gifsicle/).

**Comment by tucomel** [comment]
Quicktime cant play videos from web (like facebook or yt)
just like @joeynotjoe said, if I wanna make clips for gif or memes (why not)

**Comment by jukrb0x** [comment]
since it came up, hope this feature will be added soon.

**Comment by xxlyu-2046** [comment]
hope this feature will be added soon. +1

**Comment by joeynotjoe** [comment]
@jukrb0x @xxlyu-2046 I've been using this [encode script](https://github.com/occivink/mpv-scripts) for awhile now. Dev is a boss, and it works perfectly with IINA as well as MPV. Highly recommend checking it out.

If you need some assistance getting it set up for use with IINA, feel free to message me.

**Comment by bchkv** [comment]
@xxlyu-2046 @jukrb0x

I made up an instruction for video slicing akin to VLC

# Guide to Set Up Video Slicing in IINA
## 1. Download the MPV script

Get **slicing.lua** script from https://github.com/Kagami/mpv_slicing/tree/master

Place the **slicing.lua** script into the `~/.config/mpv/scripts` directory. If these directories do not exist, create them

## 2. Adjust the Script Configuration

### Set the Output Directory

  ``` lua
  target_dir = "/path/to/your/output/directory"
  ```

### Set the Encoding Parameters

To produce compressed files, set the following parameters in the script:
  ``` lua
  vcodec = "libx264"
  acodec = "aac"
  ext = "mp4"
  vf = "format=yuv420p$hqvf,scale=in_color_matrix=$matrix,format=bgr24"  -- optional
 ```

## Set up IINA 

Settings —> Advanced —> toggle Enable **Advanced Settings** 

Settings —> Advanced —> **Use config directory** —> toggle and set to the `~/.config/mpv/`

Settings —> Key Bindings —> Add key bindings for the script: 
- For video slicing put mpv command: `script-binding slicing_mark` 
- For audio slicing put: `slicing_audio` 

And choose preferable keys

**Comment by uiryuu** [comment]
IINA won't support video recording features, it's a mpv frontend after all. Please seek for other software to do such task.
