### ISSUE TITLE
Fullscreen player window not returning to front as it should

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [iina/iina#1157]
Neither of the recent updates have killed this bug.

When a video is playing in IINA, no matter what the window size is, pressing ⌘+Tab in an application you just swiched to _should_ return the player window to the front immediately.

Currently that only works if the player window is NOT fullscreen.

Same goes for clicking the Dock icon:
Clicking it once brings the player to the front ONLY if the window isn't fullscreen, otherwise it takes two clicks.

I watch most vids fullscreen, and often need to switch to other apps while they're playing or paused.
When I'm ready to continue watching them, I want to quickly bring the player to front, not have to mess around with multiple clicks on an icon.

- OS X 10.12.6
- IINA 0.0.14

**Expected behavior:**

I expect to be able to click the Dock icon ONCE to bring the player window (no matter what size) to the front so I may resume watching.

And I expect the ⌘+Tab shortcut to bring the player window (no matter what size) to the front so I may resume watching.

**Steps to reproduce:**

Play a video in anything other than fullscreen, and either let it play or pause it.

⌘+Tab to another app, then ⌘+Tab back to the player and it snaps  to the front as it should.

Then make the player fullscreen and ⌘+Tab to another app.

When you ⌘+Tab again, the player fails to snap to front, but IINA's menu populates the menu bar.
 
Pressing ⌘+Tab again only removes IINA's menu from the bar and replaces it with one for the app you were already in.

**How often does this happen?**

EVERY TIME.

**Comment by xjbeta** [comment]
You can report it to Apple.
The system applications have the same problem.

**Comment by GitTheHellOutaHere** [comment]
VLC doesn't function that way - it operates as expected.

Which means if it can do it, then so can mpv.

**Comment by alejx** [comment]
It's macOS' system behavior. If you really want to change this behavior, run `defaults write com.apple.dock workspaces-auto-swoosh -bool YES` in your terminal. Note that this will change all the behavior in your system.
