### ISSUE TITLE
playlist should be in numerical order

### ISSUE THREAD

**Issue by kelystor** [iina/iina#1190]
When I drag multiple files (or a folder contains multiple files) to IINA, it arranged files by aphabetical order.
e.g:

```
1 xxx.mp4
10 aaa.mp4
2 bbb.mp4
```

the order should be: 

```
1 xxx.mp4
2 bbb.mp4
10 aaa.mp4
```

**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.14.1

**Comment by inflation** [comment]
It is hard to determine whether sort by numerical or lexicographical order when you are dealing with arbitrary filenames. I suggest naming your files with leading 0's.

**Comment by yalva** [comment]
Should've a search option to trim down the list in playlist

**Comment by anohren** [comment]
@inflation, you don't have to decide

> localizedStandardCompare(_:)
> Compares strings as sorted by the Finder.

https://developer.apple.com/documentation/foundation/nsstring/1409742-localizedstandardcompare

**Comment by qaisjp** [comment]
Was this implemented?

**Comment by anohren** [comment]
See my linked issue for the commit where it was fixed
