### ISSUE TITLE
H.264 1080i issues

### ISSUE THREAD

**Issue by bunglemeister** [iina/iina#1238]
IINA seems to have problems correctly playing back h.264 1080i footage.

**System and IINA version:**

- macOS 10.13
- IINA 0.0.14.1

**Expected behavior:**
Smooth playback with no tearing. Correct vertical resolution displayed in the info dialogue for 1080i footage.

**Actual behavior:**
Tried to playback footage shot with an older camera. File format is .mov (h.264) shot in 1080i. IINA shows a resolution of 1072 pixels vertically (Quick Time Player shows the correct 1080) and the visual show tearing and weird artefacts. Same file plays just fine on Quick Time Player.

![screen shot 2017-11-20 at 11 54 37](https://user-images.githubusercontent.com/610340/33000156-b6d6d114-cde9-11e7-960e-b10ac003bbe3.jpg)

**Steps to reproduce:**
Open video footage shot in 1080i.

- [?] MPV does not have this problem.
What's MPV?

**How often does this happen?**
Every time

**Comment by inflation** [comment]
Did you turn on deinterlace?

**Comment by wonderwarthog** [comment]
No, I just opened the video via double-click (IINA is the default video player for everything on my Mac). When I opened the video in MPV (found the app btw) it played back just fine as is. So I think this should work without any user interaction ideally (since it does with Quick Time Player and MPV).

**Comment by atomicsaiko** [comment]
Can you post a MediaInfo output or provide a sample of the mov file?

**Comment by lizihan021** [comment]
Thanks for the great IINA player. I really like it, so I want to help improve it. 
Is this problem resolved? I met the same problem. My video was exported from Premiere Pro CC with:
- H.264, 1920*1080 (1.0), 29.97 fps, Upper, VBR, 1 pass, Target 10.00 Mbps, ACC.
When I play it with:
- IINA 0.0.14.1 Build 55
- Mac OS 10.13.1
There are tearing and glitches. 
<img width="869" alt="screen shot 2017-12-14 at 3 02 21 pm" src="https://user-images.githubusercontent.com/16623299/34012342-62f7dfa6-e0e1-11e7-8c44-b615159b7360.png">

**Comment by inflation** [comment]
@lizihan021 @wonderwarthog Could you attach any log when you play the video?

**Comment by bendingtime** [comment]
I have just discovered that disabling Hardware Acceleration fixes this issue.

**Comment by bunglemeister** [comment]
>disabling hardware acceleration

Well it's a workaround, not a fix ;-) But then there's this thing called battery life…

**Comment by alejx** [comment]
If this issue still persists, please consider reporting this issue to [mpv](https://github.com/mpv-player/mpv/issues) or [FFmpeg](https://ffmpeg.org/bugreports.html).
