### ISSUE TITLE
Migrating to an organization

### ISSUE THREAD

**Issue by saagarjha** [iina/iina#1318]
I've created an umbrella organization for the IINA project; this issue is to track the migration process.

**Comment by saagarjha** [comment]
@lhc70000 @HarukaMa @inflation @alejx you should be receiving an invitation shortly.

**Comment by saagarjha** [comment]
I've completed the migration of one of our repositories, a fork of [GRMustache.swift](https://github.com/groue/GRMustache.swift), from my account to the IINA organization. I'd recommend that everyone start moving their individual IINA support repositories there.

**Comment by saagarjha** [comment]
I'm going to invite all the people listed in the About window as translators to the translation team. Currently, that's @lhc70000, @LEOYoon-Tsaw, @superzazu, @metacosm, @shilch, @shorshe, @J-rg, @cgand, @matsune, @darkbrow, @euf, @imKota, @eminhaqi, @Aikyuichi, @sevenfourk, @dionvl, @Marvin99com, and @thkir–if I need to add or drop anyone please let me know; otherwise you guys should be getting an invite soon.

**Comment by imKota** [comment]
@saagarjha, I'm ready :)

**Comment by saagarjha** [comment]
Great! You should have received an invitation to join the organization.

**Comment by imKota** [comment]
So far, nothing has been received :c

**Comment by cgand** [comment]
Joined https://github.com/iina

**Comment by shilch** [comment]
Long time ago that I did translations for IINA.  
Hope that I will find time again. Thanks for the invitation!
