### ISSUE TITLE
改版后的配色使功能无法清晰辨认

### ISSUE THREAD

**Issue by ElvinTrancy** [iina/iina#1323]
不是什么大问题，但是改版前的透明度真的好多了，标题行变得很模糊，功能提示夜难以辨认，为什么不维持之前的呢？顺便，非常感谢创作者带给我们如此优秀的产品

**Comment by lhc70000** [comment]
「改版」是指什么？请附上对比截图。

**Comment by ElvinTrancy** [comment]
是指v14.1之前的版本，ui字体大概是白色或者浅灰色的，我不知道如何降级因此无法截图原版本的

问题如附件图所示，标题和功能提示的部分看不清了……
![img_20180108_154236](https://user-images.githubusercontent.com/35214540/34662543-6dc25632-f48c-11e7-9f28-b89ddb128ff8.jpg)

![10282592-e54d-4d41-9eff-9d8d6ac5c0f4](https://user-images.githubusercontent.com/35214540/34662608-cfa83efc-f48c-11e7-80c8-37c407d1901c.png)

**Comment by lhc70000** [comment]
系统版本是什么？

**Comment by ElvinTrancy** [comment]
不是很清楚上一版本使哪一版了，大约是2017年3，4月份的版本，系统的版本是 OS X Yosemite 10.5

**Comment by lhc70000** [comment]
@ElvinTrancy 我会查看。

另外，10.10 的支持迟早是会放弃的，请尽快升级新版本。

**Comment by ElvinTrancy** [comment]
是的，，之前使10.10 因收到了可能会放弃支持的信息，更新到了14 导致了 ui的问题，发生问题的不是之前的版本。。。
