### ISSUE TITLE
工具栏底部的时候,侧边控制栏不好关闭

### ISSUE THREAD

**Issue by SLboat** [iina/iina#1344]
必须点击横线的左边一点才有效,非常的不直观.
![slboat-mac-screen 2018-01-11 21 59 53](https://user-images.githubusercontent.com/4231376/34829184-d38fcf4a-f71a-11e7-8420-66f36faa60e0.jpg)

**Comment by lhc70000** [comment]
@SLboat 理论上点击整个视频区域都会收回侧边栏，现在无法关闭吗？
播放控制是其他样式的时候呢？

**Comment by SLboat** [comment]
@lhc70000 老哥晚上好!真及时!真难想象你用多大的决心做了这玩意!!!首先是致敬!

这个有QQ群什么样的地方吗?很好奇见到你们的思考方式是怎样的哈哈!

关于这个问题,最bootom模式的时候才会是困扰,因为直觉的反应应该是点击回去齿轮按钮关闭,但是这里刚好遮住了,所以导致了可怜的问题.

**Comment by SLboat** [comment]
@lhc70000 自己玩啊玩的自学着玩了3年objc, Swift,ios,mac开发,老哥有什么缺mac开发者人儿的时候算我一个嘛,我自己写了很多小工具自己玩着.但苦恼于玩儿的要满足生活糊口的同时的那些烦人时而.

总而言之,这个问题在这里是非常不妥当的!

纯粹致以敬意,哈哈!i

**Comment by SLboat** [comment]
http://see.sl088.com/wiki/IIna 在自己网站写了个简单的介绍,表示致敬.再见.

**Comment by SLboat** [comment]
尺寸全屏的时候,总会感觉这个关闭过程非常不自然,在底部的时候,工具栏不传贯穿底部像是更可靠的方式.

![close_full_screen](https://user-images.githubusercontent.com/4231376/34830340-88f75a30-f71e-11e7-8a5b-65e78b94a059.gif)
![close_controller](https://user-images.githubusercontent.com/4231376/34830341-8936d818-f71e-11e7-8854-cd3c79c54628.gif)

**Comment by SLboat** [comment]
![slboat-mac-screen 2018-01-11 22 28 06](https://user-images.githubusercontent.com/4231376/34830411-b7777912-f71e-11e7-8e65-0e97187182f6.jpg)
这是movist的布局.

好了,我的汇报就这些玩意了.祝老兄一切顺好!

**Comment by Miigon** [comment]
@lhc70000 其实我也认为当播放控制样式为顶部或底部的时候，侧边栏不应该遮住播放控制栏的，这看起来很不自然。
我的想法是播放控制栏缩短，为侧边栏让出空间，或者侧边栏底部贴紧播放控制栏，而不是覆盖。
对于窗口标题栏同理。
