### ISSUE TITLE
Aspect ratios less than 1.0 doesn't work (since 0.0.15 version)

### ISSUE THREAD

**Issue by alexander-ii** [iina/iina#1354]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15 build 62

**Expected behavior:**
When setting an aspect ratio value less than `1.0`, it should affect window aspect ratio. Vertical videos usually have such aspect ratios.

**Actual behavior:**
Window aspect ratio stays the same.

**Steps to reproduce:**
1. Open a file and start playing
2. Try to set an aspect ratio value less than `1.0` (`0.6` or `1:2` for example)
3. See that an aspect ratio of a player window hasn't changed (but it should).

- [x] MPV does not have this problem.
- [x] IINA 0.0.14 does not have this problem.

**Comment by ckesc** [comment]
Demo video: https://www.youtube.com/watch?v=jsCLxfFd6KU

Result on IINA 0.0.15 
![image](https://user-images.githubusercontent.com/2548610/34906302-fbfc6b8e-f87b-11e7-91d7-d0cc174a160e.png)

**Comment by lhc70000** [comment]
@ckesc What's your screen resolution?

**Comment by ckesc** [comment]
I have 2560 x 1600 Retina
But window on the screenshot is not in full screen. When I switch to full screen - everything fine.
The problem occurs only in windows mode.

**Comment by alexander-ii** [comment]
It needs to be mentioned that in music mode (yep, I have tried to play video in music mode) it works normally as well.

**Comment by lhc70000** [comment]
I've fixed it in a new build: https://dl-portal.iina.io/IINA.v0.0.15-build63.dmg

Please have a try.

**Comment by alexander-ii** [comment]
Works well for me.

**Comment by ckesc** [comment]
Yep. You fixed bug 👍
