### ISSUE TITLE
[UI/UX]Quicksettings covered the OSC while OSC layout set to Bottom.

### ISSUE THREAD

**Issue by Miigon** [iina/iina#1396]
As mentioned in #1344. When OSC layout set to Bottom. Quicksettings Tab can cover a part of OSC.
<img width="862" alt="2018-01-20 1 16 22" src="https://user-images.githubusercontent.com/16161991/35164839-f8c63b2e-fd86-11e7-9c35-348789c4dfaa.png">

Users could be confused by buttons' being covered. Maybe some tweaks are needed?

Here are my ideas:
**1.**
<img width="1179" alt="2018-01-20 12 54 47" src="https://user-images.githubusercontent.com/16161991/35164995-929ecb94-fd87-11e7-9c39-5ddc2c4af287.png">
**2.**
<img width="1155" alt="2018-01-20 1 06 00" src="https://user-images.githubusercontent.com/16161991/35164997-9664b25c-fd87-11e7-8d8b-85ecf22265f7.png">
*(the bottom-right corner)*

I personally like the first one more. But considering the title bar, the second one may be better.

**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Comment by alejx** [comment]
Did you actually made it happen other than just make the pictures? You can send a PR based on the second design.

**Comment by lhc70000** [comment]
Closing since we have no plan to change it.
