### ISSUE TITLE
JSON IPC - get_property geometry or a way to get current window size and position

### ISSUE THREAD

**Issue by krlklm** [iina/iina#1405]
**System and IINA version:**
- macOS 10.11.6
- IINA 0.0.15 Build 62 (mpv 0.27.0)

**Expected behavior:**
When sending `echo '{ "command": ["get_property", "geometry"] }' | socat - /tmp/mpvsocket1` in the CLI it should output the current geometry of the window (size, position x, position y).

**Actual behavior:**
The CLI outputs the size and position of the movie window when it was created, not the current values.

- MPV log:
http://www.dienststelle.de/projekte/2017/videoplayer/mpv/output.log

- IINA log:
http://www.dienststelle.de/projekte/2017/videoplayer/iina/iina_output.log

**Steps to reproduce:**
- in the CLI type `iina /path/to/movie.mpg --mpv-geometry=50%+20+10 --mpv-input-ipc-server=/tmp/mpvsocket1`
- in the CLI type `echo '{ "command": ["get_property", "geometry"] }' | socat - /tmp/mpvsocket1`
- it will output the geometry of the movie when it was created
- move and scale the window with the mouse
- in the CLI type `echo '{ "command": ["get_property", "geometry"] }' | socat - /tmp/mpvsocket1` again.
- it will still output the old values

**MPV vs IINA:**
MPV does have the same problem!
I opened an [issue on the mpv github repository](https://github.com/mpv-player/mpv/issues/5426#issuecomment-359238743). They answered that i should open an issue here at the IINA repository, as IINA takes care of the windows management itself.

**How often does this happen?**
Always

**Use case:**
This is for an art installation. Several movies should open and play at predefined positions and window sizes over time. The score will be run by Ableton Live (www.ableton.com). Audio loops in Ableton Live will be synchronised to video loops with IINA. We are using IINA instead of mpv, as the windows should look like regular QuickTime Player windows. The IINA player will be controlled via a Max4Live instrument / patch that can send commands via CLI (www.ableton.com/en/live/max-for-live/).

For a convenient way to design the layout of the score over time it would be good (or even necessary) to be able to drag the movie windows, resize them and then get these values to store them.

Ideally we could even control the position and size of the windows after creation, but I learned that this is not possible (at least at the moment).

**Comment by lhc70000** [comment]
IINA is ready for it. Once mpv implemented this feature, we'll update IINA accordingly.

**Comment by Akemi** [comment]
https://github.com/mpv-player/mpv/issues/3872 the related issue/feature request on mpv's issue tracker. you probably want that property to be observable after all.
