### ISSUE TITLE
fast-forward action using cmd + -> cause the player stop playing

### ISSUE THREAD

**Issue by x-tropy** [iina/iina#1439]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
just hold on to cmd + -> keys, don't release for like 8 secs maybe.

- [ ] MPV does not have this problem.

**How often does this happen?**
It happens everytime if I do it too constantly and don't give it a break.
Only restart my macOS will remedy this.

**Comment by lhc70000** [comment]
But ⌘→ should be "next media" rather than fast-forward……

Do yo have a customized key binding configuration?

**Comment by RYOHOI** [comment]
It is fast-forward when I hold on to this key combo, I mean keeping those key down.
While I found that the issue maybe caused by macOS, since all video player can be affected, even one on the webpage.
