### ISSUE TITLE
Youtube Live Stream is very slow and unplayable

### ISSUE THREAD

**Issue by kxxc** [iina/iina#1459]
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15 b 68

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by saagarjha** [comment]
I can confirm that this is still an issue on the latest build of IINA.

**Comment by kxxc** [comment]
yeah, the old version before was okay. but after that the couple of new versions can't work.

**Comment by rsispal** [comment]
Here in 2019 and I find that IINA does not play YouTube live videos for longer than 5s. Can I confirm that this was once possible?

**Comment by kxxc** [comment]
> Here in 2019 and I find that IINA does not play YouTube live videos for longer than 5s. Can I confirm that this was once possible?

you can do this and use your own youtube-dl (install by yourself).
[https://i.imgur.com/MHsKXSR.png](url)
