### ISSUE TITLE
Please add ability to play BDMV file

### ISSUE THREAD

**Issue by stevelong3** [iina/iina#1521]
**System and IINA version:**

- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by ErikMinekus** [comment]
I have a BDMV file which plays just fine in IINA. What happens when you try to play the file?

**Comment by stevelong3** [comment]
Hi! Thank you for reply.
I was not precisely described my issue. Sorry for that.
My issue is: when I drop the BDMV file into IINA. IINA read files inside BDMV one by one and play them. So it will play some .jpg .TS etc.. I wish IINA can play BDMV as a disc. So after drop the BDMV then straight play the video/film.
Hope I clearly described.
By the way. IINA is a very nice player! It’s my main player already.

Thank you & look forward for your reply.

Sent from my iPhone

On 26 Feb 2018, at 06:11, ErikMinekus <notifications@github.com<mailto:notifications@github.com>> wrote:


I have a BDMV file which plays just fine in IINA. What happens when you try to play the file?

**Comment by alejx** [comment]
A BD folder should like this:

XXXX_XXXXX
|- BDMV
|- CERTIFICATE

You probably dragged `BDMV` folder into the player. However we are currently checking the parent directory of `BDMV` folder; which is to say, you can drag the parent folder of `BDMV` into the player and it will play BDMV as a file.

It is also reasonable to check `BDMV` folder directly as well. I'll consider to make a commit on it.

**Comment by stevelong3** [comment]
Got it.
Thank you so much! Keep going!

Sent from my iPhone

On 25 Mar 2018, at 13:09, Yuze Jiang <notifications@github.com<mailto:notifications@github.com>> wrote:


A BD folder should like this:

XXXX_XXXXX
|- BDMV
|- CERTIFICATE

You probably dragged BDMV folder into the player. However we are currently checking the parent directory of BDMV folder; which is to say, you can drag the parent folder of BDMV into the player and it will play BDMV as a file.

It is also reasonable to check BDMV folder directly as well. I'll consider to make a commit on it.

**Comment by Fang-** [comment]
Opening either the BDMV or the parent directory in IINA 0.0.15 just plays the first video file `00000.m2ts` for me.

I'm unsure whether this is related to/the same issue as #1404, but tagging it just in case.

**Comment by low-batt** [comment]
Support was added in IINA 1.4.0-beta1.
