### ISSUE TITLE
Is there a way to change language?

### ISSUE THREAD

**Issue by Nicoulaisen** [iina/iina#1550]
Hi, so I just downloaded the new version of IINA, and it changed the language from English to my main language Danish, why is obviously nice that it is in my main language, though I would much rather have it in English. I think it would be nice feature because not everyone wants to have their own language as the only one, and plus it is way easier to identify problems, since it is not always translated in a way that makes it easy to find.
**System and IINA version:**

- macOS 10.13.3
- IINA 0.0.15 Build 68

**Comment by cgand** [comment]
To switch application languages I use this free utiltiy:
[http://www.tj-hd.co.uk/en-gb/languageswitcher/](http://www.tj-hd.co.uk/en-gb/languageswitcher/)

**Comment by fbongcam** [comment]
I second @Nicoulaisen ! I'd really like an option in the application to change UI language.

System and IINA version:

macOS 10.14.2
IINA 1.0.0
