### ISSUE TITLE
Auto download subtitles

### ISSUE THREAD

**Issue by amithiel** [iina/iina#1676]
Hey there,

Is there any plans for auto saving the subtitles? or at least set a timer to auto save after 20 min or something like that. I often forgot to save them, and have to click search online everytime. If for some reason i have no internet connection, its a bummer.
Thanks, and nice job with this player! finally dumped vlc

**Comment by kaassouffle** [comment]
I second this request. Maybe have:
- Auto save (or option to auto save in settings)
- Save button next to download button in the popup window that shows subtitles found online
