### ISSUE TITLE
Use Crowdin

### ISSUE THREAD

**Issue by alejx** [iina/iina#1681]
[Crowdin](https://crowdin.com/) is an automated localization tool, it helps translators get rid of the git and GitHub stuff. Crowdin is now free for open source projects.

@saagarjha @inflation @lhc70000 Any ideas on it?

**Comment by alejx** [comment]
@superzazu @cgand @J-rg @shorshe @LEOYoon-Tsaw @darkbrow @euf @imKota @matsune @eminhaqi @dionvl @Aikyuichi @sevenfourk @Marvin99com @thkir

Sorry for bordering but I also want to know how you guys think for this.

**Comment by cgand** [comment]
Never used, but not seem bad.
All already translated strings can be uploaded to the platform or we have to start form scratch?

**Comment by alejx** [comment]
@cgand I don't have experience on it either, but I believe you don't have to start from scratch.

**Comment by imKota** [comment]
@alejx I do not see anything wrong.
I think we can try.

**Comment by inflation** [comment]
I think it’s worth trying. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shorshe** [comment]
Let’s try it out.

**Comment by Marvin99com** [comment]
sure, I'm in

**Comment by euf** [comment]
Current workflow is OK for me, but if this tool can make things easier for new translators, it's worth it. I agree.

**Comment by shorshe** [comment]
Hi all,

Don't want to derail this thread and I'm all for testing this new tool (as I wrote before). But just one remark (@alejx):
Do you know about the built-in translations functionality of Xcode via XLIFF-Files?
Xliff-Files can be exported from Xcode worked on outside of Xcode with free tools and imported back into Xcode. 
The translator doesn't need Xcode for this. I used Xliff-Files for my first german translation of IINA.

https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html
