### ISSUE TITLE
Open Link in IINA

### ISSUE THREAD

**Issue by Wdavery** [iina/iina#1746]
**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0-beta2

**Expected behaviour:**

When reading the documentation and code for the safari/chrome extensions there are hints of an  "open link in IINA". I expect to right click on a link and have "Open link in IINA" appear as an option.

**Actual behaviour:**

Currently all that appears when right clicking a link is "Open Current Page in IINA"

**Comment by AlekLT** [comment]
Also noticed this, and would appreciate 'Open Link' functionality in the Safari extension.

**Comment by Wdavery** [comment]
Is that confirmation enough? ^

**Comment by saagarjha** [comment]
I think we have this already?
