### ISSUE TITLE
Wireless headphones can not pause/play video!

### ISSUE THREAD

**Issue by ahmadseleem** [iina/iina#1749]
Hi,

Wireless headphones can NOT pause/play video!
But, wired headphones can.

- macOS 10.12.6
- IINA 1.0.0-beta build 80
mpv 0.28.2

**Comment by alejx** [comment]
What kind of wireless headphones are you using? Can they pause/play other apps like iTunes?

**Comment by ahmadseleem** [comment]
-> Beats X.
It has that W1 chip...
But, still a normal bluetooth when connected, I guess.
................................
& Yes, I can pause/play iTunes with it or Quicktime or Youtube...etc.

And actually when I pressed to play while having a safari page open with a youtube video paused; instead of pausing the ( active app ) IINA *playing* audio, it played the youtube video.
It's like the bluetooth did not register you or that you need to register bluetooth - if active - in the app.
