### ISSUE TITLE
control play back of multiple players in sync

### ISSUE THREAD

**Issue by justmelnyc** [iina/iina#1833]
is it possible to control play back of multiple players in sync, like a master / slave player set up?

essentially I want to use as a video wall, made with 4 screens.

**Comment by Enzime** [comment]
[Syncplay](https://syncplay.pl/) already exists, I'm not sure if there's an easy way to make it work with IINA, but it already supports mpv.

**Comment by inflation** [comment]
Just my two cents, I think you can try it with `iina-cli`.

**Comment by justmelnyc** [comment]
Hello guys, if I want to play instances of IINA in sync on the same machine, I would still need something like Syncplay? Syncplay looks interesting, but I'm not very familiar with python, and just getting started with swift. don't want to overload.

sorry if this is the wrong forum for these kinds of questions.

**Comment by Geo1088** [comment]
Just gonna reference this discussion thread from the syncplay repo: https://github.com/Syncplay/syncplay/issues/144

I've just started using IINA after seeing the 1.0 release posted on Reddit, it's really great so far. Having syncplay compatibility would be icing on the cake and would mean I don't have to keep VLC installed. Unfortunately I don't have the time to contribute to this myself, but if no one picks it up in the future it might be something I could look into.

**Comment by albertosottile** [comment]
Syncplay 1.6.7 will add support for IINA. The first beta of this release is avaliable here: https://github.com/Syncplay/syncplay/releases/tag/v1.6.7-Beta1. Any feedback would be truly appreciated!
