### ISSUE TITLE
[Want to add] PiP button to TouchBar options

### ISSUE THREAD

**Issue by jordibruin** [iina/iina#1900]
I would like to add a PiP button to the TouchBar options. Similar to the native video player Touch Bar you see on YouTube.

I've got this working already locally, this is a request to submit a pull request.

**Comment by lhc70000** [comment]
Thanks, please submit the pull request. Sorry for late reply!

**Comment by alejx** [comment]
Be aware of this https://github.com/lhc70000/iina/issues/1937.
