### ISSUE TITLE
Question about Chinese characters garbled

### ISSUE THREAD

**Issue by WANGYINGYU** [iina/iina#1975]
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

One problem that has always existed in various versions of IINA is that the file title and album name are garbled when it is Chinese. This may be due to the file being generated under the Windows operating system, but I hope to get a good solution, thank you.

**Comment by lhc70000** [comment]
Could you share a sample file with us?

**Comment by mrwtakev** [comment]
![Uploading image.png…]()

**Comment by mrwtakev** [comment]
![image](https://user-images.githubusercontent.com/31499655/45349446-e3de4b00-b5e3-11e8-8ffb-5050ffdf7a68.png)

**Comment by HarukaMa** [comment]
Are you really sure that "MPV does not have this problem."?
