### ISSUE TITLE
Screenshots of x265 10-bit HDR have dull colors

### ISSUE THREAD

**Issue by joacogui** [iina/iina#1981]
I've been using IINA exclusively to watch 10 Bit HDR files. However, I've found that when I take screenshots using the app's CMD+S command the colors are dull, as if the HDR file wasn't being processed correctly. I've noticed the colors look the same as if I'd played the file using Quicktime X.

Here is a [comparison between IINA screenshot and Mac OS X screenshot](https://imgur.com/a/n1GUXtO)

Is there something I'm doing wrong?

**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
You probably have the same issue as here: https://github.com/mpv-player/mpv/issues/5498

Please try with the latest version and see if anything changed. Thank you.

**Comment by s3lfish** [comment]
This issue still exists with the macOS version 1.1.2 Build 128
