### ISSUE TITLE
Safari Service to open youtube links with Iina

### ISSUE THREAD

**Issue by gferreroferri** [iina/iina#1990]
Could someone help me? I would like to have a Service on macOS so that when I right click on a YouTube link in Safari I could get the option to open the youtube video with Iina. I have tried without success (I am not a programmer). Any help would be welcome.
Thanks

**Comment by AnanyaKirti** [comment]
There is an extension for chrome.
Safari extension isn't signed and won't work with current version of Safari

**Comment by gferreroferri** [comment]
Thanks! I finally managed to do an Automator Service to open YouTube links in Safari. It is not the best and you need to give permission to launch the app every time, but at least it works and does what I wanted. If someone has any idea on how to improve it.

<img width="706" alt="captura de pantalla 2018-09-22 a las 14 51 07" src="https://user-images.githubusercontent.com/823394/45916946-0c353780-be77-11e8-81ff-38fefffbe7a4.png">

**Comment by saagarjha** [comment]
We have an extension to do this, so I'm going to close this. If anyone wants a service feel free to ask to have this reopened, or create a new issue.
