### ISSUE TITLE
Thumbnail preview not working on beta 4

### ISSUE THREAD

**Issue by Phil57** [iina/iina#2002]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0-beta4 (92)

**Expected behavior:**
Show thumbnail preview when overing the progress bar doesn't work on this version but works on beta 2
Cache stays at 0b

**Steps to reproduce:**

Play a video with beta 2, thumbnail preview is working.
Update from beta 2 to beta4 or clean install beta4 and thumbnail preview is not working

**How often does this happen?**
Always on beta 4

**Comment by lhc70000** [comment]
@Phil57 Are you playing a file stored on a mounted (non-local) drive?

**Comment by Phil57** [comment]
Shame on me I didn't test that.

Yes I'm playing from a network Samba drive. Using a local file, the thumbnail preview is working as expected.

(It used to work from a network drive)

**Comment by lhc70000** [comment]
It was disabled in beta 4 to prevent unnecessary network requests. For now you can type the following command in terminal to enable it:

```
defaults write com.colliderli.iina enableThumbnailForRemoteFiles -bool YES
```

BTW do you think it's necessary? If most users don't want this change, I'll set it to enabled by default.

**Comment by Phil57** [comment]
Necessary, no but it can be useful feature depending on what you are doing.
You might probably add an option in the settings to enable it or not.

Thanks for the explanation

**Comment by LeoNatan** [comment]
Is there a way to distinguish between. A local network remote file and a “remote” remote file? If a file is on a network share on the local network, the setting should be enabled.

**Comment by inflation** [comment]
@LeoNatan Technically you can, for example, testing the latency. But from the URL perspective view, they are the same.

**Comment by anohren** [comment]
> Yes I'm playing from a network Samba drive. Using a local file, the thumbnail preview is working as expected.

Since the problem has been identified the issue could use a title update.

I'm all for thumbnails over local network. It works just fine over SMB.

**Comment by LeoNatan** [comment]
@lhc70000 Will thumbnails now work by default on SMB shares?
