### ISSUE TITLE
Theme setting not respected in 10.14

### ISSUE THREAD

**Issue by YourMJK** [iina/iina#2005]
**System and IINA version:**

- macOS 10.14
- IINA 1.0.0-beta4

**Expected behavior:**
The "Theme" setting in IINA's preferences pane changes the theme regardless of macOS's global theme/appearance setting. I.e if "Light" is selected, IINA's UI is _always light_ and if "Dark" is selected the UI is _always dark_.

**Actual behavior:**
IINA's UI theme _always_ matches macOS's global theme, _regardless_ of IINA's "Theme" setting.

<img width="1150" alt="screenshot" src="https://user-images.githubusercontent.com/37852512/46016984-ac3ccc00-c0d6-11e8-840c-5cac7f6d7406.png">

**Steps to reproduce:**
Open IINA's preferences pane and change the "Theme" setting.

- [x] MPV does not have this problem.

**How often does this happen?**
Always.

**Comment by lhc70000** [comment]
Currently it's an intended behavior (this option only controls the appearance of video window).

**Comment by YourMJK** [comment]
Oh right, I see.
In my opinion that's a bit confusing, I expected the setting change the UI of the video window _as well as_ the "welcome window".

**Comment by lhc70000** [comment]
Yes, I think at least the welcome window should follow the appearance setting. I'll update it in the next version.

**Comment by YourMJK** [comment]
Thanks, I appreciate it!
