### ISSUE TITLE
快进键问题

### ISSUE THREAD

**Issue by BryceMicheal** [iina/iina#2012]
版本：beta4
issues：在iina中使用的是Movist Default快捷键，以前按cxz（快进后退还原键）都可以正常显示在视频窗口左上方，现在不显示了快进速度了，不知为何，不是因为更新了mac系统的原因，在更新了iina后出现了此问题。

**Comment by BryceMicheal** [comment]
> beta 3 的时候正常吗？

不太清楚了，但是beta2是正常的。

**Comment by BryceMicheal** [comment]
> beta 3 的时候正常吗？

我完全卸载iina之后，重新安装问题还是无法解决。

**Comment by oflyme12** [comment]
特意关注，我刚0.0.15升级beta4的时候，使用c x z来进行快进的时候，也发现不显示快速速率了。

**Comment by oflyme12** [comment]
特意关注，我刚0.0.15升级beta4的时候，使用c x z来进行快进的时候，也发现不显示快速速率了。

**Comment by alejx** [comment]
Might related to mpv-player/mpv#6349

**Comment by alejx** [comment]
Track this issue in #2206.
