### ISSUE TITLE
Add beta download to website to reflect the great project activity

### ISSUE THREAD

**Issue by wedi** [iina/iina#2024]
Hi,
I just happened to stumble about IINA again and visited the website and would like to give some feedback. 

My first and immediate impression was that the project is dead. The site shows very prominently _"Updated on Jan 13"_ and _"New website & 1.0 release are coming soon!"_. A very typical sign of an abandoned project. How wrong this first impression was!

As one is very rarely the only one I'd strongly suggest adding a beta download button with the latest release date. As a goodie maybe even a short text telling about the current status to make it 6 text boxes.

**Edit:** I just found the gh-pages branch but, unfortunately,  did not find the website source itself to make a pull request. I guess it is not publicly available, @lhc70000?

**Comment by lhc70000** [comment]
Sorry for the delay 😅

I'll try my best to get the 1.0 public release done in one month. Of course I'll also publish a new website for 1.0 at https://iina.io and the source code will be available on GitHub. Please stay tuned!
