### ISSUE TITLE
[CRASH] Crash on file load.

### ISSUE THREAD

**Issue by ybma-xbzheng** [iina/iina#2027]
Some files can cause crashes, adding code protection to thumbnail generation?

**System and IINA version:**

- macOS 10.14
- All versions have this problem

**How often does this happen?**
Every time.

![1539059196194](https://user-images.githubusercontent.com/13780309/46646880-69dbba80-cbbf-11e8-8673-e763601c2999.jpg)

**Comment by ybma-xbzheng** [comment]
I have fixed this bug.
Add the following code after `avcodec_parameters_to_context(pCodecCtx, pVideoStream->codecpar);`
```objc
    if (pCodecCtx->pix_fmt == AV_PIX_FMT_NONE) {
        avcodec_free_context(&pCodecCtx);
        avformat_close_input(&pFormatCtx);
        return -1;
    }
```

**Comment by lhc70000** [comment]
Thanks! Would you mind submitting a pull request?
