### ISSUE TITLE
Incompatible with FileZilla FTP server

### ISSUE THREAD

**Issue by sanxing-chen** [iina/iina#2038]
**System and IINA version:**

- macOS 10.14
- IINA 1.0.0 beta4

**Expected behavior:**

The player should be able to open a URL of a video file in a FileZilla server.

**Actual behavior:**

After pending in the `Opening Stream` screen for a while, it reported a `Cannot open file or stream!` error.

I also checked the FileZilla server's log, and find out beblow.
```
202 UTF8 mode is always enabled. No need to send this command.
421 Connection timed out.
```

I guess this issue may associated with something like https://github.com/jlaffaye/ftp/issues/77.

- MPV log:
```
[   4.459][v][ffmpeg] Opening ftp://...
[ 124.537][e][ffmpeg] ftp: FTP open failed
[ 124.537][e][stream] Failed to open ftp://...
[ 124.537][v][cplayer] Opening failed or was aborted:  ftp://...
```

**Comment by inflation** [comment]
Please report it to mpv. Thank you. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
