### ISSUE TITLE
Notarize IINA

### ISSUE THREAD

**Issue by saagarjha** [iina/iina#2050]
Apple has been pushing for all developer ID-signed apps to go through their notarization process (see [this WWDC session](
https://developer.apple.com/videos/play/wwdc2018/702)), and I think that we should submit IINA to be notarized. From our side, we'd need to opt in to the new Hardened Runtime. I believe this should have little impact on IINA, since it does things like disable JIT and enable library validation, which we don't do (to my knowledge)–and even if we do, we can request an exception by adding certain entitlements.

Thoughts?

**Comment by LeoNatan** [comment]
I am in the same boat in my app. I should do it, but I haven't figured out a flow yet how to automate it. Do you build your releases manually right now? In that case, it should be as easy as clicking a button in Xcode. I don't think the hardened runtime is a requirement for notarization.

I build my app from a script which I currently run manually, but I could run in CI in theory. The script builds, generates a github release, uploads the build and finally triggers an update for the appcast. I don't see how this can be automated at all.

**Comment by saagarjha** [comment]
> I should do it, but I haven't figured out a flow yet how to automate it.

The Application Loader command-line tool, along with `stapler` (which is optional, but highly recommended)?

> I don't think the hardened runtime is a requirement for notarization.

It is. We can opt out of the protections by declaring entitlements, but I see no need to do this for IINA.

**Comment by saagarjha** [comment]
The notarized runtime will be a requirement for some apps starting in [macOS 10.14.5](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution). Calling @lhc70000 to weigh in.

**Comment by saagarjha** [comment]
As per [Advances in macOS Security](https://developer.apple.com/videos/play/wwdc2019/701), new versions of IINA will no longer run on macOS Catalina if they are not notarized.

**Comment by LeoNatan** [comment]
I've been notarizing and waiting to staple my app in a script. I even fill in the required details in the xcarchive metadata so that the notarization log is shown in Xcode organizer.

https://github.com/wix/DetoxInstruments/blob/c1e43d07b90170e5905be324ba84ef838c8c6427/releaseVersion.sh#L97

It's a simple process. Archive, export, ZIP, notarize, retry every 30 seconds to see if notarization was successful (usually takes 2-3 min, sometimes less), staple .app, rezip, distribute to GH releases.
