### ISSUE TITLE
是否能够支持网盘视频的播放

### ISSUE THREAD

**Issue by ydx1013** [iina/iina#2085]
经常使用player，里面网盘视频播放感觉非常的实用，mac电脑普遍内存较小，如果能够增加网盘播放，愿意付费购买，另外，，，，可以考虑上架appstore ，毕竟不少冒充的视频播放器出没，可以适当收费，我想开发者年费肯定会赚够的。。谢谢

**Comment by ydx1013** [comment]
经常使用Nplayer，里面网盘视频播放感觉非常的实用，mac电脑普遍内存较小，如果能够增加网盘播放，愿意付费购买，另外，，，，可以考虑上架appstore ，毕竟不少冒充的视频播放器出没，可以适当收费，我想开发者年费肯定会赚够的。。谢谢

**Comment by xjbeta** [comment]
支持WebDAV 的网盘可以在线播放

**Comment by ydx1013** [comment]
onedrive，解析以后貌似是直链，建议可以增加onedrive的视频播放功能，另附一个，onedrive搭建网盘直链播放的项目    [https://github.com/donwa/oneindex](https://github.com/donwa/oneindex)

**Comment by oscar-c** [comment]
I hope there's PLEX support as well.
