### ISSUE TITLE
How to make Repeat mode enabled by default?

### ISSUE THREAD

**Issue by SarveZir** [iina/iina#2139]
Hi Guys

Every time I close the app **Repeat mode** becomes disabled so I have to enable it manually. Possible to change it to **enabled** by default?

**Comment by bw-space** [comment]
Can you please elaborate your issue?

**Comment by SarveZir** [comment]
MPV : **--loop** to loop the playlist, **--loop-file** to loop playlist entries.
inna : ? 

(No need to say I want an inna's permanent option to work like that; Just like mpv config options)

**Comment by PaulSlocum** [comment]
Really needs a way to do this.  I would want a preference in settings that specifies the default loop mode.

**Comment by tertiumsquid** [comment]
I'd like this as well, as Iina has become my go-to music player.  If possible, maybe have two settings - one for music playback and one for video, as I'd rather my videos didn't loop by default.

**Comment by thinker-g** [comment]
I'd like to have this feature also.
How about just to make IINA to "remember" the user's choice? Just like it remembers the timestamp of last play of each video.

**Comment by abplcode** [comment]
i need this.

**Comment by Acciente717** [comment]
I would also like to have this feature.

**Comment by JiashengWu** [comment]
> MPV : **--loop** to loop the playlist, **--loop-file** to loop playlist entries.
> inna : ?
> 
> (No need to say I want an inna's permanent option to work like that; Just like mpv config options)

Per my understanding, I suppose in INNA setting loop/loop-file to 1, 2, ..., inf would do the same?
It's in Preference -> Advanced -> Additional mpv options

**Comment by thinker-g** [comment]
Dears, I figured out how to turn on the playlist loop by default.

Just to set an additional mpv option in  Preference -> Advanced -> Additional mpv options, with following values:
name: **loop-playlist**
value: **inf**

PS: For other available values of this option, you may refer to the [official mpv-player document](https://mpv.io/manual/master/#options-loop-playlist).

**Comment by PaulSlocum** [comment]
Adding "loop-playlist"/"inf" to mpv options did not cause videos to loop on startup for me.  I'm on IINA 1.2.0 on MacOS.

One of the reasons this feature is needed is because when opening short MP4 loops that are only a couple/few seconds, IINA often finishes playing and jumps to the next video before you have any time to active the loop function.

**Comment by tomtomkk** [comment]
> Adding "loop-playlist"/"inf" to mpv options did not cause videos to loop on startup for me. I'm on IINA 1.2.0 on MacOS.
> 
> One of the reasons this feature is needed is because when opening short MP4 loops that are only a couple/few seconds, IINA often finishes playing and jumps to the next video before you have any time to active the loop function.

Just to set an additional mpv option in Preference -> Advanced -> Additional mpv options, with following values:
name: loop-file
value: inf

**Comment by MartinJRS** [comment]
Seems not to work anymore after updating to 1.3.2 Build 135

Does anybody confirm?

**Comment by tertiumsquid** [comment]
Confirmed, doesn't work anymore in 1.3.1 or 1.3.2

**Comment by reaver585** [comment]
i'd like to bump this issue. it is still relevant. thanks in advance.

**Comment by surgever** [comment]
Reporting that using `name: loop-playlist` `value: inf` is working for me now.

**Comment by MartinJRS** [comment]
Nice. But still not for me. Quite a bit unbelievable that this seems to be a bigger issue to solve for the developer ... or not interesting enough ...

IINA 1.3.4

**Comment by dbwugm** [comment]
> Nice. But still not for me. Quite a bit unbelievable that this seems to be a bigger issue to solve for the developer ... or not interesting enough ...
> 
> IINA 1.3.4

Name: loop
Value: inf

Try this, worked for me.

**Comment by MartinJRS** [comment]
Awesome, that's working. Thanks many times ...

**Comment by low-batt** [comment]
A setting for this has been added to on the `General` tab in the `Playlist` section in the development version of IINA. This setting will be included in the next release of IINA.

**Comment by Zorast** [comment]
I need this to be a global option in settings to play ALL videos on repeat if there’s no other video in the playlist or opened. So, when I double-click to open a video, it must play on repeat automatically. This would be nice! There is also no shortcut for “play video on repeat.” It must currently be set for every video with the mouse in the options.

<img width="340" alt="Image" src="https://github.com/user-attachments/assets/1dd2c321-dbdd-43ca-b2d6-a79fbf1e0779" />

**Comment by low-batt** [comment]
We are currently in final testing before releasing the first beta of the upcoming IINA release. This version adds a setting that allows you to enable looping by default as seen here:
![Image](https://github.com/user-attachments/assets/c9ed5bea-173f-4bd6-bfbe-5604064fd222)

Good point about the lack of a key binding for controlling the looping of the playlist. If you want to assign your own key binding follow these instructions:

- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Key Bindings`
- Click on `IINA Defaults`
- Click on `Duplicate…`
- Enter `loop-playlist` for the name of the new key bindings
- On the right side of the panel click on `+` to add a new key binding
- Press ⌃⌘O (or your choice of key)
- Enter `cycle-values loop-playlist "inf" "no"` for the mpv command
- Click `Ok`
![Image](https://github.com/user-attachments/assets/55a10529-0fc7-407b-8a50-0fb5da553b1e)

**Comment by low-batt** [comment]
Support was added in IINA 1.4.0-beta1.

**Comment by erythrocytes** [comment]
> Support was added in IINA 1.4.0-beta1.

How do I turn it on? Ver. 1.4.0 (Build 158)

**Comment by low-batt** [comment]
Sorry for the slow response…

Follow these instructions:
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the `General` tab scroll down to the `Playlist` section
- Enable the `When a file is opened manually` setting
- Select `Loop playlist` or `Loop single file`

![Image](https://github.com/user-attachments/assets/5b827f18-fa50-41ea-8a47-aee5fe2b1984)
