### ISSUE TITLE
I just deleted the IINA player on my MBP

### ISSUE THREAD

**Issue by bhd4545** [iina/iina#2146]
I installed the latest inna player and then removed from my app list but still all the video file's thumbnail is set to IINA player.
please, I want to remove this IINA thumbnail 
**System and IINA version:**

- macOS 10.13.6
- IINA  latest

**Expected behavior:** 

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by saagarjha** [comment]
> removed from my app list

How exactly did you do this? Did you drag IINA to the trash?

**Comment by bhd4545** [comment]
yeah

**Comment by bhd4545** [comment]
I literally pu the IINA app to Bin.... is this wrong??

**Comment by saagarjha** [comment]
Does the issue persist if you empty the trash?

**Comment by bhd4545** [comment]
Yeah....

**Comment by bhd4545** [comment]
like this....
<img width="113" alt="2018-12-28 1 03 46" src="https://user-images.githubusercontent.com/46202214/50494392-7217f900-0a3c-11e9-908f-04efea8c884a.png">

**Comment by bhd4545** [comment]
even though I deleted the app
It still show with those thumbnail

**Comment by xjbeta** [comment]
Finder won't update thumbnail icons realtime. Wait until Finder update it.
Update it manually? This is dangerous.
https://gist.github.com/fabiofl/5873100

**Comment by rr0ss0rr** [comment]
You should be able to change the default app for the extension.  Choose a file with the extension you want to change -> Get Info -> Open With then Change All

**Comment by LeoNatan** [comment]
Reboot your Mac. That will most likely trigger a refresh in Finder's icons.

**Comment by saagarjha** [comment]
Closing, unless you're still having this issue and think it's a bug in IINA.
