### ISSUE TITLE
Hide main window when entering PiP

### ISSUE THREAD

**Issue by CourierKyn** [iina/iina#2147]
**System and IINA version:**

- macOS 10.14.2 (18C54)
- IINA 1.0.0-rc

**Expected behavior:**
When entering Picture in Picture mode, the former IINA window should hide immediately, leaving only the PiP visible. That's just like how it works in iTunes. 

**Actual behavior:**
When entering Picture in Picture mode, the main IINA window remains visible, together with the PiP.

**Steps to reproduce:**
N/A

- [x] MPV does not have this problem.

**How often does this happen?**
N/A

**Comment by anohren** [comment]
Highly disagree. For those interested, the reasons for this can be found in this discussion: https://github.com/iina/iina/pull/2128

**Comment by CourierKyn** [comment]
I appreciate your support very much.

**Comment by dhoepfl** [comment]
I agree with the request.

Having a normal window telling me that there is a PIP window is like having a normal window telling me that the content is presented in fullscreen. Who would do that?

**Comment by LEoREo2247** [comment]
I personally also appreciate this.
Sometimes I just wanted to use PiP to simply reduce all the scattered windows, and this feature can make that possible. However, I'm pretty sure some may not appreciate this change as well, therefore this can be optional.
Anyway, I'll try to look into it to see if it's something that I can do it.

**Comment by saagarjha** [comment]
I think we've fixed this with #2192.
