### ISSUE TITLE
"Cannot create folder in Application Support directory" shown up when I start IINA

### ISSUE THREAD

**Issue by chungmarcoo** [iina/iina#2150]
MacOS 10.14.2 & IINA 0.0.15 build68

"Cannot create folder in Application Support directory" <- this message keep pops up when I try to open IINA, how to fix it? I have already reinstall it via downloading dmg and drag it to "Application". And the error is still here. Thanks

**Comment by chungmarcoo** [comment]
here is the screenshot for reference 
![2018-12-29 11 11 43](https://user-images.githubusercontent.com/36217606/50539680-25a8f680-0bbf-11e9-9284-fa2a0f744cdb.png)

**Comment by inflation** [comment]
Something wrong with your Application Support directory. Maybe incorrect permission or lack of space or anything else could lead to it. There's little we can do in our side. 

Maybe you can manually create the folder and set the right permission? I'm not sure if that would help. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chungmarcoo** [comment]
> Something wrong with your Application Support directory. Maybe incorrect permission or lack of space or anything else could lead to it. There's little we can do in our side.
> 
> Maybe you can manually create the folder and set the right permission? I'm not sure if that would help.
> 
> Sent with [GitHawk](http://githawk.com)

Thanks for your prompt reply. Issue fixed, here is the solution:

Go to Library in Finder and find "Application Support" folder -> right click it -> "Get info" -> click the lock icon on the right bottom corner -> change the permission of "everyone" to "Read and Write"

**Comment by saagarjha** [comment]
This makes your system more insecure than it needs to be. You should be able to get away with "Everyone" set to "No Access" and your user having "Read & Write" access.

**Comment by chungmarcoo** [comment]
> This makes your system more insecure than it needs to be. You should be able to get away with "Everyone" set to "No Access" and your user having "Read & Write" access.

Changed it back, thanks for your reminder.
