### ISSUE TITLE
[Feature request] Do not display useless subtitle

### ISSUE THREAD

**Issue by gagarine** [iina/iina#2151]
Some mp4 videos come with one subtitle like "Chapter 1" that is displayed during the entire video. I guess it's the export software that add those.

I can of course disable the subtitle. But perhaps we can disable subtitle by default when their is only one sentence? Or hide it after 2 second?

![screenshot 2018-12-30 at 22 38 41](https://user-images.githubusercontent.com/164074/50551601-bba65500-0c83-11e9-9b93-fe187c01d4e3.png)

**System and IINA version:**
- IINA 1.0.0-RC

**Comment by HarukaMa** [comment]
@gagarine It would be too difficult for a player to decide which subtitle is “useless”. I don’t think a player should do that.

**Comment by joelgetaction** [comment]
I would 

> Some mp4 videos come with one subtitle like "Chapter 1" that is displayed during the entire video. I guess it's the export software that add those.
> 
> I can of course disable the subtitle. But perhaps we can disable subtitle by default when their is only one sentence? Or hide it after 2 second?
> 
> ![screenshot 2018-12-30 at 22 38 41](https://user-images.githubusercontent.com/164074/50551601-bba65500-0c83-11e9-9b93-fe187c01d4e3.png)
> 
> **System and IINA version:**
> 
> * IINA 1.0.0-RC

I would also like this feature.  It would make it a lot easier to view certain tutorial and instructional videos in IINA.

**Comment by gagarine** [comment]
I think it's not that hard to detect those.

If a subtitle of less than 3 words and stay on the entire video it's certainly useless and we can dis-activate the subtitle when the video is opened. Then if the user really want it, it can always go on the menu and activate subtitle for this video.

**Comment by inflation** [comment]
You can do it by writing a plug-in. We want to keep the player itself as universal as possible. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gagarine** [comment]
@inflation an option to stop displaying any subtitles by default would be enough for me. In fact, 99% of the time, I do not want subtitle.

**Comment by alejx** [comment]
@gagarine That seems to be a good idea, could you please open a new issue for that?

**Comment by gagarine** [comment]
done #2201
I'm closing this one.
