### ISSUE TITLE
Congratulations on launching 1.0.0

### ISSUE THREAD

**Issue by LeoNatan** [iina/iina#2163]
Not an issue actually. Wanted to say congratulations to the IINA team and contributors for launching 1.0.0! This is the best macOS video player because of your dedication!

**Comment by saagarjha** [comment]
I think the celebration's over, but if you still want to hang around for the afterparty you're free to do so ;)

**Comment by LeoNatan** [comment]
I’ll make sure to open a new “issue” on 2.0.0! 😂
