### ISSUE TITLE
no offence 

### ISSUE THREAD

**Issue by L1cardo** [iina/iina#2171]
Tongji Medical School of Huazhong University of Science and Technology 看不懂，我也是笑了好吧
我说了，我喜欢汉化，我的 repo 哪个跟汉化没关系？

**Comment by L1cardo** [comment]
希望iina 越做越好，  诸位2019 开心！

**Comment by lhc70000** [comment]
我是作者（或者说是项目的发起者）。**如果有什么误会**，我个人向你道歉。

你的 pull request 改的都是 placeholder 字符串，是不需要翻译的，恕不能接受。这也说明你没有仔细阅读本项目的 readme 和 wiki。

IINA 会接受一切确实改善了项目的质量的 pull request。
