### ISSUE TITLE
Inspector window - Arrow keys do not work in inspector window

### ISSUE THREAD

**Issue by probablykasper** [iina/iina#2175]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0 build 100

When IINA's tab bar is focused (which it is by default), you cannot navigate to the other tabs by using the arrow keys and space bar, as you can in QuickTime and iTunes - You'd do this by moving focus to another tab using the arrow keys, and pressing the space bar to open to the tab. The arrow keys instead move media playback 5s, though the space bar seems to work as expected.
![image](https://user-images.githubusercontent.com/11315492/50593912-ac4d2480-0e9a-11e9-8734-dd8bf9157194.png)

**Comment by svobs** [comment]
I stumbled onto this one. This appears to be working correctly in IINA 1.3.1 Build 133, and in the latest `develop` (39801567ac3c836e655f37041bf2af5f277cad69).

Unclear when it was fixed, but hooray.
