### ISSUE TITLE
Customize skip forward/backward duration

### ISSUE THREAD

**Issue by devros42** [iina/iina#2177]
**Actual behavior:**

It would be nice to be able to set the duration for skipping forwards and backward.  With VLC I can set it so a skip ahead is 40s and a skip back is only 10s.  This is really handy if you need to quickly skip through a video looking for something specific.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
You can customize it in Preferences - Key bindings.

Although it's a bit obsolete, this wiki page may explain more: https://github.com/iina/iina/wiki/Manage-Key-Bindings
