### ISSUE TITLE
Thumbnails don't work

### ISSUE THREAD

**Issue by Nes-si** [iina/iina#2186]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0 build 100

**Problem:**
There are no thumbnails. I've enabled/disabled they in settings with no effect.
However, thumbnails have worked in earlier versions (possibly 0.0.14).

**Comment by anohren** [comment]
While playing local files or non-local (e.g. over SMB) video?

**Comment by Nes-si** [comment]
@anohren yes, it's AFP.
Also I've opened a local file — thumbnails was correct. Next I've opened file on AFP and I've seen thumbnails from previous file.

**Comment by anohren** [comment]
Both of these problems have open issues
https://github.com/iina/iina/issues/2136 https://github.com/iina/iina/issues/2002

**Comment by lhc70000** [comment]
Closing since both issues have been resolved.

**Comment by firstel** [comment]
Is there an update?  when i check for updates - it says none available.  I am on 1.0.1 - the thumbnails do not work when starting the app.  If it toggle them off and on again in preference they start to work, but the thumbnails do not change for the next video, and are strange grey static like thumbnails also.

**Comment by alejx** [comment]
@firstel Please stay tuned, 1.0.1 did not ship with the fix. Please wait for the next release.
