### ISSUE TITLE
The forward is ok when using -> but the backward can not work. 

### ISSUE THREAD

**Issue by liysky** [iina/iina#2199]
**System and IINA version:**

- macOS 10.14.2
- IINA 1.0.0

**Expected behavior:**
when I want to backward the video 5s, it doesn't work. 
Works only forward.

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by alejx** [comment]
Cannot reproduce. Please check your keybinding settings.
