### ISSUE TITLE
Track list background in new release

### ISSUE THREAD

**Issue by JARVIS-AI** [iina/iina#2218]
**Basic Info :**
- macOS High Sierra 10.13.6
- IINA 1.0.0

**Bug :**

The track list on background show some unexpected white box shadow over everything
I provide a screenshot for this

**Screen Shots and Documents :**

![IMG](https://raw.githubusercontent.com/JARVIS-AI/img-storageprojects/master/Bugs/IINA/IINA.png)

**Expected behavior :**
- Must be same as main container transparent in every mode ``{Dark LDark Ligh LLight}``

**Comment by JARVIS-AI** [comment]
Still have this issue in new version
Track List in all UI color have border background not transparent
Thanks

**Comment by ungraphic** [comment]
Version 1.0.7 still has this problem in High Sierra.
