### ISSUE TITLE
IINA vs VLC performance

### ISSUE THREAD

**Issue by asoksevil** [iina/iina#2219]
**System and IINA version:**

- macOS  10.4
- IINA  1.0.0.

**Expected behavior:**

IINA should consume less resources than VLC and have a better picture quality?

**Actual behavior:**

VLC pretty much beats IINA in all formats, 720p,1080p,4k, H264 H265, even in RAM usage (first attempt on IINA).

Here's the direct link to the thread on Reddit: https://www.reddit.com/r/apple/comments/aenk8c/vlc_to_cross_3_billion_downloads_tomorrow_says/

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
There’s not much we can do in that aspect. The decoder is from ffmpeg and pretty much the standard in the field. 

We could work on things if you found any performance reduction or abnormally resources usage between IINA and mpv (which we use as core). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
