### ISSUE TITLE
大神，有没有能解杜比视界的视频的计划？？

### ISSUE THREAD

**Issue by welon2005** [iina/iina#2222]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
Please confirm with mpv. In theory, there should be no problem decoding any HDR format. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by welon2005** [comment]
@inflation 大神，mpv不能解dolby vision的格式

**Comment by alejx** [comment]
mpv 不能解的话我们也没什么办法。你可以试试去给他们提个 issue。
