### ISSUE TITLE
全屏展示系统时间格式问题

### ISSUE THREAD

**Issue by xieao100** [iina/iina#2224]
- macOS 
- IINA 
全屏展示系统时间以及电量的问题，系统时间能否改成与mac系统时间格式一致啊？上个版本是24h制，现在是12h制，很不习惯啊，不如直接改成和mac系统时间格式一样的或者可以设置时间格式，这样方便用户自己选择，谢谢了！

**Comment by alejx** [comment]
Duplicate of #1688

**Comment by alejx** [comment]
请升级至最新版本，这个问题应该已经修过了。

**Comment by xieao100** [comment]
> 请升级至最新版本，这个问题应该已经修过了。

目前是正式版1.0.1最新版，要下载beta版本吗

**Comment by lhc70000** [comment]
![fc9cc128-f05b-44e3-b8a3-1b67c1bfa461](https://user-images.githubusercontent.com/8478049/51301365-e8bb7b80-1a69-11e9-90e1-2a026e1b5837.png)

请确认一下是在这里设置 24 小时制，不是日期和时间那里。

应该是没问题的。

**Comment by xieao100** [comment]
> ![fc9cc128-f05b-44e3-b8a3-1b67c1bfa461](https://user-images.githubusercontent.com/8478049/51301365-e8bb7b80-1a69-11e9-90e1-2a026e1b5837.png)
> 
> 请确认一下是在这里设置 24 小时制，不是日期和时间那里。
> 
> 应该是没问题的。
可以了 感谢！！！
