### ISSUE TITLE
Download video feature support

### ISSUE THREAD

**Issue by n00d1e5** [iina/iina#2225]
**System and IINA version:**

- macOS 10.14 Mojave
- IINA 1.0.0

This is not an issue, it maybe a feature request or even a question.
Your IINA is great, thanks in advanced for that.

Well, with youtube-dl, I could probably download the video.
But all the issue and article is about downloading subtitle.

**What I did:**
- IINA installed.
- Chrome extension installed.

When I open a video in chrome, and click IINA extension, the IINA main window just pop-up and starts to play.
There is not any other button or feature with IINA extension.
And I did not found any button to download the video which is playing by IINA.

**So, my question is:**
Do IINA support video download?
If so, how could I do that?
Thanks.

Video example:
[http://tv.cctv.com/2012/12/15/VIDE1355585699479704.shtml](url)

PS:
I know IINA do not support you-get, but I just tried you-get in my terminal. The video mentioned above could be downloaded by you-get. It may helps. :)

**Comment by alejx** [comment]
There're a lot of apps you can choose to download online videos; I don't think a player should support downloading online videos.

**Comment by n00d1e5** [comment]
> There're a lot of apps you can choose to download online videos; I don't think a player should support downloading online videos.

Totally agree with you.
Just the youtube-dl extension and cache setting make me think that IINA may support video download.
This issue could be closed (I'll do that).
Thanks.
