### ISSUE TITLE
建议：增加画中画模式下的一些设置

### ISSUE THREAD

**Issue by xieao100** [iina/iina#2228]
目前画中画模式下，小窗口一直强制置顶，而且在小窗口展示出来 大的播放器窗口隐藏的情况下 无法使用键盘快捷键 快进 快退 空格暂停等这些功能，只能在大窗口展示的情况下使用。

昨天上班时用画中画模式偷偷看视频，发现对于我来说缺少2个功能。
所以提两个建议：
1、画中画模式下 小窗口上面可以增加一个 置顶标记 点击切换播放时置顶 还是一直置顶 还是不置顶，这样 我设置好了 领导来了 点击网页 就隐藏掉了 谁也看不到 😆
2、画中画模式下 增加对快捷键 快进 快退 空格暂停等的支持 
另外再加上昨天提的时间格式24小时的设置，非常感谢！

**Comment by alejx** [comment]
Picture in Picture 是 macOS 的私有 API，我们无法改变它的行为。
https://support.apple.com/zh-cn/HT206997
