### ISSUE TITLE
Remove MIDI file association

### ISSUE THREAD

**Issue by MaddTheSane** [iina/iina#2235]
**System and IINA version:**

- macOS 10.14.2 (18C54)
- IINA 1.0.1 Build 103

**Expected behavior:**
Opening a MIDI file plays music.

**Actual behavior:**
Opening a MIDI file produces an error saying that the file or stream couldn't be opened.
MIDI support would be great, especially as there isn't a built-in app that plays MIDI anymore (QuickTime Player 7 supports it, but Apple will be dropping support for the 32-bit runtime it needs in the next OS release). 

It looks like MPV doesn't support MIDI, either.

Despite lacking a playback app for MIDI, there are Core Audio APIs that can be called to load and play back MIDI files. 

- [ ] MPV does not have this problem.

**Comment by inflation** [comment]
Unfortunately, we don't want to add new codecs which mpv doesn't support for now. Please raise an issue there and hopefully they would implement this. Thank you.

**Comment by wincss** [comment]
I think IINA should not associate .mid file to itself if it cannot play MIDI file.

**Comment by HarukaMa** [comment]
Looks like mpv [really doesn’t want to support this](https://github.com/mpv-player/mpv/commit/16b44d93f7014b3abd8f21a4035fd4ebeed1d2c0#diff-190f104e97c4fc5b69511713b39d635d080f10d5fd5920f6d7a3f2ad5797269e) (which is pretty disappointing, personally. Proper FluidSynth integration would be great). 

FFmpeg “supports” midi playback but it really should be avoided. I think we should remove file association now if we don’t want to actually fork mpv for a home-brew midi playback feature.
