### ISSUE TITLE
 preserve window position when media is opened

### ISSUE THREAD

**Issue by igorwojda** [iina/iina#2239]
**System and IINA version:**
macOS 10.13.6
IINA 1.0.1

**Expected behavior:**
When opening a file (by dragging or clicking in Finder) I would expect for the window to stay at the same position, not animate to the center of the screen. This behavior is very inconvenient on high-res screens where you usually want to split screen space across few windows. When watching video training it is usually preferred to watch the video in window mode (rather than fullscreen), so we can take some notes or good relevant stuff.

![drag](https://user-images.githubusercontent.com/530122/51439563-3f1bfa80-1cb4-11e9-9f55-3c09fffdb80c.gif)

**Actual behavior:**
When dragging the file into player window position is changed (center of the screen)

**Steps to reproduce:**
Drag video into the player

**How often does this happen?**
Always

**Comment by adamwinn** [comment]
I see this same behavior too and would like it to remember the window position
