### ISSUE TITLE
SVP4 doesn't work with IINA 1.0.1

### ISSUE THREAD

**Issue by sosbxx0928** [iina/iina#2248]
**System and IINA version:**

- macOS  10.14.2 
- IINA 1.0.1 

After IINA updated to 1.0.1, SVP4 mac cannot be loaded when playing videos. There were no such issue with older IINA versions. All settings were remained the same. 

SVP4 mac also works well if using MPV.

**Comment by inflation** [comment]
You need to patch IINA after every update for now. We would add VapourSynth support in the future release.
