### ISSUE TITLE
showvolume filter

### ISSUE THREAD

**Issue by brimestoned** [iina/iina#2264]
I can see how to add video filters, but not sure how to do **showvolume**. Got this from the mpv docs.

--lavfi-complex='[aid1] asplit [t1] [ao] ; [t1] showvolume [t2] ; [vid1] [t2] overlay [vo]

**System and IINA version:**

- macOS **10.13.6**
- IINA **1.0.1**

**Expected behavior:**
overlay volume indicator

- [x] MPV does not have this problem.

**Comment by lhc70000** [comment]
The GUI doesn't support complex filters currently.

If you don't need to toggle the filter, now you can add it as an extra mpv option:

![ff706400-2606-4fba-8e41-f76a446a9150](https://user-images.githubusercontent.com/8478049/51961897-4489f980-2499-11e9-9557-1c0dd2199ba5.png)

**Comment by brimestoned** [comment]
Thanks.

**Comment by brimestoned** [comment]
I tried several ways to add it but doesn't seem to work. I even tried to do config using some text mpv script but no luck.

saw this
static let lavfiComplex = "lavfi-complex"

on ../Data/MPVOption.swift

How can one use that?

**Comment by lhc70000** [comment]
Just see my screenshot above. Add it to Preferences - Advanced and restart IINA.
