### ISSUE TITLE
[Feature request] Touch Bar: Add track title and track cover option

### ISSUE THREAD

**Issue by giuseppeangri** [iina/iina#2279]
**System and IINA version:**

- macOS:  10.14.2
- IINA:  1.0.1 Build 103

**Expected behavior:**
It would be nice if the Touch Bar customization options will provide also the possibility to add the track title or the track cover image.

**Actual behavior:**
Actually the Touch Bar customization controls allow to insert only the buttons to control the reproduction and the time indicators.

**Comment by alejx** [comment]
Although I'm not against this idea, but doing so might not be a good idea.
> The Touch Bar shouldn’t display alerts, messages, scrolling content, static content, or anything else that commands the user’s attention or distracts from their work on the main screen.

... says Apple macOS Human Interface Guidelines.

**Comment by giuseppeangri** [comment]
Ok, I didn't know this Apple Guideline, but I think that show the title isn't a reason of distraction. 
I suggested this feature because I use [Muse](https://xzzz9097.github.io), an iTunes/Spotify controller with Touch Bar support that shows title and cover, and I appreciate a lot this feature :)

**Comment by alejx** [comment]
Just show title is "static content". If the title is too long, and we might want to scroll them (just like what we do in Music Mode), then it's "scrolling content".
