### ISSUE TITLE
Localization Update Request for 1.0.2 Release

### ISSUE THREAD

**Issue by alejx** [iina/iina#2285]
As per https://github.com/iina/iina/commit/ad28cec7e049e739064a27c8395760c1f4531de3, the localization is frozen for 1.0.2 release. No wording/string change will be made on develop branch until next release.

Since 1.0.1 release, we have the following string changes that need to update:
- An added section under Preferences > UI > Picture-in-Picture (#2192)
- "pl_menu.browser", "pl_menu.copy_url", "pl_menu.copy_url_multi" in `localizable.strings` (#2271)
- "touchbar.toggle_pip" in `localizable.strings` (#1900)

(Closes #2054)

**Status**
- [x] fr @superzazu
- [x] it @cgand
- [x] de @J-rg @shorshe 
- [x] ko @darkbrow
- [x] ru @euf @imKota @Semty
- [x] ja @matsune, @LEoREo2247 
- [x] nl @ErikMinekus
- [x] es @Aikyuichi
- [x] uk @AthirnEleidan
- [x] sk @marianvinicay
- [x] pt-BR @pradorocchi, @ailtonvivaz 
- [x] sv @anohren 
- [x] ro @sfDuhNinja
- [x] hi @SensehacK
- [x] cs @vojtakonarik 
- [x] zh-Hans -
- [x] zh-Hant -
- [ ] da @thkir
- [x] tr @eminhaqi
- [ ] pl @Greenek

**Comment by alejx** [comment]
Be sure to work on and make pull request base on branch `release/1.0.2`. I'll create the release branch when such issue is made next time to avoid confusions.

**Comment by igorwojda** [comment]
@Greenek Polish translation is here 
https://github.com/iina/iina/pull/2358

**Comment by imKota** [comment]
@alejx Oh, completely forgot. Tomorrow I will update the translation

**Comment by alejx** [comment]
@imKota Any updates?

**Comment by imKota** [comment]
@alejx #2368

**Comment by hazarek** [comment]
@alejx tr checkbox should be checked in The Status List (turkish).

and turkish files completely up to date with this pull request.
https://github.com/iina/iina/pull/2680#issue-359202853
