### ISSUE TITLE
Improve "Receive Updates for Beta Versions" button text

### ISSUE THREAD

**Issue by JeffreyCA** [iina/iina#2287]
**System and IINA version:**

- macOS 10.14.3
- IINA 1.0.1

I think better labels would be "Not Now" and "Yes" instead of "Cancel" and "OK".

<img width="421" alt="screen shot 2019-02-09 at 4 18 18 pm" src="https://user-images.githubusercontent.com/9157833/52527948-8a5b7480-2c86-11e9-88b8-02920c455b63.png">

**Comment by anohren** [comment]
I think "Cancel" and "Receive Beta Updates" are better titles for the buttons: "Cancel" to rest assured that it will exit without any changes and without having to read any of the text, which most people don't want to do, and "Receive Beta Updates" for understanding the consequences of the affirmative action without -- you guessed it -- having to read any of the text. Which most people don't want to do.

**Comment by saagarjha** [comment]
I would tend to agree with @anohren, but we'd need to bikeshed the new label names. One thing that absolutely needs to be changed is "IINA v1.0 is coming" :)

**Comment by anohren** [comment]
> we'd need to bikeshed the new label names

Thanks for giving me a reason to finally look up bikeshedding @saagarjha. That was a lot more interesting than I would have guessed. But as I understand it, bikeshedding is actually what we're currently doing. Are you proposing we take it even further? 😅

**Comment by saagarjha** [comment]
Yeah, I'm suggesting taking it to the next level ;) We should probably look into prior art of what a dialog with an affirmative response not being the default option should look like.

**Comment by alejx** [comment]
Ping

**Comment by saagarjha** [comment]
Oh, I'm assigned on this issue. Still not sure how we should present this though…to be honest, I haven't looked into prior art.

**Comment by alejx** [comment]
@saagarjha No hurry since our next release should be UI (localization) changes free.
