### ISSUE TITLE
A BUG ABOUT fastforward and backforward

### ISSUE THREAD

**Issue by cuifeiran** [iina/iina#2294]
I set the right-click in the configuration file to Fast Forward for 5 seconds, exit and then open, but it doesn't work. Fast forward 20 seconds by default
It's no use trying to uninstall and reinstall

- macOS  10.14.2 
- IINA   1.0.1 Build 103 

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by alejx** [comment]
Please use exact instead.
![image](https://user-images.githubusercontent.com/20237141/52545341-667a5a80-2d7c-11e9-9ada-3139554d0ef0.png)

**Comment by cuifeiran** [comment]
but how can I find this interface？I didn't find it in preference

**Comment by lhc70000** [comment]
Please check out this.

https://github.com/iina/iina/wiki/FAQ#why-the-seeking-time-is-not-precise-when-pressing-arrow-keys

**Comment by cuifeiran** [comment]
Thank you for using your advice to solve the problem perfectly.I really prefer IINA :）
