### ISSUE TITLE
Can add [UI Language] options(not [subtitle language])? / 能否添加【界面语言】的选项（不是【字幕语言】呀）

### ISSUE THREAD

**Issue by iSwfe** [iina/iina#2298]
希望添加个【界面语言】的选项
使用多语言环境的macOS时，iina的界面语言也跟着系统变动，很多专业的参数一时看不懂。
所以希望添加【界面语言】选项，类似钉钉这样：
![image](https://user-images.githubusercontent.com/20889699/52553588-efe26900-2e1e-11e9-8a06-66496e13e36b.png)
设置好后就可以固定iina的界面语言，不被系统环境所影响。

**Comment by alejx** [comment]
如果看不懂的话，为什么不直接使用中文系统呢？

**Comment by iSwfe** [comment]
> 如果看不懂的话，为什么不直接使用中文系统呢？

很简单，系统要在多处使用，系统一般跟着地区而改变语言显示，这样使用比较方便。但是iina设置专业术语太多就蛋疼了，进去要反应一会儿。。。

**Comment by xudong7930** [comment]
改中文:   defaults write com.colliderli.iina AppleLanguages '("zh-cn")'

**Comment by iSwfe** [comment]
> 改中文: defaults write com.colliderli.iina AppleLanguages '("zh-cn")'

NICE! ~~~
