### ISSUE TITLE
Blue Screen displayed when playing video

### ISSUE THREAD

**Issue by SensehacK** [iina/iina#2305]
**System and IINA version:**

- macOS 10.13.6 
- IINA v1.0.1 

**Expected behavior:**

The Video should be playing instead of displaying blue screen.

**Actual behavior:**

The video is playing with sound properly but isn't displaying any video, just full blue screen. Even resizing or playing the next video off the playlist doesn't seem to work.

Note: Thumbnails Scrobble / Seeking display just fine with proper video but the main video is still Blank Blue Screen.
It happens once in a while & only solution for me was to `Quit Application` & then restart the video again.

</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

I still haven't got the steps to reproduce it yet.

- [ ] MPV does not have this problem.
The issue has been raised for Windows 10.
I'm running Mac OS X. So raised the issue. 
[Link Windows 10](https://github.com/mpv-player/mpv/issues/6367)

**How often does this happen?**

Once in a while when playing mp4 files & it grasps all of the files under that directory with subtitles also been downloaded.

**Comment by lhc70000** [comment]
I believe that it's a mpv/ffmpeg problem. As a workaround please try disabling hardware decoding and wait for updates in upstream libraries.
