### ISSUE TITLE
Outdated youtube-dl

### ISSUE THREAD

**Issue by L3rchal** [iina/iina#2308]
**System and IINA version:**

- macOS 10.14.3
- IINA 1.0.1

**Expected behavior:**
To watch youtube video via INNA.

**Actual behavior:**

There was an error. I tried manually `youtube-dl` command cli and noticed same bug for same video. I solved the problem updating youtube-dl and replacing one in application path. 

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
Every time. youtube-dl is broken.

**Comment by alejx** [comment]
Will update youtube-dl in our next release.

**Comment by L3rchal** [comment]
Closing due duplicate of https://github.com/iina/iina/issues/2303
