### ISSUE TITLE
too high CPU usage when output on 4k display

### ISSUE THREAD

**Issue by jfdnet** [iina/iina#2310]
**System and IINA version:**

- macOS 
- IINA 
- Macbook Air 2018

**Expected behavior:**
Low CPU usage (below 20%) when output on 4K display

**Actual behavior:**
High CPU usage (above 70%) when output on 4k display
Same issue happened when switched to MPV 
But normal on using VLC or Movist

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
every time

**Comment by inflation** [comment]
Then please contact with them to see if anything could help.
