### ISSUE TITLE
翻译可有从项目中独立出一个项目吗，全是翻译的commit。。。

### ISSUE THREAD

**Issue by bluesummerv** [iina/iina#2316]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by alejx** [comment]
不可以。
