### ISSUE TITLE
打开视频是总是显示上一个播放的画面！！！

### ISSUE THREAD

**Issue by sailxp** [iina/iina#2330]
[打开视频是总是显示上一个播放的画面！！！，最新版本还是这样！！]
比如打开《巴比龙》却显示上一个播放的《波西米亚狂想曲》的画面，能不能改成黑屏呢？
![2019-02-25 2 24 09](https://user-images.githubusercontent.com/47845368/53318178-57151880-3909-11e9-88f7-cd9b68467c85.png)

**Comment by jkpang** [comment]
> [打开视频是总是显示上一个播放的画面！！！，最新版本还是这样！！]
比如打开《巴比龙》却显示上一个播放的《波西米亚狂想曲》的画面，能不能改成黑屏呢？

你使用的是哪个版本？我这边v1.0.2表现正常   @sailxp 

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by sailxp** [comment]
> > [打开视频是总是显示上一个播放的画面！！！，最新版本还是这样！！]
> > 比如打开《巴比龙》却显示上一个播放的《波西米亚狂想曲》的画面，能不能改成黑屏呢？
> 
> 你使用的是哪个版本？我这边v1.0.2表现正常 @sailxp
> 
> Sent from [PPHub For GitHub](https://itunes.apple.com/cn/app/id1314212521)

我用的也是1.0.2

**Comment by sh2sg** [comment]
it happens if "Quit after all windows are closed" is un-checked.

**Comment by sailxp** [comment]
> it happens if "Quit after all windows are closed" is un-checked.

Thank you！

**Comment by inflation** [comment]
Duplicate with #2197.
