### ISSUE TITLE
Issue about subtitles in full-screen. 

### ISSUE THREAD

**Issue by Sponge-bink** [iina/iina#2331]
**System and IINA version:**

- macOS 10.14.3 
- IINA 1.0.2 

**Expected behavior:** Subtitles in full screen to be aligned from edges of the screen instead of edges of the video. Pic attached.

<br>
<img width="2304" alt="image" src="https://user-images.githubusercontent.com/33798984/53323791-1d98d900-391a-11e9-88e7-f30e8fceef4d.png">

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.
MPV act like this too, but some former version of IINA aligns subtitles from the edges of screen instead. Probably a better way to get the most out of the screen. :)

**How often does this happen?**

Always.

**Comment by inflation** [comment]
![cleanshot 2019-03-05 at 11 36 08](https://user-images.githubusercontent.com/2375962/53820979-e2f6f800-3f3a-11e9-9e1d-afa11cd38958.png)
It exactly says here. 

P.S. Letterbox means "黑边" if you don't know it.

**Comment by Sponge-bink** [comment]
> ![cleanshot 2019-03-05 at 11 36 08](https://user-images.githubusercontent.com/2375962/53820979-e2f6f800-3f3a-11e9-9e1d-afa11cd38958.png)
> It exactly says here.
> 
> P.S. Letterbox means "黑边" if you don't know it.

Didn’t notice that! Thanks!
