### ISSUE TITLE
Window focus on click

### ISSUE THREAD

**Issue by steveooo9** [iina/iina#2332]
Other apps need a single click to focus on the clicked window. Most native media player don't have this, which means on a single click into the unfocused window, the click get's recognized by the app immediately.

Would be great to have the option to switch between this, because normally, you expect to click first to focus and click second to an action.

Would be great to have this in IINA!

**Comment by alejx** [comment]
I've tried iTunes and QuickTime, they responded the first click when clicking on buttons. Not sure what action you are talking about. Did you bind single click to some action?

**Comment by steveooo9** [comment]
@alejx That's right. But this single-click behavior is somewhat inconsistent with other apps like Chrome or Finder, where you need to click first to focus and then click for action.

Would be great if there could be a option to switch the behavior to the ones you find in apps like Finder, Chrome, ..., so:
Option to have the logic to click for focus and click for pausing/starting a video.
