### ISSUE TITLE
Customized key binding not working. 

### ISSUE THREAD

**Issue by Sponge-bink** [iina/iina#2335]
**System and IINA version:**

- macOS  10.13.4
- IINA  1.0.2 Build 105

**Expected behavior:** Seek backwards and forwards by the value I set in the key binding config file. 

**Actual behavior:** Seek backwards and forwards by some random value, like 10 s, 1 s, 8 s, or 6 s.

- [ ] MPV does not have this problem. MPV seems like to act the same. 

**How often does this happen?**
Always.

**Comment by lhc70000** [comment]
Check out this: https://github.com/iina/iina/wiki/FAQ#why-the-seeking-time-is-not-precise-when-pressing-arrow-keys
