### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by cc3t** [iina/iina#2343]
- macOS: 10.14.3 Mojave
- IINA:  1.0.2

I just played a *.mkv video with higher than 100% cpu. Even I paused the video, it still occupied 90+% cpu usage. I tried ⌘+i to check the hw decoder. It showed "videotoolbox". Additionally I tried VLC to play the same video, but it just occupied less than 40%.

IINA is a modern and beautiful player. Hope you guys can fix it.

**Comment by inflation** [comment]
It could use a lot of CPU when generating thumbnails for preview. This would only happen at the first time you open the video. 

You can disable the feature and see if anything changed.
