### ISSUE TITLE
Adding Custom (mpv) audio filter with no values causes crash

### ISSUE THREAD

**Issue by ekstasis** [iina/iina#2348]
**System and IINA version:**
- macOS:   10.13.6 
- IINA:         1.0.2

**Crash:**
Creating a new Custom (mpv) audio filter with both "Filter value" and "Filter name" fields empty causes a crash.

 I can work on this if you'd like.  I suggest that the Add button be disabled if the value and name fields are blank.  (I'm a newb, but I think I can figure this out)

**Cause:**
MPVFilter.swift:129
`MPVFilter.init?(rawString: String)`  is called with `rawString` "=", so `splitted.count` is 0, which triggers the guard statement here:

```
    let splitted = rawString.split(separator: "=", maxSplits: 1, omittingEmptySubsequences: true).map { String($0) }
    guard splitted.count == 1 || splitted.count == 2 else { return nil }
```
The actual nil unwrapping and crash happen in FilterPresets.swift:164:
```
static private let customMPVFilterPreset = FilterPreset("custom_mpv", params: ["name": PM.text(defaultValue: ""), "string": PM.text(defaultValue: "")]) { instance in
      return MPVFilter(rawString: instance.value(for: "name").stringValue + "=" + instance.value(for: "string").stringValue)!
  }
```

**Steps to reproduce:**
1. Select "Audio Filters..." from the Audio menu
2. Hit + button to add a filter
3. Select "Custom (mpv)"
4. Hitting "Add" button without giving a name or value causes a crash.

Creating a "Custom (FFmpeg)" filter with no parameters does not cause a crash; instead it creates filter with string "lavfi=[=]"

**Comment by lhc70000** [comment]
Thanks, please feel free to open a pull request.
