### ISSUE TITLE
Speed adjust keyboard shortcut inconvenient

### ISSUE THREAD

**Issue by mymmoonoa** [iina/iina#2353]
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.2

why in old IINA verison, keyboard shortcut [] can be used to multiply speed by 1.1.
After update to 1.02, [] shortcut is removed. Instead command +[] will divide or multiply speed by 2.
Can we get the old feature back or can we specify the coefficient for divide or multiply? 
*2 or /2 is really too fast or slow for watching videos

**Comment by lhc70000** [comment]
Please add or customize them by your self: https://github.com/iina/iina/wiki/Manage-Key-Bindings#key-bindings

**Comment by mymmoonoa** [comment]
@lhc70000 Thanks for you help, it works.
command+] > multiply speed by 2.0x. The default coefficient is not so reasonable. It's better if we can change the default IINA configuration.
