### ISSUE TITLE
Smaller steps for playback speed

### ISSUE THREAD

**Issue by jrz** [iina/iina#2361]
Playback speed currently is 2x or 0.5x.
This is fairly useless unless you're skipping. It'd be great if the steps would be incremented by 0.25.

**Comment by lhc70000** [comment]
You can customize them freely in Preferences - Key Bindings by changing the actions for ⌘[ and ⌘].

See https://github.com/iina/iina/wiki/Manage-Key-Bindings#key-bindings.

Note that you can also change the speed by dragging the slider in sidebar (video quick settings).

**Comment by jahirfiquitiva** [comment]
I found this after searching the issues and almost creating a new one and I can say that it isn't really intuitive. Hope there was a more easy to access way to change the playback speed, like VLC, for example. 😕 Thanks anyways for the great player.

**Comment by Pash237** [comment]
You can now press ⌥⌘[ and ⌥⌘] to adjust playback speed in smaller steps.

**Comment by plibither8** [comment]
⌥⌘[ and ⌥⌘] is awesome! I would also love it if we could __increment_/_decrement_ the playback speed (e.g. 0.25) instead of just multiplying.

**Comment by PostsDesert** [comment]
You can increment/decrement the playback speed by changing the actions for `⌘[` and `⌘]` in Preferences - Key Bindings.

I set `⌘[` to `add speed -.1` and `⌘]` to `add speed .1`.

Source: https://superuser.com/questions/1733076/how-do-i-configure-mpvs-speed-to-add-instead-of-multiply
