### ISSUE TITLE
Feature Request: web browser plugin for safari that plays unsupported codecs (eg webs) in the web page

### ISSUE THREAD

**Issue by ghost** [iina/iina#2362]
**System and IINA version:**

- macOS 14.3
- IINA 1.0.2

**Expected behavior:**

Hello. This is more of a personal suggestion, because I don't think many people face this problem, but if this can be achieved by the IINA team, then that would just be awesome.

I frequent a lot of sites that use the WebM format to display their video content. It is also known that Apple doesn't like playing with WebMs since the Safari browser just doesn't work these formats. Now, there is the option of just downloading Google Chrome and playing WebMs on that, but I feel that Safari's are better optimised for Macs, and if this one hiccup can be avoided, that would make at least my general experience fantastic.

Until a few macOS releases ago, to play WebMs natively in Safari, one had to download the VLC browser web plugin, but the VLC seems to have abandoned the project, and the latest release seems to be unsupported by Mojave and Safari 12.0.3.

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by saagarjha** [comment]
> the latest release seems to be unsupported by Mojave and Safari 12.0.3

I'm pretty sure that's because the plugin API for this has been removed in macOS Mojave :/

> if this can be achieved by the IINA team, then that would just be awesome

I would tend to agree–if you *do* know a way to make this work I'd be happy to look at it!

**Comment by kraftpunk97** [comment]
Unfortunately, this is something beyond my programming capabilities as of now. If I can, I'll definitely come back to this in the future. Thanks!

**Comment by saagarjha** [comment]
Closing, as we can't implement this.
