### ISSUE TITLE
Subtitles size inconsistent

### ISSUE THREAD

**Issue by hsuehpascal** [iina/iina#2363]
**System and IINA version:**

- macOS Mojave Version 10.14.4 Beta
- IINA 1.0.2

**Expected behavior:**
The size of subtitles should preferably be in consistent proportion to that of the video.

**Actual behavior:**
Below are screenshots I took when streaming the same Youtube video in normal size and full screen. Subtitles are set to 36pt, Helvetica Neue, positioned 100%.
<img width="1072" alt="Screen Shot 2019-03-14 at 3 17 06 AM" src="https://user-images.githubusercontent.com/31957703/54308140-528a7880-4608-11e9-9d8d-1e3ab42ae211.png">
<img width="1440" alt="Screen Shot 2019-03-14 at 3 17 20 AM" src="https://user-images.githubusercontent.com/31957703/54308142-53bba580-4608-11e9-8811-cb1e499a6dfc.png">

As you can see, the subtitles in the photos are not at the same position nor of the same size in relation to the video, which means I would need to configure different settings when playing videos 1:1 from when in full screen. 

I've noticed the subtitles are always relatively bigger in full-screen mode, and for wide screen videos they're almost left in the lower black margin when I position them to 100%. 

My speculation is that the subtitles enlarge in proportion to the height of the window (instead of the video itself), which when in full screen includes not only the playback area but the black spaces around it. 

Personally I think this can be seen as a bug that should be fixed (though I am no expert in mpv configurations), or at least an option for users who like the size of their subtitles to be consistent compared to the videos.

**Comment by lhc70000** [comment]
You may need to uncheck "Scale subtitles with window size" in Preferences - Subtitle - Position.

**Comment by hsuehpascal** [comment]
I tried what you proposed but it did not work. What I meant by my post is that I want the subtitles scaled alright but somehow in full screen the scale and position seem off, or, as I said, inconsistent. This can be observed when you enlarge the same video so the window fits the screen (1st screenshot) and compare it to when you simply put it in full screen (2nd screenshot).
<img width="1440" alt="Screen Shot 2019-03-14 at 5 42 46 PM" src="https://user-images.githubusercontent.com/31957703/54346842-b9e40f00-4680-11e9-8592-64df6cae1e2b.png">
<img width="1440" alt="Screen Shot 2019-03-14 at 5 42 51 PM" src="https://user-images.githubusercontent.com/31957703/54346846-bc466900-4680-11e9-8339-8f2651bab9a8.png">

As is self-apparent the positioning as well as scaling is different in the two instances despite the video being display at exactly the same size.

**Comment by jerkstore369** [comment]
the subs should probably be more consistent but the location of them is proper in full screen. It is better to have the subs in the black bars whenever possible. Why would you want the subs to be over the image when there is space below it? You know there are hotkeys to manually move the subs wherever you want, right?

**Comment by hsuehpascal** [comment]
Well I wouldn't be so sure. It's completely preferential for all I know, and I'm proposing fixing the size as well as the placement simply because I think it might be easier for the coding process (but I know nothing about coding so do correct me); plus, the size of the black bars vary according to videos and I don't think it'll be visually pleasant just to put the subtitles in the very bottom of every video.

**Comment by lhc70000** [comment]
@hsuehpascal Then there's also an option "display subtitles in letterboxes while in full screen" for this.

**Comment by hsuehpascal** [comment]
> @hsuehpascal Then there's also an option "display subtitles in letterboxes while in full screen" for this.

OMG Thank you so much.
