### ISSUE TITLE
音乐模式做一个合盖不睡眠的功能是不是很赞

### ISSUE THREAD

**Issue by iAPPOpen** [iina/iina#2365]
不知道有这种需求的是不是只有我一个人，感觉这种功能挺实用的，感觉这种功能应该是挺特别的，不知道实现起来有难度吗

**Comment by lhc70000** [comment]
@iAPPOpen 据我所知只有把睡眠延迟几分钟程度的 API，没有阻止睡眠的

**Comment by iAPPOpen** [comment]
> @iAPPOpen 据我所知只有把睡眠延迟几分钟程度的 API，没有阻止睡眠的

果然是有难度的，那就只能用专门软件来实现了。
多问一下，不知道iina有没有开发路线图，主要是想知道下一步开发重点是什么。
说实话我的Mac上还安装了一个Windows纯粹就只为PotPlayer这一个软件了，如果iina支持书签功能我可能就可以删了Windows了。
iina现在有捐助渠道了吗。

**Comment by lhc70000** [comment]
最近很忙，开发速度非常不稳定，完全看时间和心情。正在做的主要就是插件系统了，书签也打算尽快做。捐助现在还没有，毕竟今年到现在都没怎么在 IINA 上努力，也不好意思要捐款对吧（

**Comment by iAPPOpen** [comment]
> 最近很忙，开发速度非常不稳定，完全看时间和心情。正在做的主要就是插件系统了，书签也打算尽快做。捐助现在还没有，毕竟今年到现在都没怎么在 IINA 上努力，也不好意思要捐款对吧（

不着急，毕竟iina现在可能连副业都算不上，肯定不能耽误主业，而且现在的iina说实话已经非常之强了，即使只是现在的完成度已经完全可以碾压macOS平台所有同类app了，等他们几年都够他们追的。甚至有些方面都已经超过邻平台的大神PotPlayer了，我本来以为PotPlayer会是个一直要用到死的软件，没想到居然出现了一个可以取代它的产品，而且还是macOS，让Windows对我的粘性进一步降低，只是这一点，iina就很了不起了。。
㊗️工作顺利😊

**Comment by noisnemid** [comment]
私以为这个场景要结合另外两种情况综合考虑：
高级播放器有一个比较有用的功能是播放完毕后的定制动作（关机、休眠/睡眠、退出……），此外MACOS的合盖动作在偏好设置里有系统层面的选项，但是如果由播放器控制的话，在“合盖后指定时间后重新将休眠/电源的控制权交还给操作系统”这个设计将会变得比较复杂化……私人感觉。

**Comment by LuvLetter** [comment]
macOS 不支持 S0ix, 做不到.
