### ISSUE TITLE
Opening a new video from the Chrome extension should use same window

### ISSUE THREAD

**Issue by jschuur** [iina/iina#2370]
- macOS 10.14.3
- IINA 1.0.2 Build 105
- IINA Chrome extension 2.0.0

**Expected behavior:**

When browsing my YouTube subscription list, I assumed that any video launched via the Chrome extension (and the 'Open this link in IINA' context menu) would open in the same video as the previous YouTube video I launched in the same way.

**Actual behavior:**

Right now, it opens in a new video every time, despite the 'Always open new media in a new window' IINA option being unchecked.

**How often does this happen?**

Consistently every time I open a new video via YouTube like this.

**Comment by anohren** [comment]
I also find it a bit unpredictable at times. As a workaround I've configured the extension (Firefox) to always show a menu of options, which requires an extra click but usually results in fewer surprises.
