### ISSUE TITLE
Auto-load all available subtitles if only one movie is found in a folder

### ISSUE THREAD

**Issue by megadr01d** [iina/iina#2373]
**System and IINA version:**

- OS X 10.11.6
- IINA 1.0.2 build 105

**Expected behavior:**

Auto-load subtitle files without video filename match:

```
Movie Example

Night Of The Living Dead.mkv
Subtitle [English].srt
Subtitle [Portuguese].srt
```

```
Series Example

[S01 E01] [01] Eye Of The Beholder.avi
[S01 E01] [01] Subtitle [English].srt
[S01 E01] [01] Subtitle [Portuguese].srt
[S01 E02] [02] The Last Flight.avi
[S01 E02] [02] Subtitle [English].srt
[S01 E02] [02] Subtitle [Portuguese].srt
```

**Actual behavior:**

No subtitle auto-loading.

**Steps to reproduce:**

Enable `Subtitle > Auto load > Detect intelligently by IINA`

**How often does this happen?**

Always.

**Comment by megadr01d** [comment]
Actually the series example works because the subtitles already include part of the video filename (`[S01 E01]...`) so the matching is applied.

I think this issue is only when one movie is found in the folder. Movist has an option to "load all subtitle files when only one movie in folder" so, the logic would be if only 1 video file is found, auto-load all subtitles without doing any filename matching.

**Comment by megadr01d** [comment]
Will `--sub-auto=all` work?
https://mpv.io/manual/master/#options-sub-auto

**Comment by inflation** [comment]
> Will `--sub-auto=all` work?
> https://mpv.io/manual/master/#options-sub-auto

This one actually messes with IINA. But you can add it then disable IINA's detection, and see if it works.

**Comment by megadr01d** [comment]
I just had the time to test it now and.. yeah, it works for for single movies (don't even have to disable IINA's detection) but it doesn't for series, so I can't have it both ways.
Let's leave this open as a feature request, then.

Maybe an internal change in IINA to detect if only one movie is found in the folder, to enable `--sub-auto=all` and disable it otherwise.

**Comment by megadr01d** [comment]
Not pursuing this anymore. I will go back to naming subtitles after the movie name, so closing.
