### ISSUE TITLE
[Feature Request] Add mutiple URLs to playlist

### ISSUE THREAD

**Issue by tomyang001** [iina/iina#2377]
**System and IINA version:**

- macOS 10.14.3
- IINA 1.0.2

**Expected behavior:**

Add mutiple URLs to playlist at the same time. I can copy dozens of URLs from a nginx WebDAV webpage, but couldn't paste them into the playlist at once. Or the Safari plugin can be improved to detect and add all the supported URLs on the webpage.

**Comment by inflation** [comment]
You can save it one by a line to a `.m3u8` file and open it as a playlist.
