### ISSUE TITLE
No auto-line-change for subtitle in Chinese

### ISSUE THREAD

**Issue by yingsha** [iina/iina#2380]
When playing videos with subtitle that contain extra long text in one paragraph, the English subtitle has auto-line-change just fine.  But the Chinese subtitle won't auto-line-change.  Make it display not complete.

**Comment by HarukaMa** [comment]
IIRC it's the limitation of underlying subtitle renderer. It's usually subtitle creators' responsibility to make sure issues like this does not happen, but well...

If your subtitle is in `.srt` or `.ass` format, you could either report it to `libass` or fix the subtitle yourself.
