### ISSUE TITLE
use hue sync caused lag

### ISSUE THREAD

**Issue by tge4785** [iina/iina#2385]
**System and IINA version:**

- macOS 10.14.1
- IINA latest

**Expected behavior:**

wer.

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>
 I use hue sync while using iina. The video looks like bit laggy, but if I stop sync light sync. The video is smooth.
I checked cpu and memory. They are normal. So I don't know what happened . It's fine if I watch video on my browser.
I tried to attach my log ,but GitHub said it's empty. sorry about that
<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
Unfortunately, without a log we know little about what happened. Since none of us has the experience with Hue Sync, there's nothing we can do.

**Comment by tge4785** [comment]
hey i got a log file. I was watching movie with Hue Sync and it still lagged.
So i hope you can look at it.
thanks
[iina.log](https://github.com/iina/iina/files/3123748/iina.log)
[mpv.log](https://github.com/iina/iina/files/3123749/mpv.log)

**Comment by saagarjha** [comment]
We appreciate the log files, but I don't think we can do much to solve this issue. Hue Sync likely does something funny to the display which is causing IINA to stutter, but we don't really know how to fix this. I'm going to close this unless we get more information on why this might be happening, and confirmation that this is in fact a bug with IINA.
