### ISSUE TITLE
toggle full screen without pause

### ISSUE THREAD

**Issue by shengyang998** [iina/iina#2386]
**System and IINA version:**

- macOS 10.14.4 (18E226)
- IINA 1.0.2 Build 105

**Expected behavior:**
toggle full screen without pausing the video temporary

**Actual behavior:**
the video temporary pause when toggle full screen

- [ ] MPV does not have this problem.

I have found that mpv **does** have the same problem if you use the ffmpeg installed by `Homebrew`. However, the problem gone if you build ffmpeg by yourself. 

Even though, I'm still hoping this problem can be solved in `iina` permanently.

**Comment by alejx** [comment]
During the window is animating to full screen, the video is not pausing. We suspend the drawing from mpv, so that what you see during the animation is the picture when the full screen animation is started.  We have tried to let mpv continue drawing during the animation, however it causes performance issues and makes the entire animation laggy. It is basically because during the animation, the geometry is constantly changing, and when mpv gets a changed size of window, it needs a significant time to calculate the video.

**Comment by shengyang998** [comment]
Is it possible to use a certain version of ffmpeg to make it work? 

It is working smoothly even on my Macbook Air 2013 with a ffmpeg and mpv built locally. I build the ffmpeg and mpv with certain flag on (for supporting libmysofa). Maybe this is the reason why it worked.

You can see the flags I am using [right here](https://github.com/shengyang998/mpv-build/blob/master/runme_shared.sh)

**Comment by megadr01d** [comment]
> During the window is animating to full screen, the video is not pausing. We suspend the drawing from mpv, so that what you see during the animation is the picture when the full screen animation is started. We have tried to let mpv continue drawing during the animation, however it causes performance issues and makes the entire animation laggy.

Movist doesn't pause or suspend the video and, as a result, it's incredibly laggy when switching to/from fullscreen (incidentally "pausing" the video more than desired, in the process), something that annoyed me for years.

I like how IINA behaves and, as far as I'm concerned, I wouldn't even mind if it paused between states.
Some of us are on old hardware (in my case, a 2007 Santa Rosa MacBook Pro with two busted fans and a capped down CPU on account of running without a battery) and every performance gain is welcome.

Just my opinion.

**Comment by kwmc-lucas** [comment]
These two seem to be the same:
https://github.com/iina/iina/issues/3212
https://github.com/iina/iina/issues/3354

Yeah, mpv's implementation looks jittery, QuickTime on the other hand is buttery smooth... I wonder how?
