### ISSUE TITLE
[Feature Request] Parameters for Playback History

### ISSUE THREAD

**Issue by BarryMode** [iina/iina#2392]
**System and IINA version:**

- macOS 10.14.4
- IINA 1.0.0

**Expected behavior:**

With playback history, it would be nice if you could have a blacklist or whitelist of directories that are logged in playback history. Use case: say for work, I have several client videos that I watch from my Downloads folder. Later on when I look for where I left off on my last show in history, I have to skim through the client videos in order to find my show. Now I realize that you can simply just search for what you need, but it would be nice not to have the option to not even log those files in the first place.

If the playback history can't be limited in this way, then another approach would be to have an option to open a video that would not record it in the playback history. I suppose this is comparable to how a private tab works in a browser in that it doesn't log sites in the history.

**Actual behavior:**

When playback history is enabled, all videos are logged.

**Comment by alejx** [comment]
Why closed this?
