### ISSUE TITLE
希望添加音视频相关参数可显示功能

### ISSUE THREAD

**Issue by yanglaoxi** [iina/iina#2394]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
请说明哪些参数

**Comment by Gentoli** [comment]
Cmd + i
