### ISSUE TITLE
Playlist reordering via drag an drop not reflected in UI

### ISSUE THREAD

**Issue by vassudanagunta** [iina/iina#2397]
**System and IINA version:**
- macOS 10.14.3
- IINA 1.0.3

**Expected behavior:**
Can re-order items in playlist panel by drag and drop.

**Actual behavior:**
Drag and drop does actually re-order the playlist, but the UI does not reflect the change unless you hide/show the panel. 

This is very inconvenient if you are doing more than one drag and drop, as you must hide/show the playlist panel to see the latest state. 

**Steps to reproduce:**
1. open multiple videos in IINA so you have a playlist.
2. show the playlist panel.
3. drag and drop to re-order one or more items.
    - Note that list does not change.
    - But the actual playback will reflect your change.
4. hide and then re-show the panel. It will show the list as re-ordered.

**Comment by alejx** [comment]
Does it also happen in v1.0.2 or older versions?

**Comment by alejx** [comment]
Thanks. Fixed in develop.
