### ISSUE TITLE
When I begin playing a video, the previous one shows for an instant

### ISSUE THREAD

**Issue by erujp** [iina/iina#2402]
**System and IINA version:**

- macOS 10.13.6 (17G6029) 
- IINA 1.0.3 Build 106 

**Expected behavior:**

When I open a new file, the previous one should NOT show, even for an instant.

**Actual behavior:**

When I open a new file, if IINA is open, the last scene of the previous file I watched shows for an instant, like a flash, at the beginning.
You can see this behaviour in this video:
https://www.dropbox.com/s/cztmh2q706jflnw/IINA%20bug.mp4?dl=0

This could potentially be very embarrassing in the presence of other people (depending on what kind of video you watched before).

If IINA is closed and launches at the time of opening the new file, it does not show the previous video. 

<br>

**Steps to reproduce:**
It just happens every time I open a video if IINA is already open.

- [x ] MPV (0.29.1) does not have this problem.

**How often does this happen?**
Every single time.

Thank you!

**Comment by inflation** [comment]
Duplicate with #2197

**Comment by sherifabdlnaby** [comment]
> Duplicate with #2197

It is duplicate of #2197 indeed, but I believe #2197 is tagged incorrectly. this is definitely a major bug and not a ui/ux enhancement! and can lead to many awkward privacy situations.
