### ISSUE TITLE
Streaming through Video camera -> HDMI -> USB-C -> Macbook Pro

### ISSUE THREAD

**Issue by paaljoachim** [iina/iina#2406]
Hey

It would be great if I could plug my video camera (Sony FDR Ax33) through HDMI to a HDMI adapter to USB-C to my Macbook Pro. To show a recording or playback. To be used as a web camera for streaming to Youtube or Facebook. Or to just show a recording. Perhaps similar to plugging in a video camera with hdmi to the tv screen to see a recording.

Perhaps like this thing: https://www.youtube.com/watch?time_continue=2&v=o6KsYpEPoss
or other similar devices.

Thanks..:)

**Comment by YourMJK** [comment]
No Mac currently supports native video _input_ over HDMI or Displayport, only output. You need a separat capture card to do this.

**Comment by paaljoachim** [comment]
Thanks for the reply @YourMJK 

I end up purchasing Elgato Cam Link. It worked well as an adapter between the Video Camera and The Mac.

**Comment by YourMJK** [comment]
Alright, great that you got it to work! If the it's resolved, please consider closing this issue.

**Comment by paaljoachim** [comment]
Will do!
