### ISSUE TITLE
It'd be great if there was a feature to convert the audio to mono.

### ISSUE THREAD

**Issue by rickwierenga** [iina/iina#2413]

**Comment by nimrodbens** [comment]
you can do it on the mac. 

system preferences -> accessibility -> audio -> play stereo audio as mono

**Comment by rickwierenga** [comment]
Thanks!

**Comment by lacek** [comment]
I prefer not to change system-wide setting and found that down mixing can be done using the audio filter in IINA. E.g. using ffmpeg pan filter:

1. IINA -> Audio -> Audio Filters -> "+"
2. Choose "Custom (FFmpeg)"
3. Enter `mono|FC<FL+FR` for Filter value (check ffmpeg [doc](https://ffmpeg.org/ffmpeg-all.html#pan-1) and [wiki](https://trac.ffmpeg.org/wiki/AudioChannelManipulation) for details)
4. Enter `pan` for Filter name
5. Press "Add" and the list in Audio Filters should now contain an item with Filter String `lavfi=[pan=mono|FC<FL+FR]`

Click save to assign a name (and optionally a shortcut key) for future use from the Saved Audio Filters with a single click (or a key press of shortcut key).
