### ISSUE TITLE
Vertical video screenshots broken

### ISSUE THREAD

**Issue by Edgeburn** [iina/iina#2415]
**System and IINA version:**

- macOS 10.14.3 
- IINA 1.0.3 

**Expected behavior:**
When taking a screenshot of a vertical video, it should take the screenshot normally. (see image 1)
<img width="557" alt="image 1" src="https://user-images.githubusercontent.com/18710959/55913638-14ef2000-5bb3-11e9-90da-3c233bd201c3.png">

**Actual behavior:**
The resulting screenshot is "compressed" and lines appear on the side. (see image 2) 
![image 2](https://user-images.githubusercontent.com/18710959/55913706-3c45ed00-5bb3-11e9-81cd-31f3c461c6b1.jpg)

**How often does this happen?**
Every time. This does not happen if I rotate the video horizontally and then take the screenshot.

**Comment by themysciraa** [comment]
Sorry to crash this place but I have the same problem when taking sceenshot of vertical videos that are rotated by their metadata. 

My video properties:
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 4942 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      **rotate          : 90**
      handler_name    : VideoHandler
    Side data:
      **displaymatrix: rotation of -90.00 degrees**

**Comment by aegamesi** [comment]
Potentially related to https://github.com/mpv-player/mpv/issues/5619

**Comment by jackthegiantkiller** [comment]
Same issue in Mac Sierra 10.12.6.
