### ISSUE TITLE
Video height is calculated incorrectly

### ISSUE THREAD

**Issue by saagarjha** [iina/iina#2417]
**System and IINA version:**

- macOS Mojave 10.14.5 Beta (18F108f)
- IINA 1.0.3

**Expected behavior:**
A 1920×1080 video shows up as such.

**Actual behavior:**
It shows up as 1920×1072. This size is corroborated by `mpv_get_property(…, "height", …)`.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by saagarjha** [comment]
Apparently disabling hardware decoding resolves the issue…

**Comment by YourMJK** [comment]
I am experiencing the same issue (IINA 1.0.3 Build 106) **but only in the inspector panel**.

While the video track in the menu and the video settings tab is listed as "… 1920×**1080** …" for example, in the "General" tab of the inspector panel it says "Size: 1920×**1072**".
Another example is 1920×**804** vs. 1920×**800**.

(tested with a few H.264 and HEVC MP4's, same video dimensions don't always have the same issue)

**Comment by lhc70000** [comment]
We get this value directly from mpv so apparently this is a mpv bug (especially if it's related to hardware decoding).
