### ISSUE TITLE
When using AirPods , it will be stuck 1s when playing after pause 

### ISSUE THREAD

**Issue by Mosaic67** [iina/iina#2421]
**System and IINA version:**

- macOS  10.14.4
- IINA  1.0.3 Build 106 (mpv 0.29.1)

**Expected behavior:**
Same as using the built-in sound when playing after pause

**Actual behavior:**
When using AirPods , it will be stuck 1s when playing after pause 

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lumanegi233** [comment]
Experiencing the same issue here, any info on how to resolve this?
