### ISSUE TITLE
1.0以后的版本都打不开

### ISSUE THREAD

**Issue by liweihao5253** [iina/iina#2422]
- macOS 10.14.4
- IINA 1.0.3

自从版本号升级到1.0之后，IINA均无法打开，表现为在dock上跳几下直接退出，连窗口菜单都没出现，所以我这里只能继续使用旧版。
系统控制台显示：Apr 14 11:02:15 liweihaodeMacBook-Pro com.apple.xpc.launchd[1] (com.colliderli.iina.35968[6434]): Service exited due to SIGILL | sent by exc handler[6434]

**Comment by lhc70000** [comment]
控制台中有没有崩溃报告？
![image](https://user-images.githubusercontent.com/8478049/56087935-35b3c000-5ea8-11e9-9a58-518adffec24b.png)

**Comment by liweihao5253** [comment]
控制台没有出现崩溃报告

发自我的 iPhone

**Comment by NathanZhengNaixian** [comment]
同样的问题，弹两下就消失了
报告在这里：
https://docs.google.com/document/d/1eWLWFPf3Nr0hqMvr77Wq8U7xP4DaVb92dlZ1yMkizmM/edit?usp=sharing

**Comment by NathanZhengNaixian** [comment]
不知道能不能看到， 实在不行我再去开个新 issue，

**Comment by lhc70000** [comment]
@NathanZhengNaixian 

你的链接需要给权限（设置所有人可见）。
开新 issue 吧，这个比较老了，可能不是一个问题。
