### ISSUE TITLE
Use monospaced digits font feature for chapter list in "Chapters" menu item

### ISSUE THREAD

**Issue by YourMJK** [iina/iina#2424]
**System and IINA version:**

- macOS 10.14.4
- IINA 1.0.3 Build 106

**Feature Request / "OCD-breaking bug":**

IINA should use the monospaced digits feature of the system font in the "Chapters" menu item which lists the chapters' timestamps along with their name.
This way the timestamps and names would all be nicely horizontally aligned (in columns) and therefore easier and more pleasant to read.

I think this can be achieved by setting the `NSMenuItem`'s `attributedTitle` to a `NSAttributeString` which has the specific font as an attribute.
The font could be obtained by calling [`NSFont.menuFont(ofSize: 0)`](https://developer.apple.com/documentation/appkit/nsfont/1533068-menufont) (to get the default menu font at it's default size) and adding the [monospaced numbers feature in the font descriptor](https://stackoverflow.com/a/42093667/3429396).

It would also be nice if as a separator between timestamp and chapter name, an _en-dash_ ("–", U+2013) or even an _em-dash_ ("—", U+2014) would be used, instead of a normal hyphen ("-") like it's currently.

Currently it looks like this:
<img width="222" alt="current screenshot" src="https://user-images.githubusercontent.com/37852512/56173195-f93dac80-5fec-11e9-9f62-98c242da1f7a.png">
As you can see, the chapter names here are _not_ nicely aligned in a column, just like the timestamp components and the separators _aren't_.

**Comment by anohren** [comment]
How about also padding all timestamps with zeros to the same length as the last timestamp? Then the titles would line up as well

**Comment by saagarjha** [comment]
<img width="350" alt="Screen Shot 2019-05-29 at 05 46 49" src="https://user-images.githubusercontent.com/13786931/58558247-29c05b00-81d5-11e9-9ca9-0fd505b7a1d1.png">
Interestingly, using the font descriptor doesn't seem to work with whatever font `NSFont.menuFont(ofSize:)` returns, so I substituted `NSFont.monospacedDigitSystemFont(ofSize:weight:)`.

**Comment by YourMJK** [comment]
Perfect! Thank you very much!
