### ISSUE TITLE
左右箭头为什么不是切换前后视频？

### ISSUE THREAD

**Issue by Smeegol** [iina/iina#2425]
为什么会有点击向左、向右箭头是设置播放速率，而不是切换播放列表前后的视频 这样傻的设定？

**Comment by xjbeta** [comment]
![issues.png](https://i.loli.net/2019/04/16/5cb558b68608a.png)

**Comment by Smeegol** [comment]
@xjbeta 这个应该成为默认的吧

**Comment by xjbeta** [comment]
这应该是参考 QuickTime 设计的
