### ISSUE TITLE
Keyboard shortcuts not being assigned correctly in custom sets

### ISSUE THREAD

**Issue by blowfish64** [iina/iina#2427]
**System and IINA version:**

- macOS 10.13.6 High Sierra 
- IINA 1.0.3 

**Expected behavior:**
Set a custom shortcut for Screenshot instead of the default Command+S.
I expect to have all the default shortcuts left as they were, and a custom assignment for the Screenshot function.

**Actual behavior:**
All the shortcuts are listed correctly with their default assigned key combos, and the Shortcut function is listed with my custom assignment, but no keyboard shortcut works aside from the custom one (that is, pressing S does make a screenshot, but other keys, such as Space for play/pause or arrows for search, do not work). Shortcuts are not even listed aside their corresponding menu items (only displayed for the aforementioned customized Screenshot function).

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
Go to Preferences pane > Shortcuts > IINA Default > Duplicate and create a custom set.
Name the set wherever you like.
Search for the Screenshot function and set it a custom key combo (I set "S").
Leave the menu and test the shortcuts.

- [ ] MPV does not have this problem.

**How often does this happen?**
Always. Even repeating the setting. Even by restarting the player with the key combo set.

**Comment by alejx** [comment]
Fixed in v1.0.4.
