### ISSUE TITLE
Light border - maximized window

### ISSUE THREAD

**Issue by JohnClay** [iina/iina#2430]
I'm pretty sure this is a macOS issue, but I'm hoping there's a workaround that can be implemented. It does seem to be [documented in other apps](https://github.com/Microsoft/vscode/issues/68789), though Amazon Music doesn't have the issue (presumably because it's not native).

After upgrading to 10.14, I'm noticing a light gradient border around files playing back when maximized (not full screen).

**System and IINA version:**

- macOS 10.14.4
- IINA 1.0.3 (106)

**Expected behavior:**

Zero/no gradient pixel border around playback window.

**Actual behavior:**

Light border is shown around maximized windows.

**Steps to reproduce:**

Maximize video file, observe edges of window. Most visible with dark content.

**How often does this happen?** Always

**Comment by JohnClay** [comment]
Looks like it's a known bug on 10.14/Mojave, but enabling dark mode support in the application can help mitigate:

https://github.com/electron/electron/issues/13164#issuecomment-462099631

**Comment by saagarjha** [comment]
This is how Apple styles apps using Dark Mode: it's a bit unfortunate, but not something we're going to go out of our way to mess with currently. Wontfix, unless there's a good reason for it to not be (for example, if getting rid of this is easy, or is a major blocker).
