### ISSUE TITLE
IINA plays no sound 

### ISSUE THREAD

**Issue by mnkyofatmn** [iina/iina#2433]
IINA plays no sound with all video formats. The volume button cannot be adjusted.

**System and IINA version:**

- macOS 10.14.4
- IINA 1.0.3

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by senn117** [comment]
I got the same problem like yours, [2374#](https://github.com/iina/iina/issues/2374#issuecomment-490491366).
Only waiting for a new version to cover this problem maybe..

**Comment by saagarjha** [comment]
Closing in favor of older issue.
