### ISSUE TITLE
/libmpv.dylib compiled with older version of Swift language

### ISSUE THREAD

**Issue by qiangzi611** [iina/iina#2439]
ld: /xxx/xxx/xxx/IINA/iina-develop/deps/lib/libmpv.dylib compiled with older version of Swift language (unknown ABI version 0x06) than previous files (unknown ABI version 0x07) file '/xxx/xxx/xxx/IINA/iina-develop/deps/lib/libmpv.dylib' for architecture x86_64

**Comment by saagarjha** [comment]
This is a spinoff of our Swift 5 support stuff. Until we update the libraries we ship with, you're going to have to [compile mpv manually](https://github.com/iina/iina#building-mpv-manually).

**Comment by saagarjha** [comment]
develop builds cleanly without warnings or errors with the latest toolchain, so I'm going to close this now.
