### ISSUE TITLE
 The system time and remaining battery capacity cannot be displayed in full screen state. Already set in the system settings.

### ISSUE THREAD

**Issue by WelKin2015** [iina/iina#2449]
**System and IINA version:**
- macOS 10.14.4
- IINA 1.0.3 Build 106

**Expected behavior:**
In full-screen mode, the system time and remaining power expected to be continuously displayed on the playback interface in a lighter color font, instead of triggering the interface to display related content each time,,like Movist does.

**Actual behavior:**

 Already set in the system settings.The system time and remaining battery capacity cannot be displayed in full screen state. I'm not sure there is something wrong with the settings ,or IINA is still not support this function.

<detiails>

</details>

**Comment by WelKin2015** [comment]
Sorry there is some issues with uploding the image.
Here is the IINA settings and playbakc interface.
![image](https://user-images.githubusercontent.com/15223736/57464981-480af900-72b0-11e9-8ed6-a975e08f6320.png)
![image](https://user-images.githubusercontent.com/15223736/57460238-4db01100-72a7-11e9-9e13-fa0e81cca2f7.png)
And here is the Movist interface
![image](https://user-images.githubusercontent.com/15223736/57465364-0b8bcd00-72b1-11e9-9c85-fcda13cebf6e.png)

**Comment by saagarjha** [comment]
I see battery/time information show up whenever the OSD does. Do you not?

**Comment by WelKin2015** [comment]
> I see battery/time information show up whenever the OSD does. Do you not?

Actually,I truly don't see the battery/time infomation while fullscreen displayed,like the screenshot shows.
Oh right, when the video control panel is displayed,there is battery/time info on the top-left corner.And as the control panel is hidden automatically,the battye/time info is hidden also.Is 
it alright?

**Comment by uiryuu** [comment]
Yes, this is the intended behavior.
