### ISSUE TITLE
打开CUE文件，章节信息乱码

### ISSUE THREAD

**Issue by goodryb** [iina/iina#2450]
**System and IINA version:**

- macOS  macOS10.14.4
- IINA  1.0.3 Build 106 

**Expected behavior:**

**Actual behavior:**
![image](https://user-images.githubusercontent.com/3907975/57464767-e21e7180-72af-11e9-96c5-1f8e486ab60b.png)

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by HarukaMa** [comment]
convert your CUE file to UTF-8 encoding and try again.
