### ISSUE TITLE
Feature request: Do not switch to IINA window when opening video via 'Open in IINA' browser extension browser with 'Enter Picture-in-Picture' enabled

### ISSUE THREAD

**Issue by Quenz** [iina/iina#2457]
If I have the 'Enter Picture-in-Picture' option enabled in the 'Open in IINA' browser extension, I'm suddenly switched to the 'This video is playing in picture in picture' window, pulling me away from my Chrome window and onto the desktop (assuming Chrome is in full-screen).

Instead, the video should simply begin playing in PiP, without dragging me away from my browser to put the background IINA window in focus.

**Comment by saagarjha** [comment]
As far as I'm aware, there is no way to prevent application activation through a URL scheme, which is what the extension uses. If someone figures out a way to do this, I'll reopen this issue.
