### ISSUE TITLE
[Feature Request] Netflix support?

### ISSUE THREAD

**Issue by SpookyiPhone** [iina/iina#2458]
Hi,

Is there a way to get Netflix working?
If not - could this be added? :)

Thanks,
Dave.

**Comment by saagarjha** [comment]
If youtube-dl can do it, we can; unfortunately they [can't right now](https://github.com/ytdl-org/youtube-dl/issues/1564). To be honest, I don't see this ever happening because Netflix uses DRM extensions to HTML video that youtube-dl (or anyone) is unlikely to ever support due to legal reasons :(
