### ISSUE TITLE
None of the subtitle options work?

### ISSUE THREAD

**Issue by kevinrenskers** [iina/iina#2460]
**System and IINA version:**
- macOS 10.14.5
- IINA 1.0.3 Build 106

**Expected behavior:**
There are a bunch of subtitle options to tweak the look and location of the subtitles. I'd expect those options to work :)

**Actual behavior:**
Sadly none of them actually seem to do anything, including the "display in letterbox while in full screen" option.

I have tried to check mvp, but I have no clue how to change preferences there? It wants me to create a .conf file and then opens it, that's it..?

**How often does this happen?**
Always

![Screen Shot 2019-05-19 at 20 51 01](https://user-images.githubusercontent.com/229384/57986736-10067180-7a79-11e9-917c-76db28d41c1d.png)

![Screen Shot 2019-05-19 at 20 50 41](https://user-images.githubusercontent.com/229384/57986737-10067180-7a79-11e9-9661-6dd072b16690.png)

**Comment by kevinrenskers** [comment]
Hm weirdly enough when I download the subtitles instead of using the ones that came with the movie itself, all the options do work just fine. What's the difference between downloaded subtitles and the ones that come with the movie? Why can one be moved down, and the other not?

![Screen Shot 2019-05-19 at 21 09 17](https://user-images.githubusercontent.com/229384/57986867-848de000-7a7a-11e9-8f06-69fd82eb4d9c.png)

**Comment by firewater2** [comment]
This is normal, uncorrectable behaviour. I'm not sure about the right terminology, but the subtitles in your first picture are essentially bitmap, rendered like hardcoded images (you can tell beside not being able to modify them, by their strange ratios and rough edges). You'll find this when dealing directly with the video source, most often with DVD .VOB files and Blu-ray .m2ts. Opposite to that, the subtitles one downloads are always in text formats which can be accessed and altered through the options available in video players.
