### ISSUE TITLE
Audio button isn't affected by OSD settings

### ISSUE THREAD

**Issue by firewater2** [iina/iina#2462]
**System and IINA version:**

- macOS High Sierra
- IINA 1.0.3

Pressing the audio button will display "Mute"/"Unmute" even if OSD is disabled. This is an inconsistency in the UI, as it's both not expected behaviour from the setting, and it's the only element that keeps reporting OSD messages after it has been disabled.

**Comment by alejx** [comment]
Thanks!

**Comment by alejx** [comment]
Fixed in v1.0.4.
