### ISSUE TITLE
Cannot reorder tracks in playlist

### ISSUE THREAD

**Issue by mwdiers** [iina/iina#2464]
- macOS 10.14.5
- IINA 1.0.3 build 106

**Expected behavior:**
When dragging a track in the playlist to a new position, the playlist should be updated with that track in the position to which it was dragged.

**Actual behavior:**
UI shows the expected feedback when dragging a track to a new position in the playlist, but upon releasing the mouse button, the track is not moved. This behavior is consistent whether in music mode or video mode.

**Comment by PubesOS** [comment]
On macOS 10.14.3 (yes, I need to update) and I'm experiencing the exact same issue. Especially irksome given that I'm watching a TV series that was aired in slightly the wrong order, which the filenames haven't taken into account.

**Comment by mwdiers** [comment]
Track reordering appears to be working in 1.0.5 on Catalina.
