### ISSUE TITLE
Frame leaks from idle closed window into a new window

### ISSUE THREAD

**Issue by orion1vi** [iina/iina#2469]
**System and IINA version:**

- macOS 10.14.5
- IINA 1.0.0-rc and on

**Expected behavior:**

New window does not display last frame of previous or other closed idle windows.

**Actual behavior:**

Frame of previous closed window (or other closed idle window) leaks into a new window if `findIdlePlayerCore()` is used since https://github.com/iina/iina/commit/c25ef55781676d0407ea0a754dc16432859c9cc8.
Always returning `true` in `shouldRenderUpdateFrame()` stops this, don't know if this introduces any unexpected behaviours.

**How often does this happen?**
Every time if `findIdlePlayerCore()` finds idle window.
Easy to reproduce on videos from internet, not as visible on local videos.

**Comment by saagarjha** [comment]
Would this happen to resolve #2197?

**Comment by orion1vi** [comment]
> Would this happen to resolve #2197?

This is the same issue. It would resolve it but I'm not sure if it's the best way to go about it, because https://github.com/iina/iina/blob/e602a57b239e72226fc332c890153785c7a6824e/iina/MPVController.swift#L373-L377
is basically same in mpv
https://github.com/mpv-player/mpv/blob/71ad1e2f4c2b87e677d01c639dbd3d28c118ac55/osdep/macOS_mpv_helper.swift#L131-L140.

**Comment by edrozenberg** [comment]
I'm seeing the same issue in 1.0.4 Build 107 - close a video window, open a different video, the last-displayed frame of the previous video appears in the new window for 1-2 seconds. But as the earlier poster commented, may be an mpv issue that IINA cannot directly fix.

**Comment by brycehammond** [comment]
I ended up just forcing the layer to redraw itself before the window is presented https://github.com/brycehammond/iina/commit/9a5530ac7fed89504cef937994e4af03cc5dd684
and this seems to work well, but does seem to be a bit of a hammer
