### ISSUE TITLE
Option to disable OSC and title bar

### ISSUE THREAD

**Issue by megadr01d** [iina/iina#2473]
Feature request:  Option to disable UI elements (OSC and title bar) for a keyboard-driven, video-only experience.

Reasoning: They get in the way more than often. Latest version doesn't even auto hide OSC and title bar when exiting fullscreen with shortcut key/remote button (exiting through menu option works) and when entering fullscreen again, the OSC stays visible.

**Comment by alejx** [comment]
> Latest version doesn't even auto hide OSC and title bar when exiting fullscreen with shortcut key/remote button (exiting through menu option works) and when entering fullscreen again, the OSC stays visible.

I cannot reproduce this bug. Can you describe it more precisely?

**Comment by megadr01d** [comment]
Enable native fullscreen, press shortcut to enter fullscreen, press shortcut key/remote button to exit fullscreen, title bar and OSC stay visible while in window mode, press shortcut to enter fullscreen again, title bar hides and OSC stays visible.

If exit fullscreen by clicking in the menu bar option (Video > Exit Fullscreen), both the title bar and OSC hide correctly after the designated timeout, while in window mode.

I can attach my preference file if you still can't reproduce it.

**Comment by megadr01d** [comment]
Also using bottom positioned OSC, if that makes any difference.

**Comment by megadr01d** [comment]
OK, found a missing detail: this only happens when, when exiting fullscreen, the cursor (although hidden) rests on top of the title bar or within the video area. If the cursor happens to be outside the window or on top of the OSC, both title bar and OSC correctly hide.

**Comment by megadr01d** [comment]
PR https://github.com/iina/iina/pull/2683 is a good start.
