### ISSUE TITLE
Control strip broken in 1.0.4b107

### ISSUE THREAD

**Issue by nicholasfechner** [iina/iina#2476]
**System and IINA version:**

- macOS 10.14.3
- IINA 1.0.4 build 107

**Expected behavior:**
The control strip should show an icon to open the IINA control strip when playing, but not active.

**Actual behavior:**
At the moment, the icon is missing for me:
<img width="1085" src="https://user-images.githubusercontent.com/3217175/58536500-0e634900-81f1-11e9-8953-25937e63a2f7.png">

**Steps to reproduce:**
Open IINA, play music, switch to different application, notice missing icon.

**How often does this happen?**
Always.

**Comment by saagarjha** [comment]
Does IINA show up in the Notification Center "Now Playing" widget?

**Comment by NicholasFechner** [comment]
Yes, it does:
<img width="337" src="https://user-images.githubusercontent.com/3217175/58544780-43c46280-8202-11e9-95c5-798ae67ee907.png">

**Comment by saagarjha** [comment]
I think the control strip is somewhat buggy, so I'm inclined to think it's an upstream issue. If the "Now Playing" widget shows content, that *should* mean we are using the Media Player API correctly: everything else should be handled by the OS. Are you getting this to show up for other apps?

**Comment by NicholasFechner** [comment]
I have never seen another app do this (not even iTunes). Do you know of any examples I could test?

**Comment by saagarjha** [comment]
Do you mean that you've never seen an app put an icon in the Touch Bar, or you've never seen an app *fail* to put an icon in the Touch Bar?

**Comment by NicholasFechner** [comment]
I have never seen an app put an icon in the right part of the touchbar while it was in the background.

**Comment by saagarjha** [comment]
Yeah, you're hitting a bug in macOS, not IINA. I have already filed rdar://problem/33296681 (Now Playing icon does not show up in Touch Bar) for this so the only thing we can do is wait for that to be resolved :(

**Comment by NicholasFechner** [comment]
ok

**Comment by NicholasFechner** [comment]
Sorry, but rdar://problem/33296681 does not describe my problem. For one: I'm on Mojave. And this happend after the last IINA update, without any changes to my macOS version.

Also: Downgrading to 1.0.3 restores the functionality:
<img width="1085" src="https://user-images.githubusercontent.com/3217175/58560826-2dc89900-8226-11e9-87da-2715c96a2214.png">

So I would suggest, that this is actually a bug in the new version.

**Comment by NicholasFechner** [comment]
Would it be possible to reopen this issue?

**Comment by NicholasFechner** [comment]
I just updated to 1.0.5. But the problem still exists..
So I'm downgrading to 1.0.3 again.
