### ISSUE TITLE
1.0.4版本,开机后第一次打开视频,必崩溃

### ISSUE THREAD

**Issue by gm100861** [iina/iina#2485]
MAC平台
开机后,使用iina播放视频,第一次打开会崩溃卡死,时间轴显示 9:99:99,一直没有响应. 要强制退出,然后再打开一次,就好了.
操作过程就是, 电脑开机, 右键视频,使用iina打开,然后就卡住了.

- macOS 10.14.2 (18C54)
- IINA  1.0.4 Build 107

**Comment by mingricha** [comment]
关机的时候保存上次操作的话，开机后直接从播放器记录里面点播放也会出卡住，macOS 10.14.5

**Comment by ArsenicX** [comment]
同，而且我这里不只是第一次打开的时候会崩，可以随时复现。
比如：现在打开一个视频，这时候不论有没有先暂停，不论是用⌘command+Q强退，还是直接点Q退出，再重新打开iina的时候，从历史记录里面选择之前的视频文件的时候，都会崩溃。鼠标一直转圈+进度条错误，只能右键dock图标强退重开，进度也会丢失
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/40692855/60379135-ea995a00-9a5f-11e9-8348-f53b07ec2962.png">

MacOS：10.14.3
iina：1.0.4 Build 107
