### ISSUE TITLE
IINA freezes when trying to resume a video file from the main window after sleep

### ISSUE THREAD

**Issue by TheMadRuffian** [iina/iina#2493]
System and IINA version:

- macOS 10.15 beta 1
- IINA 1.0.4 Build 107

Expected behavior:
When resuming the video file, the file should resume at the point where previously left off after waking the mac from sleep. It happens always after the update to the Build 107 when the player was quit in a different workspace.

Actual behavior:
Resuming the video file after waking the mac from sleep through the main window causes the player to freeze. There was no issues in the previous version.

![Screen Shot 2019-06-13 at 00 02 22](https://user-images.githubusercontent.com/42994263/59377059-0669e400-8d6f-11e9-85a1-30095596a5d8.jpg)
![Screen Shot 2019-06-12 at 23 59 31](https://user-images.githubusercontent.com/42994263/59377060-0669e400-8d6f-11e9-8548-61a47af3a3ca.jpg)

**Comment by mingricha** [comment]
macOS 10.14.5, same issue.

**Comment by mduchev** [comment]
Build 107 did it, yep. Happening on Mojave also.

**Comment by f0rl00p** [comment]
Same issue on mojave, hopefully this gets a fix.

**Comment by kerim** [comment]
Same issue on 1.0.6 Build 113  (newest version according to the check for updates) running Catalina (10.15.2).

**Comment by egoreburial** [comment]
Same now on Catalina 10.15.4 (19E287) with IINA 1.0.6 Build 113

**Comment by TheMadRuffian** [comment]
The issue seems to have been solved with the latest version (1.1.2). I have tried to reproduce multiple times with no issues on Big Sur.
