### ISSUE TITLE
Feature Request: Ability to open the Inspector window with a key binding

### ISSUE THREAD

**Issue by SimonGr3dal** [iina/iina#2495]
As the title says.

I want the ability to configure a key binding for opening the Inspector window in IINA. Currently I can add key bindings for opening the side panel, but not the Inspector window.

Configuring the key binding with system preferences does not provide the ability to asign single-button shortcuts.

**Comment by alejx** [comment]
<kbd>cmd</kbd>+<kbd>i</kbd> is the default keybinding to open the inspector window.
