### ISSUE TITLE
Shown the last video picture

### ISSUE THREAD

**Issue by kxxc** [iina/iina#2498]
**System and IINA version:**

- macOS  10.14.5
- IINA  1.0.4 b 107

**Expected behavior:**
Do not show the video picture I played last time.

**Actual behavior:**
When I click(open) a new video,
it'll appear a video picture that I watched last time,
and it brothers me.
How can I fix it?

Thanks.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by anohren** [comment]
#2197
