### ISSUE TITLE
IINA auto resizes video even when it shouldn't

### ISSUE THREAD

**Issue by jerkstore369** [iina/iina#2503]
I think there's a conflict somewhere with the video resizing. For example, I have the initial window size set to 1000 and initial positions set. I have resize window to fit video size set to always (I don't even know what the difference is when it's set to disabled. The window always resizes to the size of the video.) Use physical resolution on Retina displays is checked. So when I manually open a file, what happens is the window opens at the size I set it to and in the proper position, which is all good. When I go to full screen and later back out of full screen, sometimes, the window will be smaller then what I set it to. I don't understand why this happens. If I quit IINA and open file manually again, file will open to the size I set it to. Some weird conflicting behaviour is going on. Thanks.

**Comment by lemikeone** [comment]
Same issue here ...
