### ISSUE TITLE
建议增加可超过100%的音量功能

### ISSUE THREAD

**Issue by YangLin1998** [iina/iina#2511]
部分美剧声音小
感觉这个功能会很实用
之前用VLC有这个功能，可是时不时的卡顿逼死人。。。

**Comment by lhc70000** [comment]
@YangLin1998 偏好设置 - 视频/音频 - 最大音量

**Comment by YangLin1998** [comment]
> @YangLin1998 偏好设置 - 视频/音频 - 最大音量

谢谢
