### ISSUE TITLE
UI: Single click pause/resume should not allow click-through

### ISSUE THREAD

**Issue by modest** [iina/iina#2513]
**Repro:**
1. Set single click to Pause/Resume (Settings: Control: Single Click)
2. Begin playback of a video
3. Click on any other window (or the desktop) to unfocus the video window
4. Click in the middle of the video window to bring it to the foreground again

**Expected behavior:**
The window should activate, but playback should not pause.

This is the standard Mac app behavior; activating click is not passed through (with a few limited exceptions).  As an example, compare the behavior to Safari's HTML5 video controls ([test page](https://www.w3.org/2010/05/video/mediaevents.html)) which handles this correctly.

**Actual behavior:**
The window activates and the video pauses immediately.  This is called "click-through" and discouraged by Apple's Human Interface Guidelines.  (This would be standard behavior on Windows, though.)

**Comment by alejx** [comment]
See #2332 and #2407.
