### ISSUE TITLE
IINA里面有音量规格化吗？有的视频声音好小啊。。。。

### ISSUE THREAD

**Issue by pcwuyu** [iina/iina#2514]
就是potplayer里面的音量标准化还是规格化来着

有的视频声音实在是太小，但是iina的最大音量也就100%，调大了系统的音量的话，系统通知或者切换到其他视频播放的时候声音会变的很大。

希望可以添加这个功能，或者把音量的上限提高。

谢谢。

**Comment by HarukaMa** [comment]
@pcwuyu #2511

**Comment by pcwuyu** [comment]
好的，多谢啦。
