### ISSUE TITLE
Forward/Backward function is not taking values from setting

### ISSUE THREAD

**Issue by rainite** [iina/iina#2515]
**System and IINA version:**

- macOS 10.14.5 
- IINA 1.0.4 build 107 

**Expected behavior:**
One click on keyboard, video should be 5 seconds forward or backwards.

**Actual behavior:**
No matter how many seconds set in the setting (like seeking forward 5 sec or 2 backward sec), it seems not taking effect. It will seek for 20s or more secs every click on keyboard.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
1. Open a video
2. Use left arrow or right arrow to forward or backward.

- [x] MPV does not have this problem.

**How often does this happen?**
Always reproducible

**Comment by gavinwyl** [comment]
I have the same problem.

**Comment by lhc70000** [comment]
https://github.com/iina/iina/wiki/FAQ#why-is-the-seeking-time-not-precise-when-pressing-arrow-keys

**Comment by loohawe** [comment]
I have the same problem, too 🙁
