### ISSUE TITLE
UI: text overlap in preferences

### ISSUE THREAD

**Issue by zxcat** [iina/iina#2519]
**System and IINA version:**
- macOS 10.12.6 (16G2016)
- IINA 1.0.4 Build 107

**Expected behavior:**
clear preferences ui without overlapping text

**Actual behavior:**
preferences → UI → picture-in-picture; header overlaps description
![iina-ui](https://user-images.githubusercontent.com/550974/60612813-46ead980-9dd2-11e9-8891-829efb05314d.png)

**Comment by anohren** [comment]
Swedish translation does something similar with the title just above it (thumbnail previews). It gets cut off vertically:

![Thumbnail previews title gets cut off](https://user-images.githubusercontent.com/3519879/60820465-c34e3580-a1a1-11e9-8c9a-c7ce32c85106.png)

**Comment by alejx** [comment]
@zxcat 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/20237141/61635609-89635000-acc6-11e9-95ef-4b5e3107ab6e.png">
@anohren 
<img width="446" alt="image" src="https://user-images.githubusercontent.com/20237141/61635957-36d66380-acc7-11e9-8391-150d315b5dfe.png">

I've tried to solve these issues. Please reopen this issue or open another one if you find anything to improve.
