### ISSUE TITLE
Can't Open DMG File.

### ISSUE THREAD

**Issue by ckizer** [iina/iina#2545]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by ckizer** [comment]
DMG Can't be open on future version of MacOS because disk images are required to be notarized
<img width="532" alt="Screen Shot 2019-07-22 at 12 38 53 AM" src="https://user-images.githubusercontent.com/191738/61614656-2798dc80-ac19-11e9-9843-8514d4c97c8d.png">

**Comment by ckizer** [comment]
You can work around this on MacOS Catalina by opening Disk Utility.app > File Menu > Open Disk Image. You can right click on it in disk utility and choose show in finder.

**Comment by alejx** [comment]
I've observed the same thing happened on Firefox Software Update, not sure what's going wrong.
<img width="532" alt="image" src="https://user-images.githubusercontent.com/20237141/61697167-4efebf00-ad69-11e9-904e-349ea8c3570a.png">

**Comment by alejx** [comment]
See https://github.com/iina/iina/issues/2050
