### ISSUE TITLE
Can't open stream in new window 

### ISSUE THREAD

**Issue by catbaron0** [iina/iina#2550]
- macOS <10.15 beta (19A512f)>
- IINA <1.0.4 Build 107 MPV 0.29.1>

**Expected behavior:**
Rright click on a video stream (.m3u8) from playlist and choose "Open in new window (在新窗口中打开)", there should be a new window and play the selected video stream.

**Actual behavior:**
Error: Can't open the file or stream! (错误 无法打开文件或流！)

**How often does this happen?**
Everytime.

**Comment by Miigon** [comment]
I'm pretty sure that it has something to do with the stream itself, not IINA.
* Have you tested if the stream would work in other players or Safari?
* Have you tried playing other streams?
* Have you tried opening the stream via `Open URL...` option in IINA menu?

Here's a stream that you can try (from apple): http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8

**Comment by catbaron0** [comment]
> Have you tested if the stream would work in other players or Safari?

Yes, the stream works in other players or Safari
> Have you tried playing other streams?

Yes, I tried, including the stream you provided above.
>Have you tried opening the stream via 'Open URL...' option in IINA menu?

Yes, IINA could play it as usual. The problem is it can't open streams from playlist in a new window.

![](https://i.loli.net/2019/07/28/5d3c7a2a06cf878199.gif)
