### ISSUE TITLE
Quit app after last window closed *and* switched to another app

### ISSUE THREAD

**Issue by ffffwh** [iina/iina#2557]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

Quit app after last window closed **and** switched to another app, which mimics some stock macOS apps like Preview.app.

This gives the user a chance to do something after having closed a video (e.g. open another file), avoiding opening / quitting IINA repeatedly. If the user does not want to do anything more, they can just switch to other apps.

This could be either a configurable or hard-coded behavior to satisfy all users.

**Actual behavior:**

IINA is quit right after last window having been closed.

**Comment by anohren** [comment]
> mimics some stock macOS apps like Calendar and Preview

I failed to replicate the behavior with Calendar. It stays open, windowless and unfocused.

**Comment by alejx** [comment]
I cannot reproduce this behavior either
