### ISSUE TITLE
Possible plagiarism

### ISSUE THREAD

**Issue by chriszhang0815** [iina/iina#2563]
There is another application called **MPlayer Pro X** in the MacApp Store, all its elements are exactly the same as iina. Does it copy iina? Or are you both based on the same design framework?

![image](https://user-images.githubusercontent.com/48575083/62988410-ec37a980-be76-11e9-8547-886e356fc7aa.png)
![image](https://user-images.githubusercontent.com/48575083/62988439-083b4b00-be77-11e9-877d-279865cdd75b.png)
![image](https://user-images.githubusercontent.com/48575083/62988448-0ffaef80-be77-11e9-9b38-2758c23f96ac.png)

**Comment by HarukaMa** [comment]
Think we may need to send another complaint to Apple.

**Comment by lhc70000** [comment]
![image](https://user-images.githubusercontent.com/8478049/64022245-57b49300-cb68-11e9-8f9c-f62b47cf18b6.png)

Follow-up: the author hasn't replied to my complaint so far and Apple is confirming that.
