### ISSUE TITLE
AppStore出现盗版IINA？还是作者自己上传的？

### ISSUE THREAD

**Issue by gujiangjiang** [iina/iina#2568]
今天看了一下AppStore的榜单，免费榜单看到一个播放器，试了一下，除了图标不一样，其他地方和IINA基本一模一样，这个是不是侵权了？

![image](https://user-images.githubusercontent.com/13273955/63363523-59cb6480-c3a6-11e9-8ed0-65812b81f57b.png)

![image](https://user-images.githubusercontent.com/13273955/63363575-6ea7f800-c3a6-11e9-9a45-4ee4280bea2a.png)

![image](https://user-images.githubusercontent.com/13273955/63363614-82ebf500-c3a6-11e9-9aa2-c695dfbd37b7.png)

App地址在此：
https://apps.apple.com/cn/app/mplayer-pro-x/id1473923864?mt=12

**Comment by gujiangjiang** [comment]
并且还强制要求用户付费。。。

![image](https://user-images.githubusercontent.com/13273955/63363758-c8a8bd80-c3a6-11e9-916a-d5bf22b4f5ae.png)

**Comment by saagarjha** [comment]
Thanks for reporting this; we're aware of this app and are tracking it in #2563.
