### ISSUE TITLE
Does IINA produce HDR output on HDR monitors?

### ISSUE THREAD

**Issue by anastasiuspernat** [iina/iina#2570]
**System and IINA version:**
- macOS 10.12.6
- IINA 1.0.1 and 1.0.0

**Expected behavior:**
IINA would produce nice looking HDR picture with details in darks and bright saturated colors in light.

**Actual behavior:**
There's an undersaturated picture with no details in darks.

**How often does this happen?**
All the time, I tried different versions of IINA on different macOS's in comparison with PotPlayer on Windows 10. I'm using LG 32UL750-W HDR 10-bit monitor (DisplayHDR 600) and on Windows everything looks perfect. On a macOS with default settings or ``tone-mapping`` set to ``reinhard`` and ``icc-profile`` set to my monitor's profile the HDR footage looks really weird.

I'm not sure if it's even possible on macOS so I'm asking - is this an expected behavior or is something wrong and IINA can output HDR picture on HDR monitor?

**Comment by Juesto** [comment]
HDR support on macOS was introduced with Catalina.

**Comment by low-batt** [comment]
Closing this issue as IINA now contains support for HDR. See the `Audio/Video` section of settings.
