### ISSUE TITLE
someone please explain what is going on with IINA development?

### ISSUE THREAD

**Issue by jerkstore369** [iina/iina#2592]
Just wondering if IINA is dead or are the devs taking a break or what? There hasn't been a new build in months. Thanks.

**Comment by anohren** [comment]
It's just a hypothesis obviously, but they might have been [promoted to senior software engineers](https://youtu.be/dzvRIwCbT4g?t=329)

**Comment by lhc70000** [comment]
I’ve been too busy this year and apologize for the inactivity. I think I can resume the development in late December. We do have recent commits focusing on bug fixes, and a new build will be probably released in no more than a month.

**Comment by jerkstore369** [comment]
No need to apologize, I, and probably others, was just wondering what was going on. Thanks for the explanation! And thanks for IINA.

**Comment by saagarjha** [comment]
Closing to move discussion to #2686.
