### ISSUE TITLE
Excessive log file creation

### ISSUE THREAD

**Issue by dakotan** [iina/iina#2601]
**System and IINA version:**

- macOS 10.14.6
- IINA 1.0.4 Build 107

**Expected behavior:**

IINA maintains a single log file that is only accessed when logging is enabled or there is a fatal error.

**Actual behavior:**

IINA creates numerous 0-byte logs. I cleared out over 5,000 from my system. Each empty log was inside it's own folder. The culprit should be found within the initial logging pull request (Logging system #1726).

**Comment by dakotan** [comment]
If logging isn't enabled, a log directory shouldn't be created.  

https://github.com/iina/iina/blob/ad21737b419fe0e72b510942caebd71d10b04fd5/iina/Logger.swift#L45-L62

**Comment by xjbeta** [comment]
https://github.com/iina/iina/blob/ad21737b419fe0e72b510942caebd71d10b04fd5/iina/Logger.swift#L75

**Comment by zfogg** [comment]
+1

i have so many log directories as well
