### ISSUE TITLE
Save URL

### ISSUE THREAD

**Issue by L1cardo** [iina/iina#2602]
**System and IINA version:**

- macOS 10.15
- IINA 1.0.4

**Actual behavior:**

Can we have a function to save the URLs? I like watching IPTV with IINA , and it is a little bit annoying to type in the URL very time .

**Comment by chenzhijie** [comment]
I have found a way. You can save the URL to a file, and rename the file with `.m3u8` extension. Next time you can `Open` this file, the player will load the playlist.

**Comment by ElfSundae** [comment]
Same for me.
