### ISSUE TITLE
One subtitle file shows two identical subtitle options

### ISSUE THREAD

**Issue by Auva-Z** [iina/iina#2613]
**System and IINA version:**

- macOS Catalina 19A582a 
- IINA 1.0.4 Build 107
![image](https://user-images.githubusercontent.com/22852587/66538555-72126100-eb57-11e9-8d11-b1ac5cf48e93.png)

**How often does this happen?**
everytime play a video

**Comment by xeron** [comment]
https://github.com/iina/iina/issues/2317
