### ISSUE TITLE
Unsupported external subtitle

### ISSUE THREAD

**Issue by yangxu1221** [iina/iina#2614]
An error occurred while loading subtitle

[[简体中英ASS]This.is.Us.S04E01.WEBDL.FIX字幕侠.ass.zip](https://github.com/iina/iina/files/3713547/ASS.This.is.Us.S04E01.WEBDL.FIX.ass.zip)

Mac OS 10.15
IINA 1.0.4 Build 107

The same subtitle file works fine on VLC

**Comment by alejx** [comment]
The subtitle file has a wrong format, and mpv rejects it.
