### ISSUE TITLE
hello，I have download the source code of develop version, and want to modify the duration time of OSD，which class can do this?thanks!

### ISSUE THREAD

**Issue by leexiaominghub** [iina/iina#2615]
hello，I have download the source code of develop version, and want to modify the duration time of OSD，which class can do this?thanks!

**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by saagarjha** [comment]
A bit late, but most of the stuff related to the OSD happens to be in the MainWindowController, which can only really be called a god class at this point. Hope this helps.
