### ISSUE TITLE
Audio does not work in Catalina

### ISSUE THREAD

**Issue by AntonovSergey2211** [iina/iina#2618]
Hi!
After update OS to Catalina audio does not work. Audio slider looks like as disabled. 

- macOS Catalina 10.15 (19A583)
- IINA 1.0.4 Build 107

<img width="962" alt="Screenshot 2019-10-12 at 18 54 28" src="https://user-images.githubusercontent.com/1331864/66704091-c8330000-ed21-11e9-8380-6f918aefe41b.png">

**Comment by junaidShaikh** [comment]
mine works just fine with the same config, please elaborate?

**Comment by AntonovSergey2211** [comment]
Works!
I completely removed and after Installed again last version.
