### ISSUE TITLE
Shaders Support

### ISSUE THREAD

**Issue by L1cardo** [iina/iina#2625]
**System and IINA version:**

- macOS  10.15
- IINA  1.0.4 Build 107

**Expected behavior:**
Shaders Support

**Actual behavior:**
Shaders Support, I want to use [Anime4K](https://github.com/bloc97/Anime4K)

**Comment by lucifer717** [comment]
me tooooooooooooo

**Comment by ztarbugz** [comment]
Why you do not create the shaders folder in your mpv folder? Used the mentioned shader as well, works for me.

**Comment by jesec** [comment]
Related issue: #2630

It would be nice to have a manager of shader list. Nonetheless, you can add shaders manually at the moment:

Download shaders to `$HOME/.config/mpv/shaders/`. (in my case, `/Users/jc/.config/mpv/shaders/`)

In Preferences -> Advanced -> Additional mpv options:

Add:

name: `glsl-shaders`
value: `/Users/jc/.config/mpv/shaders/Anime4K_Denoise_Bilateral_Mode.glsl:/Users/jc/.config/mpv/shaders/Anime4K_Upscale_CNN_L_x2_Deblur.glsl`

Note that `:` is the separator on macOS.

**Comment by airward-svg** [comment]
I keep getting this error "Error occured when setting filters. Please check your parameter format." I've double checked the value and the correct path to shaders. Can you please let me know what I'm doing wrong?

Apple MacBook Air M1 (12.1)
Anime4k v4.0 shaders 
IINA 1.2.0 build

**Comment by ben-cl** [comment]
> Related issue: #2630
> 
> It would be nice to have a manager of shader list. Nonetheless, you can add shaders manually at the moment:
> 
> Download shaders to `$HOME/.config/mpv/shaders/`. (in my case, `/Users/jc/.config/mpv/shaders/`)
> 
> In Preferences -> Advanced -> Additional mpv options:
> 
> Add:
> 
> name: `glsl-shaders` value: `/Users/jc/.config/mpv/shaders/Anime4K_Denoise_Bilateral_Mode.glsl:/Users/jc/.config/mpv/shaders/Anime4K_Upscale_CNN_L_x2_Deblur.glsl`
> 
> Note that `:` is the separator on macOS.

I figured that you can import the input.conf inside Key Bindings in preferences. :)It is working for me
![image](https://user-images.githubusercontent.com/32286421/173251256-f364d584-4539-4c26-b72e-1e684c66b3b2.png)
