### ISSUE TITLE
[Fix] cache options are removed in mpv 0.30.0

### ISSUE THREAD

**Issue by subdiox** [iina/iina#2628]
## Overview
The cache options were removed in mpv 0.30.0 ([source](https://github.com/mpv-player/mpv/wiki/FAQ#why-were-some-cache-options-removed-or-changed-stream-cache)), but the IINA uses `cache-default` and `cache-backbuffer` options [here](https://github.com/iina/iina/blob/master/iina/MPVOption.swift) and [there](https://github.com/iina/iina/blob/master/iina/MPVController.swift). It causes an error indicating `option not found` if I replace libmpv.dylib to the current latest version, 0.30.0, in `/Applications/IINA.app/Contents/Frameworks` .
<img width="532" alt="スクリーンショット 2019-10-28 12 38 08" src="https://user-images.githubusercontent.com/20740664/67650297-d3239c80-f97f-11e9-9f60-8edcab3614ac.png">
<img width="532" alt="スクリーンショット 2019-10-28 12 38 13" src="https://user-images.githubusercontent.com/20740664/67650303-d9197d80-f97f-11e9-9e8f-b1e3de185dcd.png">

## Environment
- macOS Catalina 10.15
- IINA 1.0.4 Build 107
- mpv 0.30.0 (I replaced the old version because I needed vapoursynth)

**Comment by rabitdash** [comment]
@subdiox 
I commented relative codes and update mpv to version 0.30.0 with vapoursynth support, it works for me.
Here's the binary I built.
https://github.com/rabitdash/iina/releases/download/v1.0.4/IINA.app.zip

**Comment by ztarbugz** [comment]
@rabitdash tried your *.zip file on my iMac (Mojave latest), but seems that it is referencing some dylib:

> Dyld Error Message:
>   Library not loaded: /usr/local/opt/mpv/lib/libmpv.1.dylib
>   Referenced from: /Volumes/VOLUME/*/IINA.app/Contents/MacOS/IINA
>   Reason: image not found

**Comment by HarukaMa** [comment]
That's why we have a script to automatically fix those reference names - executables need to reference libraries using @rpath instead of fixed paths. The script still couldn't automatically fix the ones for python, though.

Or try the experimental build (with vapoursynth support) in https://github.com/iina/iina/wiki/Use-SVP-with-IINA.

**Comment by alejx** [comment]
1.0.5 will ship the latest version of mpv.
