### ISSUE TITLE
IINA macOS Catalina problem

### ISSUE THREAD

**Issue by Lincoln-Zhou** [iina/iina#2661]
**System and IINA version:**

- macOS 10.15.1
- IINA 1.0.4

**Expected behavior:**
Open software interface after double click an video file.

**Actual behavior:**
The icon will show up in the dock and pulsing, which means the system is trying to open IINA, however, this starting process is extremely long and under most circumstances IINA will finally become no response(though it does open after waiting a long time once). Rebooting can fix it temporarily.

**Steps to reproduce:**
Open a video file?

**How often does this happen?**
Randomly. It starts about a week ago.

**Comment by alejx** [comment]
I think it's a Catalina issue. Do you still experience such issue?

**Comment by zhyiyu** [comment]
I am also experiencing this, and it is quite often for me though. I am not sure if there is a pattern like video format or something else, but I can keep you updated.

**Comment by lhc70000** [comment]
Please search for "apple ocsp" for more info.

**Comment by zhyiyu** [comment]
I think we need to whitelist OCSP according to [reddit](https://www.reddit.com/r/pihole/comments/e4kdhp/what_is_ocspapplecom/)?

**Comment by zhyiyu** [comment]
I think I figured out the pattern

1. Completely quit IINA if it is open.
2. Insert an external **NTFS** hard drive that contains a video in any format.
3. Open the video.

If the IINA is opened in full screen, then it will crash, if not, it will be fine.

However I am not sure how to adjust the behavior of opening in full screen or not. But this is want I found.
