### ISSUE TITLE
1.0.5: 'Open in IINA' Safari plugin is missing

### ISSUE THREAD

**Issue by phhoef** [iina/iina#2693]
**System and IINA version:**

- macOS 10.15.2
- IINA 1.0.5 build 111

**Expected behavior:**
The IINA Safari Plugin should show up in the Safari -> Settings -> Extensions menu.

**Actual behavior:**
After updating IINA to 1.0.5 the Safari Plugin is gone.

**Steps to reproduce:**
As far as I can tell, just update IINA.

**Comment by saagarjha** [comment]
If you re-download 1.0.4 and open it, does the extension show up again?

**Comment by phhoef** [comment]
Yes, indeed.
I downloaded 1.0.4, opened it once to let macOS know the app is trustworthy and the Safari plugin appeared again.

**Comment by saagarjha** [comment]
This is probably some sort of codesigning or notarization issue. Let me see what's going on here.

**Comment by saagarjha** [comment]
Running `pluginkit -a /Applications/IINA.app/Contents/PlugIns/OpenInIINA.appex/` gives me this in the Console:

```
[d <private>] [u 2689917F-7857-48C2-8999-860722341A9A] [<private>(<private>)] rejecting; Ignoring mis-configured plugin at [/Applications/IINA.app/Contents/PlugIns/OpenInIINA.appex]: plug-ins must be sandboxed
```

I wonder if Notarization tightens sandboxing for application extensions or something.

**Comment by plgagne** [comment]
This issue also happens to me on 10.14.6

**Comment by Dreamisdead** [comment]
Happens on 10.14.6 for me too.

**Comment by hsuehpascal** [comment]
Same here on 10.15.3.

**Comment by phhoef** [comment]
Thanks, IINA 1.0.6 fixes the problem for me
