### ISSUE TITLE
Music Player hide the IINA logo part

### ISSUE THREAD

**Issue by microfx** [iina/iina#2697]
Hey!

IINA is very nice for listening to music. It would be nice to get  rid of the huge image - it would look so much nicer to just have the player/playlist without the image at the top (what is it for? cover art?)!

Cheers

**Comment by LamJH** [comment]
It's actually cover art. And you can hide it by clicking the little CD case icon on the right.
<img width="412" alt="截屏2020-01-09下午8 38 45" src="https://user-images.githubusercontent.com/19835896/72068932-0e97fb00-3321-11ea-9223-81857ead394a.png">

**Comment by microfx** [comment]
Thanks a  lot!
