### ISSUE TITLE
Rmove base frame after entered mini player mode | 进入迷你模式时，应该隐藏原有窗口，这样很不方便

### ISSUE THREAD

**Issue by KyleBing** [iina/iina#2710]
**What you want IINA to do:**
Remove base frame after entered mini-player mode

**What IINA does currently:**
After entered mini mode, it leaves the origin frame wherewith origin size of it, very inhuman. if so, it's no point to enter in mini mode.

<img width="1280" alt="Screen Shot 2020-01-11 at 23 40 23" src="https://user-images.githubusercontent.com/12215982/72206693-dd0f6300-34cb-11ea-9448-6428a2ba5fd9.png">

**Why you think this should be added:**
After entered mini mode, it should behave like QuickTimePlayer, do not leave the origin frame there.

**Examples of other projects that have something similar:**
QuickTime Player

**Comment by saagarjha** [comment]
QuickTime doesn't actually support "true" picture-in-picture, so it's not the best application to compare with. The rationale behind the current behavior is that the original window should remain so that you can animate back to it, plus it gives you access to the controls that the picture-in-picture window doesn't show.

**Comment by KyleBing** [comment]
> QuickTime doesn't actually support "true" picture-in-picture, so it's not the best application to compare with. The rationale behind the current behavior is that the original window should remain so that you can animate back to it, plus it gives you access to the controls that the picture-in-picture window doesn't show.

Sometime I just what the playing window to get to the corner, so it won't get in the way of which I want to see. In this case, the origin window would be very inconvenient. 

If it can't be set to default, at least add a setting option to this feather, it would be very helpful. I would very like to turn it on. Something to consider.

**Comment by saagarjha** [comment]
Perhaps one of these options might be helpful?

<img width="565" alt="Screen Shot 2020-01-18 at 07 23 59" src="https://user-images.githubusercontent.com/13786931/72666068-81f5d880-39c3-11ea-97d1-92dc652c067d.png">

**Comment by KyleBing** [comment]
I just notice this setting.
But after I checked to hide or minimize, none of those two are actually do anything, the original window is still there. Any setting I have missed?

**Comment by saagarjha** [comment]
Would you happen to be in fullscreen mode? Neither of those will work in that state. (And I'm not sure what you would like IINA to do if you *are* in that mode–what content would you see other than the desktop background?)

**Comment by KyleBing** [comment]
Oh yes, I'm in fullscreen mode, sorry I didn't notice about that before.

Anyway, I think it should do the same thing whether in fullscreen mode or not when I clicked what mini button.
In fullscreen mode, there would be no point if it doesn't hide the original screen, kind of strange behave.

I think it should leave the fullscreen mode and do what it should do in normal mode.

**Comment by KyleBing** [comment]
Quick Time does behave like IINA in fullscreen mode. But I don't see the point of it. it still blocks what behind it.

In my opinion, it should either behave hiding the original window or just don't show this button in fullscreen mode.
