### ISSUE TITLE
关于macOS下ass字幕中文字体无法正确调用

### ISSUE THREAD

**Issue by gzn25** [iina/iina#2711]
也不是新问题了，目前只查找到以下两处信息：
https://zrstea.com/261/
https://www.v2ex.com/t/454158

系统是10.15.2，IINA是1.0.5。
如果将ass字体改为PostScriptName，Windows下又无法识别。
然而目前系统下手动修改IINA.app的内容会导致无法打开app，于是陷入了死胡同。
最近发现Kodi也有这个问题，完全不知道怎么改，真是抓狂。

**Comment by Rikkano** [comment]
你需要安装`fontconfig`
终端运行`brew install fontconfig`
当然你要先有`home-brew`

**Comment by gzn25** [comment]
> 你需要安装`fontconfig`
> 终端运行`brew install fontconfig`
> 当然你要先有`home-brew`

fontconfig已安装，libass library也已替换进IINA.app，然而并没有解决问题，中文字体反而变得大小不一。

我不是程序员没有足够的知识去手动编译解决这个问题，但有一点很疑惑：
外挂中文字幕字体普遍出错，这应该不是少数人遇到的，难道不是软件本身应该去解决的问题么？难道一直放着不管，还需要用户具备相应专业知识自己去修改么？

**Comment by inflation** [comment]
> 难道不是软件本身应该去解决的问题么？

这并不是软件的问题，因为`libass`在macOS上就是用`CoreText`实现的，而Apple的东西只认符合标准的字体文件。如果你的字体是从字体厂商购买的macOS字形或较新的OpenType字体，那么没有任何问题。

`fontconfig`本身是Linux的技术，因为是开源所以有可能识别一些非标准的字体，在macOS上属于非官方支持的做法，会发生什么全靠自己。

**Comment by gzn25** [comment]
> 这并不是软件的问题，因为`libass`在macOS上就是用`CoreText`实现的，而Apple的东西只认符合标准的字体文件。如果你的字体是从字体厂商购买的macOS字形或较新的OpenType字体，那么没有任何问题。

考虑到兼容我制作的字幕通常只采用黑体和Tahoma，那是否有推荐的中文字体能多平台使用而不会出现这个问题？

**Comment by Rikkano** [comment]
> fontconfig 已安装，libass library 也已替换进 IINA.app，然而并没有解决问题，中文字体反而变得大小不一。

这个问题可能和字幕里调用的字形有关，字体本身缺字就会出现这种情况，参考[这个帖子](http://bbs.vcb-s.com/thread-5161-1-1.html)，方便的话可以上传个字幕文件看看

**Comment by Rikkano** [comment]
> > 这并不是软件的问题，因为 `libass` 在 macOS 上就是用 `CoreText` 实现的，而 Apple 的东西只认符合标准的字体文件。如果你的字体是从字体厂商购买的 macOS 字形或较新的 OpenType 字体，那么没有任何问题。
> 
> 考虑到兼容我制作的字幕通常只采用黑体和 Tahoma，那是否有推荐的中文字体能多平台使用而不会出现这个问题？

[中日字体匹配方案](http://bbs.vcb-s.com/search.php?mod=forum&searchid=315&orderby=lastpost&ascdesc=desc&searchsubmit=yes&kw=%E4%B8%AD%E6%97%A5%E5%AD%97%E4%BD%93%E5%8C%B9%E9%85%8D)

**Comment by Rikkano** [comment]
>fontconfig 已安装，libass library 也已替换进 IINA.app，然而并没有解决问题，中文字体反而变得大小不一。

或者干脆`brew install ffmpeg`

**Comment by Rikkano** [comment]
> > 这并不是软件的问题，因为 `libass` 在 macOS 上就是用 `CoreText` 实现的，而 Apple 的东西只认符合标准的字体文件。如果你的字体是从字体厂商购买的 macOS 字形或较新的 OpenType 字体，那么没有任何问题。
> 
> 考虑到兼容我制作的字幕通常只采用黑体和 Tahoma，那是否有推荐的中文字体能多平台使用而不会出现这个问题？

你用的黑体嘛，那怪不得，macOS 自带的中文字形几乎都是**简繁分开**的，所以你如果选自带的字体，只能从华文三兄弟里挑，如果另装字体，可以考虑**文泉驿微米黑**
![image](https://user-images.githubusercontent.com/44722787/73236680-3cf55180-41ce-11ea-8ce1-48af2febbb6f.png)

**Comment by gzn25** [comment]
> > > 这并不是软件的问题，因为 `libass` 在 macOS 上就是用 `CoreText` 实现的，而 Apple 的东西只认符合标准的字体文件。如果你的字体是从字体厂商购买的 macOS 字形或较新的 OpenType 字体，那么没有任何问题。
> > 
> > 
> > 考虑到兼容我制作的字幕通常只采用黑体和 Tahoma，那是否有推荐的中文字体能多平台使用而不会出现这个问题？
> 
> 你用的黑体嘛，那怪不得，macOS 自带的中文字形几乎都是**简繁分开**的，所以你如果选自带的字体，只能从华文三兄弟里挑，如果另装字体，可以考虑**文泉驿微米黑**

好的，看来最简便的方法还是换字体。
多谢两位解惑。

**Comment by Rikkano** [comment]
> > > > 这并不是软件的问题，因为 `libass` 在 macOS 上就是用 `CoreText` 实现的，而 Apple 的东西只认符合标准的字体文件。如果你的字体是从字体厂商购买的 macOS 字形或较新的 OpenType 字体，那么没有任何问题。
> > > 
> > > 
> > > 考虑到兼容我制作的字幕通常只采用黑体和 Tahoma，那是否有推荐的中文字体能多平台使用而不会出现这个问题？
> > 
> > 
> > 你用的黑体嘛，那怪不得，macOS 自带的中文字形几乎都是**简繁分开**的，所以你如果选自带的字体，只能从华文三兄弟里挑，如果另装字体，可以考虑**文泉驿微米黑**
> 
> 好的，看来最简便的方法还是换字体。
> 多谢两位解惑。

其实，https://zrstea.com/261/ 这篇文章给出的解决方案，按理说是有效的，我目前就在用；
但不知道为什么你还是遇到了问题，这可能还和你选用的字体有关系。
最好发下 IINA 的 log 和相关的字幕文件，看看能不能彻底解决。

**Comment by gzn25** [comment]
> 其实，https://zrstea.com/261/ 这篇文章给出的解决方案，按理说是有效的，我目前就在用；
> 但不知道为什么你还是遇到了问题，这可能还和你选用的字体有关系。
> 最好发下 IINA 的 log 和相关的字幕文件，看看能不能彻底解决。

[終末なにしてますか？忙しいですか？救ってもらっていいですか？.EP12.世界で一番幸せな女の子.Blu-Ray.1080p.x265.FLACx2.ass.zip](https://github.com/iina/iina/files/4120825/EP12.Blu-Ray.1080p.x265.FLACx2.ass.zip)
[iina.log](https://github.com/iina/iina/files/4120837/iina.log)
[mpv.log](https://github.com/iina/iina/files/4120838/mpv.log)

字幕文件见上。刚更新了IINA 1.0.6 修改libass后启动基本不报错了。
字体FullName选用黑体或华文黑体都不能正确显示，有时会出现大小不一的问题。PostScriptName没有问题。

**Comment by Rikkano** [comment]
> > 其实，https://zrstea.com/261/ 这篇文章给出的解决方案，按理说是有效的，我目前就在用；
> > 但不知道为什么你还是遇到了问题，这可能还和你选用的字体有关系。
> > 最好发下 IINA 的 log 和相关的字幕文件，看看能不能彻底解决。
> 
> [終末なにしてますか？忙しいですか？救ってもらっていいですか？.EP12. 世界で一番幸せな女の子.Blu-Ray.1080p.x265.FLACx2.ass.zip](https://github.com/iina/iina/files/4120825/EP12.Blu-Ray.1080p.x265.FLACx2.ass.zip)
> [iina.log](https://github.com/iina/iina/files/4120837/iina.log)
> [mpv.log](https://github.com/iina/iina/files/4120838/mpv.log)
> 
> 字幕文件见上。刚更新了 IINA 1.0.6 修改 libass 后启动基本不报错了。
> 字体 FullName 选用黑体或华文黑体都不能正确显示，有时会出现大小不一的问题。PostScriptName 没有问题。

我前面已经提到了：macOS 自带的中文字形几乎都是**简繁分开**的。「黑体」在 macOS 下的正确写法应该是「黑体-简」或者「黑体-繁」；而且关于「华文三兄弟」还特意截了图告诉你，「华文黑体」不在其中。所以你选用这两个字体，是绝不可能得到正确效果的。

针对动漫，我建议正文部分，中文选用「方正准圆_GBK」，日文选用「DFPHSMaruGothic-W4」

**Comment by Rikkano** [comment]
另外，不管是「黑体」还是「华文黑体」都是中文字形，我看你 OP ED 日文部分也是用的默认样式，自然会导致缺少的日文部分 fallback 回苹方。如果你不打算单独给 OP  ED 单独设置样式，可以用「文泉驿微米黑」包含中日全部字形

**Comment by gzn25** [comment]
我是在寻找能同时兼容Mac和Windows平台的解决方法，由于还要分享给别人，所以优先采用无需额外安装的字体，并且尽量做到傻瓜化。
日文倒不要紧，极少做这部分，苹方能看就行。倒是中英双语比较多，几个版本前，黑体+Tahoma在任何平台上都是没有问题的。
之前截图没有显示出来，现在可以看到了。

**Comment by Rikkano** [comment]
既然对字体显示效果没什么太大要求，那就干脆全用默认的 Arial，让缺失的字形 fallback 回系统默认字体算了（话说这也太没追求了吧

**Comment by gzn25** [comment]
苹方过小，宋体不能忍……只好给Win另做一版了哎。

**Comment by Rikkano** [comment]
你是一人字幕组吗，99.9%的正规字幕组，肯定要另外安装字体啊
题外话：末日没空不是已经有字幕了嘛，http://bbs.vcb-s.com/forum.php?mod=viewthread&tid=2763&highlight=%E6%9C%AB%E6%97%A5

**Comment by gzn25** [comment]
自娱自乐做的，下载的字幕也会自己统一改改格式自用，有点强迫症。
末日大概是太冷门了，现有字幕翻译有些错漏，于是自己按喜好修了一版。

**Comment by Rikkano** [comment]
巧了，我也是自用强迫症，但是我自己修改肯定要用到多种字形、样式，光系统那点字体哪够用。
看 Anime 的话，电脑里没个[几十G的字体](https://vcb-s.com/archives/1114)，能行？（引战发言

**Comment by gzn25** [comment]
一是有时需要拷给同事朋友什么的，也没法要求别人去安装字体。二是现在各种移动平台并不方便装字体（而且特效写得越多越容易出事），所以想用泛用字体来统一字幕风格省事。平时还是Win的思维，所以选了黑体。
动画收藏并不多，倒是美剧占大头，目前还是偏好下面的风格。
![截屏2020-01-28下午5 17 44](https://user-images.githubusercontent.com/3909503/73250822-9f604900-41f2-11ea-9414-26ee2e9341be.png)

**Comment by Rikkano** [comment]
macOS 自带的字体，就下面这些，而且都是独有的版本
![image](https://user-images.githubusercontent.com/44722787/73251650-501b1800-41f4-11ea-9fcc-b16101ab6be8.png)
用 `sed` 命令，或者 Sublime Text 之类的编辑器什么的，把「黑体」改成「黑体 - 简」就是 macOS 独有的版本，只能这样了

**Comment by MikeWang000000** [comment]
ass的字体问题确实是个比较麻烦的事情。我有一个解决方案，就是用mkvtoolnix，将视频、ass文件、字体文件全部装入mkv容器（字体以attachment的形式装入），打包做成一个mkv视频文件。

优点是在各个平台不用安装字体，iPad上可以用VLC播放器直接自动载入嵌入字体，手机同样。
神奇的是，同样的日文字体嵌入mkv文件之后，IINA的字体不识别问题也一起解决了。
缺点就是，所有字体，要嵌入每一集视频，相当于同样的字体复制了很多遍，比较占用空间。

**Comment by Rikkano** [comment]
> ass 的字体问题确实是个比较麻烦的事情。我有一个解决方案，就是用 mkvtoolnix，将视频、ass 文件、字体文件全部装入 mkv 容器（字体以 attachment 的形式装入），打包做成一个 mkv 视频文件。
> 
> 优点是在各个平台不用安装字体，iPad 上可以用 VLC 播放器直接自动载入嵌入字体，手机同样。
> 神奇的是，同样的日文字体嵌入 mkv 文件之后，IINA 的字体不识别问题也一起解决了。
> 缺点就是，所有字体，要嵌入每一集视频，相当于同样的字体复制了很多遍，比较占用空间。

这个方法理论可行，然而没有太大实用价值。
https://zrstea.com/261/已经给出了完美的解决方案

**Comment by MikeWang000000** [comment]
谢谢回复。实用价值在于顺便解决Issue Author这个问题

> 一是有时需要拷给同事朋友什么的，也没法要求别人去安装字体。二是现在各种移动平台并不方便装字体（而且特效写得越多越容易出事）

其实现在懒人居多（我就是），如果有频繁切换于各种平台播放的需求，直接嵌入字体也未尝不是一种好方法。
当然，我只是提供一种可选的解决方案。IINA不需因此改变些什么，因为这并不是IINA的问题。

**Comment by Rikkano** [comment]
> 谢谢回复。实用价值在于顺便解决 Issue Author 这个问题
> 
> > 一是有时需要拷给同事朋友什么的，也没法要求别人去安装字体。二是现在各种移动平台并不方便装字体（而且特效写得越多越容易出事）
> 
> 其实现在懒人居多（我就是），如果有频繁切换于各种平台播放的需求，直接嵌入字体也未尝不是一种好方法。
> 当然，我只是提供一种可选的解决方案。IINA 不需因此改变些什么，因为这并不是 IINA 的问题。


![image](https://user-images.githubusercontent.com/44722787/74079991-d0097380-4a79-11ea-9baf-0b9b2221e591.png)
_Nekomoe kissaten&LoliHouse组_ 把用到的字（体）单独提取出来嵌入到 MKV，似乎是个不错的办法

**Comment by leolbyy** [comment]
Hi
我之前也遇到了无法正确加载中文字幕的问题
但是因为homebrew不再支持options
所以我的解决方法是手动编译libass文件后 替换进iina libs folder并用xcode进行build
现在ass等字幕可以正确加载 但是UTF-8 encoding的SRT字幕会出现字体大小不一的情况
请问这个有什么解决方法吗
<img width="1512" alt="Screenshot 2023-02-26 at 10 07 45 PM" src="https://user-images.githubusercontent.com/80955869/221415533-453fe04b-50e2-4c4e-ba1f-5db4403a27eb.png">

**Comment by Fujiwara-Chika** [comment]
> Hi
> 我之前也遇到了无法正确加载中文字幕的问题
> 但是因为homebrew不再支持options
> 所以我的解决方法是手动编译libass文件后 替换进iina libs folder并用xcode进行build
> 现在ass等字幕可以正确加载 但是UTF-8 encoding的SRT字幕会出现字体大小不一的情况
> 请问这个有什么解决方法吗
> <img alt="Screenshot 2023-02-26 at 10 07 45 PM" width="1512" src="https://user-images.githubusercontent.com/80955869/221415533-453fe04b-50e2-4c4e-ba1f-5db4403a27eb.png">

我之前好像也遇到过大小不一的问题，但是后来怎么解决的也给忘了，要不你试试这个 [libass.9.dylib.zip](https://github.com/iina/iina/files/10833941/libass.9.dylib.zip)
或者参考下[这个](https://github.com/iina/iina/issues/3328#issuecomment-826008079)，换个字体？

**Comment by Fujiwara-Chika** [comment]
> > 谢谢回复。实用价值在于顺便解决 Issue Author 这个问题
> > > 一是有时需要拷给同事朋友什么的，也没法要求别人去安装字体。二是现在各种移动平台并不方便装字体（而且特效写得越多越容易出事）
> > 
> > 
> > 其实现在懒人居多（我就是），如果有频繁切换于各种平台播放的需求，直接嵌入字体也未尝不是一种好方法。
> > 当然，我只是提供一种可选的解决方案。IINA 不需因此改变些什么，因为这并不是 IINA 的问题。
> 
> ![image](https://user-images.githubusercontent.com/44722787/74079991-d0097380-4a79-11ea-9baf-0b9b2221e591.png) _Nekomoe kissaten&LoliHouse组_ 把用到的字（体）单独提取出来嵌入到 MKV，似乎是个不错的办法

顺便挖个自己的坟。
目前已经有了字体子集化方案，直接就将 ass 字幕及字体封装成 mks，可以参考[这篇文章](https://kyoani.notion.site/7786e97254e44500859a02ec80d35c3d)

**Comment by whitewatercn** [comment]
可以在设置里面选择字幕字体，换几个试试

<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/e2b3d837-51d0-45cf-8f2c-3649f6397c5f" />

**Comment by shakaflee** [comment]
刚好也遇到了这个问题，分享一下。

版本：1.3.5

改变字体就可以了（但样式上可能不太好看，不过能用）。

这是改变字体之前：

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/d64f3ffe-db5e-4857-9fb0-1f3213dfcc11" />


这是改变字体的过程（设置 - 字幕 - 文本字幕 - 字体选择）：

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/955a4a3f-0855-41b4-a222-b3ec23bd9d33" />


这是改变后的样子：

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/6acc8089-8c8b-4bb0-a3e4-252fdd127d03" />

**Comment by Fujiwara-Chika** [comment]
> 是的，压根不能再次打开iina

你把 2017 年 x86 的 dylib 塞进 2025 年 ARM 的 IINA 里，能打开就怪了。
苹方不行是因为 macOS15 的 bug 需要重新下载苹方。
