### ISSUE TITLE
No affordance of scrollability in welcome window's recent files list

### ISSUE THREAD

**Issue by anohren** [iina/iina#2715]
**System and IINA version:** 
10.14
1.0.5

**Expected behavior:**
The list of recently opened items in the welcome window conveys scrollability

**Actual behavior:**
!(The list of recently opened items in the welcome window conveys scrollability)

In the absence of scroll bars, a section border, or a list item that is only partially visible there is noting indicating that the list is scrollable.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by saagarjha** [comment]
Not showing a scrollbar is an accessibility issue, +1. The only reason I can see why we *might* disable it is because it might look bad on vibrant material? @lhc70000, thoughts?

**Comment by alejx** [comment]
It looks …… not bad
![image](https://user-images.githubusercontent.com/20237141/74628251-c7203e00-511a-11ea-9ad3-2f5aa046e5d7.png)
I think we should add it

**Comment by saagarjha** [comment]
> I think we should add it

*adds it*

**Comment by anohren** [comment]
It doesn't look as good with a mouse plugged in, i.e. with "always show scrollbars" enabled. Perhaps just remove the scrollbar background and only show the handle? Not sure about this. It looks ok in dark mode, but otherwise the scrollbar looks a bit "unterminated". 

What do you think?

![scrollbar](https://user-images.githubusercontent.com/3519879/82913560-bfb8ce00-9f6e-11ea-9bfa-99437f1b5d40.png)
