### ISSUE TITLE
Changes to youtube-dl raw options do not stick between app launches

### ISSUE THREAD

**Issue by anohren** [iina/iina#2716]
**System and IINA version:**

- macOS  10.14
- IINA  1.0.5

**Expected behavior:**
Changes to raw youtube-dl options stick. 

**Actual behavior:**
Changes to  youtube-dl raw options are reversed after a relaunch of the app.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

1. Open network settings
2. Select your current raw youtube-dl options in the text field, right click and cut the text out
3. Close the window
4. Quit the app
5. Relaunch the app and inspect the text field to see all your edits undone. The text has reappeared.

- [ ] MPV does not have this problem.

**How often does this happen?**
Every time. Has been happening in previous versions as well.

**Comment by saagarjha** [comment]
Probably some sort of bindings thing that only gets saved after focus leaves the text field? Not completely sure; I'll ask around to see how this is supposed to behave.

**Comment by saagarjha** [comment]
Update: I think this is because we have it set to not continuously update, so it should actually save once you press enter. Does that work?

**Comment by anohren** [comment]
Yes that’s the workaround I’ve been using for the past year. Forgot to mention that. Enter should not be necessary. 

But it only kind of works when I press enter while focused on the text field, since it usually takes two relaunches before the options actually take effect / show up correctly. I.e. it lags behind one launch. At least that is my experience for the last year. 

I seem to recall reporting this somewhere and discussing it but apparently I couldn’t find it when opening this issue, so it must have been in chat.

**Comment by alejx** [comment]
Then should we set all the input textfield continuously update? @saagarjha

**Comment by saagarjha** [comment]
That sounds like it'd work.
