### ISSUE TITLE
Frozen when trying to remove all playback history 

### ISSUE THREAD

**Issue by sgyzetrov** [iina/iina#2722]
**System and IINA version:**

- macOS 
10.14.6 (18G103)
- IINA 
1.0.4 Build 107
**Expected behavior:**
Delete all playback history using command+A to select all.

**Actual behavior:**
Application froze.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
<img width="979" alt="Screen_Shot_2020-01-18_at_11_19_12_png" src="https://user-images.githubusercontent.com/34640565/72669439-84b5f500-39e6-11ea-8bcc-0509b07b1480.png">
<img width="487" alt="Screen Shot 2020-01-18 at 11 19 30" src="https://user-images.githubusercontent.com/34640565/72669453-9d260f80-39e6-11ea-8a80-d46d0511748e.png">

- [ ] MPV does not have this problem.
I not sure if this is related to MPV.

**How often does this happen?**
Did not happen when I just select few playback entries to delete, but rather when I select all playback history to delete.

**Comment by saagarjha** [comment]
To clarify, you're saying that IINA ended up going into a "not responding" state? Can you reproduce this reliably?

**Comment by sgyzetrov** [comment]
Hi Saagar,

Yes, in fact, I just crashed it again (see updated OP). I cannot seem to find crash log in `~/Library/Logs/DiagnosticReports/`, maybe that's because IINA did not crashed on itself but rather force terminate by me.

I have one idea of what's going on: Hypothetically, if a user has large playback history (n >= 600), deleting them all at once caused the application to hang, and this classified as `UI enhancement`, I think. Sluggish when deleting massive amount of playback history is foreseeable. Maybe either prompt user that application could hang, or try deleting in batches in background. Anyway, this could have been not the reason for this hang at all, and my suggestions are just my two cents.

Thank you!

Best,
Simon

**Comment by alejx** [comment]
O(nlogn) + O(n * file I/O) => O(n) + O(file I/O)
Should be fast enough now
