### ISSUE TITLE
[Bug] mpv cache settings stopped working after updating from iina 1.0.4 to 1.0.6.

### ISSUE THREAD

**Issue by zxzzz8** [iina/iina#2724]
after updating iina from version 1.0.4 to 1.0.6 [macOS ver: high sierra 10.13.6], when opening the app, i get this error message :

Error setting option --cache=131072 with return value -7. Please check your extra option settings in Preference > Advanced.

[and the setting don't take affect]
the setting i have there is:
cache
131072
and trying to change the number didn't help

sense all my stuff are always on external drives, when i don't have that setting on, it constantly lag, so i can't really watch without that setting....

for now i downgraded it b' to 1.0.4 and it works again, but i can't use the newer versions until its fixed pretty much....

[also, i moved the 1.0.6 from the apps folder and changed its file name, and put 1.0.4 w the original name, but despite doing the whole ''Set IINA as the deafult application'' when 1.0.4 is open, when i tried to open a file it try to open it w the 1.0.6 i archived and renamed.... i can only reset every filetype one by one in the getinfo, i think you need to fix that the ''Set IINA as the deafult application'' will set the specific iina currently in use as deafult app over other iina apps as well, and not just other apps in general, i guess thats another bug then....? at least make it set the iina w the deafult name in applications folder as a minimum fix.]

**Comment by lhc70000** [comment]
mpv has changed the behavior of the `cache` option since 0.30.0: https://mpv.io/manual/master/#options-cache

You may want to use `--demuxer-max-bytes` instead.

**Comment by zxzzz8** [comment]
i guess it have something to do w:
''Updates mpv to 0.31.0, with FFmpeg 4.2.1''
in the 1.0.5 update? am i suppose to write that setting differently maybe?

**Comment by zxzzz8** [comment]
oh lol 10 seconds away from your replay XD
thanks ill try that and see if it works....

**Comment by zxzzz8** [comment]
hmmmm, it still seems to lag? i don't think it worked....
i also tried to add cache-on-disk=yes

**Comment by zxzzz8** [comment]
btw i think its a pretty basic setting, i really wish it was in the actual iina settings = X

**Comment by lhc70000** [comment]
>  i really wish it was in the actual iina settings

Yes it is:

![image](https://user-images.githubusercontent.com/8478049/72430817-3dedb280-37ce-11ea-959b-e626b85127e8.png)

> hmmmm, it still seems to lag? i don't think it worked....

How did you set the values? It works for me though (please remember to restart IINA):

![image](https://user-images.githubusercontent.com/8478049/72430874-637abc00-37ce-11ea-98ed-d7f909094886.png)

**Comment by zxzzz8** [comment]
i restart iina every time no worry, but this setting is for network stuff, not cache for viewing local files....

**Comment by zxzzz8** [comment]
also in this update, did it make it pause when skipping parts in the vid?! is there any way to disable that?

**Comment by zxzzz8** [comment]
also after resuming from skipping, it puts me at the start of the video, thats a bug i guess 0_0

**Comment by zxzzz8** [comment]
![Screen Shot 2020-01-15 at 13;51;41](https://user-images.githubusercontent.com/20977838/72431709-239be080-379e-11ea-949b-fb8b38d78e1a.png)

**Comment by lhc70000** [comment]
So do you still have problem with the configurations in the screenshot? If so, what's the error message?

> did it make it pause when skipping parts in the vid?

Please provide detailed steps on how to reproduce this issue, like which button did you press.

**Comment by zxzzz8** [comment]
anyway i kind of gave up for now and returned to version 1.0.4 where everything seems to work smooth....
idk enough of whats going on about both the cache for local files, or the skipping misbehaving in the new version

**Comment by zxzzz8** [comment]
not any error message, it just occasinally lag like it didn't take effect i think?
it doesn't in 1.0.4....

**Comment by lhc70000** [comment]
>  but this setting is for network stuff, not cache for viewing local files....

No. These settings links directly to `cache` and `demuxer-max-bytes`.

**Comment by zxzzz8** [comment]
the settings under ''network'' in iina setting ui?

**Comment by zxzzz8** [comment]
im having a hard time to pinpoint the issues, i guess ill just use 1.0.4 until new versions come out and then try this whole thing again w newer versions....

**Comment by zxzzz8** [comment]
at least i know there is a new settings format to mpv that ill need to figure out....

but its really confusing in the settings, under network tab, is the catch setting there include local files or not....? coz if it is i don't think it needs to be under that ''Network'' tab, as its global, but if it isn't then it needs to be named as ''cache for streaming'', this current situation makes it seems like it can be either tbh....

anyway to close the issue for now?
