### ISSUE TITLE
播放列表滚动闪退

### ISSUE THREAD

**Issue by metokk** [iina/iina#2727]
打开播放列表滚动会直接闪退

macOS 10.13.6
iina 1.0.6

**Comment by hydd** [comment]
我也遇到了相同的问题，有时候甚至只点击播放列表就会导致崩溃。 
macOS 10.15.3(及更新前上一个版本)
iina 1.0.6
附上日志文件：
[temp.txt](https://github.com/iina/iina/files/4151343/temp.txt)

**Comment by alejx** [comment]
Duplicate of #2745

**Comment by alejx** [comment]
Duplicate of #2745
