### ISSUE TITLE
Unable to toggle saved audio filters

### ISSUE THREAD

**Issue by ekstasis** [iina/iina#2729]
**System and IINA version:**

- macOS:  Mojave 10.14.6
- IINA:  1.0.6 Build 113 (develop HEAD)

**Behavior:**
Clicking the checkbox next to saved audio filters doesn't remove/add the checkmark, and the audio filter doesn't activate/deactivate.

Will provide mpv log on request.
<br>

**Steps to reproduce:**
1. Start a video so that you can hear the audio track.
2. Bring up Audio Filter dialog (Cmd-Shft-G) and create a new audio filter, e.g., Custom(mpv):
 Filter Name ="volume", Filter Value="volume=0.1"
3.  Hit save button and give it any name
4. Click checkbox next to this new saved filter
5. Checkmark should have changed and audio should have become barely audible

- I don't know if MPV has this problem.

**Solution:**
The issue is the `toggleSavedFilterAction` IBAction near/on line 168  in `FilterWindowController.swift`.  It calls `playercore.addVideoFilter` or `removeVideoFilter` even for audio filters.  I have rewritten the function -- let me know if I should go ahead and create a pull request.

**How often does this happen?**
Always.

**Comment by saagarjha** [comment]
> I have rewritten the function -- let me know if I should go ahead and create a pull request.

That would be great!
