### ISSUE TITLE
delete file shortcut

### ISSUE THREAD

**Issue by gg2hh** [iina/iina#2730]
Love the program. 

I was wondering if there was a way to assign the menu command

File > Delete Current File

to a keyboard shortcut?

Thanks

**Comment by xjbeta** [comment]
https://support.apple.com/guide/mac-help/mchlp2271/mac

**Comment by gg2hh** [comment]
Thank you!

Do you know any reason why my mac won't let me use cmd+delete for this shortcut? It accepts cmd+D as the shortcut but not cmd+delete?

**Comment by xjbeta** [comment]
Don't use common shortcuts.

**Comment by gg2hh** [comment]
My prior video player used cmd+delete and I though it was a good choice given that the same shortcut is used in Finder to delete files.

Something that I also liked in my prior player was that it would make a sound whenever you deleted a file. (I think it was the same sound made by Finder when you delete a file.) The feedback that you had achieved what you wanted to do was nice.

**Comment by gg2hh** [comment]
Actually you can delete a file from inside iina directly (and hence there no need to do what is suggested in the first reply - thanks of course anyway xjbeta). 

In the iina preferences, under Key Bindings, when creating a new binding there is a drop down menu titled "Select action". The "Delete current file" action is in there. (I missed this whole menu previously.)
