### ISSUE TITLE
Inconsistent action between opening playlist items and chapters

### ISSUE THREAD

**Issue by anohren** [iina/iina#2734]
**System and IINA version:**

- macOS  10.14
- IINA  1.0.6

Chapters in the sidebar should require double clicks to open, because of 1. consistency with the playlist view, and 2. because jumping in the timeline is a destructive action, and as long as there's no "Undo jump in timeline" feature it throws away current progress, forcing the best of users to binary search the timeline if the jump was an error. That makes this an action that should not be this easy to perform accidentally. 

**Expected behavior:**
Consistent action to open playlist items and chapters since they're presented in the same way with pretty much identical UI elements.

**Actual behavior:**
Playlist items require double clicks, chapters only single clicks. 

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by alejx** [comment]
There are more actions to the playlist item than to the chapters, like we can right click on the playlist items or select multiple of them and delete and so on. But I think it's still reasonable to consider making single-clicking on chapters only highlights the row.

**Comment by anohren** [comment]
I understand that that's the reason playlist  items require double clicks, but that's no excuse for needles inconsistency.
