### ISSUE TITLE
screenshot format is not clickable? Bug

### ISSUE THREAD

**Issue by telepati** [iina/iina#2742]
Hi, I almost click every sub-menu but when I want to change screenshot format it is not clickable. I fully uninstall and re-install again but its still the same. 

**Fond temporary solution**
If anyone struggling with this I found the spot where you can click; Under the P but not inside the bubble its edge of the bubble not outside. I made also a video you can see the right spot.

![Screen Shot 2020-01-26 at 17 25 48](https://user-images.githubusercontent.com/3812286/73136717-c5a2af00-4061-11ea-93a5-b0308edd710e.png)
![Screen Shot 2020-01-26 at 17 29 42](https://user-images.githubusercontent.com/3812286/73136721-cafff980-4061-11ea-8c12-72b675c7a45c.png)

[Screen Recording 2020-01-26 at 18.16.17.mov.zip](https://github.com/iina/iina/files/4113619/Screen.Recording.2020-01-26.at.18.16.17.mov.zip)

iMac 9,1 Unsupported Mac Catalina 10.15.2
INNA 1.0.6 Build 113

**Comment by hazarek** [comment]
known bug https://github.com/iina/iina/pull/2726
