### ISSUE TITLE
Auto-enable Picture-In-Picture?

### ISSUE THREAD

**Issue by mgtest42** [iina/iina#2743]
Is it possible to automatically enable picture-in-picture mode, if the user is switching to another full-screen app?

Currently, IINA allows only manually enable PIP mode, and the user have to disable it to return to full-screen mode.

If you use only one monitor, it's very common that you need to switch to another window, but don't want to interrupt the watching video.

**Comment by anohren** [comment]
What, you mean this? https://github.com/iina/iina/issues/2326

**Comment by anohren** [comment]
I think an attempt was made, but it proved difficult to implement properly.
