### ISSUE TITLE
A problem about the screenshot in general preference

### ISSUE THREAD

**Issue by Corezcy** [iina/iina#2747]
- macOS <-- macOS Mojave 10.14.6 -->
- IINA <-- 1.0.6 -->

when I choose the screenshot option in general preference and copy it to clipboard,
![image](https://user-images.githubusercontent.com/33271784/73444376-71663a80-4393-11ea-9aba-18aa1197fab2.png)
the screenshot in the desktop is correct 
![(P18  18 2 7 2 价格指数：价格指数的分类)-0006](https://user-images.githubusercontent.com/33271784/73444433-86db6480-4393-11ea-8df2-d74f171b5e9c.jpg)
but in clipboard there is something wrong
![image](https://user-images.githubusercontent.com/33271784/73444445-8ba01880-4393-11ea-9f65-c7ec435161df.png)

**Comment by megadr01d** [comment]
Cannot reproduce. Captured to file and clipboard, imported from clipboard to Preview.app and it was OK.

**Comment by Core055** [comment]
Maybe this problem is related to the format of the video。In  some .mp4 files , it  really has this problem 
![image](https://user-images.githubusercontent.com/33271784/74586143-9c9d8a80-501f-11ea-881c-06efd8e696cb.png)
 According to my test , in .avi files , it's  correct.
