### ISSUE TITLE
When finishing a video on a secondary monitor, the whole window moves to the primary window when the next video plays

### ISSUE THREAD

**Issue by chrisblakley** [iina/iina#2749]
**System and IINA version:**

- macOS 10.15.2
- IINA 1.0.6

Note: This has been happening for quite some time on previous OS versions and IINA versions.

**Expected behavior:**

When a video finishes while playing on a secondary monitor, the next video should play without the window moving at all.

**Actual behavior:**

The video finishes while playing on a secondary monitor and then the next video begins and at the same time the window moves to the primary monitor.

**Steps to reproduce:**

Open a video on the secondary monitor (or move the window to the secondary monitor). Make sure another video exists in that directory and that autoplay is on. I have my settings to have the window fill the screen automatically. Let the video finish and when the next video begins the entire window will move to the primary display. 

- [ ] MPV does not have this problem. **I am unable to test in MPV at this time**

**How often does this happen?**

Everytime unless I use fullscreen mode.

**Comment by chrisblakley** [comment]
More information– it seems like it's whichever display the cursor is currently on that causes the IINA window to move to when the video changes.

I see a commit was made, but I wanted to follow-up to make sure I noted this additional information. Thanks.

**Comment by alejx** [comment]
Does this bug happen every time when the cursor is on another screen?

**Comment by chrisblakley** [comment]
That is correct– I have tested this by manually going to the next video and also letting it happen naturally and anytime the cursor is on a different window the IINA window moves to that display. It also happens when I am focused on a different window (like my browser)– in that case, the IINA window moves to that display behind the active window.

The only time this does not happen is if IINA is in fullscreen mode.

**Comment by alejx** [comment]
Can you help us to test this build?
https://drive.google.com/open?id=12xjfdIy7X6eC6_YB7FsAkwaLXnWf-mmB
If you can still observe the window moves to another display, please tell us your configuration (like how you place your two displays) and the exact steps to reproduce the bug.

**Comment by chrisblakley** [comment]
Sure thing– I will test that tonight and provide as much as I can.

**Comment by chrisblakley** [comment]
This version does not move to another display, but it does move to the edge of the window closest to that display.

It looks like the window tries to re-center itself when transitioning from one file to another. This works fine when manually skipping to the next video or letting the next video automatically start with the cursor is on the same display (and if the window is off-center, it re-centers itself to that same display).

If I open a video and then move my cursor to a different display, when the video ends and the next video beings instead of re-centering to the original display, it shifts all the way to the left side of the screen (since my cursor moved to a display left of the screen that the video was playing on).

Here's an attempt at a visual explanation:

When the video changes with the mouse remaining on the same display as the video, it re-centers:
![Screen Shot 2020-02-19 at 7 59 45 PM](https://user-images.githubusercontent.com/6349678/74890627-94608a80-5352-11ea-9e75-eaa42d60b5c5.png)

But, if the video transitions while my cursor is on the display to the left of the one with the video, the IINA window shifts all the way to the left:
![Screen Shot 2020-02-19 at 8 00 21 PM](https://user-images.githubusercontent.com/6349678/74890651-a9d5b480-5352-11ea-885f-9b6ee37a601c.png)

Here is my display arrangement:
![Screen Shot 2020-02-19 at 8 02 07 PM](https://user-images.githubusercontent.com/6349678/74890671-bf4ade80-5352-11ea-8914-8fd23524a3fb.png)
Note: my primary display is the left display, but I have IINA playing on the right display. Screenshots above are all from the right display.

Hope that helps– let me know if there is any additional info I can provide.

**Comment by alejx** [comment]
Do you have initial window position checked?
![image](https://user-images.githubusercontent.com/20237141/74899076-7fd7be80-5361-11ea-9dcf-ecfe949ac4b4.png)

btw nice two 21:9 displays :)

**Comment by chrisblakley** [comment]
I do not have the Initial window position option checked– I like it to be maximized in the center of the screen at all times so I leave that unchecked.

Just tested that latest build at it acts the same as the previous build as described above (centered when I manually go to the next video, but moves to the left edge if my cursor is on my main display).

![Screen Shot 2020-02-20 at 12 08 57 AM](https://user-images.githubusercontent.com/6349678/74902816-398c5a80-5375-11ea-9a13-532ceecc9b5f.png)

**Comment by alejx** [comment]
https://drive.google.com/open?id=19wfTwXPWoTOQi01aTHLoJ9R0zxy1uAjm

Okay, last time! This really should work correctly.

**Comment by chrisblakley** [comment]
Perfect!

**Comment by JohnClay** [comment]
I wonder if this is related to #2801, where all files now open on the primary display.
