### ISSUE TITLE
When I open a new video，The picture of the previous video will stay for a moment

### ISSUE THREAD

**Issue by TechOtaku2233** [iina/iina#2753]
**System and IINA version:**

- macOS 10.15.2
- IINA 1.0.6

**Expected behavior:**
When I open a new video，The picture of the previous video will stay for a moment，about 0.1s-0.3s
，This will show the porn movies I watched last time，this can cause embarrassment when there are others
**Actual behavior:**
Don't show the  picture of the previous video I watched

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
Play any movie, close it, open new movie

- [ ] MPV does not have this problem.

**How often does this happen?**
every time
**Remark**
I know this is duplicated with 2197, but this issue is not resolved

**Comment by saagarjha** [comment]
I think this is the same as #2197, so I'm going to close this in favor of that issue. Please follow that one instead!
