### ISSUE TITLE
Timing bug with a specific video

### ISSUE THREAD

**Issue by francesco-re-1107** [iina/iina#2759]
**System and IINA version:**

- macOS 10.15.3
- IINA 1.0.6 Build 113 (mpv 0.31.0)

**Actual behavior:**
There is an issue when playing this video:
<img width="812" alt="Schermata 2020-02-11 alle 18 20 07" src="https://user-images.githubusercontent.com/32838171/74261449-8f209180-4cfb-11ea-80ec-ca3ccc908604.png">

The issue is about the elapsed time in the control bar. Sometimes it accelerates (e.g. goes from 00:00 to 00:10 in 5 seconds), sometimes it just stops and after a few seconds it is updated again. It is not regular. 
I can't attach the video but I hope that I explained enough the issue.

<br>

<details>
<summary><b>mpv log:</b></summary>

[mpv.log](https://github.com/iina/iina/files/4187076/mpv.log)
</details>

<br>

**How often does this happen?**
Every time I play this video and other similar with the same codec.

**Comment by alejx** [comment]
Have you tried to play this file with mpv directly?

**Comment by francesco-re-1107** [comment]
> Have you tried to play this file with mpv directly?

I've tried it now, and it gives the same issue when played with mpv.

**Comment by alejx** [comment]
Please consider filing this issue to https://github.com/mpv-player/mpv
