### ISSUE TITLE
move file from Finder to IINA play list

### ISSUE THREAD

**Issue by gMan1990** [iina/iina#2764]
**System and IINA version:**

- macOS 10.14.6 18G103
- IINA 1.0.6 Build 113
- media file name: `[test][05][GB][HEVC-10Bit][1080P].mp4`

**Expected behavior:**
1. display the right media file name
2. and the media file can be play

**Actual behavior:**
1. the media file name in play list is error
2. and the media file can not be play

<img width="162" alt="WX20200214-024720@2x" src="https://user-images.githubusercontent.com/5050994/74467891-e29a0780-4ed4-11ea-8f1d-4de08ecda521.png">

**Steps to reproduce:**
1. open some other file
2. open IINA play list
3. open Finder, and move the file to play list

**How often does this happen?**
every time

**Comment by inflation** [comment]
If you are referring the first one, the file name is too long to show so it's abbreviated. If you right click the item you should see the full name.

Also it's too vague to say anything about the playing issue, do you have more information on that? Like codec, logs, and etc.

**Comment by gMan1990** [comment]
@inflation no, the second one in the image
1. file `[test][05][GB][HEVC-10Bit][1080P].mp4` in Finder
2. move it into IINA playlist
3. then the IINA playlist display the error file name

**Comment by inflation** [comment]
"%5D" is particular an URL encoding for "]". So are you playing an URL from a network volume>

**Comment by gMan1990** [comment]
@inflation no, a local file.
