### ISSUE TITLE
Change speed in setting didn't update on video hovering controller panel

### ISSUE THREAD

**Issue by KyleBing** [iina/iina#2766]
**System and IINA version:**

- macOS 10.15.3
- IINA 1.0.6 build 113

**Expected behavior:**
update speed multiplier in video controller after change speed in the play setting manually

**Actual behavior:**
didn't change

 ˙
<img width="948" alt="Screen Shot 2020-02-14 at 10 05 13" src="https://user-images.githubusercontent.com/12215982/74495429-d6349f80-4f12-11ea-9cbd-c445fe191a4a.png">

<br>

<br>

**Steps to reproduce:**

1. open play setting panel on the side
2. change video playing speed
3. video control panel didn't update the speed multiplier

**How often does this happen?**
every time

**Comment by inflation** [comment]
Can't reproduce. Can you provide any log when this happens?
