### ISSUE TITLE
Stay in paused state after seeking to a new position with touch bar

### ISSUE THREAD

**Issue by JuniperPhoton** [iina/iina#2767]
**What you want IINA to do:**

When you pause the video and seek to a new position using **TouchBar**, after seeking, the video should stays in pause state.

**What IINA does currently:**

When you pause the video and seek to a new position using the **main UI on screen**, after seeking, the video is still in the pause state.

However, when using touchbar, video will be played automatically.

**Why you think this should be added:**

This feature will match the behavior when you do the same thing using the main UI on screen.

**Comment by alejx** [comment]
Thanks for reporting. Fixed in develop.
