### ISSUE TITLE
PIP can not withdraw Full Screen Mode

### ISSUE THREAD

**Issue by Rikkano** [iina/iina#2775]
![image](https://user-images.githubusercontent.com/44722787/74650154-0bafe600-51bc-11ea-9cdc-89f7d10cd124.png)
IINA 1.0.6
macOS 10.13.6

**Comment by saagarjha** [comment]
This behavior is currently intentional, but I'd be open to changing it. I feel like someone has asked for this before…

**Comment by anohren** [comment]
I'm the one who changed this behavior. The rationale is in my PR I think. 

@saagarjha feel free to argue for this in that PR even though it is closed. It's easier to have all of it in one place.

**Comment by saagarjha** [comment]
Aha, #2128 was what I was looking for. I think I am still convinced by @anohren's reasoning, so I would have to ask you, @Rikkano, to explain why you think it should behave this way.

**Comment by Rikkano** [comment]
> Aha, #2128 was what I was looking for. I think I am still convinced by @anohren's reasoning, so I would have to ask you, @Rikkano, to explain why you think it should behave this way.

OK, you talk me into it.

**Comment by saagarjha** [comment]
Closing, then. @anohren is too persuasive ;)
