### ISSUE TITLE
两个功能建议

### ISSUE THREAD

**Issue by SealinRepo** [iina/iina#2778]
大佬， 能不能给iina加下这两个功能啊：
1. 只启动一个实例的配置
2.铺满屏幕功能， 现在有的视频左右或者上下有两条黑框

**Comment by lhc70000** [comment]
1. 取消偏好设置 - 通用 - 总是在新窗口打开视频
2. 现在长宽比是固定的，以后会支持解锁长宽比

**Comment by SealinRepo** [comment]
好的， 谢谢
