### ISSUE TITLE
Setting "Single click to hide OSC" not funtioning

### ISSUE THREAD

**Issue by ethawesomee** [iina/iina#2779]
Expected to click in the player and OSC will hide (setting is enabled)
However, the player does not hide.
But for example if right click is configured to hide OSC, it will work fine.

How to reproduce:
Under "Control" configure "Single click to:" to "Hide OSC"
Click in an open video 

Version 1.0.6 Build 113
MacOS 10.15.1 Beta (19B77a)

**Comment by alejx** [comment]
Are you using a magic mouse?

**Comment by ethawesomee** [comment]
Actually, no, but is a Magic Mouse required? It functions fine with right click so I didn’t think so.

**Comment by alejx** [comment]
No, it does not require a magic mouse, but magic mouse could cause this problem. Are you using a regular mouse, then? Because I cannot reproduce using a touchpad.

**Comment by ethawesomee** [comment]
Yea, a MX Master. I should probably reinstall and see if it fixes itself.

I’ll also try and see if I can reproduce it on another computer. We’ll see how that goes

**Comment by ethawesomee** [comment]
Yea, so it just seems like an issue with the installation. After reinstalling it worked fine. Thanks alejx!

**Comment by ethawesomee** [comment]
Actually, never mind its still here. Heres a video showing the issue. At the first (left) click, you can see a significant delay between clicking and it disappearing. On the right-click, it goes away instantly. i have been able to reproduce this on a MacBook and an iMac with two mice.

[IMG_2600 (1).mov.zip](https://github.com/iina/iina/files/4237866/IMG_2600.1.mov.zip)

**Comment by alejx** [comment]
This is the intended behavior. The delay is to distinguish between a single click and a double click. If there's no click after the first click within, say, 1s, we can then assume this is a single click.

**Comment by ethawesomee** [comment]
Okay. I understand. However, I would suggest that maybe the delay should be made a tad shorter as it could be infuriating for some people.

**Comment by alejx** [comment]
This value is not arbitrarily set by us, there's a system setting for this under accessibility:

![image](https://user-images.githubusercontent.com/20237141/75104471-ef9eb100-55ce-11ea-81a9-188b6564ff42.png)

Please consider changing this setting if you think it's too long.

**Comment by ethawesomee** [comment]
Okay, thanks for the help!
