### ISSUE TITLE
Add option to enable Do not Disturb when going full screen

### ISSUE THREAD

**Issue by Stanzilla** [iina/iina#2786]
**What you want IINA to do:**
I want it to automatically enable/disable the macOS DnD mode when entering or leaving fullscreen

**What IINA does currently:**

**Why you think this should be added:**
- I don't want to get interrupted while watching movies

**Examples of other projects that have something similar:**

- MPC-HC
- VLC

**Comment by alejx** [comment]
Info: https://stackoverflow.com/questions/25210120/is-it-possible-to-turn-on-off-do-not-disturb-for-os-x-programmatically

**Comment by megadr01d** [comment]
Declined duplicate of https://github.com/iina/iina/issues/1368.

**Comment by Stanzilla** [comment]
Oh I did not see that, I hope this gets reconsidered.
