### ISSUE TITLE
Add option to save streamed videos

### ISSUE THREAD

**Issue by maa3x** [iina/iina#2790]
I see a lot of videos and movies via online streaming (aka Open URL) using the browser extension. Sometimes I like to save the video I've streamed after it's finished. Currently, if I want to save that video as a file I have to re-download it again.
Is it possible to add an option to save video as it's streamed or after it's done (of course when it's thoroughly seen, I mean if it's not sought or skipped)?

Thanks!

**Comment by inflation** [comment]
Unfortunately, streaming doesn't always keep the whole file (so it won't take up all available spaces). You can use `youtube-dl` directly to download anything that IINA could play.

**Comment by maa3x** [comment]
Yup, IINA just makes a buffer of the video, but it's possible to save that buffer on the disk as it's getting played.

**Comment by jorijnsmit** [comment]
How @maa3x?

**Comment by maa3x** [comment]
@jorijnsmit By saving download buffer to a file on disk (in case the user does not seek the video). I think MPV has the option to save the streaming video to a file.
It is even possible to create a torrent like file format to shrink video into small parts and if the user does fast forward, IINA downloads the missing or broken parts.

**Comment by jorijnsmit** [comment]
Yeah OK but just to be clear: when you are stating that it is "possible", you mean this in a _theoretical_ sense right? I don't believe IINA offers any of those options you mention (save buffer, shrink into smaller parts etc.)

**Comment by maa3x** [comment]
As you can see this is a feature request and the first option (which is saving buffer on disk permanently) is not hard, but it has limitations that I mentioned.
And yes the torrent-like file format possibility is too far and I don't believe that IINA is going to implement this ever. Just said that because you asked "How?".
