### ISSUE TITLE
Some problems about HDR/SDR support

### ISSUE THREAD

**Issue by Neptune13** [iina/iina#2792]
**System and IINA version:**

- macOS 10.15.3 

- IINA  v1.0.6

**Expected behavior:**
I have no idea whether the IINA recognizes the HDR content because it doesn't look like real.  
Recently I found the Movist Pro(v.2.2.15) has a button on the toolbar to show if it's a HDR video and provide a function to make HDR to SDR conversion.

**Actual behavior:**
When using IINA to play HDR videos, it seems that the color space has some deviation and the HDR content doesn't have enough brightness and dynamic range. 

**Here are some screenshots (Monitor： Dell U2718Q )**
<img width="1920" alt="截屏2020-03-0117 52 22" src="https://user-images.githubusercontent.com/61647673/75626373-15950880-5c02-11ea-8bbc-aa6ba87f00e2.png">
<img width="1920" alt="截屏2020-03-0117 52 34" src="https://user-images.githubusercontent.com/61647673/75626377-1fb70700-5c02-11ea-9b11-75c248cc87dd.png">
<img width="1920" alt="截屏2020-03-0117 56 40" src="https://user-images.githubusercontent.com/61647673/75626380-234a8e00-5c02-11ea-8585-6fdaf7b32c65.png">
<img width="1920" alt="截屏2020-03-0117 58 24" src="https://user-images.githubusercontent.com/61647673/75626425-73c1eb80-5c02-11ea-933e-fc99de4bf6ba.png">

**The button on Movist Pro**
<img width="317" alt="截屏2020-03-0119 22 16" src="https://user-images.githubusercontent.com/61647673/75626978-1d0ae080-5c07-11ea-9d7f-7cabe054d795.png">

**Comment by inflation** [comment]
If you don't have an HDR monitor, you couldn't really tell which tone mapping is "closer" to the original experience. Then it's just a preference over the brightness, color, and etc. 

Currently, there are several tone mapping algorithms in mpv. You can check those settings in this thread: https://github.com/mpv-player/mpv/issues/6405
