### ISSUE TITLE
Homebrew-mpv-iina tap fails

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [iina/iina#2793]
[MacOS Catalina 10.15.3]

I'm trying to install mpv-iina and following the Manual Build steps.  However, I am unable to tap inna/hombrew-mpv-iina, so I'm stuck.  See error below.
I have re-installed my homebrew and updated (of course) but the problem still exists. I've reported the error on their repo but I think you should be aware as well.
I'm looking for a media player since my previous one will not run under MacOS Catalina, so I am a potential new iina user and hope this issue is quick and easy to resolve.

        brew tap iina/homebrew-mpv-iina
        ==> Tapping iina/mpv-iina
        Cloning into '/usr/local/Homebrew/Library/Taps/iina/homebrew-mpv-iina'...
        remote: Enumerating objects: 38, done.
        remote: Counting objects: 100% (38/38), done.
        remote: Compressing objects: 100% (26/26), done.
        remote: Total 125 (delta 18), reused 31 (delta 12), pack-reused 87
        Receiving objects: 100% (125/125), 44.74 KiB | 881.00 KiB/s, done.
        Resolving deltas: 100% (58/58), done.
        Error: Invalid formula: /usr/local/Homebrew/Library/Taps/iina/homebrew-mpv-iina/ffmpeg-iina.rb
        ffmpeg-iina: undefined method `use_from_macos' for #<Class:0x00007fb982250240>
        Error: Cannot tap iina/mpv-iina: invalid syntax in tap!

**Expected behavior:**
That the following commands work as expected:

    $ brew tap iina/homebrew-mpv-iina
    $ brew install mpv-iina

**Actual behavior:**
See error message above.

**Comment by lhc70000** [comment]
Seems that @alejx missed a letter in his last commit. I just updated it and please try again now.

**Comment by Napoleon-BlownApart** [comment]
Thanks!!
The Tap worked, and most of the mpv-iina install was successful.  There was a problem linking the docutils-0.16 package:

        brew install mpv-iina
        ==> Installing mpv-iina from iina/mpv-iina
        ==> Installing dependencies for iina/mpv-iina/mpv-iina: docutils, texi2html, aom, frei0r, libidn2, libtasn1, nettle, p11-kit, unbound, gnutls, fribidi, lzo, pixman, cairo, graphite2, icu4c, harfbuzz, libass, libbluray, libsoxr, libvidstab, rtmpdump, libogg, flac, libvorbis, libsndfile, libsamplerate, rubberband, snappy, speex, giflib, leptonica, tesseract, ffmpeg-iina, libarchive, lua@5.1, mujs and uchardet
        ==> Installing iina/mpv-iina/mpv-iina dependency: docutils
        ==> Downloading https://homebrew.bintray.com/bottles/docutils-0.16.catalina.bottle.tar.gz
        ==> Downloading from https://akamai.bintray.com/0e/0ef5a1355a1eeb6d30a19ed818494363151bc05446dddeffed214c8d80e85832?__gda__=exp=1583075749~hmac=b2fc438eaa3cd0302b66bd620f64dd1152ffe3a8b4d8a3433a7ef3b7
        ######################################################################## 100.0%
        ==> Pouring docutils-0.16.catalina.bottle.tar.gz
        Error: The `brew link` step did not complete successfully
        The formula built, but is not symlinked into /usr/local
        Could not symlink bin/rst2html.py
        Target /usr/local/bin/rst2html.py
        already exists. You may want to remove it:
          rm '/usr/local/bin/rst2html.py'
        
        To force the link and overwrite all conflicting files:
          brew link --overwrite docutils
        
        To list all files that would be deleted:
          brew link --overwrite --dry-run docutils
        
        Possible conflicting files are:
        /usr/local/bin/rst2html.py
        /usr/local/bin/rst2html4.py
        /usr/local/bin/rst2html5.py
        /usr/local/bin/rst2latex.py
        /usr/local/bin/rst2man.py
        /usr/local/bin/rst2odt.py
        /usr/local/bin/rst2odt_prepstyles.py
        /usr/local/bin/rst2pseudoxml.py
        /usr/local/bin/rst2s5.py
        /usr/local/bin/rst2xetex.py
        /usr/local/bin/rst2xml.py
        /usr/local/bin/rstpep2html.py
        ==> Summary
        🍺  /usr/local/Cellar/docutils/0.16: 771 files, 8.1MB

**Comment by Napoleon-BlownApart** [comment]
Is the inna version of docutils customised?
In any case, I will try to build the rest tomorrow and hopefully it will work.  

In the meantime, I installed inna using `brew cask install iina`.  However it crashed before it finished playing the first song, while trying to show me the contents of my music repo in the side panel.  I'm getting the Apple 'spinning wheel' a lot while inna is accessing the file system for song names or changing tracks.

I'll see how I go with the build.

**Comment by lhc70000** [comment]
If you are not going to use your own mpv build, please use the prebuilt binary (from brew cask, GitHub release or iina.io).

> Is the inna version of docutils customised?

No. It doesn't contain formulae other than mpv and ffmpeg, and the script should uninstall all dependencies before building. It might be a problem with your homebrew and you can try uninstalling it manually. Anyway, it's always recommended to use a clean environment when building manually.

> However it crashed before it finished playing the first song, while trying to show me the contents of my music repo in the side panel

I believe that this has been fixed in the latest beta version. It will be released soon, and you can get it now from [https://dl.iina.io/IINA.v1.0.7-beta1.dmg](https://dl.iina.io/IINA.v1.0.7-beta1.dmg).
