### ISSUE TITLE
 How to solve the problem that the plug-in local subtitles cannot be loaded in ttml format?

### ISSUE THREAD

**Issue by nikilin233** [iina/iina#2794]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
You need to implement that feature in ffmpeg first.
