### ISSUE TITLE
ADD &nbsp; ignore option

### ISSUE THREAD

**Issue by mileu32** [iina/iina#2795]
There are many subtitles that use & n b s p ; for make blank.
Like daum potplayer on windows, ignore & n b s p ; or add this for option would be great!!
![스크린샷 2020-03-02 오후 3 06 41 복사본](https://user-images.githubusercontent.com/13388715/75649838-aec22e80-5c97-11ea-8f0b-81e2e95282a5.jpg)

**Comment by inflation** [comment]
mpv would be a better place to add this feature. Thank you.
