### ISSUE TITLE
可以做一个播放列表吗？自己添加进来或者设置文件夹自动扫描

### ISSUE THREAD

**Issue by Daxx88** [iina/iina#2799]
在MAC上这款软件很棒了，但是mac的坊达不好用，希望能在软件内就能直接点击视频播放，拥有一个播放列表，而不是观看历史记录，再次感谢作者提供这么棒的软件！

**Comment by YYAppleFan** [comment]
Translation:
Can developers add a function to let users add a playlist or generate a playlist basing on folders? 
IINA is now great on macOS, but Finder isn't that good. I hope I can play the videos in the same folder just by clicking on them in the playlist in IINA. Playlist isn't "History",right?
Thanks again for the great app！

**Comment by iSteveyang** [comment]
这个还有什么不好用的？
<img width="1074" alt="图片" src="https://user-images.githubusercontent.com/20753221/75817375-e8975000-5dd1-11ea-825f-9bed43429170.png">

**Comment by inflation** [comment]
![image](https://user-images.githubusercontent.com/2375962/76001912-d69dd600-5ed3-11ea-8d3c-15094cda26b6.png)
Have you tried the button in the middle? 😅

**Comment by swbbs1982-sys** [comment]
We hope to implement a more user-friendly playlist feature in IINA, allowing users to play videos directly by clicking on playlist files. While IINA does already have a playlist function, could we add functionality to save and track playback positions within the playlist? This way, users could simply click on the playlist file to resume playback from where they left off.
