### ISSUE TITLE
[BUG]Subtitle's sync drifts gradually on few files.

### ISSUE THREAD

**Issue by linxucc** [iina/iina#2800]
**System and IINA version:**

- macOS 
Mojave , 10.14.6
- IINA 
1.0.6

**Expected behavior:**
Playing all kinds of video files, subtitles are perfectly synced.

**Actual behavior:**
When playing some mkv video files, subtitle's sync will drift gradually while playing. 
Upon start, it's all good, but with the playing going on, the actual sync will drift, at the end of a show(about 40 minutes), the subtitle will be 1 or 2 secs later, so I have to manually offset it once at a time.

=========
Hi guys,

Firstly thanks for you guys for developing this brilliant video player for Mac, to now it's the best one can found for Mac.

My problem above looks like a timing/syncing problem, I know this thing happens on audio tracks, so modern video players have a re-sync thing to solve the audio drift problem. This is similar to the audio drift, but this time it's the subtitles.

To my guess, maybe the problem is some subtitles (like this one I encounter) are synced to the audio tracks, but due to the FPS thing, the audio is synced to video once about a time, so gradually, the audio is fine, but the subs are drifted just like the audios without the re-sync. 

I'm not sure it's a bug thing or maybe a little feature like "sync subs to audio" may fix this.
But there are a lot of videos out there may have similar problems (especially the old/classic ones, newer ones are mostly fine), this fix may help a lot.

Thanks!

==========

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment]
This should be a feature in mpv itself. So you could file a request there. Thank you.

**Comment by BeHooman** [comment]
I'm using IINA 1.3.1 Build 133, the aforementioned problem persists.

**Comment by HarukaMa** [comment]
If it's only about oldish files, then most probably it's because the subtitle has been timed on a video that had a slightly different FPS than the current one. Please check if the same subtitle has identical behavior on other players and on MPV.
