### ISSUE TITLE
All videos open on primary display

### ISSUE THREAD

**Issue by JohnClay** [iina/iina#2801]
**System and IINA version:**

- macOS 10.15.3
- IINA 1.0.7b1 (build 115)

**Expected behavior:**

Files open on the most recently used display

**Actual behavior:**

Files are opening on the primary display (the display set in System Preferences -> Displays to have the menu bar)

</details>

<br>
<br>

**Steps to reproduce:**

- Open file, relocate to secondary display.
- Close file (or leave open)
- Open another file. File opens on primary display, rather than display previously used.

**How often does this happen?**
Always. Started with 1.0.7b1/build 115; not an issue with 1.0.6

Initial window position is not set in preferences.

**Comment by lhc70000** [comment]
This is intended in 1.0.7. I think we can add an option to re-enable this.

cc @alejx

**Comment by JohnClay** [comment]
Can I suggest noting that in the release notes? It's a very annoying behaviour if you have multiple displays.

An option to force files to open on a specific display would be pretty nice (similar to VLC), but otherwise just respecting the most recently used display works well.

**Comment by douglasmaltby** [comment]
I see the commit, so thanks for resolving this behavior in beta1! I came here to report this exact issue. 

Opening every video on the primary display should not be the default behavior. My preference is to open new videos at last window location. My second (of 3) monitors is where I generally play video. At minimum, make the behavior a user defined parameter (e.g. always open on primary or open at last window position).

It appears that the commit setting UserDefaults with MainWindowLastPosition should resolve this issue. Thanks! 

IINA is great work and I look forward to next beta build.

**Comment by JohnClay** [comment]
Thanks for the fix. Much appreciated!

**Comment by alexandre-zia-ifood** [comment]
This is annoying, I have 3 displays and any new video opens on the primary display ...
