### ISSUE TITLE
Option to not show popup on chapter change

### ISSUE THREAD

**Issue by Stanzilla** [iina/iina#2805]
**What you want IINA to do:**
Offer an option to not show a notification when a movie switches to a new chapter

**What IINA does currently:**
Every time a movie reaches a new chapter, there is a popup that overlays the video

**Why you think this should be added:**
The UI should not overlay the video in this case and be optional. I understand showing the popup when the file changes but not for chapters

**Examples of other projects that have something similar:**

**Comment by YourMJK** [comment]
I fully agree with this. It's very distracting when watching a movie in fullscreen.
I would even argue that this should be disabled per default.

**Comment by GraOrigin** [comment]
Noticed this too, since the last update..
It seems to be connected to "On-Screen-Display Setting" and can be deactivated in Settings -> Display. This deactivates the OSD of Volume & Time as well, but better than the annoyance of every chapter...

**Comment by lhc70000** [comment]
Thanks for reporting this problem, and we are going to fix it in the 1.0.7 stable release.

As a reminder, please always indicate your IINA version when reporting issues. We will pay special attention to regressions and newly introduced bugs in beta versions.
