### ISSUE TITLE
请考虑更新下字幕的渲染样式，若可以则字幕的美观度将会有质的提升。Please consider updating the rendering style of the subtitles, if possible, the aesthetics of the subtitles will be improved qualitatively.

### ISSUE THREAD

**Issue by smart-z** [iina/iina#2808]
请考虑更新下字幕的渲染样式，若可以则字幕的美观度将会有质的提升。
目前的字幕渲染比较简单，如果可以的话，可以做如下功能：

1. 字幕的边框渲染可以设置为0.1这样的，目前边框最小为1，无论怎么设置，字幕的效果就是一个粗粗的大边框，去掉边框的话字幕在某些环境下又难以辨认。
2. 字幕的字体可以设置渐变，如果可以的话。
3. 字幕的边框可以设置渐变，如果可以的话。
4. 字幕的模糊也可以设置为1以下，可以设置为0.1这样的。

下面的图简单随随便便画了一下，一个是目前系统我可以调的字幕样式，一个是根据上面的新功能可以做到的样式。因为是随便画的配色啥的请忽略。若单论新样式，美观度还是很值得的。

如果可以请务必考虑。🙏

My English is so poor, so thanks Google Translate. I AM SORRY.😭

Please consider updating the rendering style of the subtitles, if possible, the aesthetics of the subtitles will be improved qualitatively.
The current subtitle rendering is relatively simple. If you can, you can do the following functions:

1. The border rendering of the subtitles can be set to 0.1, and the minimum border is currently 1. No matter how it is set, the effect of the subtitles is a thick and large border. If the borders are removed, the subtitles are difficult to recognize in some environments.
2. The font of the subtitles can be set to a gradient, if possible.
3. The border of the subtitles can be set to a gradient, if possible.
4. The blurring of subtitles can also be set to less than 1 and can be set to 0.1.

The following pictures are simply and casually drawn, one is the subtitle style that I can adjust in the current system, and the other is the style that can be done according to the new features above. Because it is a random color scheme, please ignore it. If you only talk about new styles, the beauty is still worth it.

Please consider it if you can.

![Xnip2020-03-06_13-15-54](https://user-images.githubusercontent.com/1166675/76055054-88f59c00-5fad-11ea-9578-cb8c2b462f40.jpg)

**Comment by inflation** [comment]
We would like to keep the viewing experience to be as universal as possible. So it would be better to keep with mpv's default behavior. Thank you.
