### ISSUE TITLE
Wish the function showing the embedded lyrics  when playing a music file.

### ISSUE THREAD

**Issue by ghGYR** [iina/iina#2813]
**What you want IINA to do:**
Show the embedded lyrics and play control  in status bar  when playing a music file.
Example:
<img width="1057" alt="截屏2020-03-0820 51 23" src="https://user-images.githubusercontent.com/16167640/76176435-a9288500-617e-11ea-8746-499e6e814804.png">

**What IINA does currently:**
not support.

**Why you think this should be added:**
Many online music app can do that but I would rather use IINA which is the best  local player.

**Examples of other projects that have something similar:**
QQ , NeteaseCloud.
LyricsX(which is a similar project but doesn't support IINA)
https://github.com/ddddxxx/LyricsX.

**Comment by inflation** [comment]
We would like to keep the function of IINA more focus on a player. Thank you.
