### ISSUE TITLE
关于加载视频内嵌字幕的问题

### ISSUE THREAD

**Issue by amosly** [iina/iina#2819]
为了测试这个问题,我找了三种视频.均为内嵌字幕.不同之处在于.

1.内嵌字幕没有指定默认字幕.
2.内嵌字幕有指定默认字幕但是并非中文.
3.内嵌字幕有指定默认字幕并且是中文.

测试过几次之后我发现IINA的字幕加载逻辑是
对于视频1.默认不加载字幕.
对于视频2.加载默认的非中文字幕.
对于视频3.可以正常加载默认的中文字幕.

对了确认我的想法,我特意去Windows平台上用potplayer进行了对比发现都可以自动加载中文字幕.

我在想是否可以让iina也可以自动选择中文字幕呢?

IINA版本 1.0.6 Build 113 Macos Mojave 10.14.6
PotPlayer版本 1.6.51480 Windows 10 1809

**Comment by inflation** [comment]
Have you tried this option?
![image](https://user-images.githubusercontent.com/2375962/76671791-8b886080-656e-11ea-8a85-e891c4fff8b0.png)

**Comment by amosly** [comment]
谢谢,这个选项可以,非常抱歉我之前没有注意到.
