### ISSUE TITLE
[Feature Request] Add Boss Key shortcut (like in VLC)

### ISSUE THREAD

**Issue by stanmots** [iina/iina#2823]
Hi,

First of all, thank you so much for this project, this is my favorite macos video player so far.

However, I would like to ask you about one little thing. It would be great, if you could implement a way to add a Boss Key shortcut. I really liked this feature in _VLC_. Boss Key, in short, functions like this: you press a key that you define, and the media player pauses the playback and minimizes all its current windows.

Currently It is possible to configure different keyboard shortcuts in _IINA_. But there is no way to add the mentioned Boss Key shortcut. 

I think, this feature could be useful for many _IINA_ users. 

Thanks in advance.

**Comment by chucker** [comment]
Other than pausing playback, you can already do this by pressing `⌘-H` or holding `⌥` and clicking any other app.

You'd probably have to tick this checkbox:

>Pause/resume when:
>
>[x] Window became inactive/active

**Comment by stanmots** [comment]
> Other than pausing playback, you can already do this by pressing ⌘-H

Yeah, but the whole point of the boss key is that I need only to click ONE button to perform two actions = convenience

>  or holding ⌥ and clicking any other app.

Sorry, I'm not sure I understand this, how would I click any other app while watching a movie in the full screen mode?

**Comment by chucker** [comment]
>Yeah, but the whole point of the boss key is that I need only to click ONE button to perform two actions = convenience

Right. Like I said, if you have "pause when window became inactive" on, it should be one action (albeit two keys).

>Sorry, I'm not sure I understand this, how would I click any other app while watching a movie in the full screen mode?

Yeah, in full-screen mode, it's quite different.

I would again suggest the "pause when window became inactive" preference. Turn on that preference, close the Preferences window (important! the video player needs to be the _only_ IINA window), then play a movie at full screen. Now, as your boss key short cut, four-finger-swipe* out of IINA. Four-finger-swipe back in, and the video resumes!

*) The actual gesture depends on your trackpad/mouse settings.

**Comment by stanmots** [comment]
Thanks for the advices, it all works fine! I think, it's a matter of a habit - I used VLC for a long time so I tried to find similar settings at first.
