### ISSUE TITLE
Thumbnails do not generate when playing video over AFP

### ISSUE THREAD

**Issue by jacobxdouglas** [iina/iina#2832]
**System and IINA version:**
- macOS 10.15.3 (19D76)
- IINA 1.0.6 Build 113

**Expected behavior:** Thumbnails generate for the video playing. This works for me with local files.

**Actual behavior:** 
Thumbnails do not generate when playing video over AFP, from a hard drive plugged into my router.

**How often does this happen?** 
Always

**Comment by robert-corlett** [comment]
`defaults write com.colliderli.iina enableThumbnailForRemoteFiles -bool YES`

though i read somewhere that this only seems to work for a single session, ie you need to issue the command again before you open IINA again

**Comment by jacobxdouglas** [comment]
@robert-corlett It seems to do the trick permanently -- thank you!

Hopefully this option can be  added the in-app preferences.
