### ISSUE TITLE
IINA crashes when trying to set a preferred subtitle language

### ISSUE THREAD

**Issue by cotaricky** [iina/iina#2847]
**System and IINA version:**
- macOS 10.15.4 
- IINA 1.0.7-beta1 (115)

**Expected behavior:**
IINA lets you type the preferred language in the preferences.

**Actual behavior:**
The app crashes.

**Steps to reproduce:**
Open the preferences and start typing the language, after you type the first E in English, the app crashes.

**How often does this happen?**
Always.

![Screenshot 2020-04-02 at 03 28 58](https://user-images.githubusercontent.com/46688224/78204902-c22d0900-7492-11ea-9701-42fd2d45ace6.png)

**Comment by saagarjha** [comment]
![image](https://user-images.githubusercontent.com/13786931/78206577-1664c880-7454-11ea-9000-687460896732.png)

**Comment by saagarjha** [comment]
I think this is #2806, though, so I'm going to close this in favor of that issue.
