### ISSUE TITLE
Friendship ended with CocoaPods; now Swift Package Manager is IINA's best friend?

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [iina/iina#2867]
## What I want IINA to do:

I propose that it's time for IINA to bid a "Cheerio!" to CocoaPods, and a "Hey-yo!" to Swift Package Manager.

## What IINA does currently:

All of IINA's dependencies are currently managed through CocoaPods, except for mpv libraries.

### CocoaPods bad

CocoaPods is [built with Ruby](https://cocoapods.org), whose runtime [will not be included in future macOS versions](https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_release_notes). Developers can always get it through Homebrew, or build it from source, or get it by some other means. However, this just adds a, albeit thin, layer of complexity in building and testing IINA.

There does exist a [macOS app for CocoaPods](https://cocoapods.org/app), which is supposed to make things easier. But instead, it just makes things more difficult, because it only releases for each major CocoaPods release, so it's seldom up-to-date.

With CocoaPods, the project's access point becomes the `.xcworkspace` file, instead of the `.xcodeproj`. This might be necessary from CocoaPods' point of view, and mostly harmless to the code. Semantically, it's absolutely unnecessary and even harmful, because the existence of a `.xcworkspace` implies multiple related Xcode projects, and IINA is a single Xcode project. It's again adding just a thin layer of complexity and a tiny bit of friction on working with Xcode projects, but it's adding on top of the already super steep learning curve of Xcode and Cocoa programming. It's not very friendly to new contributors.

CocoaPods adds an additional point of failure (and one more with Ruby in future macOS releases). Having CocoaPods, Ruby, and Xcode stuff at the same time has the potential of things getting messy for some developers who need to use different versions of things for different project on the same system. One wrong step, and it could be hours of fiddling with system files before things get right again. [Kinda-related xkcd](https://xkcd.com/1987/).

### Swift Package Manager good

Swift Package Manager is part of the Swift language, and comes with Xcode. It doesn't need anything or any steps of building it or whatnot. It just works. 

Xcode has one-click's for most of SwiftPM things. No more needs for error-prone command line operations.

Swift Package Manager has first-party support from the Swift core team.

Swift Package Manager doesn't alter file structures unnecessarily. It's friendly to everyone.

All IINA's existing dependencies except for Sparkle has full SwiftPM support. Sparkle's SwiftPM support requires a [feature](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md) that's recently [accepted](https://forums.swift.org/t/se-0271-package-manager-resources/30730/63) and [implemented in Swift 5.3](https://forums.swift.org/t/se-0271-package-manager-resources/30730/74). There has been [discussions](https://github.com/sparkle-project/Sparkle/issues?q=swift+package+manager) and [work done](https://github.com/sparkle-project/Sparkle/pull/1486/commits/c263dda33f17fa61862dd81613cd8fa7eb1a10c4) on bringing SwiftPM support to Sparkles. It's probably safe to assume that it'll come soon-ish.

Even if Sparkle will never fully support Swift Package Manager, it can always join mpv libraries, added and linked to the project manually.

## Examples of other projects that have something similar:

N/A, Irrelevant for this particular issue.

## And now for something completely different:

Because I can't help myself, here is a premature celebration.

![Friendship_ended_with_CocoaPods_Now_Swift_Package_Manager_is_IINA's_best_friend](https://user-images.githubusercontent.com/55120045/79083447-66694800-7cfc-11ea-8d2a-3be12241cbe4.jpg)

**Comment by WowbaggersLiquidLunch** [comment]
I was playing around a bit with IINA's dependencies and Swift Package Manager. Just realised that IINA maintains its own version of Just. So far, it seems like it's "implicitly" supported by SwiftPM. 

I see there are some additional compiler flags in IINA's version's "swift-5" branch. I'm not sure if the upstream did anything for SwiftPM support. If it did, would it benefit or hurt from rebasing onto the upstream?

**Comment by saagarjha** [comment]
Personally, I’m not a huge fan of CocoaPods, so I wouldn’t be opposed to switching to Swift Package Manager. I’m not sold on the Ruby argument as I wouldn’t be surprised if it shipped with the Command Line Tools in the future, but I do agree that it’ll probably reduce complexity. 

That being said, I haven’t looked into how Swift Package Manager works or how well Xcode supports it these days so this would be somewhat new. We vendor some of our dependencies because we’ve historically adopted new versions of Swift faster than they have; I have not checked if this is still an issue. We could probably rebase them if necessary. 

If you think you can get this to work nicely I wouldn’t be against it, but I think it’d be nice to hear what the other maintainers have to say.

**Comment by lhc70000** [comment]
I have no objection and would be happy to switch to SPM if it works well. If you have done some work locally, a pull request is also welcomed.

**Comment by WowbaggersLiquidLunch** [comment]
resolved by #2877 and #3365
