### ISSUE TITLE
置顶窗口，拖动

### ISSUE THREAD

**Issue by wayone** [iina/iina#2869]
Version 1.0.7-beta1 Build 115

当此应用窗口置顶后，然后鼠标点击别的应用窗口，这样置顶窗口就失去焦点了。此时，将鼠标移动到置顶窗口的上面，直接拖动，发现拖不动，需要点击一下置顶窗口后，再拖动才可以。

希望不用那次点击，可以直接拖动。

**Comment by lhc70000** [comment]
正好 1.0.7 beta1 中在「偏好设置-控制」中加入了「没有焦点时接受第一次鼠标点击」的选项，启动即可。
