### ISSUE TITLE
小建议: 在 Finder 中显示

### ISSUE THREAD

**Issue by lyqflnh** [iina/iina#2870]
当电脑文件多了之后, 而视频又在一层一层的文件夹中, 
'在 Finder 中显示' 这个功能用到的频率就很高了

当看完一个文件夹内最后一个视频后, 
现在, 可以在播放列表里右键视频文件, 在 Finder 中显示

虽然, 也不麻烦, 但有一次, 右键后, 手一抖, 选成了"移到垃圾桶"(2个选项离得很近)...
而视频又在移动硬盘里, 直接没出现在系统的垃圾篓中, 而是在移动硬盘隐藏的垃圾篓中, 
不知道这一点的同学, 可能当场就 MMP 了...

**一个小建议:** 
在 偏好设置 -> 界面->  播放控制 -> 工具栏自定义里 加一个按钮 
或者
最简单的, 添加一个快捷键

**Comment by zcccccc1** [comment]
"When there are too many files on the computer, and the video is in a folder layer by layer,
'show in Finder' is used a lot

When you've watched the last video in a folder,
Now, you can right-click the video file in the playlist and display it in the Finder

Although it doesn't bother, but once, right after a shake of the hand, I selected "move to the trash can "(the 2 options are close)...
And the video is on the removable hard drive, it didn't move to the system's trash bin, but in the removable hard drive's hidden trash bin,

**Tip:**
Add a button in the preferences -> UI -> On Screen Controller -> toolbar customization
or
At its simplest, add a shortcut"

**Comment by alejx** [comment]
右键点击菜单栏里的文件图标（后面的文件名也行），然后点第一层文件夹 就会弹出 Finder 并高亮当前正在播放的文件
