### ISSUE TITLE
Crash at startup - IINA 1.0.7 beta 1

### ISSUE THREAD

**Issue by Oleg-Chashko** [iina/iina#2873]
Crash at startup - IINA 1.0.7 beta 1
macOS v.10.15.4 (19E287)
[Diagnostic Reports IINA_crash.zip](https://github.com/iina/iina/files/4475296/Diagnostic.Reports.IINA_crash.zip)

**Comment by lhc70000** [comment]
Seems that it crashed when loading the default Movist key binding.
```
globalinit_028_33B0E3DBCAC57BABBAE76BA0478A3CE2_func1355 (in IINA) (PrefKeyBindingViewController.swift:34)
```

I think a simple reinstallation may solve your problem. But before you do that, could you navigate to `/Applications/IINA.app/Contents/Resources/config/` (by right-clicking IINA.app - show package contents) and check whether the file `movist-default-input.conf` exist? Normally you will find four .conf files in the `config` folder. It would help if you could upload those files for our inspection.

**Comment by Oleg-Chashko** [comment]
Yes, I also correct this, reinstall IINA. "Movist" I deleted. I like the "IINA" player more, a good audio player in it.

**Comment by Oleg-Chashko** [comment]
Installed "IINA 1.0.7 beta 2" and "Movist Pro v.2.2.16". During the 5 hours of the test, there was no crash. Deleted "Movist Pro", everything works fine. I think the topic can be closed. Thanks.
[config.zip](https://github.com/iina/iina/files/4476857/config.zip)
