### ISSUE TITLE
The "SVP - iina" collaboration is not working anymore, possible fix in next release?

### ISSUE THREAD

**Issue by vacarogit** [iina/iina#2875]
I use IINA to play video a lot, I follow instructions below to
1.install MPV
2. replace libmpv.1.dylib and symlink it for IINA ...
https://www.svp-team.com/wiki/SVP:IINA

But If I do these in terminal, my IINA play can't open

1. brew install mpv
2. brew reinstall --build-from-source mpv
3. Open Terminal and remove all the libmpv.* files distributed with IINA:
rm -f /Applications/IINA.app/Contents/Frameworks/libmpv.*
4.Link Homebrew's mpv to IINA.app:
ln -s /usr/local/lib/libmpv.1.dylib
/Applications/IINA.app/Contents/Frameworks/libmpv.1.dylib
OR ln -s  /usr/local/Cellar/mpv/0.32.0/lib/libmpv.1.107.dylib
/Applications/IINA.app/Contents/Frameworks/libmpv.1.dylib

*********
Below is excerpt of iina's log,

libmpv.1.107.0.dylib is what brew installed in my cellar. I have no clue

Path:                  /Applications/IINA.app/Contents/MacOS/IINA
Version:               1.0.7-beta1 (115)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           IINA [56674]

Date/Time:             2020-04-03 18:03:26.730 +0800
OS Version:            Mac OS X 10.13.6 (17G3025)

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: _$S10Foundation10CocoaErrorVN
  Referenced from:
/Library/Developer/CommandLineTools/usr/lib/swift/macosx/libswiftCoreData.dylib
  Expected in: /Applications/IINA.app/Contents/MacOS/../Frameworks/libswiftFoundation.dylib
 in /Library/Developer/CommandLineTools/usr/lib/swift/macosx/libswiftCoreData.dylib

       0x1026ff000 -        0x102a4afff +libmpv.1.107.0.dylib (0)
<4BDE29BE-83D4-36A6-BDA1-8DB8C7D29474>
/usr/local/Cellar/mpv/0.32.0/lib/libmpv.1.107.0.dylib

**Comment by lhc70000** [comment]
Please compile mpv with the `--disable-swift` option. Since homebrew has removed these flags, you must run `brew edit mpv` and change the formula manually as below:

![image](https://user-images.githubusercontent.com/8478049/79249014-3910cb80-7eaf-11ea-9310-1fde57c578ad.png)
