### ISSUE TITLE
Temporary conditional compilation in Travis CI build job

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [iina/iina#2880]
Because of pull request #2877's removal of CocoaPods, I propose for a temporary Travis CI build job configuration that conditionally compile IINA based on the presence of `Podfile` in this transitionary period. 

This is the relevant snippet of the build job log showing the build failure is because `Podfile` is gone:

> ```
> 642 $ pod update
> 643 [!] No `Podfile' found in the project directory.
> 644 The command "pod update" failed and exited with 1 during .
> 645 
> 646 Your build has been stopped.
> ```

The full log can be found [here][log]

If this proposal is accepted, this CI configuration change will come as its own pull request, and pull request #2877 will add a commit to remove the conditional compilation and use only CocoaPods-less configuration.

(I was going to just post this as a comment to issue #2867. However, seeing how this would possibly impact other pending pull requests, I think it deserves its own thread.)

[log]: https://travis-ci.com/github/iina/iina/jobs/319717810#L642

**Comment by saagarjha** [comment]
I think we can just edit .travis.yml in the pull request and Travis will pick it up? If not, I think we can just do a clean break.

**Comment by WowbaggersLiquidLunch** [comment]
I edited `.travis.yml` in the pull request, and Travis did pick it up.

I couldn't figure out how to have `Podfile`'s presence as a condition for Travis CI, though. I just removed pods, and had Travis CI build only the project instead of the workspace.
