### ISSUE TITLE
Secondary subtitle position can be adjustable?

### ISSUE THREAD

**Issue by edok10** [iina/iina#2890]
**What you want IINA to do:**
I want to adjust secondary subtitles position to be displayed below the primary subtitles.
**What IINA does currently:**
Secondary subtitle position can not be adjustable.
**Why you think this should be added:**
It should be looks like this.
![image](https://user-images.githubusercontent.com/22033645/79763371-934dd880-8356-11ea-9a80-565776570e03.png)

**Comment by askenson** [comment]
Guys, yess it's a very annoying thing. When you want to show 1-subtitles below 2-subtitles BUT not at the corners (up / down) of the screen. Pleeeaase, fix this!

**Comment by mbogos** [comment]
Hello, dear iina team! Please make the possibility to move down the second subtitles. It's a really important option!

<img width="1792" alt="Снимок экрана 2020-04-22 в 15 53 00" src="https://user-images.githubusercontent.com/64144148/79984338-af19c180-84b1-11ea-92b7-000d60031bbb.png">

**Comment by euf** [comment]
As far as I know, this is a limitation in the mpv
https://github.com/mpv-player/mpv/issues/3022

**Comment by lhc70000** [comment]
Sorry but it's not possible since mpv doesn't support it.

**Comment by aliyazdi75** [comment]
@lhc70000
I think they added this function in https://github.com/mpv-player/mpv/pull/13073
I don't if it's late after 4 years :)

**Comment by LgnGithub** [comment]
Seriously not supporting such super basic option as moving subtitles downward? Garbage player.
