### ISSUE TITLE
视频旋转后建议截图应该截取视频旋转后的图

### ISSUE THREAD

**Issue by martin-meng** [iina/iina#2892]
如上述描述，比如我用手机横屏录制了画面，在电脑端用播放器播放需要旋转270°才是横屏，此时如果用播放器截图，前往截图文件夹发现，图片都是错位拉伸变形的。

**Comment by lhc70000** [comment]
目前这里由 mpv 控制，没有办法改进。

建议直接使用预览 App 转回来。有能力的话，请向 mpv 反馈。
