### ISSUE TITLE
更新了1.0.6版本后无法通过拖拽边缘进行自由比例缩放

### ISSUE THREAD

**Issue by CELESTEDULANDAL** [iina/iina#2893]
如题，没有修改任何东西，现在如果不进入全屏模式只能按照影片原有的比例进行缩放，而不能通过上下自动补黑边进行自由缩放，在观看一些21：9的宽幅影片时的体验很差。有没有人能告诉我该怎么样恢复自由缩放啊？（捂脸）
Mac型号为mbp13 2016 with 4 thunderbolts， Mac OS版本为 10.15.2

**Comment by lhc70000** [comment]
IINA 一直都是锁定长宽比的，可能你之前遇到的是 bug。

自由缩放会在后续版本添加：https://github.com/iina/iina/milestone/10。
