### ISSUE TITLE
Offset the subtitles while bottom navigation bar is on

### ISSUE THREAD

**Issue by NikeX** [iina/iina#2900]
**What you want IINA to do:**
I would like when the mouse is moved and the bottom nav bar is present the subtitles to be offset by the bar.

**What IINA does currently:**
Currently when the navigation bar is on the subtitles are overlapped and they are hard to read.

**Why you think this should be added:**

**Examples of other projects that have something similar:**
The pictures below show how it looks now and how I imagine it to work.
<img width="1280" alt="Screenshot 2020-04-26 at 11 48 30" src="https://user-images.githubusercontent.com/27137177/80302996-1d15ff80-87b6-11ea-8869-a70a38c66a5c.png">
<img width="1280" alt="Screenshot 2020-04-26 at 11 48 30 2" src="https://user-images.githubusercontent.com/27137177/80302997-2010f000-87b6-11ea-8cec-ffa2e8327740.png">

**Comment by lhc70000** [comment]
See #2717, #1340, #42.
