### ISSUE TITLE
如何逐帧播放呢？版本号1.0.7

### ISSUE THREAD

**Issue by baduyifei** [iina/iina#2901]
如何逐帧播放呢？版本号1.0.7

**Comment by 1c7** [comment]
逗号和句号可以上一帧/下一帧

**Comment by baduyifei** [comment]
如何在播放进度条上显示帧数，而不是时间呢？



    


            在2020年04月29日 12:36，Cheng Zheng 写道： 

逗号和句号可以上一帧/下一帧



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/iina/iina/issues/2901#issuecomment-620983940",

"url": "https://github.com/iina/iina/issues/2901#issuecomment-620983940",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by lhc70000** [comment]
> 如何在播放进度条上显示帧数，而不是时间呢？

在考虑，后续版本会加入。
