### ISSUE TITLE
When using the command (open /Applications/IINA.app) to start, can I specify the url to play, what to do, thank

### ISSUE THREAD

**Issue by hugbio** [iina/iina#2909]
When using the command (open /Applications/IINA.app) to start, can I specify the url to play, what to do, thank

**Comment by lhc70000** [comment]
If you want to invoke IINA from the command line, please use the bundled `iina-cli`:

```
/Applications/IINA.app/Contents/MacOS/iina-cli
```

Run `iina-cli --help` for the usage.

**Comment by hugbio** [comment]
Ok.  Thank you
