### ISSUE TITLE
Comment overlay or display of comments

### ISSUE THREAD

**Issue by curetypeface** [iina/iina#2912]
I'd like the ability to read a comment file with timecode written in XML and overlay it on top of the video like niconico/bilibili ,or display it in a sidebar.

Currently, there is no such application under continuous development, and I would like to enjoy comment overlay,and timecode jump, when watching locally saved videos or live broadcast archives.

**Comment by lhc70000** [comment]
This will be achievable when the plugin system is finished. Please stay tuned.
