### ISSUE TITLE
Macbook Pro启动独显进行加速问题

### ISSUE THREAD

**Issue by acwe11** [iina/iina#2919]
最近播放120fps的4k视频，比如《头号玩家》《双子杀手》，MKV封装，H265编码，120fps，在Macbook Pro上默认启用的是Intel UHD630集显加速，无法实现流畅播放，帧率大概在40-60之间，50以下比例很大。但在iMac下，可以直接调用独显加速。不知道可否加入调用独显加速的方法。或者，是不是mpv内核无法适合Macbook Pro 16的独显？而可以识别iMac 5k的独显？

**Comment by lhc70000** [comment]
不太确定这个问题（如何看出当前使用哪个显卡加速？），如果可以的话建议向 mpv 询问。

IINA 最多可以考虑加入强制独显的选项，但是需要验证一下可行性。

**Comment by hooke007** [comment]
＋1，我以为是我黑苹果的问题，逛了一圈果然白苹果也是一样，QuickTime能流畅无比的解码，iina这边完全是ppt，尝试改用软解能缓解，但是处理器略弱还是会时不时掉帧。

**Comment by gth7754125** [comment]
iina 基于 mpv， 应该支持 mpv 的设置
若播放4k， 建议在 config 中添加：
macos-force-dedicated-gpu=yes  # 强制使用mac 下的 AMD GPU
deband=no  # 关闭去色带
vd-lavc-threads=32

mpv 在 mac 下播放4k以上的视频几乎不能添加任何 glsl-shader, scaler 尽量别用高配置，否则会出现笔记本发热严重引起降频卡顿。

**Comment by lhc70000** [comment]
mpv 的 `macos-force-dedicated-gpu` 不会工作，但是下个版本会添加同样的设置。
