### ISSUE TITLE
使用音乐模式播放音乐时BUG报告，IINA崩溃 (附mpv.log)

### ISSUE THREAD

**Issue by Bannyoo** [iina/iina#2924]
**System and IINA version:**

- macOS  10.15.1
- IINA  1.0.6

**Expected behavior:**

**Actual behavior:**
播放音乐并使用音乐模式时
点击 截图快捷键(screenshot)   会使IINA崩溃自动关闭
点击 播放列表面板快捷键(@iina playlist-panel)   不能打开音乐列表

<details>
<summary><b>Crash report:</b></summary>

播放音乐并使用音乐模式时
点击 截图快捷键(screenshot)   会使IINA崩溃自动关闭
点击 播放列表面板快捷键(@iina playlist-panel)   不能打开音乐列表

</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

-----iina.log------
12:27:44.717 [iina][d] App will launch
12:27:44.770 [iina][d] App launched
12:27:44.773 [iina][d] Loading key bindings
12:27:44.779 [iina][d] Set key bindings
12:27:44.910 [iina][d] Setting up MediaPlayer integration
12:27:44.916 [player0][d] Set path to /Applications/IINA.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
12:27:44.990 [player0][d] Track list changed

-----mpv.log------
[   0.014][v][cplayer] mpv 0.31.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
[   0.014][v][cplayer]  built on Mon Jan 13 00:10:36 CST 2020
[   0.014][v][cplayer] ffmpeg library versions:
[   0.014][v][cplayer]    libavutil       56.31.100
[   0.014][v][cplayer]    libavcodec      58.54.100
[   0.014][v][cplayer]    libavformat     58.29.100
[   0.014][v][cplayer]    libswscale      5.5.100
[   0.014][v][cplayer]    libavfilter     7.57.100
[   0.014][v][cplayer]    libswresample   3.5.100
[   0.014][v][cplayer] ffmpeg version: 4.2.1
[   0.014][v][cplayer] 
[   0.014][v][cplayer] Configuration: waf configure --prefix=/usr/local/Cellar/mpv-iina/0.31.0 --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-uchardet --enable-libbluray --disable-swift --disable-debug-build --disable-macos-media-player --confdir=/usr/local/etc/mpv --datadir=/usr/local/Cellar/mpv-iina/0.31.0/share/mpv-iina --mandir=/usr/local/Cellar/mpv-iina/0.31.0/share/man --docdir=/usr/local/Cellar/mpv-iina/0.31.0/share/doc/mpv-iina
[   0.014][v][cplayer] List of enabled features: 51deb aligned_alloc asm atomics bsd-fstatfs build-date cocoa coreaudio cplayer cplugins drmprime fchmod ffmpeg gl gl-cocoa glob glob-posix gnuc gpl iconv javascript jpeg lcms2 libarchive libass libass-osd libav-any libavcodec libavdevice libavutil libbluray libdl libm libmpv-shared lua macos-10-11-features macos-10-12-2-features macos-10-14-features macos-touchbar optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads rubberband stdatomic uchardet videotoolbox-gl videotoolbox-hwaccel zlib
[   0.014][v][cplayer] mpv 0.31.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
[   0.014][v][cplayer]  built on Mon Jan 13 00:10:36 CST 2020
[   0.014][v][cplayer] ffmpeg library versions:
[   0.014][v][cplayer]    libavutil       56.31.100
[   0.014][v][cplayer]    libavcodec      58.54.100
[   0.014][v][cplayer]    libavformat     58.29.100
[   0.014][v][cplayer]    libswscale      5.5.100
[   0.014][v][cplayer]    libavfilter     7.57.100
[   0.014][v][cplayer]    libswresample   3.5.100
[   0.014][v][cplayer] ffmpeg version: 4.2.1
[   0.014][v][cplayer] 
[   0.014][v][cplayer] Configuration: waf configure --prefix=/usr/local/Cellar/mpv-iina/0.31.0 --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-uchardet --enable-libbluray --disable-swift --disable-debug-build --disable-macos-media-player --confdir=/usr/local/etc/mpv --datadir=/usr/local/Cellar/mpv-iina/0.31.0/share/mpv-iina --mandir=/usr/local/Cellar/mpv-iina/0.31.0/share/man --docdir=/usr/local/Cellar/mpv-iina/0.31.0/share/doc/mpv-iina
[   0.014][v][cplayer] List of enabled features: 51deb aligned_alloc asm atomics bsd-fstatfs build-date cocoa coreaudio cplayer cplugins drmprime fchmod ffmpeg gl gl-cocoa glob glob-posix gnuc gpl iconv javascript jpeg lcms2 libarchive libass libass-osd libav-any libavcodec libavdevice libavutil libbluray libdl libm libmpv-shared lua macos-10-11-features macos-10-12-2-features macos-10-14-features macos-touchbar optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads rubberband stdatomic uchardet videotoolbox-gl videotoolbox-hwaccel zlib
[   0.015][v][bdmv/bluray] Opening /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.016][v][file] Opening /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.016][d][file] resize stream to 131072 bytes
[   0.016][d][file] Stream opened successfully.
[   0.016][v][input] Parsing input config file /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.016][v][input] Input config file /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf parsed: 69 binds
[   0.016][d][global] user path: '/Users/lihong/Library/Logs/com.colliderli.iina/2020-05-08-12-27-44_SnbQeD/mpv.log' -> '/Users/lihong/Library/Logs/com.colliderli.iina/2020-05-08-12-27-44_SnbQeD/mpv.log'
[   0.016][d][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.016][d][stats] Loading lua script @stats.lua...
[   0.016][d][console] Loading lua script @console.lua...
[   0.016][d][osx] Exiting...
[   0.017][v][cplayer] Set property: vo="libmpv" -> 1
[   0.017][d][stats] loading mp.defaults
[   0.017][d][console] loading mp.defaults
[   0.017][d][ytdl_hook] loading mp.defaults
[   0.017][v][cplayer] Set property: keepaspect="no" -> 1
[   0.017][v][cplayer] Set property: gpu-hwdec-interop="auto" -> 1
[   0.017][v][cplayer] Waiting for scripts...
[   0.019][d][console] loading @console.lua
[   0.019][d][stats] loading @stats.lua
[   0.019][d][ytdl_hook] loading @ytdl_hook.lua
[   0.022][d][stats] reading options for stats 
[   0.022][d][stats] script-opts/stats.conf not found. 
[   0.022][d][stats] lua-settings/stats.conf not found. 
[   0.022][d][ytdl_hook] reading options for ytdl_hook 
[   0.022][d][ytdl_hook] script-opts/ytdl_hook.conf not found. 
[   0.022][d][ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[   0.059][v][ao/coreaudio] selected audio output device:  (57)
[   0.062][d][console] reading options for console 
[   0.063][d][console] script-opts/console.conf not found. 
[   0.063][d][console] lua-settings/console.conf not found. 
[   0.064][d][cplayer] Run command: define-section, flags=64, args=[input_stats, i script-binding stats/display-stats
[   0.064][d][cplayer] I script-binding stats/display-stats-toggle
[   0.064][d][cplayer] , default]
[   0.064][d][cplayer] Run command: enable-section, flags=64, args=[input_stats, allow-hide-cursor+allow-vo-dragging]
[   0.064][d][cplayer] Run command: define-section, flags=64, args=[input_forced_stats, , force]
[   0.064][d][cplayer] Run command: enable-section, flags=64, args=[input_forced_stats, allow-hide-cursor+allow-vo-dragging]
[   0.069][v][cplayer] Done loading scripts.
[   0.070][v][osd/libass] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[   0.070][v][osd/libass] Setting up fonts...
[   0.073][v][osd/libass] Using font provider coretext
[   0.073][v][osd/libass] Done.
[   0.073][d][cplayer] Run command: define-section, flags=64, args=[input_console, , default]
[   0.073][d][cplayer] Run command: enable-section, flags=64, args=[input_console, allow-hide-cursor+allow-vo-dragging]
[   0.073][d][cplayer] Run command: define-section, flags=64, args=[input_forced_console, , force]
[   0.074][d][cplayer] Run command: enable-section, flags=64, args=[input_forced_console, allow-hide-cursor+allow-vo-dragging]

</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
every time

**Comment by lhc70000** [comment]
已确认，感谢报告。
