### ISSUE TITLE
Disable full screen animation

### ISSUE THREAD

**Issue by mdanetzky** [iina/iina#2927]
**What you want IINA to do:**
A switch in the preferences pane to disable the fullscreen animation.
That way the transition between fullscreen and windowed mode would be instantaneous.

**What IINA does currently:**
Currently such option is missing and the video is paused for the duration of the animation.

**Why you think this should be added:**
It will greatly improve the user experience.

**Examples of other projects that have something similar:**
https://mplayerosx.ch/ did just that.

**Comment by aminozuur** [comment]
I would like this as well

**Comment by mdanetzky** [comment]
Yes! This is exactly what I was looking for.
Maybe renaming the option to something like "disable fullscreen animation" would help.
I disabled the osx animations, because they take over a second. When you get an email and want to quickly check it and then get back to the movie - the animations get annoying very fast.
