### ISSUE TITLE
Always skips 60s forward and backward

### ISSUE THREAD

**Issue by NagisaVon** [iina/iina#2929]
I try to set the left and right arrow key to skip 5secs, but it always skip 60secs no matter what setting I chose. Even when the options at the top bar shows left arrow for 5secs right arrow for 5secs, it still skips 60s for me.

**Comment by danielye8** [comment]
Similar issue for me, except it is skipping forward and backwards 20 sec whenever I press left or right buttons. Tried to re-install; now for some reason it skips by 30 secs. 

Seems like the skip duration is being increased by some other action... but I'm not sure what. Issue only surfaced yesterday, which is also the same time as I used float on top and picture in picture. Not sure if they have any correlation.
