### ISSUE TITLE
Improve startup time on hard drive-based Macs

### ISSUE THREAD

**Issue by mariobrostech** [iina/iina#2932]
IINA version: 1.0.7 beta 2
macOS version: 10.14.6 Mojave
Disk info: 1.1 TB Fusion Drive (128GB SSD with 1TB 5400rpm HDD)

Compared to QuickTime Player, which takes one bounce in the dock to open, IINA takes 5-6 bounces to open from a fresh system restart. Is there any way you can optimize the app a little more and cut down on the startup time for HDD-based Macs?

Thanks!

**Comment by lhc70000** [comment]
Sorry but I'm not sure if I have time to do this recently…

**Comment by shivam212** [comment]
If we could do this, how would we go about it?

**Comment by mariobrostech** [comment]
IINA 1.1 seems to decrease the startup time significantly on all of the Macs I've tested it on, especially those with mechanical hard disks. Great job with the update! I'm closing this issue for now, but if anyone experiences further issues, feel free to open it up again :)
