### ISSUE TITLE
https://translate.iina.io/上展示的繁体中文配图不合法

### ISSUE THREAD

**Issue by Newamber** [iina/iina#2938]
你好 翻译网站 https://translate.iina.io/ 上展示的繁体中文配图是中华民国的国旗，这和一个中国的原则相违背，应该立刻换成中国人民共和国的国旗，谢谢！

![截屏2020-05-17 10 24 09](https://user-images.githubusercontent.com/22588931/82134401-24b34c00-982a-11ea-8450-9d33d72ca374.jpeg)

**Comment by HarukaMa** [comment]
@Newamber 给你指条明路：https://crowdin.com/contacts

**Comment by quanbrew** [comment]
这使用了 crowdin 的翻译服务，并不在这个项目的控制之内

**Comment by Newamber** [comment]
> 这使用了 crowdin 的翻译服务，并不在这个项目的控制之内，上面的链接就是 crowdin 的联系方式，希望您能和他们沟通

要联系也是你们项目的维护者去联系，为什么要一个路人去联系？作为开发者维护者，难道没有责任和义务做这些？只关心技术？

**Comment by Newamber** [comment]
> @Newamber 给你指条明路：https://crowdin.com/contacts

你们是接口人，这些事情要你们cover住。 打个不太恰当的比喻，好比说我购买使用用一台国产电视有问题，厂商告诉我出问题是电视芯片，厂商是美国的，让我自己去找他们解决，合理吗？

**Comment by MamaShip** [comment]
接口人可还行，看来是老华为员工了

**Comment by Newamber** [comment]
> 接口人可还行，看来是老华为员工了

找人处理非技术问题也是需要解耦的，接口人很精炼说法嘛，不一定华为才用啊

**Comment by MamaShip** [comment]
> > 接口人可还行，看来是老华为员工了
> 
> 找人处理非技术问题也是需要解耦的，接口人很精炼的说法嘛，不一定华为才用啊

这不是你们公司，没有什么接口人。你要么主动为开源社区做贡献（自己去推动修改），要么「请求」有意愿的开发者帮你改进。没有人有义务为你做所有事。

何况华为的部门间服务也是要付钱的。你没有为开源软件付过钱。

**Comment by Newamber** [comment]
> > > 接口人可还行，看来是老华为员工了
> > 
> > 
> > 找人处理非技术问题也是需要解耦的，接口人很精炼的说法嘛，不一定华为才用啊
> 
> 这不是你们公司，没有什么接口人。你要么主动为开源社区做贡献（自己去推动修改），要么「请求」有意愿的开发者帮你改进。没有人有义务为你做所有事。
> 
> 何况华为的部门间服务也是要付钱的。你没有为开源软件付过钱。

啥都自己搞定了，我也没必要在这提issue了好吧，这不是技术问题，是开发者的态度问题。

**Comment by MamaShip** [comment]
> > > > 接口人可还行，看来是老华为员工了
> > > 
> > > 
> > > 找人处理非技术问题也是需要解耦的，接口人很精炼的说法嘛，不一定华为才用啊
> > 
> > 
> > 这不是你们公司，没有什么接口人。你要么主动为开源社区做贡献（自己去推动修改），要么「请求」有意愿的开发者帮你改进。没有人有义务为你做所有事。
> > 何况华为的部门间服务也是要付钱的。你没有为开源软件付过钱。
> 
> 啥都自己搞定了，我也没必要在这提issue了好吧，这不是技术问题，是开发者的态度问题。

你说的没错。但我觉得你的态度并不利于解决问题。有很多原本是中立的开发者（比如我），看到你的言辞就不会愿意帮你改进了。

**Comment by Newamber** [comment]
> > > > > 接口人可还行，看来是老华为员工了
> > > > 
> > > > 
> > > > 找人处理非技术问题也是需要解耦的，接口人很精炼的说法嘛，不一定华为才用啊
> > > 
> > > 
> > > 这不是你们公司，没有什么接口人。你要么主动为开源社区做贡献（自己去推动修改），要么「请求」有意愿的开发者帮你改进。没有人有义务为你做所有事。
> > > 何况华为的部门间服务也是要付钱的。你没有为开源软件付过钱。
> > 
> > 
> > 啥都自己搞定了，我也没必要在这提issue了好吧，这不是技术问题，是开发者的态度问题。
> 
> 你说的没错。但我觉得你的态度并不利于解决问题。有很多原本是中立的开发者（比如我），看到你的言辞就不会愿意帮你改进了。

你说都没问题，我只是觉得吧，这也不是啥技术问题，而是一种大多数国人都有的共识吧，是一种红线问题，作为项目都维护者我觉得不至于不会发现这个，这么长时间都没人去关注有点离谱，现在有人提出来了，又直接甩给别人解决。如果你们是确实直接和这个翻译项目的工作人员联系了，并获得他们的回复得知无法解决，表明不在你们的控制范围之内，那我觉得这是一个合理的态度和方式，我会去尝试自己解决的。

**Comment by Newamber** [comment]
有大佬说我言辞不善，对于我发言不善的评论我给予删除，在此我请求各位项目维护者主动解决这个问题，我应该搞不定～

**Comment by xqq** [comment]
![hscecesrhx](https://user-images.githubusercontent.com/4645762/82136010-a364b500-983b-11ea-97c2-d4cf9aa302a4.jpeg)
![1](https://user-images.githubusercontent.com/4645762/82136014-a52e7880-983b-11ea-945c-cfc1d61b4928.jpg)

**Comment by MamaShip** [comment]
> > > > > > 接口人可还行，看来是老华为员工了
> > > > > 
> > > > > 
> > > > > 找人处理非技术问题也是需要解耦的，接口人很精炼的说法嘛，不一定华为才用啊
> > > > 
> > > > 
> > > > 这不是你们公司，没有什么接口人。你要么主动为开源社区做贡献（自己去推动修改），要么「请求」有意愿的开发者帮你改进。没有人有义务为你做所有事。
> > > > 何况华为的部门间服务也是要付钱的。你没有为开源软件付过钱。
> > > 
> > > 
> > > 啥都自己搞定了，我也没必要在这提issue了好吧，这不是技术问题，是开发者的态度问题。
> > 
> > 
> > 你说的没错。但我觉得你的态度并不利于解决问题。有很多原本是中立的开发者（比如我），看到你的言辞就不会愿意帮你改进了。
> 
> 你说都没问题，我只是觉得吧，这也不是啥技术问题，而是一种大多数国人都有的共识吧，是一种红线问题，作为项目都维护者我觉得不至于不会发现这个，这么长时间都没人去关注有点离谱，现在有人提出来了，又直接甩给别人解决。如果你们是确实直接和这个翻译项目的工作人员联系了，并获得他们的回复得知无法解决，表明不在你们的控制范围之内，那我觉得这是一个合理的态度和方式，我会去尝试自己解决的。

首先我表明我的立场: 我是纯粹中立的。

我觉得开发者有各自关注的领域，有些人不愿意在政治话题上花太多功夫。而 IINA 这个仓库目前有800+ open issues，contributors 当然会从中挑选严重的/自己感兴趣的优先处理。

当然你可能觉得政治问题**就是**严重的。这就又回到前一点，人们的关注点各有不同，可能对你来说比较重要，那你自己主持推进会是效果更好的。

******

另一个值得考量的情况是，结婚都要双方同意才构成合法婚姻。一国概念是否是双方同意的呢？我对此持中立立场。

如果这个项目中，有来自台湾的开发者做出了贡献，并且他们不支持相关立场，我们强制性地做出这种政治目的的修改是否合适呢。

事实上，你标题所指的「合法性」，是一个悬置的概念。究竟是该合哪国的法？

出于对此类争议的考量，我想中立开发者会持保留观点。

******

结论还是: 这个事情你按照自己主张去推进比较好。强制要求别人花功夫推进第三方做修改是不合适的。

**Comment by Newamber** [comment]
> > > > > > > 接口人可还行，看来是老华为员工了
> > > > > > 
> > > > > > 
> > > > > > 找人处理非技术问题也是需要解耦的，接口人很精炼的说法嘛，不一定华为才用啊
> > > > > 
> > > > > 
> > > > > 这不是你们公司，没有什么接口人。你要么主动为开源社区做贡献（自己去推动修改），要么「请求」有意愿的开发者帮你改进。没有人有义务为你做所有事。
> > > > > 何况华为的部门间服务也是要付钱的。你没有为开源软件付过钱。
> > > > 
> > > > 
> > > > 啥都自己搞定了，我也没必要在这提issue了好吧，这不是技术问题，是开发者的态度问题。
> > > 
> > > 
> > > 你说的没错。但我觉得你的态度并不利于解决问题。有很多原本是中立的开发者（比如我），看到你的言辞就不会愿意帮你改进了。
> > 
> > 
> > 你说都没问题，我只是觉得吧，这也不是啥技术问题，而是一种大多数国人都有的共识吧，是一种红线问题，作为项目都维护者我觉得不至于不会发现这个，这么长时间都没人去关注有点离谱，现在有人提出来了，又直接甩给别人解决。如果你们是确实直接和这个翻译项目的工作人员联系了，并获得他们的回复得知无法解决，表明不在你们的控制范围之内，那我觉得这是一个合理的态度和方式，我会去尝试自己解决的。
> 
> 首先我表明我的立场: 我是纯粹中立的。
> 
> 我觉得开发者有各自关注的领域，有些人不愿意在政治话题上花太多功夫。而 IINA 这个仓库目前有800+ open issues，contributors 当然会从中挑选严重的/自己感兴趣的优先处理。
> 
> 当然你可能觉得政治问题**就是**严重的。这就又回到前一点，人们的关注点各有不同，可能对你来说比较重要，那你自己主持推进会是效果更好的。
> 
> 另一个值得考量的情况是，结婚都要双方同意才构成合法婚姻。一国概念是否是双方同意的呢？我对此持中立立场。
> 
> 如果这个项目中，有来自台湾的开发者做出了贡献，并且他们不支持相关立场，我们强制性地做出这种政治目的的修改是否合适呢。
> 
> 事实上，你标题所指的「合法性」，是一个悬置的概念。究竟是该合哪国的法？
> 
> 出于对此类争议的考量，我想中立开发者会持保留观点。
> 
> 结论还是: 这个事情你按照自己主张去推进比较好。强制要求别人花功夫推进第三方做修改是不合适的。

害，没人愿意搞我就自己搞呗～ 你说的对，别人没义务搞这个问题，那我就自己尝试解决好了，至于你说的担心台湾开发者的问题，我觉得你还是挺为别人台湾同胞着想的～

**Comment by MamaShip** [comment]
> 害，没人愿意搞我就自己搞呗～ 你说的对，别人没义务搞这个问题，那我就自己尝试解决好了，至于你说的担心台湾开发者的问题，我觉得你还是挺为别人台湾同胞着想的～

为什么你在统独问题上持「统」的立场，说话间还是「别人台湾」同胞呢？

我个人只是尊重各方立场，因为我理解双方的诉求和矛盾，但又没有办法调和和解决。

如果你只是在形式上追求这种压倒性的「拒绝承认」，那你只会把台湾民众的心越推越远而已。

政治话题我就不想多聊了。我有很多台湾的朋友，我觉得他们都很赞。
