### ISSUE TITLE
Export PNG screenshot as 8 bit if video source is 8 bits

### ISSUE THREAD

**Issue by GuillaumeBringard** [iina/iina#2943]
**What you want IINA to do:**
I'd like IINA to export screenshots as 8 bits PNG, when the video source file depth is 8 bits.

**What IINA does currently:**
Currently IINA exports 16 bits PNG, even if the video source file is 8 bits.

**Why you think this should be added:**
It would make PNG size smaller (and maybe speed up the export ?)

**Examples of other projects that have something similar:**

**Comment by Rikkano** [comment]
https://mpv.io/manual/master/#options-screenshot-high-bit-depth

**Comment by GuillaumeBringard** [comment]
Thanks, I added the "screenshot-high-bit-depth" option and set it to "no", and the resulting PNG are indeed 8 bits :-)

Also thank you for pointing me to mpv's options, I managed to set a screenshot template name to have timestamp in the file name. Shame there isn't a time-code pattern like HH-MM-SS-FF but for now the milliseconds will do :-)
