### ISSUE TITLE
plugin system implemention?

### ISSUE THREAD

**Issue by latel** [iina/iina#2949]
is there any possibility to implement a plugin system? compared to watching videos online, watching videos locally(suck as from disk, nas) is more boring. one of the most differece is that when watching online we have the danmu, which brings a lot of fun.

I'd like to see a plugin, which load danmu from online video site, and displaying them when iina is playing videos locally.

**Comment by anohren** [comment]
...danmu? 🤔

**Comment by jerkstore369** [comment]
> ...danmu? 🤔

It's some stupid chinese thing where you can post messages on streams or something so what another person gets to that point in the movie they can see your message. I guess a lot of kids like it but when someone watches something, you'd think they'd watch it for the content not dumb messages.

**Comment by anohren** [comment]
Oh, I see, thanks for the explanation. 

To answer @latel, yes, a plugin system appears to be in development so you might have an opportunity to hack something together in the future. I don't know much about it though.

Personally, I would like to help people become _less_ distracted, so I'm not sure how I feel about the concept 🙂 I even think that e.g. defaulting to displaying ratings for TV episodes in Kodi is kind of crazy -- stop telling people what to enjoy, and to what extent, before they watch it!

**Comment by lhc70000** [comment]
I'm working on it at the [plugin-system](https://github.com/iina/iina/tree/plugin-system) branch. This can be achieved by displaying an overlay on the video.

**Comment by aheadlead** [comment]
Thanks to @lhc70000 efforts on it. I plan to write a plugin to support people watch a same video in different place with same playback progress synchronously.
