### ISSUE TITLE
如何去掉检测更新

### ISSUE THREAD

**Issue by xhzth7091** [iina/iina#2951]
如何在代码里去掉检测更新，不弹出这个弹窗，谢谢
![截屏2020-05-27 下午6 44 54](https://user-images.githubusercontent.com/13980546/83010142-658d3b00-a04a-11ea-84e3-10cc07fc0aed.png)

**Comment by CHBrianLiu** [comment]
Do you mean configuration in IINA or customize the source code to fit your need? If it is the former, you can uncheck the update check frequency option in `Preferences > General > Behavior > Check for updates`.

<img width="914" alt="image" src="https://user-images.githubusercontent.com/38838945/83287615-8d2fff00-a214-11ea-8d68-96260b3068f5.png">
