### ISSUE TITLE
如何只允许运行一个实例？

### ISSUE THREAD

**Issue by qtwrk** [iina/iina#2952]
比如我现在有一个视频在播放，那么当我双击另外一个视频文件时，会有2个iina同时运行。

如何能够设置成  第一个iina播放器自动切换为第二个被打开的文件而不是同时运行2个？

谢谢。

**Comment by Rikkano** [comment]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/44722787/83101608-498aa780-a0e5-11ea-8e6c-c3b264352704.png">

**Comment by qtwrk** [comment]
非常感谢
