### ISSUE TITLE
为什么我加速播放了，还会有300毫秒的延迟

### ISSUE THREAD

**Issue by xhzth7091** [iina/iina#2955]
为什么我加速播放player.setSpeed, 还会有300毫秒的延迟，不同步， 我想把延迟降到100毫秒以内，如何设置。  不是网络的原因

**Comment by lhc70000** [comment]
如果和 #2955 不是一个问题，请 reopen。

我其实不太明白延迟是怎么算出来的，和什么相比出现的延迟。
