### ISSUE TITLE
IINA 1.0.6 双击打开mp3后，马上按Command+I，IINA大概率会闪退。

### ISSUE THREAD

**Issue by zxl777** [iina/iina#2956]
IINA 1.0.6 双击打开mp3后，马上按Command+I，IINA大概率会闪退。

**Comment by ZoolYe** [comment]
我播放MP4，点播放列表，大概率会崩溃，感觉没有以前稳定了

**Comment by lhc70000** [comment]
@zxl777 请确认 1.0.7 beta 有没有修复这个问题，如果没有修复，提供崩溃报告。

播放列表的问题已在 1.0.7 beta 修复，可以试用。
