### ISSUE TITLE
建议在画中画模式下单击画中画中任意位置暂停播放而不是现有的特定按钮暂停播放

### ISSUE THREAD

**Issue by fylsan3** [iina/iina#2965]
建议：在画中画模式下鼠标点击画中画中任意位置暂停播放而不是现有的特定按钮暂停播放
           同样这个功能不限于画中画模式，其它模式也可以使用这种方式。

**Comment by lhc70000** [comment]
画中画是系统功能，没办法更改。如果希望在窗口中单击画面暂停，可以去偏好设置 - 控制设置鼠标单击操作。
