### ISSUE TITLE
Twitch no longer works

### ISSUE THREAD

**Issue by hellojole** [iina/iina#2966]
**System and IINA version:**

- macOS 10.15.5
- IINA 1.0.6

**Expected behavior:**
Opening a Twitch stream, like https://www.twitch.tv/blastpremier, should work in IINA.

**Actual behavior:**
It does not.

**Comment by Hebo** [comment]
I've noticed this too (on 10.14) as of a day or two ago. In the meantime, I'm piping streamlink into IINA, which works fine:

```
streamlink --stdout https://www.twitch.tv/lirik 720p | iina --stdin
```

I have a [short wrapper](https://gist.github.com/Hebo/a2faf5f6f1e5d0fc1b60e001909b7fb8) that makes it slightly less verbose, so you can just do `stream kitboga`

**Comment by lhc70000** [comment]
Updating youtube-dl might help: https://github.com/iina/iina/wiki/Use-youtube-dl-with-IINA

IINA 1.0.7 is about to be released (in 2-3 days) and we will also update the bundled youtube-dl accordingly.

**Comment by Hebo** [comment]
Thanks for the lead. I found the current version of youtube-dl doesn't work either, already filed as an issue [here](https://github.com/ytdl-org/youtube-dl/issues/25528). Presumably that's the root cause of IINA not working.

**Comment by Shirk** [comment]
So with the referenced issue on YouTube-dl fixed, is there a chance to get a fix for IINA?

**Comment by tsologub** [comment]
Any updates from the maintainers on this one?

**Comment by Shirk** [comment]
Seems that all that is required would be a new release with updated youtube-dl. At least that's what I'm doing right now, installed a recent youtube-dl via homebrew and told Iina to use it instead of it's bundled version.

**Comment by donmurdoc** [comment]
> Seems that all that is required would be a new release with updated youtube-dl. At least that's what I'm doing right now, installed a recent youtube-dl via homebrew and told Iina to use it instead of it's bundled version.

How can I do that?

**Comment by Shirk** [comment]
> > Seems that all that is required would be a new release with updated youtube-dl. At least that's what I'm doing right now, installed a recent youtube-dl via homebrew and told Iina to use it instead of it's bundled version.
> 
> How can I do that?

The easy answer would be "read the documentation it's in the manual", but basically you want to set it in Network Prefs - point IINA at the directory your YouTube-dl is installed (mine is from homebrew:):
<img width="918" alt="image" src="https://user-images.githubusercontent.com/304352/118785547-3e4e0000-b891-11eb-8813-4ff62ec488cf.png">

**Comment by muescha** [comment]
is the current version able to stream twitch? 

which link is the right one? `https://www.twitch.tv/username` ?
