### ISSUE TITLE
additional, playlist window docking or window mode

### ISSUE THREAD

**Issue by curetypeface** [iina/iina#2974]
Currently, the playlist and chapter listings are shown as an overlay,
but i want to have a mode to **dock** to or display in a **separate window**

like #2972 ,
I want to watch the video without any deficiencies while always displaying the OSC.

Even in the case of overlay, I'd like to have a mode that disappears in focus out, like the OSC

**Comment by lhc70000** [comment]
Please see my comments in #2972.

Closing this issue due to duplication.
