### ISSUE TITLE
cocoa-force-dedicated-gpu not supported in IINA 1.0.7

### ISSUE THREAD

**Issue by farmostream** [iina/iina#2982]
System and IINA version:

macOS 10.14.6
IINA 1.0.7

- macOS 
- IINA 

**Expected behavior:**

should support cocoa-force-dedicated-gpu option as 1.0.6.

**Actual behavior:**

not supported in 1.0.7.

After upgrading IINA to version 1.0.7,  cocoa-force-dedicated-gpu is not supported anymore.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/20183545/84524992-74901080-ad0d-11ea-9832-0ee0b77ce41e.png">

**Comment by lhc70000** [comment]
@farmostream It only works for mpv. IINA will add a similar option in the next version.

**Comment by farmostream** [comment]
> @farmostream It only works for mpv. IINA will add a similar option in the next version.


Nice.Thanks.

**Comment by farmostream** [comment]
> @farmostream It only works for mpv. IINA will add a similar option in the next version.

So INNA changed how rendering works in 1.0.7? Anyway,Thanks.

**Comment by lhc70000** [comment]
You should use `macos-force-dedicated-gpu` BTW.

> So INNA changed how rendering works in 1.0.7?

IINA has a different implementation for rendering from the beginning. 

Basically all mpv options starting with `--macos-` won't work in IINA, such as `--macos-title-bar-material`, since apparently IINA has its own window implementation.
