### ISSUE TITLE
IINA quits suddenly when playing a “*.MKV”file.

### ISSUE THREAD

**Issue by DarthMikuH** [iina/iina#2985]
macOS Catalina 10.15.5
IINA 1.0.7

**Comment by lhc70000** [comment]
Please provide crash report or steps to reproduce.

**Comment by DarthMikuH** [comment]
[Process.docx](https://github.com/iina/iina/files/4775911/Process.docx)
This is the provided report.

**Comment by percy507** [comment]
same questions
[log.txt](https://github.com/iina/iina/files/4776201/log.txt)

**Comment by lhc70000** [comment]
@percy507 It's not the same issue. Your crash is #2889.

**Comment by lhc70000** [comment]
@DarthMikuH 

I'm not sure about the reason, but please go to Preferences - Utilities and click "Clear Thumbnail Cache". This should resolve your problem.

Please reopen this issue if it happens again.
