### ISSUE TITLE
OSD text dimension not coherent

### ISSUE THREAD

**Issue by Iuser7** [iina/iina#2986]
- macOS 10.14.6
- IINA 1.0.7

**Expected behavior:**
Modifying pref / interface / OSD / text dimension should work every time an action invokes the panel in play times.
Example: It actually works when you skip 5s with arrows

**Actual behavior:**
When you stop a video (ex: spacebar), the play/pause notice will appear modified while the total/playing time under it will remain in default dimension, too small to be seen on far displays.

**Comment by Iuser7** [comment]
![Stop:Play](https://user-images.githubusercontent.com/36303147/84592078-22510b80-ae43-11ea-8ea8-7f71b11de6b9.png)
![Arrow skipping](https://user-images.githubusercontent.com/36303147/84592080-254bfc00-ae43-11ea-964d-ff2d09922e5d.png)

**Comment by lhc70000** [comment]
Fixed via 165c799.
