### ISSUE TITLE
Can no longer stream from YouTube 

### ISSUE THREAD

**Issue by eunjeongji** [iina/iina#2995]
**System and IINA version:**

- macOS  10.15.5
- IINA  1.0.7

**Expected behavior:**
Streaming YouTube on Safari

**Actual behavior:**
Since I updated IINA today, YouTube is not streaming on safari.
It shows An error occurred. Please try again later.  

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

  
<details> 
<summary><b>mpv log:</b></summary> 
 

```
mph 0.32.0
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
all the time

<img width="970" alt="Screenshot 2020-06-16 22 56 32" src="https://user-images.githubusercontent.com/67006297/84778754-c9da6380-b026-11ea-9765-73d6be65804e.png">

**Comment by saagarjha** [comment]
Are you sure this isn't a problem with YouTube itself?

**Comment by eunjeongji** [comment]
I have no idea but YouTube was working until I updated IINA.

**Comment by eunjeongji** [comment]
> Are you sure this isn't a problem with YouTube itself?

I didn't know what causes the problem but today it's working again. Maybe it was a problem with YouTube. Thanks for your reply.
