### ISSUE TITLE
IINA cant open, aka IINA quit unexpectedly.

### ISSUE THREAD

**Issue by NathanZhengNaixian** [iina/iina#3014]
**System and IINA version:**

- macOS <!14.6 Mojave>
- IINA 

IINA quit unexpectedly.

Crash File: 
https://docs.google.com/document/d/1eWLWFPf3Nr0hqMvr77Wq8U7xP4DaVb92dlZ1yMkizmM/edit?usp=sharing

Crash every time.

**Comment by lhc70000** [comment]
It crashed in your audio driver `RazerKraken`. Please consult Razer support or uninstall it.

**Comment by NathanZhengNaixian** [comment]
谢谢
