### ISSUE TITLE
The preview image of MOV format videos are up side down.

### ISSUE THREAD

**Issue by xiaotianxt** [iina/iina#3015]
**System and IINA version:**

- macOS 10.15.5
- IINA 1.0.7 Build 119

**Expected behavior:**

**Actual behavior:**
![image](https://user-images.githubusercontent.com/17041194/85845744-5202fa80-b7d7-11ea-96dd-f6fbfa4f9e29.png)

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by anohren** [comment]
Thumbnail previews apparently don't tak exif/rotation metadata into account

**Comment by xiaotianxt** [comment]
> Thumbnail previews apparently don't take exif/rotation metadata into account

It's really an annoying issue and only happens in this particular video, I don't know about any MOV format code that may cause the problem, I can provide the video file for analysis.

**Comment by alejx** [comment]
@xiaotianxt Can you provide your video for testing? Thanks
