### ISSUE TITLE
Hope to increase the volume like vlc

### ISSUE THREAD

**Issue by hexiaoyanh** [iina/iina#3022]
Sometimes the volume is still not enough

**Comment by unique-username313** [comment]
You can set maximum volume (and initial volume) in the preference window under Audio/Video. If maximum volume is 100, you can set it to 130 (I think that’s the VLC default)

**Comment by hexiaoyanh** [comment]
> You can set maximum volume (and initial volume) in the preference window under Audio/Video. If maximum volume is 100, you can set it to 130 (I think that’s the VLC default)

Thank you for your answer
