### ISSUE TITLE
Move IINA window with single left-click when not in focus

### ISSUE THREAD

**Issue by jmstacey** [iina/iina#3025]
**What you want IINA to do:**

Single left-click and hold to move the iina window around on the screen when the iina player window is not in focus -- just like it works when the iina window does have focus.

**What IINA does currently:**

Single left-click moving of the iina window only works if the window is in focus.

**Why you think this should be added:**

Behavior consistency, and when i noticed that this did not work it felt like it should.

**Examples of other projects that have something similar:**

Apple Quicktime Player works this way. Single left-click works regardless of if the window is in focus.

**Comment by alejx** [comment]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/20237141/86205281-09af5800-bb9c-11ea-91a8-c676bb4314d3.png">
Make sure you have "Accepts first mouse click when not focused" under Preference > Control tab, then you will get the behavior you want.

**Comment by jmstacey** [comment]
Aha Brilliant! Closing this out.
