### ISSUE TITLE
Increase compatibility with slightly incorrect srt format

### ISSUE THREAD

**Issue by AndreKurait** [iina/iina#3033]
I ran across an srt file formatted like the following:
```
1

00:02:17,440 --> 00:02:20,375
Senator, we're making
our final approach into Coruscant.

2

00:02:20,476 --> 00:02:22,501
Very good, Lieutenant.

```

as opposed to the correct

```
1
00:02:17,440 --> 00:02:20,375
Senator, we're making
our final approach into Coruscant.

2
00:02:20,476 --> 00:02:22,501
Very good, Lieutenant.

```

IINA gives an error message when opening the file, however, when opening in VLC no error is shown and subtitles shown as expected. I understand the formatting is incorrect, but adding support for a file formatted like this may decrease future user frustration. Interestingly, removing the new line after the "1" but leaving the rest of the file alone resolves the issue.

**System and IINA version:**

- macOS 10.15.5
- IINA 1.0.7

**Expected behavior:**
Load subtitle

**Actual behavior:**
Error: Unsupported external subtitle.

<br>

**Steps to reproduce:**
1. Obtain video with matching srt file that contains a line break after each identifier.
2. After "double clicking" to play the video, the error message appears

**How often does this happen?**
Every Time

**Comment by alejx** [comment]
Please report this issue to https://github.com/mpv-player/mpv/issues .
