### ISSUE TITLE
Arrow keys skip time instead of characters when in settings input field

### ISSUE THREAD

**Issue by Ahrdie** [iina/iina#3039]
When a medium is playing and you access an input field in the playback settings panel via the gearwheel, the arrow keys still skip time instead of moving the curser in the input field.

**System and IINA version:**
- macOS 10.15.5
- IINA 1.0.7 Build 119

**Expected behavior:**
Pressing the arrow keys inside an input field should move the curser inside it.

**Actual behavior:**
Pressing the curser keys inside a playback-settings input field skips time inside the medium, that's currently playing.

<br>

<br>

**Steps to reproduce:**
1. Start a medium, e.g. a video
2. enter the playback settings panel via the gear
3. klick on an input field (e.g. playback speed)
4. press an arrow key to move the curser

- [ ] MPV does not have this problem.

**How often does this happen?**
Every time you want to move the curser inside an input field

**Comment by low-batt** [comment]
This was fixed in IINA 1.4.0-beta1.
