### ISSUE TITLE
Does IINA upload my subtitles?

### ISSUE THREAD

**Issue by chloup** [iina/iina#3043]
I am aware of the "Find Online Subtitles..." and the "Download Online Subtitle" feature of IINA, and I wonder if the subtitles on my PC could be by any chance uploaded or shared? I just started out fansubbing and am looking for a player that does not share the subtitles that I am still working on. 

**System and IINA version:**

- macOS 10.15.6
- IINA 1.0.7

**Comment by lhc70000** [comment]
No, IINA won't upload anything on your computer.

**Comment by chloup** [comment]
Got it, thank you!
