### ISSUE TITLE
Overlapped Subtitles 

### ISSUE THREAD

**Issue by sanmaruy** [iina/iina#3052]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**
Overlapped Subtitles. 

<img width="1278" alt="Screen Shot 2020-07-28 at 11 14 59 PM" src="https://user-images.githubusercontent.com/68935616/88752558-39fcfe80-d128-11ea-9698-0a36f2e86014.png">

**How often does this happen?**

**Comment by lhc70000** [comment]
Are these bitmap subtitles (you can confirm this in the inspector (Cmd+I))? You need to set a text-based subtitle as the secondary subtitle and it will be displayed fixed at the top, or you can set a text-based subtitle as the main subtitle and adjust its vertical position.

If both subtitles are bitmap subtitles, there's no way to display them at the same time without overlapping.

**Comment by ArtemBernatskyy** [comment]
+1 for this issue

**Comment by lhc70000** [comment]
@ArtemBernatskyy It should work well for text-based subtitles, which is the usual case, but technically there's no way to avoid overlapping if both subtitles are image-based. We can do nothing if mpv doesn't support it.

**Comment by ArtemBernatskyy** [comment]
temporary fix using Subler (suitable for .mks files or .mkv files containing subtitle tracks)

1. Download the latest [Subler](https://subler.org/)
2. Open and go to Preferences > OCR > Download relevant languages
3. Go to Preferences > Advanced, and make sure VobSub to Tx3g is enabled
4. Select Open and open your MKS or MKV file
5. Deselect all tracks except the subtitle track
6. Choose File > Save, leave extension as .m4v and confirm
7. It will now OCR the subtitles and save a .m4v file
8. When it's done, highlight the subtitle track and choose File > EXPORT. This will save as .srt
9. Import our new subtitle and use it as a second subtitle in IIna.

[kudos to reddit](https://www.reddit.com/r/ffmpeg/comments/gjpkd2/tutorial_mac_how_to_ocr_and_convert_vobsub_subs/)
