### ISSUE TITLE
音乐模式下播放列表显示不正常

### ISSUE THREAD

**Issue by nasaboy** [iina/iina#3062]
**System and IINA version:**

- macOS 
10.13.6 (17G14019)
- IINA 
1.0.7 Build 119
**Expected behavior:**

**Actual behavior:**
![屏幕快照 2020-08-09 下午1 44 01](https://user-images.githubusercontent.com/5997682/89725943-e784e180-da47-11ea-8aea-bb8f34209a77.png)
![屏幕快照 2020-08-09 下午1 50 35](https://user-images.githubusercontent.com/5997682/89725946-eeabef80-da47-11ea-9421-e8686f0afeb4.png)

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
打开音乐文件进去音乐模式就可以复现

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
这是 10.13 系统的 bug，目前没有精力也没有设备测试修复。请考虑升级系统。
