### ISSUE TITLE
Native Apple Silicon support.

### ISSUE THREAD

**Issue by MaddTheSane** [iina/iina#3067]
With Apple migrating to their own CPUs, Making IINA be a native ARM application might make it run better, as well as future-proofing.

I tried to build it using Xcode 12 beta 4. It failed to link: almost all of the third-party frameworks/libraries it links against are x86-64.

**Comment by saagarjha** [comment]
We’re (slowly) working on it; we still have a number of dependencies to deal with as you’ve noticed. While not optimal, IINA does run under Rosetta–however, we’d prefer getting it built for Universal before the first Apple silicon Macs ship to the public of course :)

**Comment by dr1llc4t** [comment]
> We’re (slowly) working on it; we still have a number of dependencies to deal with as you’ve noticed. While not optimal, IINA does run under Rosetta–however, we’d prefer getting it built for Universal before the first Apple silicon Macs ship to the public of course :)

Any updates？

**Comment by saagarjha** [comment]
At least on my computer the dependency chain includes Rust, so this might take a little while.

**Comment by berkus** [comment]
Rust is getting aarch64 into Tier-1 support, and I use it daily for builds **on** and **for** RasPi4 all the time, so this shouldn't be a problem at all.

**Comment by saagarjha** [comment]
I believe aarch64-apple-darwin has been merged in and is available on nightly, but I don't think there is a stable release yet.

**Comment by xdanger** [comment]
> I believe aarch64-apple-darwin has been merged in and is available on nightly, but I don't think there is a stable release yet.

We just need an UNSTABLE one.

**Comment by berkus** [comment]
I tried IINA (found it on the https://doesitarm.com/app/iina/ so heh lucky find) and I liked it, so when my M1 machine arrives I might give a port a go. Don't wait for me if you have M1 yourself, though :P

**Comment by berkus** [comment]
M1 machine arrived - the state of aarch64-apple-darwin rustc is... unstable at the moment - most of the binaries it generates are randomly terminated via SIGKILL by some BigSur subsystem, I'm going to build rustc locally and observe the behavior.

**Comment by berkus** [comment]
Meanwhile, I see somebody already finished building an arm version of the binary - and it seems to work.

**Comment by berkus** [comment]
Xref #3218

**Comment by xazac** [comment]
I'm waiting for M1 support as well!

**Comment by MeteorsHub** [comment]
any update？

**Comment by saagarjha** [comment]
Rust supposedly has made a new build available with tier 2 support on Apple silicon. I'm taking a look at how this plays with package managers, as that was the blocker last time I tried this.

**Comment by git-anish** [comment]
any betas available? IINA (Intel) is currently using 2x system resources on identical files compared to Movist pro (ARM) on the M1

**Comment by vladstudio** [comment]
> any betas available? IINA (Intel) is currently using 2x system resources on identical files compared to Movist pro (ARM) on the M1

Someone published an M1 build in the other thread: https://github.com/iina/iina/issues/3218

**Comment by berkus** [comment]
VLC has released a native Apple Silicon version.

**Comment by saagarjha** [comment]
Well aware ;) We have been working on Apple silicon builds as well and have a test build to share: http://server.saagarjha.com/IINA.v1.2.0.dmg. We're interested to hear what you think, so if you have Apple silicon hardware feel free to give it a spin and report issues that you find. Development-wise we are still working out how we want to handle our dependencies (as this was mostly a one-off build based on Homebrew artifacts) but hopefully this should satisfy those that are itching to try out native IINA on their new computers.

P.S. we will probably roll these builds out to the beta program soon, but until then please try not to overload my cheap VPS that I'm temporarily hosting this on too much :)

**Comment by berkus** [comment]
Installed it, seems to work just fine. Will test more on larger video files.

**Comment by ipfans** [comment]
@saagarjha It seems high cpu loads when open some mp4 files.
<img width="1024" alt="Xnip2021-01-26_18-39-27" src="https://user-images.githubusercontent.com/363344/105834802-ec454e00-6005-11eb-87e1-635df452158b.png">

**Comment by tonilampela** [comment]
After quick testing I didn't have problems playing larger 4K MKV files. CPU was around 20%. Will do further testing later.

**Comment by skobylite** [comment]
I'm seeing a weird behaviour on apple silicon only when opening a second file: https://github.com/iina/iina/issues/3320

**Comment by gdubicki** [comment]
> http://server.saagarjha.com/IINA.v1.2.0.dmg. 

This link doesn't work anymore, @saagarjha .

**Comment by saagarjha** [comment]
I did some spring cleaning and took it down, since you should be able to just download it from https://github.com/iina/iina/releases/tag/v1.2.0.

**Comment by ThomasWaldmann** [comment]
1.2.0 with M1 support is now on GitHub releases (not yet on IINA.io), close?

**Comment by MarceloAvalos** [comment]
It's been 10 months since the release of 1.2.0 and the website still points to 1.1.2.

If I hadn't checked GitHub then I wouldn't know there's an Apple Silicon version available.

**Comment by Hitsu91** [comment]
Why the website still points to 1.1.2? Glad I checked the GitHub repository, otherwise I wouldn't know there is an apple silicon native version!

**Comment by low-batt** [comment]
Closing. IINA 1.3.0 has been released with native support for M1.

IINA 1.3.0 can be downloaded from the official [IINA](https://iina.io/) website.
