### ISSUE TITLE
Unsupported external subtitle for subtitle  srt file!!!!

### ISSUE THREAD

**Issue by zhouyuan901** [iina/iina#3069]
**System and IINA version:**

- macOS  10.15.5
- IINA  1.0.7

**Expected behavior:**
IINA show error for an "Unsupported External subtitle" When I try to open the mp4 video with SRT subtitle in same name and same dir.

**Actual behavior:**
Every time I manually open the MP4 video file with the SRT subtitle is for, IINA complains "Unsupported External subtitle

**Steps to reproduce:**

1. Have a video file and a subtitle file in the same dir ready. Assume named vid.mp4 and vid.srt, such that IINA can automatically load the subtitle when the video plays;

2. Open the video with IINA and begin playing;

3. IINA and now it complains about an "Unsupported External subtitle".

**How often does this happen?**

Every time.

**Comment by 1c7** [comment]
Would you mind upload that .srt file somewhere 
(Github maybe, since it's really small text file)
So we can check what's wrong.

**Comment by zhouyuan901** [comment]
Well is that possible to change the txt to srt?

[10. Steganography.txt](https://github.com/iina/iina/files/5078219/10.Steganography.txt)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/90305985-ee559d80-defa-11ea-9c18-4a4ba290c4dc.png)

This is not a standard .srt file

## This is wrong
```
0
1
00:00:00,420 --> 00:00:07,370
Steganography is the process, the science of taking data and hiding it in other data.
1

2
00:00:07,410 --> 00:00:14,160
Now be careful with this because cryptography is the process of taking data and encoding it in some
2

3
00:00:14,160 --> 00:00:20,010
way so that other people can see that there is data there but they can't read it. With steganography.
3
```

### Here is correct example
```
1
00:00:00,420 --> 00:00:07,370
Steganography is the process, the science of taking data and hiding it in other data.

2
00:00:07,410 --> 00:00:14,160
Now be careful with this because cryptography is the process of taking data and encoding it in some

3
00:00:14,160 --> 00:00:20,010
way so that other people can see that there is data there but they can't read it. With steganography.
```

**Comment by 1c7** [comment]
## Use this
[10.Steganography.srt.zip](https://github.com/iina/iina/files/5078236/10.Steganography.srt.zip)

## This is corrent one
![image](https://user-images.githubusercontent.com/1804755/90306049-c74b9b80-defb-11ea-9dc9-ad0968b70320.png)

**Comment by 1c7** [comment]
## Conclusion
IINA did nothing wrong, this file is wrong

**Comment by zhouyuan901** [comment]
BTW I try the other player like Movist but they support this " not standard srt". Is not a big deal but the user experience feels bad if needs manual change the srt file to the "standard srt" .

I double-check the one you correct but still shows "Unsupported external subtitle for subtitle srt file"...
Do you need also to upload the mp4 file to you for the debug?


![image](https://user-images.githubusercontent.com/17016718/90306371-44dac180-de92-11ea-8e7b-1e6750965d9b.png)

**Comment by 1c7** [comment]
Where is this `10. Steganography.txt` come fome?
download from youtube? udemy? using what tools?

I have some experiences with subtitle file like vtt, srt, ass
This `10. Steganography.txt` is clearly a srt file in the wrong format.

I have no idea why Movist support it

I don't need that mp4 file

**Comment by 1c7** [comment]
You should download the `10.Steganography.srt.zip`
unzip it.
and drag the .srt onto IINA

**Comment by zhouyuan901** [comment]
Ok, I got it. Yes "drag the .srt onto IINA" when the mp4 is playing is works. But when I open the mp4 file the IINA autoload the subtitle and shows "Unsupported external subtitle for subtitle srt file" that's the main problem for now. Any suggestions for this? or ignore the error drag the srt every time？

**Comment by zhouyuan901** [comment]
> Where is this `10. Steganography.txt` come fome?
> download from youtube? udemy? using what tools?
> 
> I have some experiences with subtitle file like vtt, srt, ass
> This `10. Steganography.txt` is clearly a srt file in the wrong format.
> 
> I have no idea why Movist support it
> 
> I don't need that mp4 file

Yes is from udemy!

**Comment by 1c7** [comment]
Just make sure whatever tool you use can get corrent subtitle. 
end of discussion.

**Comment by 1c7** [comment]
> But when I open the mp4 file the IINA autoload the subtitle and shows "Unsupported external subtitle for subtitle srt file" that's the main problem for now. Any suggestions for this? or ignore the error drag the srt every time？

make sure there are no same name .txt file, 
that should works, I am not sure, you have to test that.
I am not core member of IINA, I haven't write any code for them.

**Comment by zhouyuan901** [comment]
Yes, No same name .txt file in the same dir.
I probably will open another case for the autoloading subtitle problem.

![image](https://user-images.githubusercontent.com/17016718/90307273-24af0080-de9a-11ea-82fe-09b67c4c57b4.png)

**Comment by yuyamaga** [comment]
Please try to modify settings:
IINA > Preferences >  Subtitle > Auto load:Subtitles containing media filename
