### ISSUE TITLE
find virus about Trojan.MAC.Shlayer

### ISSUE THREAD

**Issue by Lguanghui** [iina/iina#3070]
**System and IINA version:**

- macOS 10.15.6
- IINA 1.0.7 

**Expected behavior:**
No virus

**Actual behavior:**
virustotal(www.virustotal.com) says there is Trojan.MAC.Shlayer in IINA and it is Ad-Aware. Is it trustworthy？
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/59787459/90034764-9a2c9c80-dcf3-11ea-81ab-ec7743286061.png">

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment]
See #1728.

Please make sure that your binary is downloaded from GitHub release or https://iina.io, and the shasum matches.
