### ISSUE TITLE
[Feature request]-Supported subtitle instead of error of "Unsupported external subtitle"

### ISSUE THREAD

**Issue by zhouyuan901** [iina/iina#3073]
**What you want IINA to do:**
When loading the subtitle ignore the 0 in the subtitle file instead of shows error. ( Because some of subtitle file start from 0, not 1)

**What IINA does currently:**
When subtitle contains 0 at the beginning of the file will pop up the error "Unsupported external subtitle"

**Why you think this should be added:**
Should be easy to fix in the program instead of the user manual change it every time if the subtitle file contains the 0.

**Examples of other projects that have something similar:**

![image](https://user-images.githubusercontent.com/17016718/90307638-cbe16700-de9d-11ea-8fb0-bb40e1e3141a.png)

**Comment by lhc70000** [comment]
See https://github.com/mpv-player/mpv/issues/3820. It might be possible to do some format checking on IINA's side, but we are currently not interested.
