### ISSUE TITLE
Can't unregister application associations

### ISSUE THREAD

**Issue by radozd** [iina/iina#3075]
- macOS 10.15.6
- IINA 1.0.7

**Expected behavior:**
Disabling association with audio files/playlists unregisters app for these extensions.

**Actual behavior:**
It doesn't

/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -u /Applications/iina.app
resets checkboxes back after first launch

**Steps to reproduce:**
Disable audio files association, try to open wav file

**How often does this happen?**
every time

**Comment by lhc70000** [comment]
There is no public API in macOS to "unset" a default application, perhaps because the system doesn't know which app should be the next default. If uninstalling and installing again doesn't work, I guess the only way is to change it manually in Finder.
