### ISSUE TITLE
Icon Stuck in Dock

### ISSUE THREAD

**Issue by faxotherapy** [iina/iina#3082]
**System and IINA version:**

- macOS: Mojave 10.14.6
- IINA: 1.0.7

**Expected behavior:**
Icon should not remain in Dock after quitting app.

**Actual behavior:**
Sometimes (unable to reproduce as it happens **sometimes**), the app icon remains stuck in the Dock. This is a recurring issue and only happens with IINA. It does not happen with any other app installed on my system.

![Icon_stuck_in_Dock](https://user-images.githubusercontent.com/6538008/91419514-643afc80-e84b-11ea-8355-ec979a8c5617.gif)

I cannot report any log, because there's no IINA related files in ~/Library/Logs/DiagnosticReports/

I cannot enable logging since the app is stuck. Apparently, the fact that icon is stuck in Dock prevents me from launching the app.

![Unable_to_open_IINA](https://user-images.githubusercontent.com/6538008/91419471-584f3a80-e84b-11ea-8a30-67c6bad4c760.gif)

The pop-up says “unable to open IINA”.

**Steps to reproduce:**

I cannot reproduce it. It only happens when IINA wants.

I've got the MPV app installed. MPV can open my videos. VLC can open them too.

**How often does this happen?**

It happens sometimes.

Also, when issuing the command `killall Dock`, the Dock does not relaunch. Hence, IINA icon still remains in the Dock. Tried to kill a thousand times this damned Dock, it doesn't want.

**Comment by anohren** [comment]
As you can see in your picture there is a dot underneath the icon in dock, which means the app has not really quit and that it is frozen. Its presence in the dock is correct in this case. 

There are tools in the system activity monitor, like taking a process sample, that can give a clue as to what's wrong with the app.
