### ISSUE TITLE
Toggling filters don't toggle but are just added onto the list of filters

### ISSUE THREAD

**Issue by satvikpendem** [iina/iina#3088]
**System and IINA version:**

- macOS 10.15.6 
- IINA 1.07

**Expected behavior:**

The filters should toggle properly, being added and removed from the list of filters. I only tried this with audio filters however, but it might be the same for video filters as well.

**Actual behavior:**

The filters are not actually toggled but instead just added onto the list. It looks like IINA treats each version of the audio filter properties as a different audio filter.

Video: https://i.imgur.com/V9iRnFx.mp4

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
As often as I toggle filters.

**Comment by low-batt** [comment]
See issue #3620 for details on the problem.
The fix in PR #3665 has been merged into the develop branch.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.

**Comment by satvikpendem** [comment]
Awesome, thanks!

**Comment by low-batt** [comment]
Thank you for taking the time to report the problem! The details you provided help me to track down the problem.
