### ISSUE TITLE
Cannot customize skip back or forward

### ISSUE THREAD

**Issue by skipstar3** [iina/iina#3094]
Hi! So I have been trying to change the skip settings because the default was too long.

I went to key bindings and created a duplicate and set it to skip by 2 seconds:
![Screenshot 2020-09-06 at 3 33 23 PM](https://user-images.githubusercontent.com/70841663/92323601-a805e100-f057-11ea-881c-12044bddd773.png)

But it hasn't changed anything. When I skip, it usually goes back/forward 30s now! And its so inconsistent because sometimes after many 30s it will skip by 10s or less. 

This is what it shows in the dropdown menu. Theres no <- or -> arrow like there should be on the side.
![Screenshot 2020-09-06 at 3 34 17 PM](https://user-images.githubusercontent.com/70841663/92323639-f0bd9a00-f057-11ea-93a2-4fcb63864c5b.png)

Am I doing something wrong? Any help would be very appreciated!

**Comment by lhc70000** [comment]
Please see this link:
https://github.com/iina/iina/wiki/FAQ#why-is-the-seeking-time-not-precise-when-pressing-arrow-keys

I'm going to alert users about this at the first launch in later versions.
