### ISSUE TITLE
iina 如何跳转到指定时间戳？

### ISSUE THREAD

**Issue by okerivy** [iina/iina#3109]
用IINA自带的 `打开URL` 或者  `/Applications/IINA.app/Contents/MacOS/iina-cli `
1，youbute 自带 的可以跳转 https://youtu.be/Nkv46M_Z6Ww?t=228
2，bilibili 的跳转不了  https://www.bilibili.com/video/av87649883?t=600s

并且本地视频也无法跳转  时间戳
 `/Applications/IINA.app/Contents/MacOS/iina-cli  xxxx.mp4` 能打开视频，但是怎么直接跳转到指定时间戳？
iina 菜单中是有这个 `播放`-> `跳转到指定时间`的。
怎么用`命令行 /iina-cli ` 或者 `iina://weblink?url=` 打开 指定的时间

**Comment by lhc70000** [comment]
请使用 mpv 选项 [time-pos](https://mpv.io/manual/master/#command-interface-time-pos):

```
iina-cli /path/to/file -- time-pos=600
```
