### ISSUE TITLE
Always On Top PIN icon should be persistent.

### ISSUE THREAD

**Issue by Careless** [iina/iina#3120]
The "Float on Top" Pin/Thumbtack Icon at the top right of the player window's title bar should have a circle/slash or an X through it if it is currently not active.

Currently IINA turns it sideways for a split second when you click it, and then it disappears. To reactive it you need to use/know the keyboard shortcut or use the task bar menu to re-enable.

It would be nice if you could just reclick the icon to re-enable this function. 

Not sure if it already does this and it's just a bug in the version I am using (1.1.0-beta1 Build 121).

**Comment by lhc70000** [comment]
There's a switch under Preferences - UI - Window.

**Comment by Careless** [comment]
> There's a switch under Preferences - UI - Window.

lol. ya know, i thought it behaved differently than the last computer I installed IINA on. 

didn't realize there was a checkbox for it. I must have had that ticked at some point.

thanks!
