### ISSUE TITLE
iina的safari扩展无法正常加载

### ISSUE THREAD

**Issue by hooke007** [iina/iina#3125]
**System and IINA version:**

- macOS  10.15.6
- IINA 1.1.0beta1

**Expected behavior:**
正常加载safari扩展后在标题栏显示图标。

**Actual behavior:**
无法加载扩展。标题栏无iina扩展图标。
手动选择重新加载，safari标题栏闪烁扩展图标，多次闪烁后图标消失

找不到相关的可用的log

**Steps to reproduce:**
如上

**How often does this happen?**

Always.

**Comment by hooke007** [comment]
手动安装扩展（v1.0version）显示不支援当前版本（safari14）

**Comment by lhc70000** [comment]
请测试 beta2。

**Comment by hooke007** [comment]
已解决。
