### ISSUE TITLE
Support iOS or iPadOS?

### ISSUE THREAD

**Issue by trusbe** [iina/iina#3129]
是否有计划支持iPhone或者iPad？iOS 或 iPadOS?

Are there any plans to support the iPhone or iPad? iOS or iPadOS?

**Comment by thuongvovan** [comment]
I also hope so.

**Comment by antoniogermano** [comment]
Me too. I came here to figure out how hard it would be to port IINA to iOS and iPadOS, but if there's going to be official support for it, it would be awesome!

**Comment by lhc70000** [comment]
Please check my answers for previous similar issues:

https://github.com/iina/iina/issues?q=ios+is%3Aclosed
