### ISSUE TITLE
Skip Forward/Backward skipping wrong amount of time in video

### ISSUE THREAD

**Issue by federicochiesa** [iina/iina#3130]
**System and IINA version:**

- macOS 10.14.6
- IINA 1.0.7

**Expected behavior:**
When I use the arrow keys or click Playback -> Step Forward 5s, the video goes forward by 30s instead, even if I didn't touch the key bindings and left the default ones.

**Actual behavior:**
When I press the left/right key or the menu option, it shoud skip the correct amount of time. 

**Steps to reproduce:**
1. Open a video file
2. Press left/right arrow keys or click Playback -> Step Forward 5s

**How often does this happen?**
Always

**Comment by lhc70000** [comment]
See https://github.com/iina/iina/wiki/FAQ#why-is-the-seeking-time-not-precise-when-pressing-arrow-keys.
