### ISSUE TITLE
Playlist panel hides volume and timeline controls

### ISSUE THREAD

**Issue by chkhld** [iina/iina#3138]
**System and IINA version:**

- macOS 10.14.6
- IINA 1.0.7 build 119

**Expected behavior:**
When displaying the playlist panel, the volume and timeline controls should not be hidden by the playlist panel, but still accessible.

**Actual behavior:**
When the playlist panel is displayed, it hides the volume and timeline controls, which significantly restricts mouse accessibility, until the playlist panel is hidden again.
<br>

Controls visible while playlist panel is hidden:
![Screenshot 2020-10-05 at 18 49 49](https://user-images.githubusercontent.com/53377392/95109208-91c57080-073c-11eb-87fb-256c83f32d37.png)

Controls hidden while playlist panel is showing:
![Screenshot 2020-10-05 at 18 49 56](https://user-images.githubusercontent.com/53377392/95109232-9c800580-073c-11eb-8c1f-1aeae2e1310b.png)

<br>

**Steps to reproduce:**
Display the playlist panel...

**How often does this happen?**
Every time

**Comment by lhc70000** [comment]
We have some proposals in #42 and #1340. This is in the plan.
