### ISSUE TITLE
Not maintain video aspect ratio when resizing the window

### ISSUE THREAD

**Issue by Kivenzhao** [iina/iina#3140]
Please Add a Feature that could not maintain video aspect ratio when resizing the window.
Because I sometimes need to adjust the window position.
Thank you.

——————
能否在调整界面大小的同时不要更改视频画面的宽高比，因为有时候想要把视频窗口和别的窗口进行组合。
非常感谢。

**Comment by lhc70000** [comment]
See https://github.com/iina/iina/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.3.0

This is in the plan.
