### ISSUE TITLE
希望视频倍速能调整1.25 1.5 1.75倍……好像只能调整1倍 2倍

### ISSUE THREAD

**Issue by zphxmz** [iina/iina#3141]
**What you want IINA to do:**

**What IINA does currently:**

**Why you think this should be added:**

**Examples of other projects that have something similar:**

**Comment by lhc70000** [comment]
- 快捷键 option+cmd+[ 或 ] 可调节 1.1 倍，菜单里按住 option 可以看到。
- 「视频」侧边栏中不仅可以拖动滑条调整速度，还可以输入任意速度。
- 所有快捷键都可以在偏好设置里自己编辑。
