### ISSUE TITLE
Playback speed in increments of 0.10

### ISSUE THREAD

**Issue by r-vivek** [iina/iina#3143]
**What you want IINA to do:**

Playback speed at 2sec is way too fast and causes gibberish audio which is not useful when learning educational videos. Can you implement playback speed at increments/decrements of 0.10.

**Examples**
VLC and Potplayer has this feature

**Comment by lhc70000** [comment]
- You can use Option+Cmd+[ or ] to speed up or down by 1.1x by default.
- You can drag the slider or type in an arbitrary speed value in the video sidebar.
- You can customize all keyboard shortcuts in Preferences - Key Bindings.

![image](https://user-images.githubusercontent.com/8478049/95320059-7ccb1780-08cb-11eb-8d4c-fb5cffbcba73.png)
