### ISSUE TITLE
iina crashes unregularly

### ISSUE THREAD

**Issue by stefan1983** [iina/iina#3176]
iina crashes unregularly on my system.
I am running a MacBook Pro 13" 2017 with macOS Catalina 10.15.7.
iina version: 1.1.0 (123)

[IINA_2020-10-27-192537.crash.log](https://github.com/iina/iina/files/5458375/IINA_2020-10-27-192537.crash.log)

**Comment by lhc70000** [comment]
It crashed in videotoolbox. Such crashes usually happen when playing certain files using hardware decoding. Please disable hardware decoding for those files, or turn hardware decoding off by default and turn it on in the sidebar when needed.
