### ISSUE TITLE
Library/Caches (thumb_cache) never cleaned - should it be?

### ISSUE THREAD

**Issue by edrozenberg** [iina/iina#3179]
1.1.0 Build 123

My `/Users/<username>/Library/Caches/com.colliderli.iina` dir is currently at 560 MiB, the majority taken up by `thumb_cache`. Does this dir ever get automatically cleaned by IINA or grows permanently?

Lots of apps, not just IINA, do not clean up their cache dirs, and it adds up to a pretty significant amount of wasted disk space.

**Comment by lhc70000** [comment]
You can set the maximum cache size in Preferences - UI - Thumbnail Preview, and next time IINA will clean old cache automatically when writing cache for a new video. I just tried and it worked well on my machine.

If you need to clean the cache immediately, there is also a button in Preferences - Utilities.

**Comment by edrozenberg** [comment]
"There's a pref for that" :). Thanks!
