### ISSUE TITLE
Support youtube-dl forks (youtube-dlc etc)

### ISSUE THREAD

**Issue by edrozenberg** [iina/iina#3180]
`youtube-dl` is currently broken for YouTube (`ERROR: Unable to extract JS player URL;`). As a result the IINA browser plugin cannot open any YT video URL's atm.

Suggestion:
Allow a custom `youtube-dl` binary to be specified. There are faster moving forks such as `youtube-dlc` (https://github.com/blackjack4494/yt-dlc) which are compatible with youtube-dl CLI parameters.

I tried custom youtube-dl path setting `/usr/local/bin/youtube-dlc` but this doesn't work - IINA looks only for `youtube-dl` binary.

Current workaround (works fine for now):
1. Remove youtube-dl (for ex. `brew uninstall youtube-dl`)
2. Install youtube-dlc manually to `/usr/local/bin/` and `/usr/local/lib/python3.9/site-packages/`
3. Symlink in `/usr/local/bin/` - `$ ln -s youtube-dlc youtube-dl`

After applying the workaround IINA browser plugin can open YT URL's just fine.

**Comment by saagarjha** [comment]
I believe it's mpv that hardcodes youtube-dl, not IINA. Might be worth asking for upstream?

**Comment by edrozenberg** [comment]
Thanks, a commit was pushed to mpv several days ago (https://github.com/mpv-player/mpv/commit/ad1ecd4350efe5580d1b1b56ebb8012df0dd93e6) in response to mpv issue https://github.com/mpv-player/mpv/pull/8207

The mpv change (which I assume will be picked up by IINA sometime) is to use the full user-specified path to a binary if the default "youtube-dl" binary is not found in that path. Meaning if the user specifies `/usr/local/bin/youtube-dlc` it will actually use that binary, instead of looking for `youtube-dl` in the path `/usr/local/bin/youtube-dlc/`.

**Comment by edrozenberg** [comment]
Also homebrew now offers the latest `youtube-dl` 2020.11.1.1 which fixes issues and everything works fine once again. Hopefully `youtube-dl` will continue to be updated and developed to handle further breakages that Google and other video sites continue to cause on purpose or otherwise.
