### ISSUE TITLE
I love iina, it made me kick vlc after nearly 2 decades :-) I passed the youtube-dl folder but how do I actually use it?

### ISSUE THREAD

**Issue by cocoonkid** [iina/iina#3187]
I love iina, it made me kick vlc after nearly 2 decades :-) I passed the youtube-dl folder but how do I actually use it?

I can't find the button to save the video anywhere.

Thanks in advance

**Comment by edrozenberg** [comment]
Welcome to IINA :) speaking as a happy user. Not aware of a way to save a video from IINA. I use IINA either to open a YouTube video using the IINA browser plugin, or give the YouTube URL to IINA via File -> Open URL.

Use the `youtube-dl` command to save a video from the command line.

View available formats to download:
`youtube-dl --list-formats https://somevideo`

Download a specific video+audio combination, for ex (you can remove the ffmpeg part if you don't want to use ffmpeg):
`youtube-dl --format 137+140 --prefer-ffmpeg https://somevideo`

Download the default video+audio (frequently of lower quality than what you get by using the specific formats with the earlier command):
`youtube-dl --prefer-ffmpeg https://somevideo`

**Comment by cocoonkid** [comment]
Thanks! I think I missunderstood.

Apparently the youtube-dl folder/plugin is just for IINA to use as default folder ?

Otherwise I am not sure what the yt-dl plugin is meant for  :smile:

**Comment by dmattera** [comment]
> Apparently the youtube-dl folder/plugin is just for IINA to use as default folder ?
> 
> Otherwise I am not sure what the yt-dl plugin is meant for

Essentially, it allows you to use IINA as the interface for watching videos such as those from youtube or any other site that youtube-dl supports without needing to use a web browser. Just press Cmd+Shift+O and paste the URL.

This is useful If your goal is to simply watch a video or playlist of videos once (as opposed to downloading them and saving "permanently".

**Comment by cocoonkid** [comment]
Thank you for clearning this up!  Maybe I am a special kind right now but it might be helpful to add a little explainer text.
