### ISSUE TITLE
Synced lyrics and .lrc files

### ISSUE THREAD

**Issue by Mrosenhave** [iina/iina#3192]
This is a feature request and maybe a bug report.
In earlier versions of iina it was possible to load a synced lyrics file (.lrc) by first opening a music file then entering the normal video viewing mode and then manually opening the .lrc file as an external subtitle. But after a recent update, selection of .lrc files is impossible when loading an external subtitle. I don't know if this is a bug or an intentional change, but I would like seeing it be reinstated. 

My feature request is better support for lyrics and synced lyrics while playing music. Maybe an accompanying lyrics panel in the music player, with a nice animation when the line changes like in Apple Music. Any implementation of this be it simple or fancy would be much appreciated :)

**Comment by edrozenberg** [comment]
This would be great. I'm also not seeing any subtitles on a .m4a even after selecting and adding external .srt, .vtt, .lrc subtitles.

**Comment by jjm2473** [comment]
.lrc support is broken in 1.4.1, nothing display after loaded .lrc.
