### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by anonymous5l** [iina/iina#3194]
on idle high cpu usage avg 122%

**System and IINA version:**

- macOS 10.14.6
- IINA 1.1.0 Build 123

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by anonymous5l** [comment]
1.1.1 fix that problem

**Comment by anonymous5l** [comment]
![屏幕快照 2020-11-12 上午1 57 41](https://user-images.githubusercontent.com/37862633/98846946-9e02c300-248a-11eb-8c79-b1109a305097.png)

i think that's the problem

**Comment by saagarjha** [comment]
A sample would probably be useful, alternatively you can expand the `-[NSApplication(NSEvent) sendEvent:]` stack.

**Comment by anonymous5l** [comment]
@saagarjha 

![屏幕快照 2020-11-12 下午4 46 41](https://user-images.githubusercontent.com/37862633/98916994-cc25e880-2506-11eb-8f4f-151271b890b4.png)

**Comment by anonymous5l** [comment]
https://drive.google.com/file/d/1cBvkNZP1B2FxO1rubtPBY3a3VElN6BX8/view?usp=sharing

Instruments.trace file could more infomation

**Comment by low-batt** [comment]
The first screenshot shows `avformat_open_input` is being called. That is a call IINA makes to obtain the duration of a video. The second screenshot shows the method `PlaylistViewController.tableView` is being called. This plus the high CPU is suggestive of issue #3162, an infinite table view reload loop. See that issue for full details on the problem.

**Comment by low-batt** [comment]
The fix in PR #3477 has been merged into the develop branch.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.
