### ISSUE TITLE
Doesn't open any links from YouTube.

### ISSUE THREAD

**Issue by Oleg-Chashko** [iina/iina#3195]
**System and IINA version:**

- macOS v.11.0.1 Beta (20B5022a)
- IINA v.1.1.1 Build 124

After upgrading to IINA v.1.1.1 Build 124. Doesn't open any links from YouTube.

<img width="299" alt="Bildschirmfoto 2020-11-09 um 18 34 48" src="https://user-images.githubusercontent.com/62497891/98576454-d784d400-22ba-11eb-92c2-af53039c2d92.png">

**Comment by lhc70000** [comment]
Thanks for the report. I have updated the GitHub release and please try again.
