### ISSUE TITLE
iina stuck in update-loop

### ISSUE THREAD

**Issue by core-code** [iina/iina#3197]
your appcast promised build 125 but installs build 124 so an up-to-date-version will still ask you to update

**Comment by lhc70000** [comment]
It might be a CloudFlare caching issue and I just purged the cache. Could you try again now?

The file downloaded from https://dl.iina.io/IINA.v1.1.1.dmg should have the SHA256 checksum `ae9ac06459c2b9cd160592881c323d3fb3b50a9b70ba89c6f9f1e13df85c6881`.

**Comment by core-code** [comment]
yes it is fixed now.
