### ISSUE TITLE
Arrow keys in input fields in Quick Settings should not affect playback

### ISSUE THREAD

**Issue by vwkd** [iina/iina#3206]
When using the arrow keys in any input field in Quick Settings, they affect the playback instead of the cursor in the input field. This is extremely annoying, since you have to move the cursor by mouse, if you want to change what you typed.

**System and IINA version:**

- macOS 11.0.1 (20B29)
- IINA 1.1.1 Build 125

**Expected behavior:**

The arrow keys move the cursor in the input field.

**Actual behavior:**

The arrow keys move the playback position.

**Steps to reproduce:**

1. Open Quick Settings while playing a video.
2. Place your cursor in any input field, for example **Speed**
3. Type something in the input field.
4. Use the arrow keys to move the cursor inside the input field.
5. Observe how the arrow keys change the playback position (for left and right) or volume (for up and down) instead of the cursor position in the input field.

**How often does this happen?**

Always

**Comment by qqvm** [comment]
Version 1.1.2 Build 128 (mpv 0.32.0), the issue is still present.

**Comment by low-batt** [comment]
This was fixed in IINA 1.4.0-beta1.
