### ISSUE TITLE
Entering fullscreen animation temporarily freezes video playback

### ISSUE THREAD

**Issue by jasonhan-vassar** [iina/iina#3212]
**System and IINA version:**

- macOS 11.0.1
- IINA 1.1.1

**Expected behavior:**

The video should play as the full screen (normal, not legacy full screen) animation plays out.

**Actual behavior:**

As IINA enters full screen, the video frames stop advancing, but the audio and time still continue.

**Steps to reproduce:**

Open any video (one with noticeable changes between frames would make it easier to tell) and enter full screen. The content should freeze up while the full screen animation plays out.

**Comment by uiryuu** [comment]
See #2386.
