### ISSUE TITLE
Step Forward 5s causing beachballs

### ISSUE THREAD

**Issue by applebait** [iina/iina#3213]
I'm getting beachballs just by keep the right arrow key pressed, which makes the _Step Forward 5s_ command. I didn't try the _Step Backward 5s_…
It wasn't having this behaviour before.

Running macOS Catalina 10.15.7 and iina version 1.1.1

TiA

**Comment by lhc70000** [comment]
See https://github.com/iina/iina/wiki/FAQ#why-is-the-seeking-time-not-precise-when-pressing-arrow-keys.
