### ISSUE TITLE
IINA doesn't render Persian subtitle properly after update from 1.1.0 to 1.1.1 or higher version

### ISSUE THREAD

**Issue by alipiry** [iina/iina#3222]
**System and IINA version:**

- macOS version: 10.15.5 
- IINA version: 1.1.1 or higher

**Expected behavior:**
IINA must render Persian subtitle properly 

**Actual behavior:**
IINA doesn't render Persian subtitle, instead, it renders some weird symbols (maybe encoding bug) 

<details>
<summary><b>Bug Report:</b></summary>
It was okay before I updated the app to v1.1.1 or higher.
<br><br>

Before update screenshot:
- IINA version: 1.1.0
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/25138854/99921223-30824c80-2d3e-11eb-9bca-3ca5a3d85b00.png">
<br><br>

After update screenshot:
- IINA version: 1.1.1 or higher
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/25138854/99921133-ab973300-2d3d-11eb-8bfb-3ee5dd8cf999.png">

</details>

<br>

**How often does this happen?**
All the time

**Comment by lhc70000** [comment]
In some previous cases where some users said Chinese subtitles disappeared in 1.1.1, the reason was that they replaced the system fonts with some custom ones before upgrading to Big Sur.

Are you using the default font in IINA? Did you modify/replace any system font?

If this is not your case, please provide a sample subtitle file for testing.

**Comment by alipiry** [comment]
> In some previous cases where some users said Chinese subtitles disappeared in 1.1.1, the reason was that they replaced the system fonts with some custom ones before upgrading to Big Sur.
> 
> Are you using the default font in IINA? Did you modify/replace any system font?
> 
> If this is not your case, please provide a sample subtitle file for testing.

No I didn't change any default font!

Here's the sample subtitle:

[The.Mandalorian.S02E04.HDR.2160p.WEB.H265-GGWP.Fa.srt.zip](https://github.com/iina/iina/files/5590807/The.Mandalorian.S02E04.HDR.2160p.WEB.H265-GGWP.Fa.srt.zip)

**Comment by lhc70000** [comment]
Seems to be a bug in libass 0.15.0. There's nothing we can do before libass fixes this issue.

**Comment by alipiry** [comment]
@lhc70000 BTW thanks for amazing work 👍

**Comment by itsMahdi** [comment]
Hi!
I had the same problem in iina version 1.1.1 and higher,
so I change the default font to "B Nazanin" and it works for me.

**Comment by sjml** [comment]
FYI, looks like the fix for this is on track for libass 0.15.1. 

https://github.com/libass/libass/issues/457

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0 by the upgrade to libass 0.15.2.
