### ISSUE TITLE
Indicate on OSD when File Loop is toggled

### ISSUE THREAD

**Issue by jasonhan-vassar** [iina/iina#3229]
Hi, is it possible for IINA to indicate when File Loop is toggled? Currently A-B Loop being toggled is indicated on the On Screen Display, so I feel that this should also be done for File Loop to keep things consistent. Please let me know what you think!

**Comment by caleidoscopio** [comment]
I agree with this. It would be very useful and it would make much more sense

**Comment by low-batt** [comment]
In addition to adding an OSD message for toggling file looping the commit in the pull request also adds an OSD message for toggling playlist looping. The text chosen for the OSD messages match up with the names used in the menus, "File Loop" and "Playlist Loop". To indicate the state of looping the new messages follow the convention of other OSD messages and use a localized "On" or "Off". When file looping is enabled the OSD will display:

```text
File Loop: On
```

The commit in the pull request will:
- Add a new enumeration case `fileLoop` to  `OSDMessage`
- Add a new enumeration case `playlistLoop` to  `OSDMessage`
- Update   `OSDMessage.message` to handle  `fileLoop`
- Update   `OSDMessage.message` to handle  `playlistLoop` 
- Add text for `osd.file_loop` and `osd.playlist_loop` to base localized strings
- Add text for `osd.file_loop` and `osd.playlist_loop` to en localized strings
- Change `PlayerCore.toggleFileLoop` to display the new OSD message
- Change `PlayerCore.togglePlaylistLoop` to display the new OSD message

**Comment by low-batt** [comment]
Support for this feature has been merged into the develop branch.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.
