### ISSUE TITLE
请问有没有可能实现直接打开本地的URL文件直接播放的功能

### ISSUE THREAD

**Issue by iAPPOpen** [iina/iina#3245]
既然有解析播放在线视频的功能，那么有没有可能实现我想收藏一个视频不用下载视频本身而是直接将网页保存为一个URL快捷方式的本地文件，用iina打开这个快捷方式然后就直接解析并播放呢，这样好像很有趣。

**Comment by wyq977** [comment]
Duplicated and iina already has a bundled cli, see #1097

```bash
iina https://www.youtube.com/watch?v=GePTPzN_Nzs #youtube
iina https://www.bilibili.com/video/BV1jf4y1i7da #bilibili
```

```

**Comment by lhc70000** [comment]
可以试试 m3u8 的播放列表文件。纯文本文件，一行写一个 url 即可。
