### ISSUE TITLE
swift 5.3 now support Windows, if it's possible, that add a Windows Version in the future

### ISSUE THREAD

**Issue by Steve-Li-1998** [iina/iina#3249]
**What you want IINA to do:**
add a Windows Version if it's possible

**What IINA does currently:**

**Why you think this should be added:**

**Examples of other projects that have something similar:**

**Comment by chucker** [comment]
IINA is mostly a GUI on top of MPV. While you could use Swift to make a Windows GUI app, you almost certainly wouldn't use AppKit/Cocoa, so you'd have to throw away much of the code.

Far easier to start from scratch and use, say, C# + WPF.

**Comment by low-batt** [comment]
The issue of supporting additional platforms is discussed in the FAQ: [Will there be a Windows/Linux/iOS version?](https://github.com/iina/iina/wiki/FAQ#will-there-be-a-windowslinuxios-version)

Similar to many open source projects IINA is layered on top of other projects. For audio/video playback IINA is using a library from the [mpv](https://mpv.io/) project. IINA is a graphical user interface specifically designed for macOS, layered on top of mpv.

@chucker is correct. Support for other platforms are really separate projects as so much of the IINA code is tied to macOS.

There are other projects that provide GUIs using `libmpv`. The mpv wiki page [gui-frontends](https://github.com/mpv-player/mpv/wiki/Applications-using-mpv#gui-frontends) lists some of them.

I am closing this issue as the IINA project has no plans to support other platforms.
