### ISSUE TITLE
[Feature Request] Playlist Filter/Search

### ISSUE THREAD

**Issue by AravindhStanley** [iina/iina#3251]
I'm not sure if IINA already has this feature, but I certainly could not find it. 

**What IINA does right now?**
When you drag a playlist with multiple files, IINA gives a neat list of all the files in the playlist tab.

**What I would like IINA to do better?**
Add some filter or search function to easily access the files you want. 

**Why would this help?**
It becomes very difficult to browse a large playlist very soon without a search function.

**Comment by anohren** [comment]
Workaround for those having this problem:

1. Click the Help menu
2. Start typing
3. You will get playlist results from the fact that the playlist is a submenu of the Playback menu

**Comment by AravindhStanley** [comment]
Thanks @anohren. That worked. 

Closing the issues as we at least have a workaround.

**Comment by anohren** [comment]
No problem!

> Closing the issues as we at least have a workaround.

I don't see the logic behind that

**Comment by ginofalaci** [comment]
I second this, it would be very useful. Im testing IINA for IPTV, with a very large streamlist, it opens, very quickly, I would just be glad to see a search bar under it, and also the tree view wich is just 2 levels: Group name - list of streams.

**Comment by mostafaznv** [comment]
> Workaround for those having this problem:
> 
> 1. Click the Help menu
> 2. Start typing
> 3. You will get playlist results from the fact that the playlist is a submenu of the Playback menu

This workaround doesn't work, but it has some problems with large playlists.
I use this app for playing IPTV playlist and it is a huge list.

**Comment by anohren** [comment]
> doesn't work, but it has some problems

Does work?

Yes, doesn't seem ideal to create these gigantic menus and then search through them using what I can only imagine are UI APIs...

Nice to see that someone is working on a proper search PR though.

**Comment by mostafaznv** [comment]
> > doesn't work, but it has some problems
> 
> 
> 
> Does work?
> 
> 
> 
> Yes, doesn't seem ideal to create these gigantic menus and then search through them using what I can only imagine are UI APIs...
> 
> 
> 
> Nice to see that someone is working on a proper search PR though. 

Sorry. it was just typo.
it works but it doesn't have good performance with large files.

someone is working on a proper search field for playlists but I don't know when he finishes his work.

it's must needed feature for people who use this app as a IPTV player.



https://github.com/iina/iina/pull/3751
