### ISSUE TITLE
Window pulldown doesn't list correct open windows

### ISSUE THREAD

**Issue by twenty-one** [iina/iina#3253]
My videos are on a LAN server. Often when I have more than one video open and I go to the Window pulldown list, the videos listed are ones that are not open or were open but are now closed. When I click on one of the incorrect items it will take me to a video that is not listed.

**Comment by low-batt** [comment]
I believe this is the same problem reported in issue #3159.

The changes in the pull request for that issue should fix this issue.

**Comment by low-batt** [comment]
The fix (a workaround) in PR #3435 has been merged into the develop branch.

Apple has fixed the AppKit defect in macOS Monterey.

See issue #3159 for details.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.
