### ISSUE TITLE
IINA播放视频和音频没声音

### ISSUE THREAD

**Issue by 1982606762** [iina/iina#3285]
前几天忽然IINA播放所有文件时都没有声音，音轨也检查过了，重装过软件也没有用，电脑的所有其他音频正常，出问题的媒体用其他播放器播放正常

**System and IINA version:**

- macOS 10.15.7
- IINA 1.1.2

**Expected behavior:**
打开播放的视频或者音频一切正常

**Actual behavior:**
没有声音，画面正常

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
每次

**Comment by 1982606762** [comment]
升级到11.1版本后依然存在这个问题

**Comment by Fujiwara-Chika** [comment]
可以提供一下播放时的截图吗，有可能误触到了静音按钮（
![image](https://user-images.githubusercontent.com/44722787/105634747-a0c26100-5e9a-11eb-81c0-89390c1a77e4.png)

**Comment by 1982606762** [comment]
> 可以提供一下播放时的截图吗，有可能误触到了静音按钮（
> ![image](https://user-images.githubusercontent.com/44722787/105634747-a0c26100-5e9a-11eb-81c0-89390c1a77e4.png)

太强了！！我居然真的是这里静音了。。。他左上角也没提示:(感觉自己的智商捉急

**Comment by chenxinggui** [comment]
牛

**Comment by SHERlocked93** [comment]
快捷键 `M` 是静音 mute，我也经常误触到…… 😅

**Comment by SobSobDu** [comment]
fuck，调了全局的音量也没有用，我也是单独把播放器静音了

**Comment by Wqingqing-sparks** [comment]
谢谢🙏，有用

**Comment by StevenGrow** [comment]
> 快捷键 `M` 是静音 mute，我也经常误触到…… 😅

确实

**Comment by StevenGrow** [comment]
<img width="376" alt="image" src="https://github.com/iina/iina/assets/105007214/30ae4c53-c5c5-42c9-b39c-40ed93c0a9e0">

今天也出现这种情况了，后来找到了设置里的音频设置，然后切换一下上面的选项就可以播放出声音了

**Comment by trxsudo** [comment]
> <img alt="image" width="376" src="https://private-user-images.githubusercontent.com/105007214/298254149-30ae4c53-c5c5-42c9-b39c-40ed93c0a9e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTMzNTksIm5iZiI6MTcxNjQ1MzA1OSwicGF0aCI6Ii8xMDUwMDcyMTQvMjk4MjU0MTQ5LTMwYWU0YzUzLWM1YzUtNDJjOS1iMzljLTQwZWQ5M2MwYTllMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODMwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjhkM2Q5MDA1ZjY3NzhlYmNjODUwYmZiMmNiMmMxODUwZDU5M2U3M2ZkOTIyODA1NzU4MmM2NjU5OTY2NjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z8QqoS7owiu6OCc_ZHb6JuZ6WSXfNXWV_6YhCm1lTTA">
> 今天也出现这种情况了，后来找到了设置里的音频设置，然后切换一下上面的选项就可以播放出声音了

请教这个音轨是怎么被切换的？是有什么快捷键吗？我今天也无缘无故出现这个情况，我起初还以为是我的音源出了问题，但我记得没有故意去切换音轨啊
