### ISSUE TITLE
Allow linear playback speed change!

### ISSUE THREAD

**Issue by Heshmatkhah** [iina/iina#3302]
Currently, IINA changes playback speed using multiplication, it multiplies current speed by `2`, `0.5`, `1.1`, `0.9091`.
so If you are at a high speed, (assume a professor that teaches too slow and you are at 4x) speed-changing steps are too big (`+2x`, `-2x`, `+0.4x`, `-0.36x`)and you should adjust the speed manually.

It will be nice if be possible to change the playback speed linearly, by adding some values like `0.1`, `0.5`, `-0.1`, `-0.5`, or something like that.

Also, it will be nice if there be a "Default Playback Speed" option in preferences so **all** new files opened at that speed.

**Comment by Fujiwara-Chika** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/44722787/105732833-d71be100-5f6b-11eb-9018-13dd22db29dd.png">

**Comment by firedev** [comment]
Drives me nuts too. +0.1 speed would be great.

**Comment by Heshmatkhah** [comment]
@Fujiwara-Chika I can't find that, my preferences is like this:

<img width="906" alt="Screen Shot 2021-01-28 at 9 50 54 PM" src="https://user-images.githubusercontent.com/10222466/106181963-7bdc2f80-61b3-11eb-9f60-83520eb05c30.png">

**Comment by Fujiwara-Chika** [comment]
<img width="731" alt="iShot2021-01-29 10 09 01" src="https://user-images.githubusercontent.com/44722787/106222235-11aaa580-621a-11eb-970a-93fcc42774f4.png">
<img width="731" alt="iShot2021-01-29 10 06 05" src="https://user-images.githubusercontent.com/44722787/106222242-13746900-621a-11eb-9620-099cfd5ea710.png">
Add or duplicate a new Conf firstly, if you want to change the Key Bindings. Or just edit it as a Plain Text.
<img width="377" alt="iShot2021-01-29 10 18 42" src="https://user-images.githubusercontent.com/44722787/106223175-e4f78d80-621b-11eb-89d1-d5aef27e4ee8.png">

This is my Conf, you can just unzip&move it into `~/Library/Application Support/com.colliderli.iina/input_conf/`
[IINA.conf.zip](https://github.com/iina/iina/files/5891142/IINA.conf.zip)

**Comment by Heshmatkhah** [comment]
As @Fujiwara-Chika said, I can add custom key binding dynamically and fully customizable, for reference of available functionalities I add a link to [its documentation](https://github.com/iina/iina/wiki/Manage-Key-Bindings).
