### ISSUE TITLE
使用ARM架构的iina，播放群晖上映射到本地硬盘的iso文件，系统崩溃重启了

### ISSUE THREAD

**Issue by alsomail** [iina/iina#3303]
panic(cpu 5 caller 0xfffffe0029762e38): "vm_object_iopl_request: missing/bad page in kernel object\n"
Debugger message: panic
Memory ID: 0x6
OS release type: User
OS version: 20B29
Kernel version: Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101
Fileset Kernelcache UUID: 35A645C8D62619060673BEF751E6A7AA
Kernel UUID: D8523129-E878-38BA-A8E0-1D0E8D2470B7
iBoot version: iBoot-6723.50.2
secure boot?: YES
Paniclog version: 13
KernelCache slide: 0x000000002191c000
KernelCache base:  0xfffffe0028920000
Kernel slide:      0x0000000022588000
Kernel text base:  0xfffffe002958c000
Kernel text exec base:  0xfffffe0029654000
mach_absolute_time: 0xdf0d6f2cbf
Epoch Time:        sec       usec
  Boot    : 0x600e1503 0x000deae5
  Sleep   : 0x60116729 0x0005449f
  Wake    : 0x6011677e 0x00049503
  Calendar: 0x6011745f 0x000512af

CORE 0 recently retired instr at 0xfffffe00297be4d0
CORE 1 recently retired instr at 0xfffffe00297be4d0
CORE 2 recently retired instr at 0xfffffe00297be4d0
CORE 3 recently retired instr at 0xfffffe00297be4d0
CORE 4 recently retired instr at 0xfffffe00297be4d4
CORE 5 recently retired instr at 0xfffffe00297bd00c
CORE 6 recently retired instr at 0xfffffe00297be4d4
CORE 7 recently retired instr at 0xfffffe00297be4d4
Panicked task 0xfffffe1679019f18: 7193 pages, 21 threads: pid 10031: IINA
Panicked thread: 0xfffffe1677362610, backtrace: 0xfffffe4017ba2780, tid: 851264
		  lr: 0xfffffe00296a1f7c  fp: 0xfffffe4017ba27f0
		  lr: 0xfffffe00296a1d48  fp: 0xfffffe4017ba2860
		  lr: 0xfffffe00297c37d0  fp: 0xfffffe4017ba2880
		  lr: 0xfffffe00297b52fc  fp: 0xfffffe4017ba2930
		  lr: 0xfffffe002965b7e8  fp: 0xfffffe4017ba2940
		  lr: 0xfffffe00296a19d8  fp: 0xfffffe4017ba2cd0
		  lr: 0xfffffe00296a19d8  fp: 0xfffffe4017ba2d40
		  lr: 0xfffffe0029e39dec  fp: 0xfffffe4017ba2d60
		  lr: 0xfffffe0029762e38  fp: 0xfffffe4017ba2f00
		  lr: 0xfffffe0029761a00  fp: 0xfffffe4017ba3020
		  lr: 0xfffffe0029d84f14  fp: 0xfffffe4017ba3150
		  lr: 0xfffffe0029d84738  fp: 0xfffffe4017ba3180
		  lr: 0xfffffe002bb6dccc  fp: 0xfffffe4017ba3240
		  lr: 0xfffffe002bb6b83c  fp: 0xfffffe4017ba3270
		  lr: 0xfffffe0029925928  fp: 0xfffffe4017ba3300
		  lr: 0xfffffe0029919dc4  fp: 0xfffffe4017ba3380
		  lr: 0xfffffe002c473da4  fp: 0xfffffe4017ba33d0
		  lr: 0xfffffe002c473814  fp: 0xfffffe4017ba34a0
		  lr: 0xfffffe002c473430  fp: 0xfffffe4017ba3510
		  lr: 0xfffffe002c4732a0  fp: 0xfffffe4017ba35f0
		  lr: 0xfffffe002c47d518  fp: 0xfffffe4017ba3700
		  lr: 0xfffffe002c46b684  fp: 0xfffffe4017ba3760
		  lr: 0xfffffe00298d2c2c  fp: 0xfffffe4017ba38c0
		  lr: 0xfffffe00298d7ed4  fp: 0xfffffe4017ba3ab0
		  lr: 0xfffffe00298d75cc  fp: 0xfffffe4017ba3b10
		  lr: 0xfffffe002c47da48  fp: 0xfffffe4017ba3bb0
		  lr: 0xfffffe002c46a3e8  fp: 0xfffffe4017ba3be0
		  lr: 0xfffffe002990dca0  fp: 0xfffffe4017ba3ca0
		  lr: 0xfffffe0029bc16c8  fp: 0xfffffe4017ba3d50
		  lr: 0xfffffe0029bc1478  fp: 0xfffffe4017ba3db0
		  lr: 0xfffffe0029c9d308  fp: 0xfffffe4017ba3e40
		  lr: 0xfffffe00297b4fe0  fp: 0xfffffe4017ba3ef0
		  lr: 0xfffffe002965b7e8  fp: 0xfffffe4017ba3f00
      Kernel Extensions in backtrace:
         com.apple.iokit.IOStorageFamily(2.1)[F2252D62-A951-339B-ACFA-8ADF55A5D04E]@0xfffffe002bb58000->0xfffffe002bb77fff
         com.apple.filesystems.udf(2.5)[6ED69DB1-EE49-3667-AD7C-E776A9A84A2B]@0xfffffe002c468000->0xfffffe002c497fff

last started kext at 957655425363: com.apple.filesystems.udf	2.5 (addr 0xfffffe0029578000, size 32768)
last stopped kext at 928994049520: com.apple.driver.usb.cdc	5.0.0 (addr 0xfffffe002905c000, size 16384)
loaded kexts:
com.apple.filesystems.udf	2.5
com.apple.filesystems.smbfs	3.4.1
com.apple.filesystems.autofs	3.0
com.apple.fileutil	20.036.15
com.apple.iokit.IOBluetoothSerialManager	8.0.1f5
com.apple.driver.BCMWLANFirmware4378.Hashstore	1
com.apple.driver.AppleAOPVoiceTrigger	11.5
com.apple.driver.AppleThunderboltIP	4.0.3
com.apple.iokit.AppleBCM5701Ethernet	11.0.0
com.apple.driver.SEPHibernation	1
com.apple.driver.CoreKDL	1
com.apple.driver.AppleUSBDeviceNCM	5.0.0
com.apple.filesystems.apfs	1677.50.1
com.apple.nke.l2tp	1.9
com.apple.filesystems.tmpfs	1
com.apple.driver.ApplePMP	1
com.apple.IOTextEncryptionFamily	1.0.0
com.apple.filesystems.hfs.kext	556.41.1
com.apple.security.BootPolicy	1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.driver.AppleSmartIO2	1
com.apple.driver.ApplePMPFirmware	1
com.apple.AppleEmbeddedSimpleSPINORFlasher	1
com.apple.driver.AppleTAS5770LAmp	437.96
com.apple.driver.AppleCS42L83Audio	437.96
com.apple.driver.AppleSPMIPMU	1.0.1
com.apple.driver.AppleT8020SOCTuner	1
com.apple.driver.AppleT8103CLPCv3	1
com.apple.AGXG13G	172.20.9
com.apple.driver.AppleAVD	373
com.apple.driver.AppleAVE2	401.63.1
com.apple.driver.AppleJPEGDriver	4.6.0
com.apple.driver.AppleMobileDispH13G-DCP	140.0
com.apple.driver.usb.AppleUSBHostT8103	1
com.apple.driver.AudioDMAController-T8103	1.53
com.apple.driver.AppleSPIMC	1
com.apple.driver.AppleS5L8960XNCO	1
com.apple.driver.AppleT8103PMGR	1
com.apple.driver.AppleS8000AES	1
com.apple.driver.AppleS5L8920XPWM	1.0.0d1
com.apple.driver.AppleS8000DWI	1.0.0d1
com.apple.driver.AppleS5L8960XWatchDogTimer	1
com.apple.driver.AppleInterruptController	1.0.0d1
com.apple.driver.AppleBluetoothModule	1
com.apple.driver.AppleSamsungSerial	1.0.0d1
com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
com.apple.driver.AppleT8020DART	1
com.apple.driver.AppleS5L8940XI2C	1.0.0d2
com.apple.driver.AppleT8101	1
com.apple.driver.AppleM68Buttons	1.0.0d1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleDiskImages2	1
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	310
com.apple.kec.InvalidateHmac	1
com.apple.driver.AppleXsanScheme	3
com.apple.driver.AppleUSBAudio	401.4
com.apple.iokit.IOAudioFamily	300.6.1
com.apple.kext.triggers	1.0
com.apple.iokit.IOAVBFamily	900.12
com.apple.plugin.IOgPTPPlugin	900.11
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleAOPAudio	14.32
com.apple.driver.IOBluetoothHostControllerPCIeTransport	8.0.1f5
com.apple.iokit.IOBluetoothHostControllerTransport	8.0.1f5
com.apple.driver.usb.AppleEmbeddedUSBXHCIPCI	1
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.AppleEmbeddedUSB	1
com.apple.driver.AppleConvergedIPCOLYBTControl	1
com.apple.driver.AppleConvergedPCI	1
com.apple.driver.AppleBluetoothDebug	1
com.apple.driver.AppleSEPHDCPManager	1.0.1
com.apple.iokit.AppleSEPGenericTransfer	1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.AppleThunderboltDPInAdapter	8.1.4
com.apple.driver.AppleThunderboltDPAdapterFamily	8.1.4
com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
com.apple.driver.AppleBTM	1.0.1
com.apple.driver.AppleDCPDPTXProxy	1.0.0
com.apple.driver.DCPDPFamilyProxy	1
com.apple.nke.ppp	1.9
com.apple.AGXFirmwareKextG13GRTBuddy	172.20.9
com.apple.AGXFirmwareKextRTBuddy64	172.20.9
com.apple.driver.AppleBSDKextStarter	3
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
com.apple.driver.AppleNANDConfigAccess	1.0.0
com.apple.driver.AppleSPU	1
com.apple.driver.AppleHPM	3.4.4
com.apple.driver.AppleCSEmbeddedAudio	437.96
com.apple.driver.AppleEmbeddedAudio	437.96
com.apple.iokit.AppleARMIISAudio	80.34
com.apple.driver.AppleStockholmControl	1.0.0
com.apple.driver.AppleDialogPMU	1.0.1
com.apple.driver.DCPAVFamilyProxy	1
com.apple.driver.ApplePassthroughPPM	3.0
com.apple.driver.AppleMCA2-T8103	510.72
com.apple.iokit.IOGPUFamily	20.9
com.apple.driver.AppleH11ANEInterface	4.51.0
com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
com.apple.driver.AppleDCP	1
com.apple.driver.AppleFirmwareKit	1
com.apple.iokit.IOMobileGraphicsFamily	343.0.0
com.apple.driver.AppleSPMI	1.0.1
com.apple.driver.AppleUSBXDCIARM	1.0
com.apple.driver.AppleUSBXDCI	1.0
com.apple.iokit.IOUSBDeviceFamily	2.0.0
com.apple.driver.usb.AppleUSBXHCIARM	1
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEmbeddedUSBHost	1
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleT8103TypeCPhy	1
com.apple.driver.AppleSART	1
com.apple.driver.ApplePMGR	1
com.apple.driver.watchdog	1
com.apple.driver.AppleDisplayCrossbar	1.0.0
com.apple.iokit.IODisplayPortFamily	1.0.0
com.apple.driver.AppleTypeCPhy	1
com.apple.driver.AppleThunderboltNHI	7.2.8
com.apple.driver.AppleT8103PCIeC	1
com.apple.iokit.IOThunderboltFamily	9.3.2
com.apple.driver.ApplePIODMA	1
com.apple.driver.AppleT8103PCIe	1
com.apple.driver.AppleMultiFunctionManager	1
com.apple.driver.AppleEmbeddedPCIE	1
com.apple.driver.AppleBluetoothDebugService	1
com.apple.driver.AppleBCMWLANCore	1.0.0
com.apple.iokit.IO80211FamilyV2	1200.12.2b1
com.apple.driver.IOImageLoader	1.0.0
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleGPIOICController	1.0.2
com.apple.driver.AppleFireStormErrorHandler	1
com.apple.driver.AppleMobileApNonce	1
com.apple.iokit.IOTimeSyncFamily	900.11
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOGraphicsFamily	585
com.apple.iokit.IOBluetoothFamily	8.0.1f5
com.apple.iokit.IOBluetoothPacketLogger	8.0.1f5
com.apple.driver.FairPlayIOKit	68.5.0
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSEPKeyStore	2
com.apple.driver.AppleUSBTDM	511.40.9
com.apple.iokit.IOUSBMassStorageDriver	184.40.6
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOSCSIBlockCommandsDevice	436.40.6
com.apple.iokit.IOSCSIArchitectureModelFamily	436.40.6
com.apple.driver.AppleIPAppender	1.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.RTBuddy	1.0.0
com.apple.driver.AppleEmbeddedTempSensor	1.0.0
com.apple.driver.AppleARMPMU	1.0
com.apple.iokit.IOAccessoryManager	1.0.0
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.AppleA7IOP	1.0.2
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleBiometricSensor	2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.AUC	1.0
com.apple.iokit.IOAVFamily	1.0.0
com.apple.iokit.IOHDCPFamily	1.0.0
com.apple.iokit.IOCECFamily	1
com.apple.iokit.IOAudio2Family	1.0
com.apple.driver.AppleEmbeddedAudioLibs	1.17
com.apple.driver.AppleFirmwareUpdateKext	1
com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
com.apple.iokit.IOSurface	289.3
com.apple.driver.IODARTFamily	1
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.kext.CoreTrust	1
com.apple.security.AppleImage4	3.0.0
com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
com.apple.driver.AppleARMPlatform	1.0.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOReportFamily	47
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1

** Stackshot Succeeded ** Bytes Traced 396497 (Uncompressed 987536) **

**Comment by alsomail** [comment]
ARM版本来自于[Native Apple Silicon support. #3067](https://github.com/iina/iina/issues/3067)

**Comment by HarukaMa** [comment]
@alsomail 看上去崩溃的地方是系统自己的 udf 文件系统驱动，问题很可能出在 iso 本身或者挂载流程上

**Comment by alsomail** [comment]
是的，我用vlc也复现了




    


在2021年01月28日 00:56，Haruka Ma 写道： 
@alsomail 看上去崩溃的地方是系统自己的 udf 文件系统驱动，问题很可能出在 iso 本身或者挂载流程上

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iina/iina/issues/3303#issuecomment-768424001",
"url": "https://github.com/iina/iina/issues/3303#issuecomment-768424001",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by a1049145827** [comment]
这个 bug 看起来提给苹果官方更合适一些

**Comment by WangEdward** [comment]
@alsomail 请问是红屏+触控板无反馈+系统重启吗，我也在放 iso 蓝光盘的时候遇到这个问题了

**Comment by alsomail** [comment]
对的 439873133 邮箱：439873133@qq.com 签名由 网易邮箱大师 定制 在2021年02月07日 21:50，Edward 写道： @alsomail 请问是红屏+触控板无反馈+系统重启吗，我也在放 iso 蓝光盘的时候遇到这个问题了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Jobsecond** [comment]
我也遇到了同样的问题。Finder里面挂载蓝光原盘ISO，用IINA打开蓝光根目录，系统死机重启。

**Comment by lhc70000** [comment]
Seems to be a driver problem. Closing this issue since it's not IINA's problem. (Please check if things changed in IINA 1.3.0: https://github.com/iina/iina/releases/tag/v1.3.0)
