### ISSUE TITLE
Did not find v1.2.0 via Check for update

### ISSUE THREAD

**Issue by henryhchchc** [iina/iina#3316]
**System and IINA version:**

- macOS 11.3
- IINA 1.1.2

**Expected behavior:**
A dialog pop up telling my that 1.2.0 update is available.

**Actual behavior:**
It told me that IINA is up to date.

<details>
<summary><b>Crash report:</b></summary>

```
It did not crash.
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
This is not related to mpv.
```
</details>

<br>

**Steps to reproduce:**
Click on the Check for Update menu.

- [ ] MPV does not have this problem.

**How often does this happen?**
Always since 1.2.0 is released.

**Comment by henryhchchc** [comment]
BTW, is 1.2.0 a stable release?

**Comment by henryhchchc** [comment]
> BTW, is 1.2.0 a stable release?

If so, I guess the cause is that, https://www.iina.io/appcast.xml is outdated, which also caused a build failure in https://github.com/Homebrew/homebrew-cask/pull/99432/.

**Comment by RobbieTT** [comment]
As I understand it 1.1.2 and 1.2.0 are the same, so aside from 1.2.0 being a Universal build for Apple Silicon then I am not sure I would expect it to show as an update for Intel Macs.

That said, it didn't offer it as an update for M1 Macs either.

Not missing much even on M1 Macs - it still uses more CPU than VLC (also Universal) and both are trounced by Apple QTP, if it is a supported file type that is.

[M1 Apple Silicon CPU Example - 4K HDR 10 MP4: IINA=23%, VLC=18%, QTP=7%]

**Comment by henryhchchc** [comment]
Thanks for the clarification. Is it considered like a "hidden" update? I mean, it won't be pushed unless the users explicitly download and install it?
