### ISSUE TITLE
Virtual Surround Sound

### ISSUE THREAD

**Issue by madhavtummala** [iina/iina#3325]
**What you want IINA to do:**
An option to turn on virtual surround sound to convert 5.1 / 7.1 supported videos to binaural audio consumable with standard headphones.

**What IINA does currently:**
IINA doesn't have this feature currently.

**Why you think this should be added:**
Virtual surround sound is creating a lot of buzz with the release of spacial audio by apple themselves. But their algorithms for converting 5.1 to binaural is only available in iOS and iPadOS. It would make more sense for such a system to be available on bigger screens like Macs and iMacs. There are several solutions to do this without using gyroscopes and accelerometers like apple does in iOS. IINA being the leading choice for a video player on Mac, would be the best place for this feature.

**Examples of other projects that have something similar:**
This feature is pretty rare to find in Macs, hence being first would benefit IINA. On Windows, several options are available like Windows Sonic, Dolby Access for Headphones. There exits a project called HeSuVi which consists of many equaliser settings need to mix 5.1/7.1 including the aforementioned solutions and many other notable ones like Razer surround. Even VLC on windows has an option to turn on headphone stereo surround, but on Mac this doesn't exist for some reason.

**Comment by orangesunny** [comment]
As this issue is closed, is there any solution?

**Comment by madhavtummala** [comment]
After this issue was raised, Apple has implemented spatial audio for macOS albeit only for the new M1 macs and only with Airpods Pro. If your content is multichannel and you play it through quicktime player or stream it through safari (ex: plex), you can turn on Spatial Audio, and its great!

IINA doesn't support this feature yet, and this issue is gaining traction: https://github.com/iina/iina/issues/3444

**Comment by mjbaldwin** [comment]
Just wanted to +1 this -- I had to stop using IINA and started using Infuse because it's the only Mac player that will output spatial audio on my M1 Mac with AirPods on my MKV files.

Would love it if IINA supported this.
