### ISSUE TITLE
Cannot Open youtube video after update to version 1.1.2

### ISSUE THREAD

**Issue by YuhaoT** [iina/iina#3337]
I recently just update iina to version 1.1.2 and suddenly it cannot load youtube playlist or youtube video. I tried to update my `youtube-dl`, but it doesn't solve the problem. Is there anything else that I can do?

**Comment by piratx** [comment]
I am having the same issue with the latest version of macOS 11.2.2 and IINA 1.1.2 (build 28). I always get the error "Cannot open file or stream!"
I've tried from the console forced the cli command and it's still the same error.

**Comment by JayBrown** [comment]
First remark: IINA is currently at v1.2.0.

I have symlinked `$HOME/Applications/IINA.app/Contents/MacOS/iina-cli` as `/usr/local/bin/iina` with an absolute path.

In Firefox (via the OpenWith extension) I execute: `/usr/local/bin/iina --no-stdin` (note: OpenWith will automatically add the URL as arguments)

In iTerm I can execute either `iina '<URL>'` or `iina --no-stdin '<URL>'`. Both work fine.

**Comment by piratx** [comment]
Haven't updated to 1.2.0 yet.

I have the same symlinks :)

<img width="695" alt="Screen Shot 2021-03-01 at 5 01 30 PM" src="https://user-images.githubusercontent.com/242366/109515636-fa2c3a00-7aaf-11eb-942a-6727d93136c6.png">

**Comment by JayBrown** [comment]
We had a similar issue here: https://github.com/iina/iina/issues/2086

One workaround before the fix was to install `expect` with Homebrew and execute:

`unbuffer -p /usr/local/bin/iina '<URL>'`
or
`unbuffer -p /Applications/IINA.app/Contents/MacOS/iina-cli '<URL>'`

But that was just a workaround for a non-interactive shell, which shouldn't be relevant for our case, i.e. executing it directly in iTerm/Terminal.

**Comment by JayBrown** [comment]
Uhm, I just checked the video from your screengrab, and the YouTube video is unavailable, so no wonder `iina` can't open it. ;D

**Comment by piratx** [comment]
What? :-P

It's working just fine here: https://www.youtube.com/watch?v=kqLYgzKKP0Q

**Comment by JayBrown** [comment]
Oh, right, sorry… TextSniper didn't get the ID correct: it had `00` instead of `0Q` at the end.

**Comment by piratx** [comment]
Software isn't always better than 👀

**Comment by YuhaoT** [comment]
I can open the youtube link after `brew upgrade iina`. Looks like there are some packages were out-dated. Thanks guys :)

**Comment by piratx** [comment]
@YuhaoT It worked with unbuffer or just iina-cli?
I have upgraded everything here but still its a no-go :(

Big Sur 11.2.2 and IINA last version.

**Comment by YuhaoT** [comment]
I'm not familiar with the shell command so I just use the iina app downloaded through homebrew. But the issue that cannot open Youtube link on app version 1.1.2 has been fixed.

**Comment by piratx** [comment]
Open URL from the app doesn't work either here :(

**Comment by a10software** [comment]
I'm on IINA 1.1.2 and I'm unable to open a YouTube video via the Safari Extension as well

**Comment by piratx** [comment]
Same error?

**Comment by a10software** [comment]
@piratx yes. Steps to repro: 
- Open any YouTube video
- Click on "Open in IINA" button on the Safari toolbar
- IINA launches and shows spinner with the correct YouTube link. "Opening stream..." with the spinner are shown.
- Error modal pops up: `Error: Cannot open file or stream!`

Environment: macOS Big Sur 11.2.2. Safari 14.0.3.

**Comment by piratx** [comment]
Yeap, same here! Have you tried the unbuffer solution?
https://github.com/iina/iina/issues/3337#issuecomment-788023690

**Comment by a10software** [comment]
I just tried that and it did not work for me unfortunately :( 

```zsh
$ brew install expect
==> Pouring expect-5.45.4_1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/expect/5.45.4_1: 49 files, 777.8KB

$ unbuffer -p /usr/local/bin/iina 'https://www.youtube.com/watch?v=2-TUIfpfjkM'
```

IINA opens up with the spinner. Same error "Cannot open file or stream!"

**Comment by piratx** [comment]
Ok, we have exactly the same problem.

**Comment by toto-minai** [comment]
I solve it by:

1. Upgrade `youtube-dl` and `iina` to the newest versions;
2. Copy the directory (**NOT** full path) from `which youtube-dl` to `Preference > Network > Custom youtube-dl path` field in IINA.app (like `/usr/local/bin/`).

BTW, if you want to execute `iina` with url in somewhere else, use the parametre `--no-stdin` like `iina --no-stdin $(pbpaste)`.

**Comment by a10software** [comment]
@toto-minai this solution worked for me! That makes me think the bundled `youtube-dl` library is just out of date.

**Comment by piratx** [comment]
YES! YES! It worked!! 🥇 
I had the full path instead of /usr/local/bin/

**Comment by cjamcu** [comment]
> I solve it by:
> 
> 1. Upgrade `youtube-dl` and `iina` to the newest versions;
> 2. Copy the directory (**NOT** full path) from `which youtube-dl` to `Preference > Network > Custom youtube-dl path` field in IINA.app (like `/usr/local/bin/`).
> 
> BTW, if you want to execute `iina` with url in somewhere else, use the parametre `--no-stdin` like `iina --no-stdin $(pbpaste)`.

YES! YES! It worked!!. Thanks 😊

**Comment by Write** [comment]
Kinda unrelated but finally got yt-dlp working with IINA.

```
brew install yt-dlp
ln -s /opt/homebrew/bin/yt-dlp /opt/homebrew/bin/youtube-dl
```

And finally add `/opt/homebrew/bin/` path in `Preference > Network > Custom youtube-dl path`

**Comment by YuhaoT** [comment]
If you cannot find the bin dir at`/opt/homebrew/`, try `/usr/local/bin`.
The approach is same for other `youtube-dl` forks and is described in #3180

**Comment by Tech6767** [comment]
Hello, I am having the seemingly same problem. I can play videos with MPV, but IINA doesn't play youtube links. I have also tried linking yt-dlp and setting it in the preferences, to no luck.
Am I the only one? I have set up SVP to work with IINA, but that shouldn't mess with youtube-dl, right?
