### ISSUE TITLE
Play state is not correctly reported to macOS

### ISSUE THREAD

**Issue by atirit** [iina/iina#3340]
**System and IINA version:**

- macOS 11.2.2
- IINA 1.1.2

**Expected behavior:**
IINA properly relays play state/media info to macOS.

**Actual behavior:**
IINA does not report play state/media info to macOS until a file is opened and then either scrubbed through or paused. After doing so, IINA will behave correctly until next launch. macOS' obliviousness is evidenced by the play/pause key on the keyboard/Touch Bar not pausing IINA and the Now Playing menu of the Menu Bar not showing IINA as playing any media.

<br>

**Steps to reproduce:**
1. Close/relaunch IINA.
2. Open a file.
3. Observe that macOS does not detect that IINA is playing media.

- [x] MPV does not have this problem.
_MPV has a different, but similar, problem. When run through the command line, MPV functions correctly. When opening a file with MPV in Finder, MPV never reports play state._

**How often does this happen?**
Whenever the above steps are followed.

**Comment by ybbond** [comment]
also happened to me on latest macOS and IINA (1.1.2 build 128)

**Comment by low-batt** [comment]
See my analysis posted in issue #3574

**Comment by low-batt** [comment]
The fix in PR #3579 has been merged into the develop branch.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.
