### ISSUE TITLE
macos 最近突然 CPU 占用特别高

### ISSUE THREAD

**Issue by zz5678** [iina/iina#3341]
macos 10.15.7
iina 1.1.2
Intel CPU
h264解码的本地文件，即便暂停后，Command + W关闭 IINA 后，CPU依然维持在 140%
相比mpv 0.33 播放，也就是 13% CPU 占用

Diagnostic Reports 在这里：
https://gist.github.com/zz5678/59444434fd9637b899c7a044ddd9da75/raw/9661f5ee8e88502b3e68c73cd9b212001e60b6a6/gistfile1.txt

**Comment by Tim2501** [comment]
同多次遇到这种情况。

**Comment by chamchenpion** [comment]
我也是升級到10.15.7後發現有這狀況，不過主要是在使用全螢幕模式才有這種狀況
不曉得您們是否也是在全螢幕模式下才有此問題？ 謝謝 :)

**Comment by low-batt** [comment]
以英语为母语的人使用翻译来发布此回复。 希望我的回答是可以理解的。 高CPU加上这个序列在发布的microstackshot:
```text
                  2   closure #2 in PlaylistViewController.tableView(_:viewFor:row:) + 1419 (IINA + 1253019) [0x1068f5e9b]
                    2   PlayerCore.refreshCachedVideoInfo(forVideoPath:) + 120 (IINA + 1389704) [0x106917488]
                      1   -[NSString(NSPathUtilities) fileSystemRepresentation] + 0 (Foundation + 51433) [0x7fff3700e8e9]
                        1   <User mode>
                      1   +[FFmpegController probeVideoInfoForFile:] + 53 (IINA + 16045) [0x1067c7ead]
```
是暗示问题#3162. 当尝试确定在播放列表面板中使用的视频的持续时间时，IINA未能正确处理错误。 处理错误失败会导致无限表视图重新加载循环。 这已经报告了播放列表中的文件别名以及HTML文件。 在这两种情况下，CPU使用率都很高。 这也可以由YouTube网址触发。 在这种情况下，有CPU和网络活动。 如果IINA无法显示播放列表中条目的持续时间，则表明此问题。

有关完整详细信息，请参阅问题#3162。

**Comment by low-batt** [comment]
PR #3477 中的修正已被合并到开发分支。

**Comment by low-batt** [comment]
关闭了。在IINA 1.3.0中修正。

Closing. Fixed in IINA 1.3.0.
