### ISSUE TITLE
video opens fine with mpv, fails with iina

### ISSUE THREAD

**Issue by nsklaus** [iina/iina#3348]
**System and IINA version:**

- macOS: 11.3 beta 3 (macbookpro M1)
- IINA: 1.2.0 build 129

**Expected behavior:**
odysee video should play

**Actual behavior:**
odysee video doesn't play

**Steps to reproduce:**
from terminal, using macport's mpv, this plays fine:
```
mpv "https://odysee.com/@Luke:7/the-war-against-web-bloat-continues...:a"
``` 
but from iina, open url, paste same address, i get:
```
error: can't open file or stream
```

to note: i'm not able to view any videos with iina from odysee on this particular channel.

**How often does this happen?**
everytime. mpv plays it fine, iina doesn't.

**Comment by nsklaus** [comment]
update: 
i made a mistake when i created this issue, i edited it to correct the error. i am *not* able to view videos from any channels on odysee with iina. `mpv [url]` plays fine, `open -a iina.app [url]` always fails.

**Comment by xjbeta** [comment]
`/Applications/IINA.app/Contents/MacOS/iina-cli "https://........"`

**Comment by nsklaus** [comment]
first, what you propose, is the same as `open -a some.app "https://....."`.
then, have you even tried it ? the result is the same. iina cannot open the video.
i provided a link to an odysee video, but you can try with any other odysee video. iina fails, mpv succeed.

**Comment by xjbeta** [comment]
If you need to use IINA in command line you need to use iina-cli instead of `open -a iina.app`.
This will provide more options.
`/Applications/IINA.app/Contents/MacOS/iina-cli --help`

IINA uses the built-in youtube-dl to open links to some websites, but the built-in youtube-dl may be out of date.

Modify the setting in IINA
`IINA - Preferences - network - custom youtube-dl path`

example:
1. `brew install youtube-dl`
2. `which youtube-dl`   output: `/usr/local/bin/youtube-dl`
3. `/usr/local/bin/`  ->  `custom youtube-dl path`

**Comment by nsklaus** [comment]
i use macport and not brew.  also, mpv uses youtube-dl too, and if mpv succeed, then it means my youtube-dl is good enough. 
```
$ which youtube-dl                                                                                                                         
/opt/local/bin/youtube-dl
[ MoltenVK ] 
$ youtube-dl --version  
2021.03.03
```

so even with this youtube-dl version, and your way of starting iina from shell, it still fails.
to be clear, i did: 
```
[ MoltenVK ] 
$ /Applications/IINA.app/Contents/MacOS/iina-cli "https://odysee.com/@Luke:7/the-war-against-web-bloat-continues...:a"
[ MoltenVK ] 
$ 
```
and that fails.
i think the problem is not from youtube-dl, but with videos from that particular channel.
i cannot view any video from that channel: `https://lbryfeed.melroy.org/channel/odysee/@Luke:7`
iina says: `error: can't open file or stream` but maybe the problem is elsewhere, maybe a codec problem or something.
just try it, any video from that channel, try with both mpv and iina and you'll see.

**Comment by nsklaus** [comment]
it's simple, try it:
```
[ MoltenVK ] 
$ mpv "https://odysee.com/@Luke:7/bitcoin-actually-explained:f"                                                                
2021-03-12 14:00:04.577 mpv[24611:3592364] This NSLayoutConstraint is being configured with a constant that exceeds internal limits.  A smaller value will be substituted, but this problem should be fixed. Break on BOOL _NSLayoutConstraintNumberExceedsLimit(void) to debug.  This will be logged only once.  This may break in the future.
 (+) Video --vid=1 (*) (h264 1920x1080 30.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
AO: [coreaudio] 44100Hz stereo 2ch floatp
VO: [libmpv] 1920x1080 yuv420p
AV: 00:00:01 / 00:07:48 (0%) A-V:  0.000 Cache: 7.2s/2MB

Exiting... (Quit)
[ MoltenVK ] 
$ open -a iina.app "https://odysee.com/@Luke:7/bitcoin-actually-explained:f"
[ MoltenVK ] 
$ 
```

**Comment by nsklaus** [comment]
ok, my problem was the options for youtube-dl i did set in iina and mpv differed:
in mpv i had:
`ytdl-format=bestvideo[height<=?720]+bestaudio/best`
in iina i had:
`format="bestvideo[height<=?720]+bestaudio/best[height<=?720]"`

i corrected iina's youtube-dl option to be:
`format="bestvideo[height<=?720]+bestaudio/best"`

and now it works. with my previous options iina tried to access unavailable formats.
sorry about that, thanks for the help.
