### ISSUE TITLE
Volume higher than 100%

### ISSUE THREAD

**Issue by TheSpyGorillas** [iina/iina#3367]
**What you want IINA to do:**To add volume above 100% like VLC

**What IINA does currently:**only limit is 100%

**Why you think this should be added:**i use more than 100% volume on VLC, I'm really interested in IINA, if this volume option is added I'll definitely switch fully. Its useful for when certain videos have a low source volume even at 100% so boosting that would be great

**Examples of other projects that have something similar:**VLC can raise volume above 100% using up arrow.

**Comment by TheSpyGorillas** [comment]
Never mind just found out we can do that in settings!

**Comment by manizm** [comment]
I can't find this in settings

**Comment by JamesMcMahon** [comment]
<img width="932" alt="image" src="https://github.com/user-attachments/assets/8025f02f-d55f-4bd8-95a4-ac7251558bb0" />
