### ISSUE TITLE
Spatial Audio Support

### ISSUE THREAD

**Issue by Joilence** [iina/iina#3377]
Is there any chance to make IINA support Apple [Spatial Audio](https://support.apple.com/en-us/HT211775)?

**Comment by Joilence** [comment]
Sorry, my bad. Currently, Spatial Audio is only supported by iOS / iPadOS devices.

**Comment by kuglee** [comment]
MacOS Monterey does support Spatial Audio now.

**Comment by thevenusbhatia** [comment]
any update?
