### ISSUE TITLE
Hotkeys for "go to 0/10/20...% progress" like on youtube player?

### ISSUE THREAD

**Issue by renox92** [iina/iina#3386]
On youtube if you hit numbers 0-9 you will jump to corresponding place in the video (beginning of the video for 0, 10% played for 1, middle of the video for 5 etc). Is there a way to set up IINA like that?

**Comment by utdrmac** [comment]
Jumping in here on similar note. I'm coming from mplayer extended. Pressing the up/down keys skipped the video forward/back by 1m (IIRC). I used this a lot but don't see it in iina. Some way to get this feature back?

**Comment by renox92** [comment]
Found what I needed: "Seek->to->X->%" or "seek X absolute-percent" for raw value.

>  Pressing the up/down keys skipped the video forward/back by 1m

Try creating binding for "Seek->forward/backward->60->s" or alternatively just enter an mpv command "seek 60" or "seek -60" for going backwards.
