### ISSUE TITLE
Hope change the icon of playlist, now is bad design

### ISSUE THREAD

**Issue by KyleBing** [iina/iina#3387]
**What you want IINA to do:**
change playlist icon on hover panel, it should be so recognizable that can recognize them at one sight.

**before**
![before](https://user-images.githubusercontent.com/12215982/114687275-2ccf8080-9d46-11eb-8460-879be54f6eeb.png)

**suggestion**
![Artboard Copy](https://user-images.githubusercontent.com/12215982/114688183-0eb65000-9d47-11eb-82af-457df3044cf4.png)

**What IINA does currently:**
The icon is so familiar.

**Why you think this should be added:**
Those two icons are so familiar, I have more than once can not recognize those at first sight.
Its icon should not with border, just the icon itself is good enough.

**Examples of other projects that have something similar:**

## Attachment
[iina - play panel - icon.sketch.zip](https://github.com/iina/iina/files/6309863/iina.-.play.panel.-.icon.sketch.zip)

**Comment by anohren** [comment]
**Thank you.** This is something that's been bugging me ever since those blurry, indistinct gray squares were introduced. 

What you've done is you've understood design and improved upon this immensely.
