### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by raghav4** [iina/iina#3388]
**What you want IINA to do:**
It would be nice if we could have custom keyboard shortcuts that we can configure to increase or decrease the playing speed, or we could configure it to rewind `x` seconds or forward `x` seconds.

**Examples of other projects that have something similar:**
Most of the mac apps now a days have Keyboard shortcuts

**Comment by Fujiwara-Chika** [comment]
https://mpv.io/manual/stable/
![image](https://user-images.githubusercontent.com/44722787/115244814-e2d80780-a156-11eb-88f0-0b20e33a8720.png)

**Comment by raghav4** [comment]
Thanks!
