### ISSUE TITLE
[bug]不知道是不是bug，在iina上播放加速时会出现少音的现象

### ISSUE THREAD

**Issue by secretandanon** [iina/iina#3391]
我发现用iina作为播放器加速播放时会出现少音的现象，具体实现如下
使用iina播放器2.14倍速播放一段英文音频，下面会提供
可以发现在整段音频中经常出现少音少音节的现象
而我用windows上的播放器potplayer / mpv以同样速度播放没有发现这样的问题。
 音频文件
[Inspector Logan《女督察洛根》Chapter 5.mp3.zip](https://github.com/iina/iina/files/6350574/Inspector.Logan.Chapter.5.mp3.zip)

**Comment by secretandanon** [comment]
希望开发者能将这个问题修复

**Comment by secretandanon** [comment]
我刚又测试了一下，苹果系统下的mpv也会出现这样的问题，我怀疑是否有macOS本身有关，如果之前有遇到的人可以讲一下

**Comment by secretandanon** [comment]
经过一番资料查询，我明白了，原来是音频滤镜的问题，iina自带的滤镜并不优质，自己在音频滤镜中添加mpv滤镜即可解决
名称scaletempo
值stride=8:overlap=1:search=10

**Comment by baodragon** [comment]
谢谢！帮了大忙
