### ISSUE TITLE
IINA lags when skipping forwards/backwards in macOS 12

### ISSUE THREAD

**Issue by jamesf-hub** [iina/iina#3422]
**System and IINA version:**

- macOS <!-macOS 12 -->
- IINA 1.2.0

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [no ] MPV does not have this problem.

**How often does this happen?**
very often

**Comment by LSiazsaHrd** [comment]
I only have this problem when I output sound through my airpods.

**Comment by Stanzilla** [comment]
Do you mean actual lag or a short freeze? Because I have freezes during normal playback which kinda reminds me of https://github.com/iina/iina/issues/1926

**Comment by pauldmps** [comment]
I have the same issue since upgrading to MacOS Monterey. And yes it happens only when audio is output to the AirPods.
