### ISSUE TITLE
Support macOS Reduce motion accessibility preference

### ISSUE THREAD

**Issue by low-batt** [iina/iina#3437]
**What you want IINA to do:**

Support the Apple Human Interface Guidelines on handling animation when the macOS System Preference Reduce motion is enabled.

Proper handling of the Reduce motion preference setting is covered in the [Apple Human Interface Guidelines under Appearance Effects and Motion](https://developer.apple.com/design/human-interface-guidelines/accessibility/overview/appearance-effects/).

The Reduce motion preference was added in iOS after new animations in iOS 7 induced cybersickness in a significant number of people. The preference was added to macOS in Sierra.

In the case of IINA sliding and zooming animations should be suppressed if Reduce motion has been enabled.

**What IINA does currently:**

IINA currently does not support this preference.

**Why you think this should be added:**

It is part of the Apple Human Interface Guidelines.

**Examples of other projects that have something similar:**

This support article for Discord discusses their support for this preference:
[Reduced Motion Setting](https://support.discord.com/hc/en-us/articles/360040613412-Reduced-Motion-Setting)

**Comment by low-batt** [comment]
The changes in the pull request suppress the zoom animation when transitioning to and from full screen mode and the sliding animation when showing and hiding the side bar when Reduce motion has been enabled.

I encountered one problem in implementing these changes. With animation suppressed `toggleFullScreen` did not restore the window to its previous size. Could this behavior be related to the "Loss of window size when switching to full screen and back" issue #3144? I added code to the `windowDidExitFullScreen` method to explicitly set the frame to `priorWindowedFrame` when animation is suppressed.

Thoughts? Critical reviews including criticism of style and naming are welcome.

**Comment by abh** [comment]
Thank you for doing this, @low-batt ! I'm looking forward to when it's released. I tried IINA again today and quickly realized why it was I never got into using it.

I know it seems weird for a video player to need this (videos are pretty universally full of motion!) but for my vestibular disorder most movies are fine, but just a moment of an animation like this in software or on websites can make me nauseous for hours.

**Comment by low-batt** [comment]
Thanks for the feedback. Nice to know someone appreciates this feature.

The change only addresses the two animations listed above. You will still see animations for transitioning to PiP and back for example. At the moment I need to stay focused on helping to get this next release out. Maybe in the future I will take another look at this and see if I can include some of the other animations.

For some reason the software industry pretty much ignores this issue. Quite a while back now a major Mac app removed their preference for disabling UI animations and then were rude and dismissive to users that asked for it to be restored.

With the rollout of computers in cars I was expecting the auto industry would ask the software industry about cybersickness as they would be worried about owners getting car sick. But I don't think that has happened.

When it comes to cybersickness it seems the software industry's focus is all on virtual reality. Maybe the software developers themselves threw up when they tested their VR goggles. There is definitely a recognition of this problem in the VR field. With several big companies working on AR and VR it will be interesting to see how they address the issue of cybersickness.

There is a good number of people who suffer from a mild form of cybersickness and don't know it. It causes them headaches after a day of computer use which they attribute to eye strain, which is a factor, but cybersickness also plays a role.

There is another group of people that ask for the ability to turn off certain animations. These are the go go go people who use a computer for work and have no patience for animations. One of the reasons for animations is to avoid "change blindness" where the user sits there waiting for the program to complete a task not noticing the screen has already been updated with the results. Animations slow this down and show the user what is happening. But this group of people would love it if the computer was blindingly fast. One example of the animations that drew the ire of this group was the extensive slow animations added to macOS when changing spaces.

If animations make you sick and you are a busy go go go person then you are really unhappy if you can't turn off certain animations as this means the computer is making you wait while it makes you sick.

Apple was forced to deal with this when they released iOS 7 with animations that made so many people sick that it was all over the news. That is the origin of the "Reduce motion" setting. That setting was eventually ported to macOS. However macOS has been going in the wrong direction. There used to be behind the scene properties that could be set to disable or speed up macOS animations. One by one support for these properties has disappeared with each new macOS release. Even though Apple explains this issue in  the [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/accessibility/overview/appearance-effects/) their own applications do not adhere to the HIG. I recently noticed Dictionary in Monterey has added a new sliding animation that wasn't there before. Given that behavior it is not a surprise that Dictionary does not contain an entry for "cybersickness".

**Comment by abh** [comment]
@low-batt hah, I can see we could easily have a good long rant together over coffee or beer! 🤣 

If you don't mind sharing your email address, then send me a note. My email address is pretty public (on https://askask.com/contact/ and elsewhere).

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.

**Comment by low-batt** [comment]
@abh And anyone else reading this old issue…

As of IINA 1.4.0-beta1 there is a new `Disable animations` setting in an `Accessibility` section at the bottom of the `UI` tab in IINA's settings. After upgrading from IINA 1.3.5 you will have to enable this setting to disable some of the animated transition effects that IINA previously disabled based on the macOS `Reduce motion` setting. You will still want to enable the macOS `Reduce motion` setting as that reduces some of the animations within IINA that are provided by AppKit.

This change is due to concerns being raised that in _fully eliminating_ some animations IINA was not adhering to the spirt of the macOS `Reduce motion` setting. With the macOS `Reduce motion` setting enabled and the IINA `Disable animations` setting _disabled_ IINA will fade in and out the side panel as specified in Apple's [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/accessibility/). With the IINA `Disable animations` setting enabled the side panel will quickly appear in place as in IINA 1.3.5.
