### ISSUE TITLE
M1 support without translation

### ISSUE THREAD

**Issue by electr1fy0** [iina/iina#3454]
Please add native Apple Silicon support

**Comment by vs40** [comment]
v1.2.0 works natively.
https://github.com/iina/iina/releases/tag/v1.2.0

**Comment by electr1fy0** [comment]
Thanks
I hope it makes into stable soon

**Comment by electr1fy0** [comment]
That's great!
Thanks for letting me know

**Comment by ThomasWaldmann** [comment]
Yup, 1.2.0 works natively on M1 mac.

Only strange:
- iina.io does not show 1.2.0 as latest release (yet)
- i first read that 1.2.0 is still beta and that one gets M1 support by switching to beta channel in preferences. THEN it offered 1.2.0 to me and i installed it.

Thanks for IINA!

**Comment by ThomasWaldmann** [comment]
close?

**Comment by imabhaysutar** [comment]
Why is 1.2.0 still min beta for so long? it should be pushed as many users switch to M1. 
Thanks.

**Comment by low-batt** [comment]
Closing. IINA 1.3.0 has been released with native support for M1.
