### ISSUE TITLE
Unlabeled trailing closure build warnings

### ISSUE THREAD

**Issue by low-batt** [iina/iina#3466]
**System and IINA version:**

- macOS 11.4
- IINA 1.2.0

**Expected behavior:**

IINA build does not report warnings

**Actual behavior:**

Xcode 12.5 is reporting the following Swift compiler warning:
```text
Backward matching of the unlabeled trailing closure is deprecated; label the argument with  'a parameter name' to suppress this warning
```

This has to do with the implementation of the following change in version 5.3 of the Swift programing language:
[Forward-scan matching for trailing closures](https://github.com/apple/swift-evolution/blob/master/proposals/0286-forward-scan-trailing-closures.md)

I will shortly post a pull request with the source changes required to label the closure arguments and eliminate these build warnings.

**Steps to reproduce:**

Build IINA using Xcode 12.5

**How often does this happen?**

Every build

**Comment by saagarjha** [comment]
Closing because the associated PR is merged, but feel free to reopen if you think it should be.
