### ISSUE TITLE
App info missing copyright

### ISSUE THREAD

**Issue by low-batt** [iina/iina#3470]
**System and IINA version:**

- macOS 10.15.7
- IINA 1.1.2

**Expected behavior:**

Right clicking on an app and selecting 'Get Info' or clicking on the app and pressing 'Control i' brings up the application info window which should show a copyright for the application like this output from the Apple Maps application:
```text
Copyright © 2012-2019
Apple Inc.
All rights reserved.
```

**Actual behavior:**

In the app info window for the IINA app the value for the copyright is missing the copyright, it only contains licensing information:

<img width="377" alt="IINA Get Info" src="https://user-images.githubusercontent.com/86170219/127797531-aec266f0-ffb1-4957-bd59-96e9e53c81bb.png">

I will submit a pull request shortly with changes to update the copyright displayed in the about window to reflect 2021 and add the copyright to the app info window.

**Comment by low-batt** [comment]
The changes in the pull request add the copyright to the app info window:

![Updated Info Window](https://user-images.githubusercontent.com/86170219/127798474-7e8560e7-4dd5-4aba-90e2-c8df1de17771.png)

And update the copyright in the about window to use the copyright symbol and reflect 2021:

![Updated About Window](https://user-images.githubusercontent.com/86170219/127798491-2ff8f6ad-6018-41f1-a3e7-095a46e1331a.png)

**Comment by saagarjha** [comment]
Closing as the associated PR is merged.
