### ISSUE TITLE
IINA Video Player - How to export subtitles downloaded via the player?

### ISSUE THREAD

**Issue by phattrance** [iina/iina#3492]
Is it possible? Im not able to see any files on my drive when downloading subtitles from the IINA player. Are the subtitles stored anywhere locally?

**Comment by low-batt** [comment]
![Subtitles-menu](https://user-images.githubusercontent.com/86170219/132255536-b767006c-6f09-4d73-9b8b-4282cfde6cc4.jpg)

**Comment by rejetto** [comment]
shouldn't this be closed?

**Comment by low-batt** [comment]
I've labeled this as a question and I'm closing it as answered.

I believe there are a number of open issues that could be closed. Been too busy to review and cleanup the state of open issues. Thanks for pointing this one out.
