### ISSUE TITLE
Script parse_doc.rb, MPVProperty fails to compile

### ISSUE THREAD

**Issue by low-batt** [iina/iina#3494]
Currently, running `other/parse_doc.rb` generates a `MPVProperty.swift` file containing this invalid code:
```swift
  /** current-tracks/... */
  static let currentTracks... = "current-tracks/..."
```

**System and IINA version:**

- macOS 11.4
- IINA 1.2.0
**Expected behavior:**

The script `parse_doc.rb` generates Swift code that successfully compiles.

**Actual behavior:**

IINA fails to build reporting:
```text
/Users/low-batt/Documents/builds/iina/iina/iina/MPVProperty.swift:453:27: error: consecutive declarations on a line must be separated by ';'
  static let currentTracks... = "current-tracks/..."
                          ^
                          ;
/Users/low-batt/Documents/builds/iina/iina/iina/MPVProperty.swift:453:27: error: expected declaration
  static let currentTracks... = "current-tracks/..."
                          ^
/Users/low-batt/Documents/builds/iina/iina/iina/MPVProperty.swift:3:8: note: in declaration of 'MPVProperty'
struct MPVProperty {
       ^
/Users/low-batt/Documents/builds/iina/iina/iina/MPVProperty.swift:453:14: error: type annotation missing in pattern
  static let currentTracks... = "current-tracks/..."
```

**Steps to reproduce:**

Just run `parse_doc.rb` and try and compile the generated sources.

- [ x] MPV does not have this problem.

**How often does this happen?**

Everytime.

I will submit a pull request with a fix to the script shortly.

**Comment by low-batt** [comment]
The failure is due to mpv adding this option:
```text
current-tracks/...

    This gives access to currently selected tracks. It redirects to the correct entry in track-list.

    The following sub-entries are defined: video, audio, sub, sub2

    For example, current-tracks/audio/lang returns the current audio track's language field (the same value as track-list/N/lang).

    A sub-entry is accessible only if a track of that type is actually selected. Tracks selected via --lavfi-complex never appear under this property. current-tracks and current-tracks/ are currently not accessible, and will not return anything.

    Scripts etc. should not use this. They should use track-list, loop over all tracks, and inspect the selected field to test whether a track is selected (or compare the id field to the video / audio etc. options).
```

The documentation for `current-tracks` deviates from how other mpv path style properties are documented, confusing the script and causing it to generate invalid code.

Since the documentation says "**Scripts etc. should not use this**" the commit in the pull request updates the script to treat `current-tracks` as a special case and only add a comment to `MPVProperty` that indicates why a constant wasn't generated for it:
```swift
 /** current-tracks/...  As per mpv doc, scripts etc. should not use this. */
```

**Comment by saagarjha** [comment]
Closing with the associated PR.
