### ISSUE TITLE
Xcode warns libmujs.so was not built for 10.11

### ISSUE THREAD

**Issue by low-batt** [iina/iina#3496]
**System and IINA version:**

- macOS 11.4
- IINA 1.2.0

**Expected behavior:**

All dependencies have been built to support macOS 10.11 and above.

**Actual behavior:**

Under macOS 11.4 and Xcode 12.5 the build contains this warning for  `libmujs.so` when dependencies have been downloaded using `other/download_libs.sh`:
```text
ld: warning: dylib (/Users/low-batt/Documents/builds/iina/iina/deps/lib/libmujs.so) was built for newer macOS version (11.0) than being linked (10.11)
```

As if `MACOSX_DEPLOYMENT_TARGET` was not set to 10.11 when this library was built.

**Steps to reproduce:**

Use `other/download_libs.sh` to obtain the dependencies required to build. Build IINA under Xcode. Look for the above warning.

- [x] MPV does not have this problem.

**How often does this happen?**

Everytime.

**Comment by haha1903** [comment]
I also had the same problem.

**Comment by haha1903** [comment]
You should move the folder iina/other/deps/lib to iina/deps/lib.

**Comment by low-batt** [comment]
Since entering this defect I have upgraded my development system. I am now using a MacBook Pro with the M1 chip. I'm running macOS 12.3.1 and building with Xcode 13.3.

I updated to the latest code in the develop branch. Deleted `deps/lib`. And downloaded the libraries again: 
```bash
low-batt@gag iina (develop $=)$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
low-batt@gag iina (develop $=)$ ls deps/
executable	include
low-batt@gag iina (develop $=)$ ./other/download_libs.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1011  100  1011    0     0   1905      0 --:--:-- --:--:-- --:--:--  1944
+ curl https://iina.io/dylibs/universal/libarchive.13.dylib
...
```

I ran `Clean Build Folder` in Xcode followed by `Build` (native for M1) and...
```text
ld: warning: dylib (/Users/low-batt/Documents/builds/iina/iina/deps/lib/libmpv.1.dylib) was built for newer macOS version (11.1) than being linked (11.0)
```

So there are still problems in this area.

**Comment by low-batt** [comment]
Closing. This was fixed during the upgrade of dependencies for the 1.3.0 release.
