### ISSUE TITLE
Downmix AAC 5.1 audio to Stereo like VLC

### ISSUE THREAD

**Issue by byGits** [iina/iina#3517]
Hi guys, most of the videos are currently in AAC 5.1, VLC Player already has an option to downmix them to Stereo and it works perfectly, that is the only reason I still use VLC instead of IINA (which IMO is much better than VLC)

No option to play 5.1 audio as stereo, audio is just so faint with those videos.

An option to play 5.1 audio as stereo.

VLC Media Player > Audio Menu > Stereo Audio Mode

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#options-ad-lavc-downmix
https://mpv.io/manual/master/#options-audio-channels

**Comment by byGits** [comment]
> https://mpv.io/manual/master/#options-ad-lavc-downmix https://mpv.io/manual/master/#options-audio-channels

Thanks, You mean there is currently a solution?

VLC does it live while playing the video, it's not required to convert the audio before playing

Is this the same? mind sharing a bit more info about how to use it in IINA?
