### ISSUE TITLE
在big sur 11.6系统上使用最新版IINA播放、暂停、快进MP4视频会卡顿，出现旋转的彩虹球

### ISSUE THREAD

**Issue by zhaoquntao** [iina/iina#3522]
在big sur 11.6系统上 AirPods2 连接蓝牙    使用最新版IINA播放、暂停、快进MP4视频会卡顿，出现旋转的彩虹球, 使用MacPro外放 恢复正常 联系水果客服 他们说目前没有碰到这种情况.

**Comment by petrel1024** [comment]
+1

**Comment by zhaoquntao** [comment]
It is normal to use other players (such as Youku).

**Comment by huangjiahua** [comment]
I'm getting this problem after upgrading to macOS 12.0.1

**Comment by zhaoquntao** [comment]
刚刚更新了 系统12.0.1 发现还是这个样子 快进就转圈

**Comment by lhc70000** [comment]
Could anyone provide a sample video? I can't reproduce any mentioned freeze/crash issues such as #3400.

**Comment by huangjiahua** [comment]
I found that I only met the problem when playing with my AirPods or other bluetooth audio connected. Other players like VLC doesn't have that problem. I'll record a video when I have a chance

**Comment by flyoverGu** [comment]
+1 用蓝牙耳机就卡了。 断开就正常

**Comment by l8higher** [comment]
> 就

确实是这样，有无解决方案啊？

**Comment by l8higher** [comment]
> +1 用蓝牙耳机就卡了。 断开就正常

确实是这样，有无解决方案啊？

**Comment by zhaoquntao** [comment]
目前 解决方案 是 只能换其他 播放器 比如 MPV 就可以实现快进快退 😁

**Comment by kisexu** [comment]
系统版本：macOS Ventura 13.2.1 
软件版本：1.3.1 Build 133

仍然有这个问题，连接蓝牙耳机后快进快退卡顿。直接用mpv不卡。
