### ISSUE TITLE
Add HDR support for M1 Pro/Max Macbook 14/16

### ISSUE THREAD

**Issue by kvell36** [iina/iina#3526]
**Support HDR playback on MacBook Pro 14 and 16" with miniLED displays:**

**What IINA does currently:** Currently iina tonemaps HDR content to SDR colorspace, ignoring the fact that these are HDR screens. 

**Why you think this should be added:** The new machines have amazing screens and iina is not taking advantage of them. The experience for content consumption would be vastly improved if the brightness and contrast improvements are taken advantage of.

**Examples of other projects that have something similar:** macOS built in preview, Final Cut Pro, and Quicktime all support these displays, allowing for an immense improvement in brightness, color and contrast. However they do not support the formats that iina does, so if iina can just add HDR output to these displays, it would be the ultimate video player for Apple's new laptops.

**Comment by pyed** [comment]
On top of QuickTime's excellent picture, playing the demo video file that @kvell36 provided uses only ~8% of the CPU, whereas IINA uses ~38% (M1 Pro 10 Cores) that's 475% increase!

**Comment by wyq977** [comment]
I think this is a issue more to do with mpv upstream like Dolby Vision and mpv's tone mapping algorithm

**Comment by Tim2501** [comment]
> I think this is a issue more to do with mpv upstream like Dolby Vision and mpv's tone mapping algorithm

It's finished

https://github.com/mpv-player/mpv/pull/8485

https://github.com/Akemi/mpv/tree/mac_layer_colorspace

**Comment by wyq977** [comment]
i guess its just well tested and not in the latest release of mpv not to mention that iina ships with its set of mpv tho u can change that in the setting, but infuse out of all supports better for DV, HDR content. Not sure since havent checked for a while.

**Comment by Akemi** [comment]
like i said on the PR. this has nothing to do with mpv supporting it. iina has to that itself, since iina is the one handling the layer.

**Comment by CarterLi** [comment]
I have made a basic implementation. Test my PR please, any feedbacks are welcome

https://github.com/iina/iina/pull/3539

**Comment by ReeganExE** [comment]
[IINA Plus fork](https://github.com/iina-plus/iina) already supported HDR.
![image](https://user-images.githubusercontent.com/7277418/155008392-872abbb9-1ded-498f-92ec-9a81a3977634.png)

**Comment by Ellypsis63** [comment]
How do you install this? there is zero instructions

**Comment by xfoxfu** [comment]
@Ellypsis63 Just to go for the releases page and grab dmg for installation in assets.

**Comment by Ellypsis63** [comment]
@xfoxfu i'm talking about iina+ for HDR

**Comment by xfoxfu** [comment]
@Ellypsis63 Sorry for misunderstanding. Go to [GitHub Actions](https://github.com/iina-plus/iina/actions), find a latest build and then go for *Artifacts* to download the corresponding arch file.

![](https://vip2.loli.io/2022/02/27/ZHc7dYvA5BgioKL.jpg)

**Comment by Ellypsis63** [comment]
Thanks mate

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.
