### ISSUE TITLE
Is IINA project dead? 

### ISSUE THREAD

**Issue by MariuzM** [iina/iina#3536]
Not seeing any new updates just thinking is it dead?

**Comment by hnewcity** [comment]
+1

**Comment by xjbeta** [comment]
Some news
https://twitter.com/lhc70000/status/1456805063133859846

**Comment by dmattera** [comment]
> Some news https://twitter.com/lhc70000/status/1456805063133859846

this is great and all but man, I kinda wish bug fixes and pending PRs would be prioritized over new feature developments....

**Comment by low-batt** [comment]
Closing. IINA 1.3.0 has been released.

IINA 1.3.0 can be downloaded from the official [IINA](https://iina.io/) website.
