### ISSUE TITLE
The ani-cli application works with mpv but not iina

### ISSUE THREAD

**Issue by tennyson-mccalla** [iina/iina#3571]
**System and IINA version:**

- macOS  12.0.1
- IINA  1.2.0

**Expected behavior:**

That it could work as a drop in replacement for mpv by editing the line in ani-cli:
`player_fn="mpv"` to be `player_fn="iina"`

**Actual behavior:**
While iina opens it fails to actually play the video.
<img width="372" alt="Screen Shot 2021-12-11 at 12 23 40" src="https://user-images.githubusercontent.com/14319110/145686521-cfaa5465-4ea7-441d-9038-14ee034b7419.png">

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

1. Get ani-cli
2. Follow the example in the "expected behavior" section above to replace mpv with iina.
3. Run ani-cli

- [x] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by lhaeger** [comment]
Did you try with `/Applications/IINA.app/Contents/MacOS/iina-cli `as well? It's supposed to take all command line options, mpv supports...

**Comment by tennyson-mccalla** [comment]
I did. Same results iirc. I’ll try again though.

**Comment by tennyson-mccalla** [comment]
Finally had time to retry this. Same failures. My "iina" is just a softlink to /Applications/IINA.app/Contents/MacOS/iina-cli anyway. Opening with /Applications/IINA.app/Contents/MacOS/IINA also doesn't work.

**Comment by tennyson-mccalla** [comment]
Resolved!
https://github.com/pystardust/ani-cli/issues/254
