### ISSUE TITLE
adjust the position of secondary subtitle instead of pinning at the top

### ISSUE THREAD

**Issue by weiyanle** [iina/iina#3580]
**What you want IINA to do:** adjust the position of secondary subtitle

**What IINA does currently:** display the secondary subtitle on the top of the window. 我在preferences和subtitle的settings里面都没找到能改动的选项

**Why you think this should be added:** make it easier to see the secondary subtitle

**Examples of other projects that have something similar:**

**Comment by hooke007** [comment]
iina目前的次字幕实现用的是mpv自带的 https://mpv.io/manual/master/#options-secondary-sid
所以功能受限于上游

**Comment by hooke007** [comment]
dup https://github.com/iina/iina/issues/2589

**Comment by weiyanle** [comment]
ok
