### ISSUE TITLE
Plugin: main entry setTimeout/setInterval not working

### ISSUE THREAD

**Issue by qinyuhang** [iina/iina#3603]
**System and IINA version:**

- macOS 12.1 (21C52)
- IINA 1.2.0 (build from plugin-system branch)

**Expected behavior:**
In plugin entry js file, setTimeout or setInterval works.

etc:
```
// code block 1
setTimeout(function() {
  console.log(1)
}, 1000)
```

code block 1 should print 1 after 1 second

**Actual behavior:**

it dose nothing.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
1 checkout to system-plugin branch
2 build and run
3 load a dev-plugin
4 use Safari dev tool to open an inspector of Main entry
5 past code block 1 into the inspector's `console` tab

- [ ] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by lhc70000** [comment]
See #3604.
