### ISSUE TITLE
最新版youtube-dl仍无法使用url或chrome插件打开youtube视频

### ISSUE THREAD

**Issue by JarringBye** [iina/iina#3609]
使用最新版youtube-dl 并且路径已经设置正确
可以观看bilibili的网页视频但是始终打不开YouTube的
是否是youtube的问题

**Comment by singkia** [comment]
> 

请问，设置代理之之后，已经能成功看youtube，但是加载每秒只有50kb左右，您知道怎么解决吗？、
正常有浏览器打开youtube，速度能到1mb以上。
在win上使用potplay也没遇见过卡顿的情况。

**Comment by lhc70000** [comment]
youtube-dl 现在不太能用了。IINA 1.3.0 换用了 yt-dlp，在等镜像站更新，所以暂时还没有推送，可以先从官网或者 GitHub 下载。
