### ISSUE TITLE
IINA hasn't had an official update in almost a year, why is that?

### ISSUE THREAD

**Issue by lukerooneyio** [iina/iina#3610]
I see there's been plenty of fulfilled pull requests since February but there hasn't been a new beta version. 

Is there any reason for this?

**Comment by meatyalien** [comment]
I was just thinking the same thing. It appears that the project may have been abandoned at this point. Luckily, I just ran across a forked repository that has a developer who has taken it upon himself to continue development. He's already added new features (like HDR playback) and lots of bug fixes.

The developer is calling it IINA+. Here's the forked repository for it: [https://github.com/iina-plus/iina](https://github.com/iina-plus/iina)

**Comment by LouieMjr** [comment]
> I was just thinking the same thing. It appears that the project may have been abandoned at this point. Luckily, I just ran across a forked repository that has a developer who has taken it upon himself to continue development. He's already added new features (like HDR playback) and lots of bug fixes.
> 
> The developer is calling it IINA+. Here's the forked repository for it: https://github.com/iina-plus/iina

How do I install this on my system?

**Comment by meatyalien** [comment]
> > I was just thinking the same thing. It appears that the project may have been abandoned at this point. Luckily, I just ran across a forked repository that has a developer who has taken it upon himself to continue development. He's already added new features (like HDR playback) and lots of bug fixes.
> > The developer is calling it IINA+. Here's the forked repository for it: https://github.com/iina-plus/iina
> 
> How do I install this on my system?

There are two links for binaries are at the bottom of the page, one for Intel and one for M1. Select the one that matches your computer's processor architecture and then you just download the latest DMG file and install it like any other application. This version will replace whatever version you currently have installed. You don't have to uninstall your current version first.

**Something to note:** This forked version of IINA is not currently using the built in updater, so you'll have to manually update it by downloading/installing the latest DMG whenever there's an update posted on the repository.

**Comment by low-batt** [comment]
The answer to the question the issue asks is:
IINA relies upon volunteers. When volunteers spare time is devoured by job or schoolwork progress on open source projects slows to turtle speed.

Not abandoned, just super slow progress.

Over on Telegram the developers have been discussing a new release. Initial steps are:

- Get the develop branch building and working under the latest Xcode. This has been done.
- Review and merge outstanding PRs related to stability (crashes / hangs). This is in progress.
- Update dependencies to latest versions. I've not checked on where this is at.

You can see this work happening. Click on "code" and then click on "commits". That shows the code changes being merged into the develop branch. You will see a bunch of activity in December. The holidays have disrupted things. Hopefully people will have time to startup reviews and merging again soon.

IINA+ has a lot of the changes proposed for the next official release. Definitely try it out and report any regressions you encounter.

**Comment by nfwyst** [comment]
The project has no maintainer, I think

**Comment by LouieMjr** [comment]
> The answer to the question the issue asks is: IINA relies upon volunteers. When volunteers spare time is devoured by job or schoolwork progress on open source projects slows to turtle speed.
> 
> Not abandoned, just super slow progress.
> 
> Over on Telegram the developers have been discussing a new release. Initial steps are:
> 
> * Get the develop branch building and working under the latest Xcode. This has been done.
> * Review and merge outstanding PRs related to stability (crashes / hangs). This is in progress.
> * Update dependencies to latest versions. I've not checked on where this is at.
> 
> You can see this work happening. Click on "code" and then click on "commits". That shows the code changes being merged into the develop branch. You will see a bunch of activity in December. The holidays have disrupted things. Hopefully people will have time to startup reviews and merging again soon.
> 
> IINA+ has a lot of the changes proposed for the next official release. Definitely try it out and report any regressions you encounter.

Im currently using IINA+ but I cant seem to get the safari extension to work. It doesn't appear anywhere. Would you have any idea about this?

**Comment by saagarjha** [comment]
You'll probably have better luck if you reported issues with IINA+ directly to them, rather than in an IINA issue specifically asking about its future.

**Comment by pleasejustgo** [comment]
> The answer to the question the issue asks is: IINA relies upon volunteers. When volunteers spare time is devoured by job or schoolwork progress on open source projects slows to turtle speed.
> 
> Not abandoned, just super slow progress.
> 
> Over on Telegram the developers have been discussing a new release. Initial steps are:
> 
>     * Get the develop branch building and working under the latest Xcode. This has been done.
> 
>     * Review and merge outstanding PRs related to stability (crashes / hangs). This is in progress.
> 
>     * Update dependencies to latest versions. I've not checked on where this is at.
> 
> 
> You can see this work happening. Click on "code" and then click on "commits". That shows the code changes being merged into the develop branch. You will see a bunch of activity in December. The holidays have disrupted things. Hopefully people will have time to startup reviews and merging again soon.
> 
> IINA+ has a lot of the changes proposed for the next official release. Definitely try it out and report any regressions you encounter.


dude, you are an amazing programmer. You're a beast. I wish I could msg you directly, I don't know how to on here but I just wanted to ask, if you have more time, maybe you could contribute to OpenEMU, a macOS multi-emulator. They have some issues that seem unsolvable for a while.

**Comment by low-batt** [comment]
Thanks for the vote of confidence.

Of course the real evaluation of my contributions to IINA is occurring right now as my submissions are being peer reviewed. All IINA users should be appreciative of the time the core developers are spending reviewing my proposed changes. Reviewing code is a tedious thankless job. The reviews are identifying the expected newbie issues. I am very appreciative of the critical comments I'm receiving in the reviews. The reviews are definitely improving my submissions. 

For those of you who don't know about software engineering, the industry works very hard to hide a vast amount of complexity from you. Us software engineers also try to make programming simpler and easier for ourselves. Sometimes it works out and programming is quick and easy and fun. Other times is it extremely time consuming and stressful as you try and figure out what could possibly be causing a problem. It is like puzzle solving where you get stuck and are simply at a loss as to how to proceed.

These days most software engineers are totally overloaded. The industry has moved to management techniques that put engineers under constant non-stop deadlines. I too have constraints on my time and I'm neglecting things to focus on IINA work. Eventually that will become a problem, but at this time I am committed to helping our overloaded excellent core developers prepare the next IINA release.

On the request for help with OpenEMU. You did get me to take a look at that project. And I did take a peek at the open issues. That project does need help. Unfortunately I am definitely overloaded. My plan is to help get the next IINA release out and then collapse from exhaustion. Sorry. I can't help with OpenEMU.

**Comment by XhstormR** [comment]
Hope the new version will come soon

**Comment by low-batt** [comment]
Can't say when it will come out, but code reviews and merging are in progress.
A couple of my proposed fixes were just merged into develop.
I posted another proposed fix a short time ago.

**Comment by nfwyst** [comment]
hope this project is still alive

**Comment by low-batt** [comment]
Closing. IINA 1.3.0 has been released.

IINA 1.3.0 can be downloaded from the official [IINA](https://iina.io/) website.
