### ISSUE TITLE
File Loop menu item does not show ✔︎ when toggled on

### ISSUE THREAD

**Issue by vassudanagunta** [iina/iina#3625]
**System and IINA version:**

- macOS 12.1
- IINA 1.2.0 build 129

**Expected behavior:**

When File Loop playback mode is enabled, the `File Loop` menu item should have a ✔︎ to show that it is `on` -- just like `Playlist Loop` menu item.

**Actual behavior:**
No ✔︎ ever appears.

**Comment by low-batt** [comment]
Reproduced for me. This is a defect. 

IINA code is treating the mpv `loop-file` property as a boolean flag. It is not a boolean. That is the source of these problems. This is the definition of the property from the mpv manual:
> **--loop-file=<N|inf|no>, --loop=<N|inf|no>**
>  &nbsp;&nbsp;&nbsp;Loop a single file N times. inf means forever, no means normal playback.

@CarterLi has a fix for this. He is currently away. I will coordinate with him when he gets back.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.
