### ISSUE TITLE
frame by frame? 

### ISSUE THREAD

**Issue by gartha1** [iina/iina#3654]
Hi

Is there a frame by frame option?

If not then perhaps it'd be worth implementing?  

Some media players have it e.g. Windows Media Player Classic   ctrl+left  ctrl+right    if you hold ctrl and tap right then it goes forward a frame.. If you hold control and with control down, hold right , then it goes slow mo forward.   Should ideally be the same for ctrl+left..

That kind of frame by frame option would be good in IINA.

It's useful too for analysing sports videos to look at techniques in that sport.

Thanks

**Comment by saagarjha** [comment]
It's under the Playback menu. The default keybindings for it are ⌥← and ⌥→.
<img width="283" alt="Screen Shot 2022-03-07 at 05 13 11" src="https://user-images.githubusercontent.com/13786931/157041058-007c4a94-3662-4ec5-8003-24ef8f992822.png">

**Comment by gartha1** [comment]
I seem to be missing that option!
![iina1](https://user-images.githubusercontent.com/12636021/157043592-7baffc92-243a-45fe-b390-167d3747ba7c.jpg)
