### ISSUE TITLE
[Feature Request] Play/resume media from the welcome window via menu and keyboard

### ISSUE THREAD

**Issue by veloxo** [iina/iina#3669]
**What you want IINA to do:**

In the **welcome window,** enable the "Resume" action under "Playback" in the menu bar, and accordingly any `cycle pause` or other `play`-like key bindings,  to _open-and-resume_ the highlighted media item at the top of the recent-media list.

It may be sensible to enable similar actions like "Next Media"/"Previous Media", too.

**What IINA does currently:**

AFAICT, in the welcome window (_Preferences > General > Behavior > At launch: "Show welcome window"_), there is no menu-bar action or keyboard shortcut to play/resume the highlighted media item. Only cursor-clicking the item will resume it.

Note that the `up` and `down` keys will play next/previous media items from the welcome window. This seems like the equivalent of an *open-and-next/previous-media* action.

**Why you think this should be added:**

This would extend keyboard-driven operation to application startup and help enable automation via AppleScript, MacOS Shortcuts, BetterTouchTool, etc. (Personally, I'm trying to configure a remote-control button that launches IINA and resumes the last-watched video.)

Thanks!

**Comment by svobs** [comment]
It does look like keyboard navigation is missing from the Welcome screen. Actually there seems to be a bug in which pressing either the UP or DOWN arrows resumes playback of the last video (doesn't matter what key bindings are set). You might be able to use either of those in your script for now ;)

It would be good if at a minimum, pressing ENTER on the Welcome screen resumes playback of the last video. Even better would be for the UP / DOWN / TAB keys to change the highlighted item, with ENTER resuming whatever item is highlighted.

**Comment by veloxo** [comment]
>It would be good if at a minimum, pressing ENTER on the Welcome screen resumes playback of the last video

Agreed, this would be the most straightforward solution!

>pressing either the UP or DOWN arrows resumes playback of the last video

To clarify: AFAICT in v1.2.0, when there's several items in the Welcome-Screen playback history, `UP` or `DOWN` start playing the earliest or latest item in the history list _below_ the highlighted/most-recent/partially-watched item. A simple "resume highlighted item" command seems to be unavailable.

>Even better would be for the UP / DOWN / TAB keys to change the highlighted item, with ENTER resuming whatever item is highlighted.

Makes sense to me (a random user), as it would allow navigation to any item in history.

**Comment by low-batt** [comment]
The implementation of this enhancement in PR #3739 has been merged into the develop branch.

**Comment by svobs** [comment]
@veloxo IINA 1.3.0 now has this feature 👍  This issue should be considered de facto closed.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.

@svobs yes, I am in the process of closing the issues addressed by 1.3.0, which includes this one.

**Comment by veloxo** [comment]
Thanks, everyone!
