### ISSUE TITLE
Enable use of macOS media keys to control playback

### ISSUE THREAD

**Issue by davidgenesiscruz** [iina/iina#3681]
**What you want IINA to do:**
Have IINA support playback control using media keys on the keyboard for macOS.

**What IINA does currently:**
IINA currently ignores the media keys.

**Why you think this should be added:**
I realize that there are keyboard shortcuts to control playback on IINA, but this would only work if the player is in the foreground.
Support for playback control native to the OS would allow me to control playback while working on other apps.

**Examples of other projects that have something similar:**
- [Spotify](https://github.com/spotify) (sorry, I don't know the relevant repository)
- [Brave Browser](https://github.com/brave/brave-browser)

**Comment by low-batt** [comment]
IINA supports use of media keys already, it is just that this feature stopped working in macOS Big Sur and is still broken in Monterey. See issue #3574 for a full discussion of the problem.

This is fixed in PR #3579 which is waiting to be reviewed and merged.

**Comment by davidgenesiscruz** [comment]
Closing as this is a duplicate of #3574.

@low-batt Thank you and sorry for creating a duplicate issue.

**Comment by low-batt** [comment]
@davidgenesiscruz No worries. With the large number of open issues it is hard to spot duplicates. I appreciate you taking the time to report the issue. The fix I referred to is expected to be included in the next release.

**Comment by low-batt** [comment]
The fix in PR #3579 has been merged into the develop branch.
