### ISSUE TITLE
A-B loop back and forth "boomerang" or "ping-pong"

### ISSUE THREAD

**Issue by uajqq** [iina/iina#3702]
**What you want IINA to do:**

It would be great if users could set an A-B loop, or regular loop, for the video to "boomerang" or "ping-pong" back and forth between two points. I.e. video would play forwards from A to B, play backwards to A, then repeat.

**What IINA does currently:**

Currently A-B loops loop from A -> B and then skip back to A.

**Why you think this should be added:**

Especially when IINA is used as a display kiosk or graphic display, it would be nice to have the option to seamlessly loop back and forth without having to edit the video. 

**Examples of other projects that have something similar:**

I don't think there are any other projects that implement this. Old versions of QuickTime used to.

**Comment by low-batt** [comment]
Hello from another IINA user!

IINA uses libmpv from the [mpv](https://mpv.io/) project for audio and video support. IINA's A-B Loop feature comes from libmpv and that feature doesn't support looping backwards. You could request this feature from mpv. It kind of supports playing backward. From the [mpv manual](https://mpv.io/manual/stable/#options-play-dir):
> **--play-dir=<forward|+|backward|->**
>
>    Control the playback direction (default: forward). Setting backward will attempt to play the file in reverse direction, with decreasing playback time.

But the manual goes on to say...

> **Note**
>
> Backward playback is extremely fragile. It may not always work, is much slower than forward playback, and breaks certain other features. How well it works depends mainly on the file being played. Generally, it will show good results (or results at all) only if the stars align.

See the mpv manual for more details on the problems with backward playback.

Anyway, mpv would need to add an option to its A-B Loop feature for IINA to support this.
