### ISSUE TITLE
Legacy FullScreen

### ISSUE THREAD

**Issue by eks28** [iina/iina#3703]
Legacy works with double click in new fix but can't see using mouse can only using arrow keys

It is just me cause I want mouse see on bar

So please fix

UPDATE:

I can scub on time bar but to do that its takes multiple mouse clicks to seek

I don't know if mac/workourk issue or buck with the workaround you implemented

**Comment by low-batt** [comment]
Not sure if what you are reporting is related to the workaround or not.

Under what version of macOS are you experiencing this?

To test the workaround you built your own version of IINA using the develop branch?

I just built the current develop branch using Xcode 13.3 under macOS 12.3.1 on a M1 Mac and tried to reproduce this. With legacy full screen enabled and playing a movie in full screen I am able to see the mouse pointer. Left clicking with my Logitech mouse on the knob in the OSC slider I am able to drag the knob and the video moves accordingly.

Maybe there is some additional factor required to reproduce this. Or am I confused about the nature of the problem?

**Comment by eks28** [comment]
i maybe open new issue later but thanks any way it kina works but just doesnt work on mkv thnx ill just use non legacy full screen
