### ISSUE TITLE
Preference panes keep shifting vertically

### ISSUE THREAD

**Issue by svobs** [iina/iina#3717]
Go to IINA > Preferences..., then try clicking on different sections on the left. Watch the vertical alignment of the pane on the right relative to the Search field. About half the time, the first row in the pane is level with the Search field, and half the time it's below it. See pictures below

- macOS 12.3.1
- IINA 1.2.0
- 2019 16" Intel Macbook Pro

**Expected behavior:**
First row should be roughly level with Search field.

**Actual behavior:**
Sometimes correct, sometimes too low, seemingly random

![1_General_Bad](https://user-images.githubusercontent.com/2213815/166633867-bb2da1cf-2354-4134-8780-150361395543.png)
![2_UI_Good](https://user-images.githubusercontent.com/2213815/166633869-152ae36d-a626-4040-8d37-24029298a96d.png)
![3_VideoAudio_bad](https://user-images.githubusercontent.com/2213815/166633870-5ef03203-409a-4ec9-b09a-a63b2edf07eb.png)
![4_General_Good](https://user-images.githubusercontent.com/2213815/166633872-2f8917b9-f035-44e3-8b9f-ce21a7312f46.png)

**Comment by low-batt** [comment]
This is fixed in the released version of IINA.
