### ISSUE TITLE
When I pause and play again, it freezes for a second before playing.

### ISSUE THREAD

**Issue by ooQAQooo** [iina/iina#3744]
**System and IINA version:**

- macOS ：macOS Monterey 
- IINA : 1.2.0

**Expected behavior:**
It plays at the same time I click play button.

**Actual behavior:**
It was stuck for a second

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
all time

**Comment by Johnny-QZ** [comment]
+1

**Comment by low-batt** [comment]
IINA 1.3.0 has recently been released. Please download the latest IINA version from the [IINA](https://iina.io/) web site, upgrade and report here if the problem is fixed by 1.3.0 or still occurs.

**Comment by ooQAQooo** [comment]
> IINA 1.3.0 has recently been released. Please download the latest IINA version from the [IINA](https://iina.io/) web site, upgrade and report here if the problem is fixed by 1.3.0 or still occurs.

I tried it, but the issue still occurs...
Actually, in a coincidence, this problem fixed when I used both VLC and IINA! When I further searched for the reason, I found that I only needed to play with VLC first, then pause and switch to IINA, and the issue was solved.
Therefore, I suspect this issue is caused by an audio playback error...

**Comment by low-batt** [comment]
That is really interesting. Thank you for investigating and reporting back.

People have been complaining about audio problems under Monterey. This Reddit post is one example: [Problem with 'coreaudiod' slowing down until forced reset](https://www.reddit.com/r/MacOS/comments/oo0uvo/q_problem_with_coreaudiod_slowing_down_until/). I have a friend who is still trying to track down why he keeps having to restart `coreaudiod` to get audio working.

Do you have any audio related applications installed? Are you using any external audio hardware?

Open `Applications`/`Utilities`/[Console](https://support.apple.com/guide/console/welcome/mac). Click on `Crash Reports`. Look for any crash reports, especially from `coreaudiod`. If you find an audio related report post it here.

Open `Applications`/`Utilities`/[Activity Monitor](https://support.apple.com/guide/activity-monitor/welcome/mac) and see if `coreaudiod` or anything else is consuming an excessive amount of CPU time.

If you can still reproduce the problem the next step is to collect IINA log files. To collect logs follow these steps:
- Open `IINA/Preferences`
- Click on `Advanced`
- Slide the `Enable advanced settings` toggle button to be on (blue)
- Check `Enable logging`
- Click on the `Open log directory` button
- Finder opens showing the top level log directory
- **Restart IINA** to active logging
- Reproduce the issue
- Quit IINA
- Click on the Finder window showing the log directory 
- If logging was enabled in the past there will be multiple sub-directories
- Double click on the latest directory
- The directory should contain two files `iina.log` and `mpv.log`
- Drag and drop those files to this issue
- Don't forget to go back and disable logging

Maybe the logs will provide some clue as to what is going on.

**Comment by Heckrexter** [comment]
I have reproduced the issue, after I pause the video and resume I have not noticed any activity excessively using computer resources on my tools. Attached are the log files iina.log and mpv.log

I hope these logs help resolve the issue as it is really annoying especially with educational content where I often have to pause the video.
Thanks 

[iina.log](https://github.com/iina/iina/files/9079168/iina.log)
[mpv.log](https://github.com/iina/iina/files/9079169/mpv.log)

**Comment by low-batt** [comment]
The mpv log contains a couple of warnings that may related to the problem at hand:

```text
[   7.768][w][cplayer] Audio device underrun detected.
[   7.770][v][cplayer] restarting audio after underrun
```

And:
```text
[   8.235][w][cplayer] Audio/Video desynchronisation detected! Possible reasons include too slow
[   8.235][w][cplayer] hardware, temporary CPU spikes, broken drivers, and broken files. Audio
[   8.235][w][cplayer] position will not match to the video (see A-V status field).
```

The next step is to try and generate a sample of the offending video file that is small enough to post to GitHub. When creating a small sample it is important that whatever program is used it does not re-encode the video. I believe this is the proper way to clip 15 seconds from the start of a video without re-encoding using [FFmpeg](https://ffmpeg.org/):
```text
ffmpeg -i long-input.mp4 -to 00:00:15 -c:v copy -c:a copy short-output.mp4
```

If you can generate a small video that reproduces the problem I can see if it reproduces for me. If it does then I can dig into the problem.

**Comment by Heckrexter** [comment]
Okay I went to test out the original video again and the problem seems to have resolved itself now. In the time between reporting the issue and now I only played a movie using IINA and now the problem is not appearing anymore but just in case i'll attach log files of me playing the same video as last time and Upload the log files. If the issue arises again Ill let you know and instantly crop the video and upload that as well alongside the log files.
Attached below are the logs now when watching the same video that previously caused the issue:-

[iina.log](https://github.com/iina/iina/files/9092715/iina.log)
[mpv.log](https://github.com/iina/iina/files/9092717/mpv.log)

**Comment by low-batt** [comment]
The audio underrun and A/V desynchronization warnings are not present in the latest logs. That seems to confirm those logs messages are related to the problem at hand. 

The next time it reproduces please check for crash reports:

Open `Applications`/`Utilities`/[Console](https://support.apple.com/guide/console/welcome/mac). Click on `Crash Reports`. Look for any crash reports, especially from `coreaudiod`.

If daemons are restarting in the background that can cause delays.

If the problem does not reproduce with a smaller sample and you need to upload a sample larger than GitHub permits then upload it to https://0x0.st/

Aspects of the particular video file may play a role, but it seems like there is something happening on the Mac that is triggering the problem.

**Comment by Heckrexter** [comment]
encountered the issue again today and I linked a video which caused the issue as well as the logs. Some things I noticed, after a restart the app player did not suffer this issue anymore for a small amount of time but then the issue returned. I see no crashreports in the console that was relevant to this issue.

I only saw one warning that was the same as the one in the old mpv log:
```
[  10.495][w][cplayer] Audio device underrun detected.
```

(don't judge the video please)
https://user-images.githubusercontent.com/102521099/178956863-c2e4a37b-410d-445e-b7f8-2dc195bcece3.mp4
[iina.log](https://github.com/iina/iina/files/9110809/iina.log)
[mpv.log](https://github.com/iina/iina/files/9110810/mpv.log)

**Comment by low-batt** [comment]
I tried to reproduce the problem multiple times using the posted example. No luck. Certain types of problems can be very elusive.

The logs show playback is using Apple supplied hardware drivers. One thing to try is to disable use of hardware drivers and see if the problem goes away. Of course if it is difficult to reproduce the problem it is hard to tell if a change makes a difference.

To force use of software instead of the hardware drivers:
- Open IINA preferences
- In the preferences window click on `Video/Audio`
- In the `Video` section change the `Hardware decoder` setting from `Auto` (the default) to `Disabled`

Of course this will increase CPU use. It is desirable to use the hardware drivers, but they can be a source of problems. If the problem does not reproduce when using software  then that would make us suspect the issue is related to the hardware drivers.
