### ISSUE TITLE
auto-profiles applies shaders multiple times

### ISSUE THREAD

**Issue by GreyAsteroid** [iina/iina#3761]
**System and IINA version:**

- macOS Monterey Version 12.5 Beta (21G5027d)
- IINA 1.3.0 Build 130

**Expected behavior:**
Shaders should be applied once regardless of how many windows have previously been open.

**Actual behavior:**
Shaders are applied multiple times depending on how many windows have previously been open.

<summary><b>mpv log:</b></summary>

[mpv.log](https://github.com/iina/iina/files/8794419/mpv.log)
(Sorry, surpasses character limit)

**Steps to reproduce:**
1. Open a video with IINA that has a glsl shader applied to it via auto profile
2. While keeping the video from Step 1 open, repeat Step 1 opening a new window then close this new window.
3. Repeat Step 2 continously while observing an increase in artifacts with each repetition.

![FirstWindow_4thWindow](https://user-images.githubusercontent.com/4615298/170894390-ded16f35-522f-41d7-81c8-996c3c0bb93f.png)
(Artifacts can be seen at full size)

- [X] MPV does not have this problem.
MPV is unable to experience this issue because of how it handles its windows.

**How often does this happen?**
Every time the steps are reproduced.

**Additionally**
I've only been able to reproduce this issue with builds of IINA using MPV 0.34.1, leading me to believe that it is caused by one of [these MPV commits.](https://github.com/mpv-player/mpv/compare/v0.34.0...v0.34.1)

**Comment by lhc70000** [comment]
Thanks for reporting. Could you provide more info about the auto profiles, like what configuration do you have and how you applied them in IINA?

**Comment by GreyAsteroid** [comment]
> Thanks for reporting. Could you provide more info about the auto profiles, like what configuration do you have and how you applied them in IINA?

Sure thing, when debugging I was using
```
[>1440p_<=30fps]
profile-cond=((p["video-params/h"]>1440 and p["container-fps"]<=30))
glsl-shader="/Users/eric/.config/mpv/shaders/SSimDownscaler.glsl"
```
just because this was what was applicable to my test file and because SSimDownscaler led to noticeable artifacts when applied multiple times.

This was applied via mpv.conf

**Comment by hooke007** [comment]
off topic:
This profile is also unusual in mpv. When you switch to another video in the single process which satisfy your `profile-cond` , it would append SSimDownscaler again. Because `--glsl-shader` is the alias of `--glsl-shaders-append`

**Comment by hooke007** [comment]
> the undocumented option glsl-shaders-clr

No it's clearly doced. Manual said `(see List Options for details).`
And you don't need to ues it. Just use `glsl-shaders=`

**Comment by GreyAsteroid** [comment]
> > the undocumented option glsl-shaders-clr
> 
> No it's clearly doced. Manual said `(see List Options for details).` And you don't need to ues it. Just use `glsl-shaders=`

You're right, seems the mpv master docs are weird about this option though. There are 2 entries for `--glsl-shader=<file>` , the one I looked at simply states that it's an alias. 

> --glsl-shader=<file>
CLI/config file only alias for --glsl-shaders-append.

Regardless, in specifically the newest IINA release using 
```
[>1440p_<=30fps]
profile-cond=((p["video-params/h"]>1440 and p["container-fps"]<=30))
glsl-shader="/Users/eric/.config/mpv/shaders/SSimDownscaler.glsl"
```

Causes this issue while using
```
[>1440p_<=30fps]
profile-cond=((p["video-params/h"]>1440 and p["container-fps"]<=30))
glsl-shaders-clr
glsl-shader="/Users/eric/.config/mpv/shaders/SSimDownscaler.glsl"
```
Does not

**Comment by hooke007** [comment]
As i mentioned here. https://github.com/iina/iina/issues/3761#issuecomment-1140728607
Your original profile is also buggy in mpv.

> Shaders are applied multiple times depending on how many windows have previously been open.

The potential reason is that mpv's each window is independent while iina is not. If it is a intentional design, I could say there is no bug here.

**Comment by GreyAsteroid** [comment]
> As i mentioned here. [#3761 (comment)](https://github.com/iina/iina/issues/3761#issuecomment-1140728607) Your original profile is also buggy in mpv.
> 
> > Shaders are applied multiple times depending on how many windows have previously been open.
> 
> The potential reason is that mpv's each window is independent while iina is not. If it is a intentional design, I could say there is no bug here.

In summary, because of how mpv handles windows my improper config doesn't cause this issue in mpv 0.34.1 but after IINA updated to mpv 0.34.1 it now triggers this issue because of how IINA handles windows differently. 

😆 What a funny issue to have. Closing, not a bug.
