### ISSUE TITLE
The openiniina extension for safari cannot be reinstalled.

### ISSUE THREAD

**Issue by skymagician** [iina/iina#3768]
I uninstalled the extension in safari by mistake, and I want to install it back. I tried reinstall iina, but it didn't work.
macbook air m1, macos 12.4, iina 1.3.0

**Comment by Aeneon** [comment]
Same Problem, after Update to 1.3.0, without removing the Extension …

**Comment by lhc70000** [comment]
Fixed in build 132. You can download it from [GitHub release](https://github.com/iina/iina/releases/tag/v1.3.0) or https://iina.io. The in-app update will be available in about 24 hours.
