### ISSUE TITLE
No OpenInIIna Safari Extension

### ISSUE THREAD

**Issue by mat1696** [iina/iina#3770]
**System and IINA version:**   

- macOS macOS 12.4
- IINA 1.3.0

**Expected behavior:**
Safari extension OpenInIIna should show up in Safari Preferences → Extensions

**Actual behavior:**
Safari extension OpenInIIna does not show up in Safari Preferences → Extensions.

**Steps to reproduce:**
1. Download Iina from website.2. 
2. Drag it into Applications folder.3. 
3. Open it

**How often does this happen?**
Always (tried on 2 macs, one with 12.4 release and the other with 12.5 beta, but same issue)

**Comment by jpsalap** [comment]
Same thing happened to me, Safari extension just vanished.
System and IINA version
- macOS 11.6.6
- IINA 1.3.0

**Comment by Aeneon** [comment]
Same Problem, also a Restore of the old IINA 1.2.0 App-Extension didn't help …

System, Safari and IINA Version

macOS 10.14.6
Safari 12.1.2
IINA 1.3.0

**Comment by christianonpele** [comment]
Same problem:


macOS 12.4
Safari 15.5
After update IINA 1.2.x -> 1.3.0

**Comment by lhc70000** [comment]
Fixed in build 132. You can download it from [GitHub release](https://github.com/iina/iina/releases/tag/v1.3.0) or https://iina.io. The in-app update will be available in about 24 hours.

**Comment by lhc70000** [comment]
In-app update is available now, closing.
