### ISSUE TITLE
Option to hide window in Picture in Picture mode

### ISSUE THREAD

**Issue by matthewdias** [iina/iina#380]
Will need to restore the window when the restore button is clicked, or the shortcut is activated.
![](https://i.imgur.com/kV2I8mA.png)

**Comment by saagarjha** [comment]
As a workaround, you can use the hide command (⌘-H) while in Picture in Picture to hide the main window. Stopping PIP, however, will not raise the window automatically (though I can probably get it to do that, if desired).

**Comment by matthewdias** [comment]
I'm using that for now. I think it'd be fine to just tell the window to hide when entering pip, and unhide when leaving. This setting should be opt-in of course.

**Comment by uiryuu** [comment]
You can configure IINA to minimize when entering PIP
