### ISSUE TITLE
Will M1 macbook air get iina HDR support anytime soon?

### ISSUE THREAD

**Issue by VivekHalakatti** [iina/iina#3806]
**What you want IINA to do:**

iina doesn't support HDR on macbook air.

Add support for HDR content on m1 macbook air.

**Examples of other projects that have something similar:**

**Comment by saagarjha** [comment]
I don't think that device has a screen that can play HDR content?

**Comment by adambuckland** [comment]
No, I don't believe it does. Needs a `Liquid Retina XDR display` to use Apple's marketing buzzwords.

**Comment by JarringBye** [comment]
400nits要什么hdr

**Comment by low-batt** [comment]
Do not forget about [Extended Dynamic Range](https://developer.apple.com/documentation/metal/hdr_content/displaying_hdr_content_in_a_metal_layer). Is this an issue with [Determining Support for EDR](https://developer.apple.com/documentation/metal/hdr_content/determining_support_for_edr_values)?

From [Play HDR video on Mac](https://support.apple.com/en-us/HT210980):
> ## Mac models that support HDR
>
>These Mac models support HDR video on their built-in display (if applicable) and external HDR10-compatible displays.
>
> - MacBook Pro introduced in 2018 or later
>- MacBook Air introduced in 2018 or later (HDR on external displays requires a model with Apple silicon)
> - iMac introduced in 2020 or later
> - iMac Pro
> - Mac mini introduced in 2018 or later
> - Mac Pro introduced in 2019
> - Mac Studio

IINA is enabling HDR on my old 2019 MacBookAir8.2 running macOS 10.15.7 when EDR is enabled. If I option-click on "Displays" in System Preferences the EDR option is shown:
![issue-3806-display-preferences](https://user-images.githubusercontent.com/86170219/172630018-c7979520-c829-45ec-8d93-729f0a4650ed.jpg)

Also from [Play HDR video on Mac](https://support.apple.com/en-us/HT210980) another way HDR might be disabled:
> - Choose Apple menu > System Preferences, then click Battery or Energy Saver. If “Optimize video streaming while on battery” is selected in battery settings, your Mac saves energy by playing HDR video in standard dynamic range (SDR) while on battery power. To play in HDR, connect your Mac to power or deselect this checkbox.

**Comment by love4taylor** [comment]
The M1 MacBook Air does not have an EDR option, but Movist Pro, Optimus Player, and QuickTime can all trigger HDR, except for IINA.

**Comment by MatthiasWinkelmann** [comment]
It does work for me on the M1 MacBook Air using an external display (XDR, 1600 nits). On MacOS 13 "Ventura" Beta 1.

(CPU usage is at 600% in my tests, but I believe there's a different issue for that already)

**Comment by low-batt** [comment]
The IINA and mpv log files might provide a clue as to what is happening. Would be nice to have those.

Based on the list from Apple above IINA should deem the M1 MacBook Air capable of supporting EDR.

From [MacBook Air (M1, 2020) - Technical Specifications](https://support.apple.com/kb/SP825?locale=en_US):
> 400 nits brightness
> Wide color (P3)

Add to that IINA is enabling HDR on my older Intel based 2019 MacBook Air.

@CarterLi, Thoughts?

This is the code from [VideoView](https://github.com/iina/iina/blob/7604e5498036a854f0284965037cb5561bb64df9/iina/VideoView.swift#L306) that decides if EDR can be enabled:
<details>
<summary><b>requestEdrMode</b></summary>

```swift
func requestEdrMode() -> Bool? {
  guard let mpv = player.mpv else { return false }

  guard let primaries = mpv.getString(MPVProperty.videoParamsPrimaries), let gamma = mpv.getString(MPVProperty.videoParamsGamma) else { return false }

  var name: CFString? = nil;
  switch primaries {
  case "display-p3":
    switch gamma {
    case "pq":
      if #available(macOS 10.15.4, *) {
        name = CGColorSpace.displayP3_PQ
      } else {
        name = CGColorSpace.displayP3_PQ_EOTF
      }
    case "hlg":
      name = CGColorSpace.displayP3_HLG
    default:
      name = CGColorSpace.displayP3
    }

  case "bt.2020":
    switch gamma {
    case "pq":
      if #available(macOS 11.0, *) {
        name = CGColorSpace.itur_2100_PQ
      } else if #available(macOS 10.15.4, *) {
        name = CGColorSpace.itur_2020_PQ
      } else {
        name = CGColorSpace.itur_2020_PQ_EOTF
      }
    case "hlg":
      if #available(macOS 11.0, *) {
        name = CGColorSpace.itur_2100_HLG
      } else if #available(macOS 10.15.6, *) {
        name = CGColorSpace.itur_2020_HLG
      } else {
        fallthrough
      }
    default:
      name = CGColorSpace.itur_2020
    }

  case "bt.709":
    return false; // SDR

  default:
    Logger.log("Unknown HDR color space information gamma=\(gamma) primaries=\(primaries)", level: .debug, subsystem: hdrSubsystem);
    return false;
  }

  guard (window?.screen?.maximumPotentialExtendedDynamicRangeColorComponentValue ?? 1.0) > 1.0 else {
    Logger.log("HDR video was found but the display does not support EDR mode", level: .debug, subsystem: hdrSubsystem);
    return false;
  }

  guard player.info.hdrEnabled else { return nil }

  Logger.log("Will activate HDR color space instead of using ICC profile", level: .debug, subsystem: hdrSubsystem);

  videoLayer.wantsExtendedDynamicRangeContent = true
  videoLayer.colorspace = CGColorSpace(name: name!)
  mpv.setString(MPVOption.GPURendererOptions.iccProfile, "")
  mpv.setString(MPVOption.GPURendererOptions.targetTrc, gamma)
  mpv.setString(MPVOption.GPURendererOptions.targetPrim, primaries)
  return true;
}
```
</details>

With an IINA log file we could see which of the log messages in that code are being emitted.

On the comments regarding the M1 MacBook Air not having a HDR capable screen, that has to do with what is ideal in a HDR display.

From the Wikipedia [Dolby Vision](https://en.wikipedia.org/wiki/Dolby_Vision) page:
> Dolby Vision mastering display require:
> - EOTF: PQ
> - Peak brightness: at least 1,000 cd/m2
> - Black level: at most 0.005 cd/m2
> - Contrast ratio: at least 200,000:1
> - Color gamut: at least 99% of P3

So ideally we want the high peak brightness of the XDR displays:

From [Pro Display XDR](https://www.apple.com/pro-display-xdr/specs/):
> **Contrast ratio**: 1,000,000:1
> **Color**: P3 wide color gamut, 10-bit depth for 1.073 billion colors
>  **XDR brightness**: 1000 nits sustained full‑screen, 1600 nits peak1 (HDR content only)
> **SDR brightness**: 500 nits

From [MacBook Pro 14” and 16” models](https://www.apple.com/macbook-pro-14-and-16/specs/):
> **XDR (Extreme Dynamic Range)**
> 1,000,000:1 contrast ratio
> XDR brightness: 1000 nits sustained full-screen, 1600 nits peak2 (HDR content only)
> SDR brightness: 500 nits
> Wide color (P3)

But Apple does not require that for HDR. A good discussion of this can be found in this video from WWDC 2021: [Explore HDR rendering with EDR](https://developer.apple.com/videos/play/wwdc2021/10161/)

How good HDR looks on a less capable display depends upon multiple factors such as the user configured display brightness setting, the lighting in the room, etc.

@love4taylor Thanks for reporting. Not the answer I was expecting. That setting is hidden by default. I had to control-click on `Displays` in `System Preferences` to get it to appear. The screenshot above was from Catalina and yet there is no mention of that setting here: [Change Display preferences on Mac macOS Catalina 10.15](https://support.apple.com/guide/mac-help/change-display-preferences-mh40768/10.15/mac/10.15). Maybe Apple has removed that hidden setting in Monterey?

**Comment by avichou** [comment]
> 400nits要什么hdr

and it can be glorious 

on my lg ul650 ,whose brightness maxxes out at 350nits i beleive (and even less in real world APL ) ,using a software able to use hdr brightness metadata even on SDR displays, the image is incredibly bright ,so much so that i was suprised it looked this good with movies like interstellar for example .

**Comment by low-batt** [comment]
Of course before it can be glorious running IINA on the M1 MacBook Air we need to determine the root cause of this issue. 

I've been testing with this YouTube HDR video: [The World in HDR in 4K (ULTRA HD)](https://www.youtube.com/watch?v=tO01J-M3g0U)

While experimenting IINA failed to enable HDR on my M1 MacBook Pro with the XDR display. I added some extra debug logging to the `requestEdrMode` method, this section in particular:
```swift
guard let primaries = mpv.getString(MPVProperty.videoParamsPrimaries), let gamma = mpv.getString(MPVProperty.videoParamsGamma) else {
  Logger.log("EDR primaries and gamma not available")
  return false
}
```

And when IINA failed to enable HDR the log contained:
```text
17:32:19.034 [iina][d] EDR primaries and gamma not available
```

Running IINA again on that same YouTube video and HDR worked:
```text
18:07:36.989 [iina][d] EDR primaries bt.2020
18:07:36.989 [iina][d] EDR gamma pq
18:07:36.989 [iina][d] EDR max potential 16.0
18:07:36.989 [hdr][d] Will activate HDR color space instead of using ICC profile
```

Apparently when mpv emits a `TrackSelection.vid` event there is a thread race condition as to whether these properties are available or not. IINA may need to directly observe these properties for changes.

@CarterLi, Thoughts?

A bit more of the debug logs:
<details>
<summary><b>IINA log HDR failed:</b></summary>

```text
17:32:01.724 [player0][d] Open URL: https://www.youtube.com/watch?v=tO01J-M3g0U
17:32:01.725 [player0][d] Opening https://www.youtube.com/watch?v=tO01J-M3g0U in main window
2022-06-13 17:32:01.755983-0400 IINA[66309:2262188] [Nib Loading] Could not connect action, target class IINA.MainWindowController does not respond to -additionalInfoTitle:
17:32:01.904 [iina][d] Created OpenGL pixel format with [__C._CGLPixelFormatAttribute(rawValue: 5), __C._CGLPixelFormatAttribute(rawValue: 96), __C._CGLPixelFormatAttribute(rawValue: 99), __C._CGLPixelFormatAttribute(rawValue: 12800), __C._CGLPixelFormatAttribute(rawValue: 73), __C._CGLPixelFormatAttribute(rawValue: 101), __C._CGLPixelFormatAttribute(rawValue: 0)]
17:32:01.931 [iina][d] Falling back to nominal display refresh rate: 120.0 from 0.0
17:32:01.934 [iina][d] window!.screen: Built-in Retina Display visible frame (0.0, 24.0, 1728.0, 1055.0)
17:32:01.934 [iina][d] NSScreen.main: Built-in Retina Display visible frame (0.0, 24.0, 1728.0, 1055.0)
17:32:01.934 [iina][d] NSScreen.screens[0]: Built-in Retina Display visible frame (0.0, 24.0, 1728.0, 1055.0)
17:32:01.935 [iina][d] MainWindowLastPosition (0.0, 65.0) matched: Built-in Retina Display visible frame (0.0, 24.0, 1728.0, 1055.0)
17:32:01.953 [player0][d] File started
17:32:01.953 [player0][d] Track list changed
17:32:01.986 [player0][d] Started auto load
17:32:01.987 [fmatcher][d] **Start matching
17:32:18.998 [player0][d] Track list changed
17:32:19.015 [player0][d] File loaded
17:32:19.016 [player0][d] Track list changed
17:32:19.034 [iina][d] EDR requestEdrMode
17:32:19.034 [iina][d] EDR primaries and gamma not available
17:32:19.040 [player0][d] Track list changed
17:32:19.584 [player0][d] Getting thumbnails
17:32:19.584 [player0][d] ...stopped because cannot get file path
17:32:20.115 [player0][d] Playback restarted
```
</details>

<details>
<summary><b>IINA log HDR worked:</b></summary>

```text
18:07:26.440 [player0][d] Opening https://www.youtube.com/watch?v=tO01J-M3g0U in main window
2022-06-13 18:07:26.449966-0400 IINA[69492:2287653] [Nib Loading] Could not connect action, target class IINA.MainWindowController does not respond to -additionalInfoTitle:
18:07:26.536 [iina][d] Created OpenGL pixel format with [__C._CGLPixelFormatAttribute(rawValue: 5), __C._CGLPixelFormatAttribute(rawValue: 96), __C._CGLPixelFormatAttribute(rawValue: 99), __C._CGLPixelFormatAttribute(rawValue: 12800), __C._CGLPixelFormatAttribute(rawValue: 73), __C._CGLPixelFormatAttribute(rawValue: 101), __C._CGLPixelFormatAttribute(rawValue: 0)]
18:07:26.545 [iina][d] Falling back to nominal display refresh rate: 120.0 from 0.0
18:07:26.547 [iina][d] window!.screen: Built-in Retina Display visible frame (0.0, 24.0, 1728.0, 1055.0)
18:07:26.547 [iina][d] NSScreen.main: Built-in Retina Display visible frame (0.0, 24.0, 1728.0, 1055.0)
18:07:26.547 [iina][d] NSScreen.screens[0]: Built-in Retina Display visible frame (0.0, 24.0, 1728.0, 1055.0)
18:07:26.547 [iina][d] MainWindowLastPosition (0.0, 65.0) matched: Built-in Retina Display visible frame (0.0, 24.0, 1728.0, 1055.0)
18:07:26.555 [player0][d] File started
18:07:26.555 [player0][d] Track list changed
18:07:26.556 [player0][d] Started auto load
18:07:26.558 [fmatcher][d] **Start matching
18:07:36.739 [player0][d] Track list changed
18:07:36.957 [player0][d] File loaded
18:07:36.957 [player0][d] Track list changed
18:07:36.983 [player0][d] Getting thumbnails
18:07:36.983 [player0][d] ...stopped because cannot get file path
18:07:36.983 [player0][d] Playback restarted
18:07:36.989 [iina][d] EDR requestEdrMode
18:07:36.989 [iina][d] EDR primaries bt.2020
18:07:36.989 [iina][d] EDR gamma pq
18:07:36.989 [iina][d] EDR max potential 16.0
18:07:36.989 [hdr][d] Will activate HDR color space instead of using ICC profile
18:07:36.989 [player0][d] Track list changed
```
</details>

**Comment by CarterLi** [comment]
> Apparently when mpv emits a `TrackSelection.vid` event there is a thread race condition as to whether these properties are available or not. IINA may need to directly observe these properties for changes.
> 
> @CarterLi, Thoughts?

Reasonable suggestion. I'll handle it.

**Comment by Quixot1k** [comment]
m1 MacBook Air needs an HDR feature, it could be more glorious and vivid though the screen is just 400nit.

**Comment by low-batt** [comment]
I tested the fix in build 145 of IINA+ and with quite a few runs IINA always enabled HDR. I was unable to reproduce the issue I reported above where HDR sometimes failed to activate. I looked over the code and the changes look good to me.

I did see this error in the log which needs to be explained:
```text
16:33:08.590 [iina][w] mpv log: [cplayer] fatal: Invalid value for option tone-mapping: auto
```
One minor thing, when calling Logger.log there is no need to pass level, it will default to `.debug`.

So the proposed fix works for me, however we don't know for sure if this is the problem behind this issue, HDR not working on the M1 MacBook Air. Is it that M1 Air owners have not tired it enough to see it work sometimes, or is there something else happening on the M1 Air?

Do any of you M1 Air owners want to give [IINA+](https://github.com/iina-plus/iina) a try? This is an experimental fork maintained by @CarterLi.

**Comment by CarterLi** [comment]
> 16:33:08.590 [iina][w] mpv log: [cplayer] fatal: Invalid value for option tone-mapping: auto

Well, it turns out that `tone-mapping=auto` is supported on MPV master only.

**Comment by low-batt** [comment]
@Quixot1k Thank you very much for checking the IINA+ 145 behavior! That you saw HDR enabled on your M1 MacBook Air confirms that this issue wasn't a result of something odd about the M1 Air, but rather this more general problem where IINA would randomly fail to enable HDR on HDR capable Macs.

Discussion about HDR and colors should continue in issue #3807.

**Comment by YuntianCheng** [comment]
> I don't think that device has a screen that can play HDR content?

<img width="841" alt="image" src="https://user-images.githubusercontent.com/29092622/184072955-3d2f5f10-17e4-4d4a-b8fd-5688b5e0273d.png">

**Comment by Dibbyo456** [comment]
M2 Air also supports HDR (500 nits)
