### ISSUE TITLE
Add master killswitch for HDR

### ISSUE THREAD

**Issue by svobs** [iina/iina#3808]
_(Filing this as a sibling to #3807, which should be addressed separately. It looks like there are some users which are having various issues with the new HDR support, and at least some of these issues are a long way from being sorted out.)_ 

**What you want IINA to do:**
Add a new checkbox to the Video section of IINA preferences: "Enable HDR support" _(question: enabled by default...?)_
* When unchecked, HDR will not be enabled for any videos.
* When checked, HDR will be enabled by default on a-per-video basis, if IINA detects that both video & display support it (aka the current behavior).

**What IINA does currently:**
IINA attempts to detect HDR support for each video and enables it each time it is found. There is an HDR checkbox in the Video Quick Settings panel for the video but it needs to be unchecked by the user every time a video is opened.

**Why you think this should be added:**
Having to disable HDR each time a video is opened is inconvenient for the affected users.

**Comment by CarterLi** [comment]
I'll look at this

**Comment by low-batt** [comment]
I tested IINA+ build 142 and the new preference worked for me.

I'm thinking the name of the property, "Enable HDR mode by default", probably should leave off the "by default". The explaination under the preference looks good.

**Comment by CarterLi** [comment]
> I tested IINA+ build 142 and the new preference worked for me.
> 
> I'm thinking the name of the property, "Enable HDR mode by default", probably should leave off the "by default". The explaination under the preference looks good.

It is "by default", as you can still enable HDR mode in quick setting panel

**Comment by low-batt** [comment]
As you can tell I didn't understand what it meant. Lets see what others think.

**Comment by CarterLi** [comment]
> As you can tell I didn't understand what it meant. Lets see what others think.

My English is not good.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/6134068/172765380-4266e798-9ee0-4490-a1cf-eb4eb3cde00f.png">

The checkbox `Enable HDR mode by default` controls whether the switch `HDR` is selected automatically when playing HDR videos. If you uncheck `Enable HDR mode by default`, the switch `HDR` is not checked automatically, but you can check it manually.

**Comment by svobs** [comment]
> The checkbox Enable HDR mode by default controls whether the switch HDR is selected automatically when playing HDR videos. If you uncheck Enable HDR mode by default, the switch HDR is not checked automatically, but you can check it manually.

I think `Enable HDR support` is  great wording for the Preferences checkbox.

Not to be confused with "tech support" or "life support" (although it's not too hard to see the relationship), it is standard parlance for software including videogames and office products. For a program to "support" Feature X is to say it *can* make use of that feature. To tell a program to "enable support" for Feature X is to say "enable the possible use of" Feature X - in other words, Feature X *may* be, but not necessarily *will* be, used. It's suitably broad so that you don't need to go into more detail (the user probably doesn't want you to anyway).

Compare this to a checkbox commanding IINA to simply "enable" something, which would usually indicate that it's always used. `Enable HDR mode by default`, when left without a second clause, would suggest a sort of template behavior - something equivalent to "Every video will start in HDR mode unless the user does something to change it".

You would be more accurate if a second clause were included: `Enable HDR mode by default when playing HDR videos` but if that were unchecked, that would be interpreted as leaving the HDR box unchecked, but still able to be checked. When I wrote this feature, I described it as a "kill switch", so unchecking that box in the preferences should leave the HDR option in the side panel unchecked and grayed out. That way, there would be no confusion about whether HDR mode was enabled and could be blamed for defects. Although I can understand arguments for just defaulting to unchecked - which is it? (I confess I just got `iina-plus` to build but I haven't yet figured out how to run it.)

**Comment by svobs** [comment]
Oh - right after send, just re-read your comments, and I understand now 😂

@low-batt what do you think? It looks like @CarterLi's solution could be pretty useful but would need a longer description. Or maybe add another checkbox about that for a master killswitch...?

**Comment by svobs** [comment]
...After some more thought my vote is just to relabel it: `Enable HDR mode by default for HDR videos`, assuming this issue will go through the Collider too

**Comment by low-batt** [comment]
> My English is not good.

Carter, I've read a lot of your posts, your English is _excellent_. My fault for not explaining better what confused me about "by default".

In a lot of cases preferences provide default values. For example, you use the `defaults` command to access them in terminal. So I'm used to "by default" being implied and left unsaid. That made me not understand why it was being included in this case.

Let's see what @lhc70000 this preference should be called.

**Comment by svobs** [comment]
> Carter, I've read a lot of your posts, your English is excellent.
Yes I think I might agree. Please excuse my long droning post. Even perfect speech can't prevent misreading 😵‍💫

**Comment by lhc70000** [comment]
How about "Enable HDR automatically when possible"?
