### ISSUE TITLE
Saved Audio Filters menu disabled in music mode

### ISSUE THREAD

**Issue by low-batt** [iina/iina#3818]
**System and IINA version:**

- macOS 12.4
- IINA 1.3.0

**Expected behavior:**
When the "Audio Filters..." menu is enabled the "Saved Audio Filters" menu is also enabled.

**Actual behavior:**
n music mode the  "Audio Filters..." menu is enabled but the "Saved Audio Filters" menu is disabled. The "Audio Filters..." menu can be used to bring up the "Audio Filters" window. Saved filters can be enabled. the "Saved Audio Filters" menu is updated to show the changes made, but that menu can not be used to enable or disable any of the saved filters.

The fix for issue #3462 in 1.3.0 failed to address this filter related problem. With 1.3.0 audio filters that used to cause problems can now be toggled, but not when in music mode.

**Steps to reproduce:**
- Open an audio file
- Use the "Audio Filters..." menu to add a saved audio filter
- Open the "Saved Audio Filters" menu
- Notice the new saved filter is present, but menu item is dim/disabled

- [x] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by low-batt** [comment]
The toggle action for `Saved Audio Filters` is tied to the `MainWindowController`, not `PlayerWindowController`. As a result when the `MiniPlayerWindowController` is active menus tied to `MainWindowController` are automatically disabled.

Working on a fix.

**Comment by low-batt** [comment]
Fixed in IINA 1.3.1

**Comment by runeflobakk** [comment]
Confirmed working here! Thanks!
