### ISSUE TITLE
High CPU usage in Macbook m1 pro when play hdr mkv file

### ISSUE THREAD

**Issue by FabbiHieuvv** [iina/iina#3836]
I'm using Macbook m1 pro 16 inch with Macos 12.4.

When play mkv file with hdr, it using too much cpu, temperature is very high even with lower Macos version.

<img width="1306" alt="Screen Shot 2022-06-15 at 20 30 00" src="https://user-images.githubusercontent.com/91968527/173840017-456b910f-fa0b-4272-ad3f-4572776eb3cb.png">

Does any one know how to fix this issue ?

**Comment by CarterLi** [comment]
Check if hardware decoder is enabled.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/6134068/173847139-114fac0e-2d65-4cd9-8f2e-e2a6fd34cd42.png">

**Comment by low-batt** [comment]
If in the `Inspector` window the value for `HW Decoder` is "no", check the mpv.log for these messages:
```text
[   2.472][d][ffmpeg/video] h264: VideoToolbox malfunction.
[   2.472][e][ffmpeg/video] h264: Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.
```

That problem has been reported to [FFmpeg](https://ffmpeg.org/) in [#9809](https://trac.ffmpeg.org/ticket/9809).

**Comment by FabbiHieuvv** [comment]
> Check if hardware decoder is enabled.
> hardware decoder is no. what should i do ?
> <img alt="image" width="449" src="https://user-images.githubusercontent.com/6134068/173847139-114fac0e-2d65-4cd9-8f2e-e2a6fd34cd42.png">
<img width="415" alt="Screen Shot 2022-06-17 at 18 58 02" src="https://user-images.githubusercontent.com/91968527/174293828-cc1527cc-4f3e-4f3f-9993-48f0439697d6.png">

**Comment by FabbiHieuvv** [comment]
> If in the `Inspector` window the value for `HW Decoder` is "no", check the mpv.log for these messages:
> 
> ```
> [   2.472][d][ffmpeg/video] h264: VideoToolbox malfunction.
> [   2.472][e][ffmpeg/video] h264: Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.
> ```
> 
> That problem has been reported to [FFmpeg](https://ffmpeg.org/) in [#9809](https://trac.ffmpeg.org/ticket/9809).

my Hw decoder is no. what should i do ?
