### ISSUE TITLE
Total time / remaining time display update

### ISSUE THREAD

**Issue by decodism** [iina/iina#3849]
**System and IINA version:**

- macOS 13.0 beta
- IINA 1.3.0

**Expected behavior:**

When the total time / remaining time is clicked, they should switch.

**Actual behavior:**

If the video is paused, the time display is only updated when the video is resumed.

**Steps to reproduce:**

- Pause a video
- Click on the total time / remaining time

**How often does this happen?**

Always

**Comment by low-batt** [comment]
I reproduced the behavior. Seems wrong to me. I will propose a fix when I get a chance.

**Comment by decodism** [comment]
It seems the issue has been mostly solved by #3602. However, there is still an edge case: position the cursor on the time display, pause with the keyboard, click on the time display without moving the cursor. I have updated my PR accordingly.

**Comment by low-batt** [comment]
I reproduced the problem running a build from develop and following the instructions to pause using the keyboard.
