### ISSUE TITLE
The Full-screen Option Exists As 2 Instances Under Different Menu Items.

### ISSUE THREAD

**Issue by scrutinizer11** [iina/iina#3857]
**System and IINA version:**

- macOS 10.14
- IINA 1.3.0

**Expected behaviour:**

Should be only 1 full-screen mode option. 2 - is redundant.

**Actual behaviour:**

There're 2 duplicates each toggling the full screen.

**Steps to reproduce:**
 See the screenshot.

**How often does this happen?**

Always
![iina_2-full-screen](https://user-images.githubusercontent.com/45983734/176317861-e35ceed1-c814-43b1-94ca-704e49de7cf1.png)
.

**Comment by low-batt** [comment]
The fix in PR [#3891](https://github.com/iina/iina/pull/3891) has been merged into the develop branch.

Keeping this issue open until the fix is in a released version of IINA.

**Comment by low-batt** [comment]
Fixed in IINA 1.3.1.
