### ISSUE TITLE
Plugin system, global can't postMessage to globalChild

### ISSUE THREAD

**Issue by whlsxl** [iina/iina#3858]
**System and IINA version:**

- macOS 12.2.1
- IINA [63caeb4a81d39ef44f78747302f027503480a072](https://github.com/iina/iina/tree/63caeb4a81d39ef44f78747302f027503480a072) plugin system

**Expected behavior:**
**Actual behavior:**

I read the source code, GlobalChild can postMessage to Global, but Global can't postMessage to GlobalChild. It is by design or a bug?

`entry => main.ts`
`globalEntry => global.ts`

```
global.postMessage [main.ts] => global.onMessage [global.ts] success
global.postMessage [global.ts] => global.onMessage [main.ts] failed
```

**Comment by whlsxl** [comment]
In `JavascriptAPIGlobalController` `func postMessage(_ target: JSValue, _ name: String, _ data: JSValue) ` the `childAPIs` is empty

**Comment by lhc70000** [comment]
`global.postMessage()` requires a target. By current design, setting the target to `null` (`global.postMessage(null, name, data)`) will post message to **all** its child players **created by `global.createPlayerInstance()`**.

 If you want to send a message to an arbitrary player instance, the player must post a message to the global script first. In the global script, when received a message, it can obtain the player id and therefore communicate with the player using this id:
  ```js
  global.onMessage("message-name", (data, player) => {
    // `player` is the identifier of the player instance
    global.postMessage(player, "response-name", some_data)
  })
  ```

Example in the youtube-dl plugin:
https://github.com/iina/iina-plugin-ytdl/blob/4132843888e8d1487178772afb730d2631cc41d8/src/global.ts#L49-L55

I'm considering adding an API to get all current player ids, or changing the behavior of setting `target` to `null`, so it can send messages to all existing players. Please feel free to leave any suggestions!

**Comment by whlsxl** [comment]
When I use `global.postMessage(null, "test", "test");` in `global.ts`, Intuitively this will sent to all the players.

> I'm considering adding an API to get all current player ids, or changing the behavior of setting target to null, so it can send messages to all existing players. Please feel free to leave any suggestions!

That's a good idea.

**Comment by brandon-fryslie** [comment]
> By current design, setting the target to null (global.postMessage(null, name, data)) will post message to all its child players created by global.createPlayerInstance().

It would be nice to put this in the docs.  I spent a couple hours trying to get this to work.

> If you want to send a message to an arbitrary player instance, the player must post a message to the global script first. In the global script, when received a message, it can obtain the player id and therefore communicate with the player using this id

It would save some boilerplate code if we could just call an API to get the list of all IDs.
