### ISSUE TITLE
IINA Closing when video starts playing.

### ISSUE THREAD

**Issue by hariharan605** [iina/iina#3869]
Attaching a Report from Mac OS .

[IINA.txt](https://github.com/iina/iina/files/9089872/IINA.txt)

**Comment by HarukaMa** [comment]
Looks like you are still running a very old version of IINA (1.1.2). Please try again with the latest version.

**Comment by hariharan605** [comment]
@HarukaMa Yes, Latest version seems to be working. Thanks!
