### ISSUE TITLE
Video Rotation shortcut

### ISSUE THREAD

**Issue by LeonardoGentile** [iina/iina#3871]
I can't seem to find a way to add keyboard shortcuts for the menu: Video/Rotation/ 0, 90, 180, 270.
Is this possible somehow? If not would it be feasible to add the option to let the user customize this menu item?

Thanks for the good work 👍

**Comment by low-batt** [comment]
Yes, it is possible to add key bindings for this.

See the discussion in closed issue #1168, in particular my response, https://github.com/iina/iina/issues/1168#issuecomment-1091009272. To get this working nicely you need to use the [Lua](https://www.lua.org/) script [cycle-video-rotate](https://github.com/VideoPlayerCode/mpv-tools/blob/master/scripts/cycle-video-rotate.lua) and bind keys to that script. See my response in #1168 for details.

**Comment by pleasejustgo** [comment]
Can't you just go to system preferences > keyboard > shortcuts in macOS and add a hotkey to any menu item?

**Comment by low-batt** [comment]
> Can't you just go to system preferences > keyboard > shortcuts in macOS and add a hotkey to any menu item?

Yes, that would work too. Of course for the case at hand you would have to add a shortcut key for each of the 4 menu items:

- `Video->Rotation->0°`
- `Video->Rotation->90°`
- `Video->Rotation->180°`
- `Video->Rotation->270°`

The script supports defining a "rotate left" and a "rotate right" key and correctly "wraps" if you keep pressing the key and rotate all the way around.

**Comment by eldridgepkwy** [comment]
According to [Rotate video by a keyboard shortcut in mpv](https://askubuntu.com/questions/1212733/rotate-video-by-a-keyboard-shortcut-in-mpv.)
I added `r cycle_values video-rotate 90 180 270 0 `to the end of custom_conf file in
`/Users/macOS_account_name/Library/'Application Support'/com.colliderli.iina/input_conf/custom_conf `which also works good.
The custom_conf is a dulicate config file from`  IINA Settings -> Key Bindings -> Select IINA Default(Or any default key binding) -> click Duplicate... button`
