### ISSUE TITLE
No option to change key binding config preference

### ISSUE THREAD

**Issue by FusionX9000** [iina/iina#3888]
**System and IINA version:** 

- macOS  12.4 Monterey
- IINA  1.3.0 

**Expected behavior:**
As per the wiki, I should have an option to change the configuration I want to use - https://github.com/iina/iina/wiki/Manage-Key-Bindings. See 1.

**Actual behavior:**
There is no option to set the configuration I want to use. 

https://i.imgur.com/HDRAoZu.png

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
1. Go to preferences.
2. Go to keybindings
3. There's no option to set key binding which will be used by IINA.

- [ ] MPV does not have this problem.

**How often does this happen?**
Always

**Comment by AManNeedsAMaid** [comment]
Why is this issue closed? As far as I can tell on IINA 1.3.1 and MacOS Ventura (13.1), this issue isn't resolved. Is there any kind of workaround to select mpv defaults?

**Comment by HarukaMa** [comment]
The issue here is the wiki is outdated. You always have the option to switch key binding presets, it's just the settings UI has been revamped before.
