### ISSUE TITLE
希望增加一个mac端投屏到智能电视的功能

### ISSUE THREAD

**Issue by duolabmeng6** [iina/iina#3892]
https://github.com/alexballas/go2tv

找到一个go实现的投屏代码希望可以加到播放器的中 已测试可用

**Comment by wisinfun** [comment]
我也很需要这个功能，希望作者大大考虑下

**Comment by duolabmeng6** [comment]
> 我也很需要这个功能，希望作者大大考虑下

https://github.com/duolabmeng6/easy_to_tv

我自己写了一个~~可以用的 没事
