### ISSUE TITLE
'Cannot open file or stream!' // works on yt and twitch but error on any other website

### ISSUE THREAD

**Issue by simonkidane** [iina/iina#3894]
Having a problem playing any video from a website. Youtube and twitch work but any other website pasted produces the error

- macOS 
version 12.4

- IINA 
1.3.0

**Expected behavior:**
iina plays the url

**Actual behavior:**
'Cannot open file or stream!'

<br>

<br>

**Steps to reproduce:**
1. copy video url
2. paste in IINA

**How often does this happen?**
Every time

**Comment by low-batt** [comment]
Did not reproduce for me.

I tried the following:
- I started IINA 1.3.0 build 132
- The welcome window appeared
- I clicked on `Open URL...`
- I dragged-n-dropped the URL for the [Vimeo](https://vimeo.com/) video [New York 8k | 4k HDR](https://vimeo.com/196168570)
- I clicked `Open`
- IINA started playing the video

Are you using the [yt-dlp](https://github.com/yt-dlp/yt-dlp) built into IINA? Or has IINA been configured to use a copy of `youtube-dl` installed on your machine? Open IINA `Preferences...`. Click on `Network`. Confirm that `Custom youtube-dl path` is not set.

**Comment by simonkidane** [comment]
> Did not reproduce for me.
> 
> I tried the following:
> 
> * I started IINA 1.3.0 build 132
> * The welcome window appeared
> * I clicked on `Open URL...`
> * I dragged-n-dropped the URL for the [Vimeo](https://vimeo.com/) video [New York 8k | 4k HDR](https://vimeo.com/196168570)
> * I clicked `Open`
> * IINA started playing the video
> 
> Are you using the [yt-dlp](https://github.com/yt-dlp/yt-dlp) built into IINA? Or has IINA been configured to use a copy of `youtube-dl` installed on your machine? Open IINA `Preferences...`. Click on `Network`. Confirm that `Custom youtube-dl path` is not set.

I just followed the yt-dlp link and downloaded it. Also, I dont have that path is empty and not set. Still not working, unfortunately. 

The video you linked works for me but something like this [Rick and Morty title](https://muchoflix.com/series/rick-and-morty/S05/E09) and sports livestreams don't work for me.

**Comment by low-batt** [comment]
Reproduced for me with that URL. This is what the failure looks like in the IINA log file:
```text
20:43:38.708 [iina][w] mpv log: [ytdl_hook] error: ERROR: Unsupported URL: https://muchoflix.com/series/rick-and-morty/S05/E09 
20:43:38.708 [player0][d] Track list changed
20:43:42.180 [player0][d] Write watch later config
20:43:42.196 [iina][w] mpv log: [ytdl_hook] error: youtube-dl failed: unexpected error occurred 
20:43:42.196 [iina][w] mpv log: [cplayer] error: Failed to recognize file format.
```

IINA 1.3.0 is embeds [yt-dlp](https://github.com/yt-dlp/yt-dlp) and uses it for streaming from web sites. If the latest version of `yt-dlp` works, then the issue is with the older version embedded in IINA. That preference I mentioned can be used to address that.

To test this I updated my copy of `yt-dlp` to the latest version:

```bash
low-batt@gag youtube-dl$ ./yt-dlp -U
Latest version: 2022.07.18, Current version: 2022.04.08
Current Build Hash 103e60f33d2602f90580a413a02e3348e4d17a46413acc3633b4ef9e3898d15a
Updating to version 2022.07.18 ...
Updated yt-dlp to version 2022.07.18; Restart yt-dlp to use the new version
```

And tried directly using `yt-dlp` to access that site:
```bash
low-batt@gag youtube-dl$ ./yt-dlp https://muchoflix.com/series/rick-and-morty/S05/E09
[generic] E09: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] E09: Extracting information
ERROR: Unsupported URL: https://muchoflix.com/series/rick-and-morty/S05/E09
low-batt@gag youtube-dl$ 
```

This tells us even the very latest version of `yt-dlp` is unable to work with that site. For IINA that makes this an "upstream" problem that has to be fixed in `yt-dlp`. 

The list of sites supported by `yt-dlp` can be found here: [Supported sites](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md#supported-sites). The site `muchoflix.com` is not in the list. For sites that `yt-dlp` does not support it falls back to a "generic information extractor" which may or may not be able to find the informstion `yt-dlp` requires. In this case that generic extractor was confused by this site and failed to find the information required.

You can request support for that site from the `yt-dlp` project here: [yt-dlp issues](https://github.com/yt-dlp/yt-dlp/issues)

**Comment by simonkidane** [comment]
> Reproduced for me with that URL. This is what the failure looks like in the IINA log file:
> 
> ```
> 20:43:38.708 [iina][w] mpv log: [ytdl_hook] error: ERROR: Unsupported URL: https://muchoflix.com/series/rick-and-morty/S05/E09 
> 20:43:38.708 [player0][d] Track list changed
> 20:43:42.180 [player0][d] Write watch later config
> 20:43:42.196 [iina][w] mpv log: [ytdl_hook] error: youtube-dl failed: unexpected error occurred 
> 20:43:42.196 [iina][w] mpv log: [cplayer] error: Failed to recognize file format.
> ```
> 
> IINA 1.3.0 is embeds [yt-dlp](https://github.com/yt-dlp/yt-dlp) and uses it for streaming from web sites. If the latest version of `yt-dlp` works, then the issue is with the older version embedded in IINA. That preference I mentioned can be used to address that.
> 
> To test this I updated my copy of `yt-dlp` to the latest version:
> 
> ```shell
> low-batt@gag youtube-dl$ ./yt-dlp -U
> Latest version: 2022.07.18, Current version: 2022.04.08
> Current Build Hash 103e60f33d2602f90580a413a02e3348e4d17a46413acc3633b4ef9e3898d15a
> Updating to version 2022.07.18 ...
> Updated yt-dlp to version 2022.07.18; Restart yt-dlp to use the new version
> ```
> 
> And tried directly using `yt-dlp` to access that site:
> 
> ```shell
> low-batt@gag youtube-dl$ ./yt-dlp https://muchoflix.com/series/rick-and-morty/S05/E09
> [generic] E09: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor.
> [generic] E09: Extracting information
> ERROR: Unsupported URL: https://muchoflix.com/series/rick-and-morty/S05/E09
> low-batt@gag youtube-dl$ 
> ```
> 
> This tells us even the very latest version of `yt-dlp` is unable to work with that site. For IINA that makes this an "upstream" problem that has to be fixed in `yt-dlp`.
> 
> The list of sites supported by `yt-dlp` can be found here: [Supported sites](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md#supported-sites). The site `muchoflix.com` is not in the list. For sites that `yt-dlp` does not support it falls back to a "generic information extractor" which may or may not be able to find the informstion `yt-dlp` requires. In this case that generic extractor was confused by this site and failed to find the information required.
> 
> You can request support for that site from the `yt-dlp` project here: [yt-dlp issues](https://github.com/yt-dlp/yt-dlp/issues)

I see. Thank you for the timely response!
