### ISSUE TITLE
Enable playback controls/seekbar in PiP mode

### ISSUE THREAD

**Issue by sujeet-agrahari** [iina/iina#3909]
**What you want IINA to do:**

It would be nice to have playback controls in PiP mode. Make video forward/backwards using arrow keys, or enable seek bar on hover. 

Please have look at the Floating player.

**What IINA does currently:**
It doesn't have the option to control the playback. It doesn't even pause on space bar press. 

**Why you think this should be added:**
It is very convenient to traverse through the video in PiP mode.

**Examples of other projects that have something similar:**
https://apps.apple.com/us/app/floating-picture-in-picture/id1508833245?mt=12

**Comment by uiryuu** [comment]
The app you provided is not using Apple's Picture-in-Picture framework, it just implements a floating window. Apple's PIP framework only provides standards controls. You can try to set "Always float on top while playing" in IINA.

**Comment by LampPrinter** [comment]
> The app you provided is not using Apple's Picture-in-Picture framework, it just implements a floating window. Apple's PIP framework only provides standards controls. You can try to set "Always float on top while playing" in IINA.

In Elmedia Player the PiP follows Apple' framework I guess. It provides standard controls but the PiP window still responds to backward and forward seek keys. Slightly handy.
Hope that can be implemented.
