### ISSUE TITLE
Url scheme open weblink with multi query params

### ISSUE THREAD

**Issue by Taosky** [iina/iina#3922]
**What you want IINA to do:**
When I used 'iina://weblink?url' open my nginx file link, it not worked.

My file link is formated by  ngx_http_secure_link_module, it has two query params :'md5' and 'expires'.

So the full url just like `iina://weblink?url=http://192.168.2.xx/share/xxxxx/video.mkv?md5=e5paPslqW6D3bwsCjk-klw&expires=212312344`

IINA treated the first parameter as a link param and the second param as a paramof the url scheme itself.

So is there any way to correctly parse the params of the video link?

**Comment by xjbeta** [comment]
`iina://weblink?url=http%3A%2F%2F192.168.2.xx%2Fshare%2Fxxxxx%2Fvideo.mkv%3Fmd5=e5paPslqW6D3bwsCjk-klw&expires=212312344`
encode the parameter value

**Comment by Taosky** [comment]
> `iina://weblink?url=http%3A%2F%2F192.168.2.xx%2Fshare%2Fxxxxx%2Fvideo.mkv%3Fmd5=e5paPslqW6D3bwsCjk-klw&expires=212312344` encode the parameter value

It worked! Thanks a lot!
