### ISSUE TITLE
Spatial Audio Support

### ISSUE THREAD

**Issue by byGits** [iina/iina#3933]
Thanks to your recent update IINA is back in business, and even supports HDR!
The only thing I wish it would support is "Spatial Audio" (both Fixed and Head-tracked)

Using Apple headsets/headphones, or even speakers on new Macbooks the Spatial Audio makes it a great audio experience (for any video with 5.1 or 7.1 audio, dolby etc.).

Currently I know one 3rd-party player that supports this:
Infuse Pro (App Store)

First parties are of course "Music" app and "Apple TV" app.

**Comment by low-batt** [comment]
IINA is a graphical user interface for [mpv](https://mpv.io/).  The mpv player is intended to primarily be used from the command line. It has a small controller on top of the video for basic control. The mpv project provides a library that can be embedded in other applications for video/audio playback. IINA provides a full GUI for mpv as well as some other features such as downloading subtitles.

What this means for the issue at hand is that mpv must first be updated to support spatial audio. Once mpv has added support, IINA would need to be updated to use it.

Such support has been requested of mpv in issue https://github.com/mpv-player/mpv/issues/9252

**Comment by michael1006** [comment]
Has there been any progress on this? In the MPV issue it looks like another player, KSPlayer, has possibly added the relevant code to support spatial audio? See https://github.com/mpv-player/mpv/issues/9252#issuecomment-1445167945

I had to switch to Infuse because of its support for spatial audio. :( I'm waiting to be able to come back to IINA once this gets enabled.

**Comment by low-batt** [comment]
As IINA uses a library from the [mpv](https://mpv.io/) project for audio/video support, IINA has to wait for mpv to add support for spatial audio and release a new version. Once that happens then IINA will need to upgrade to the new version of mvp and make any changes needed to support spatial audio.

Checking the mvp project, issue https://github.com/mpv-player/mpv/issues/9252 still seems like the correct issue to monitor for progress.

**Comment by uiryuu** [comment]
Track in #3444

**Comment by xuio** [comment]
any update on this? it seems that mpv supports spatial audio now

**Comment by low-batt** [comment]
The main issue for this is #3444.  In [this comment](https://github.com/iina/iina/issues/3444#issuecomment-2301477510) there is a screenshot showing the new `Audio driver` setting that allows you to switch to the `AVFoundation` audio driver that supports Spatial Audio. Spatial Audio has been tested with this driver and is working. This driver is considered experimental.
