### ISSUE TITLE
Latest IINA video freezing on macOS Ventura beta

### ISSUE THREAD

**Issue by ans87gh** [iina/iina#3942]
**System and IINA version:**

- macOS 13.0 Beta 22A5342f
- IINA 1.3.0 Build 132

**Expected behavior:**
Normal play, pause, forward,  backward; general playback

**Actual behavior:**
app randomly freezes video while audio continues; requires forced quit to start video again. Any attempt to pause using external factors (headset, play pause in menu bar) does not work.

Issue has been happening ever since developer beta was installed. Even after the latest release, issue persists. Attempted clean install of app; did not resolve issue.

<details>
<summary><b>Crash report:</b></summary>
[no crash log found in directory]

</details>

<br>

<details>
<summary><b>mpv log:</b></summary>
[   0.005][v][cplayer] mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
[   0.005][v][cplayer]  built on Sat May 28 15:57:18 UTC 2022
[   0.005][v][cplayer] FFmpeg library versions:
[   0.005][v][cplayer]    libavutil       56.70.100
[   0.005][v][cplayer]    libavcodec      58.134.100
[   0.005][v][cplayer]    libavformat     58.76.100
[   0.005][v][cplayer]    libswscale      5.9.100
[   0.005][v][cplayer]    libavfilter     7.110.100
[   0.005][v][cplayer]    libswresample   3.9.100
[   0.005][v][cplayer] FFmpeg version: 4.4.2
[   0.005][v][cplayer] 
[   0.005][v][cplayer] Configuration: waf configure --prefix=/opt/homebrew/Cellar/mpv-iina/0.34.1 --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-uchardet --enable-libbluray --disable-swift --disable-debug-build --disable-macos-media-player --confdir=/opt/homebrew/etc/mpv --datadir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/mpv-iina --mandir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/man --docdir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/doc/mpv-iina --lua=luajit
[   0.005][v][cplayer] List of enabled features: asm bsd-fstatfs build-date cocoa coreaudio cplayer cplugins ffmpeg ffmpeg-aviocontext-bytes-read gl gl-cocoa glob glob-posix gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared lua luajit macos-10-11-features macos-10-12-2-features macos-10-14-features macos-touchbar optimize osx-thread-name plain-gl posix posix-or-mingw pthreads rubberband stdatomic uchardet vector videotoolbox-gl videotoolbox-hwaccel zimg zlib
[   0.005][v][cplayer] mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
[   0.005][v][cplayer]  built on Sat May 28 15:57:18 UTC 2022
[   0.005][v][cplayer] FFmpeg library versions:
[   0.005][v][cplayer]    libavutil       56.70.100
[   0.005][v][cplayer]    libavcodec      58.134.100
[   0.005][v][cplayer]    libavformat     58.76.100
[   0.005][v][cplayer]    libswscale      5.9.100
[   0.005][v][cplayer]    libavfilter     7.110.100
[   0.005][v][cplayer]    libswresample   3.9.100
[   0.005][v][cplayer] FFmpeg version: 4.4.2
[   0.005][v][cplayer] 
[   0.005][v][cplayer] Configuration: waf configure --prefix=/opt/homebrew/Cellar/mpv-iina/0.34.1 --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-uchardet --enable-libbluray --disable-swift --disable-debug-build --disable-macos-media-player --confdir=/opt/homebrew/etc/mpv --datadir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/mpv-iina --mandir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/man --docdir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/doc/mpv-iina --lua=luajit
[   0.005][v][cplayer] List of enabled features: asm bsd-fstatfs build-date cocoa coreaudio cplayer cplugins ffmpeg ffmpeg-aviocontext-bytes-read gl gl-cocoa glob glob-posix gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared lua luajit macos-10-11-features macos-10-12-2-features macos-10-14-features macos-touchbar optimize osx-thread-name plain-gl posix posix-or-mingw pthreads rubberband stdatomic uchardet vector videotoolbox-gl videotoolbox-hwaccel zimg zlib
[   0.005][d][global] config path: '' -> '-'
[   0.005][d][global] user path: '~~home/' -> ''
[   0.005][d][global] user path: '~~old_home/' -> ''
[   0.005][d][global] user path: '/Applications/IINA.app/Contents/Resources/config/iina-default-input.conf' -> '/Applications/IINA.app/Contents/Resources/config/iina-default-input.conf'
[   0.005][v][bdmv/bluray] Opening /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.005][v][file] Opening /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.005][d][file] resize stream to 131072 bytes, drop 0 bytes
[   0.005][d][file] Stream opened successfully.
[   0.005][v][input] Parsing input config file /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.005][v][input] Input config file /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf parsed: 69 binds
[   0.005][d][global] user path: '/Users/home/Library/Logs/com.colliderli.iina/2022-09-13-23-33-59_OcApin/mpv.log' -> '/Users/home/Library/Logs/com.colliderli.iina/2022-09-13-23-33-59_OcApin/mpv.log'
[   0.005][d][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.005][d][stats] Loading lua script @stats.lua...
[   0.005][d][console] Loading lua script @console.lua...
[   0.005][d][auto_profiles] Loading lua script @auto_profiles.lua...
[   0.005][d][osx] Exiting...
[   0.005][d][ytdl_hook] loading mp.defaults
[   0.005][d][auto_profiles] loading mp.defaults
[   0.006][d][stats] loading mp.defaults
[   0.006][v][cplayer] Set property: vo="libmpv" -> 1
[   0.006][d][console] loading mp.defaults
[   0.006][v][cplayer] Set property: keepaspect="no" -> 1
[   0.006][v][cplayer] Set property: gpu-hwdec-interop="auto" -> 1
[   0.006][d][auto_profiles] loading @auto_profiles.lua
[   0.006][d][ytdl_hook] loading @ytdl_hook.lua
[   0.006][d][stats] loading @stats.lua
[   0.006][d][console] loading @console.lua
[   0.006][d][ytdl_hook] reading options for ytdl_hook 
[   0.006][d][ytdl_hook] script-opts/ytdl_hook.conf not found. 
[   0.006][d][ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[   0.007][d][stats] reading options for stats 
[   0.007][d][stats] script-opts/stats.conf not found. 
[   0.007][d][stats] lua-settings/stats.conf not found. 
[   0.098][v][ao/coreaudio] selected audio output device: AirPods Pro (92)
[   0.101][d][console] reading options for console 
[   0.101][d][console] script-opts/console.conf not found. 
[   0.101][d][console] lua-settings/console.conf not found. 
[   0.101][d][auto_profiles] Exiting...
[   0.101][d][cplayer] Run command: define-section, flags=64, args=[name="input_console", contents="", flags="default"]
[   0.101][d][cplayer] Run command: enable-section, flags=64, args=[name="input_console", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.101][d][cplayer] Run command: define-section, flags=64, args=[name="input_forced_console", contents="", flags="force"]
[   0.101][d][cplayer] Run command: enable-section, flags=64, args=[name="input_forced_console", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.101][v][cplayer] Waiting for scripts...
[   0.101][d][osd/libass] ASS library version: 0x1502000 (runtime 0x1502000)
[   0.101][v][osd/libass] libass API version: 0x1502000
[   0.101][v][osd/libass] libass source: tarball: 0.15.2
[   0.102][v][osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 4.2.1 (COMPLEX)
[   0.102][v][osd/libass] Setting up fonts...
[   0.102][v][osd/libass] Using font provider coretext
[   0.102][v][osd/libass] Done.
[   0.102][d][cplayer] Run command: define-section, flags=64, args=[name="input_stats", contents="", flags="default"]
[   0.102][d][cplayer] Run command: enable-section, flags=64, args=[name="input_stats", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.102][d][cplayer] Run command: define-section, flags=64, args=[name="input_forced_stats", contents="", flags="force"]
[   0.102][d][cplayer] Run command: enable-section, flags=64, args=[name="input_forced_stats", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.102][v][cplayer] Done loading scripts.

</details>

<br>

**Steps to reproduce:**
Play any video, usually at an accelerated playback speed. Attempt scrubbing through the video and toggling fullscreen on and off. The video will eventually freeze.

- [ ] MPV does not have this problem.

**How often does this happen?**
Every time

**Comment by low-batt** [comment]
This is issue #3931, which was closed by the submitter. The mpv player also has the same problem, reported in issue https://github.com/mpv-player/mpv/issues/10579. We've heard that Apple plans to revert the offending change, which was added in Beta 6, but the issue was reported too late to get this fixed for Beta 7. Hopefully this will be corrected in the next release of Ventura.

**Comment by revunix** [comment]
13.0 Beta 8 (22A5352e) is out, I think it's fixed now. Can someone else confirm?!

**Comment by GreyAsteroid** [comment]
> 13.0 Beta 8 (22A5352e) is out, I think it's fixed now. Can someone else confirm?!

All good on my machine 👍

**Comment by low-batt** [comment]
Thanks to everyone for confirming Apple has fixed this as of Ventura Beta 8.

**Comment by Fishel-The-Genius** [comment]
I installed Ventura today and Whenever I open a Window, switch between full-screen mode, or hit "Play" the app freezes for a few seconds.

I'm using the latest version of the app (1.3.0)

**Comment by low-batt** [comment]
@Fishel-The-Genius I have entered issue #4011 for your report as this closed issue concerns Beta 8.
