### ISSUE TITLE
Please add syncplay support!

### ISSUE THREAD

**Issue by winfr34k** [iina/iina#396]
Hi,

as using syncplay (https://syncplay.pl) is really difficult on Mac OS X, it would be AMAZING if you could integrate it into this app!

Thanks and best regards,

Thomas

**Comment by albertoxamin** [comment]
I feel like in times of quarantine, this feature should have some more priority.

**Comment by albertosottile** [comment]
Syncplay 1.6.7 will add support for IINA. The first beta of this release is avaliable here: https://github.com/Syncplay/syncplay/releases/tag/v1.6.7-Beta1. Any feedback would be truly appreciated!

**Comment by albertoxamin** [comment]
> Syncplay 1.6.7 will add support for IINA. The first beta of this release is avaliable here: https://github.com/Syncplay/syncplay/releases/tag/v1.6.7-Beta1. Any feedback would be truly appreciated!

Awesome! I quickly tried loading media and playing/pausing and seems to register the actions on syncplay. Will try a real movie soon.

at this point @winfr34k @alejx I think this issue could be closed.

Thanks @albertosottile
