### ISSUE TITLE
"Reveal in Finder" should be renamed to "Show in Finder"

### ISSUE THREAD

**Issue by svobs** [iina/iina#3976]
**System and IINA version:**

- macOS 12.6
- IINA 1.3.0 Build 132

Not sure when it happened, but the standard English language label for this functionality appears to be "Show in Finder", not "Reveal in Finder". IINA should be updated to match.

Examples:

1. Open Chrome. Go to "chrome://downloads/"
2. Open a project in XCode. Right-click on a file in the Navigator.
3. Right-click on any application in the Dock > Options > Show in Finder

**Expected behavior:**
Preferences > Key Bindings has a button labeled "Show config file in Finder".
File > Playback History -> (right-click on a row in Player History window) > context menu has an item labelled "Show in Finder"
Preferences > Plugins has a button labeled "Show in Finder"

**Actual behavior:**
Preferences > Key Bindings has a button labeled "Reveal config file in Finder"
File > Playback History -> (right-click on a row in Player History window) > context menu has an item labelled "Reveal in Finder"
Preferences > Plugins has a button labeled "Reveal in Finder"

**Comment by low-batt** [comment]
Other actions in IINA that bring up a `Finder` window:
-  `Go to Screenshot Folder` in the `Video` menu
- `Open log directory` in `Advanced` preferences

**Comment by uiryuu** [comment]
I'll try to make a fix. It might be complicated than just renaming the texts since I also want to rename the corresponding key (`pl_menu.reveal_in_finder`), and I'm not sure how Crowdin would handle such key change.

**Comment by uiryuu** [comment]
`"alert.config.file_existing.message" = "This should not happen. Choose OK to overwrite, Cancel to reveal the file in Finder.";`
Another "reveal" spotted.

**Comment by uiryuu** [comment]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/20237141/195552216-b988c737-4fb1-4555-8463-bbccfc944adf.png">
This is in the OSD after a screenshot is taken. What do you guys think about this one? (I'm not a native English speaker)

**Comment by svobs** [comment]
> This is in the OSD after a screenshot is taken. What do you guys think about this one? (I'm not a native English speaker)

My vote is to change to "Show" as well. It looks like another case of "Show in Finder" functionality, but due to the limited space and use of block character font it makes sense to shorten it to one word - to avoid ambiguity about the bounds of the button/link.

**Comment by svobs** [comment]
Slightly unrelated, but thought this was helpful: [guidelines for the use of "Show" vs. "Reveal" vs "Indicate" in research papers](https://www.editage.com/insights/scientific-writing-difference-between-to-reveal-to-show-and-to-indicate#:~:text=Therefore%2C%20use%20%22reveal%22%20to,you%20can't%20be%20sure.):
> **_"Show"_** is perhaps the plainest of the three. Use it when the statement obviously follows from the source...
> ...Use _**"reveal"**_ to convey that it took some analysis or interpretation of the data to arrive at the conclusion.
> _**"Indicate"**_ is similar to "show" but introduces a note of uncertainty: that the data leads you to suspect something but you can't be sure. 

Maybe Apple's original thought was that using "reveal" instead of "show" would help indicate that it would involve going outside the current application. But the word itself didn't lend anything to indicate that, other than being different; the user would have to learn that over time, and it wasn't a feature which had common enough use for that to be worthwhile.

**Comment by low-batt** [comment]
This is fixed in the released version of IINA.
