### ISSUE TITLE
Add hidden info about the build to the About window

### ISSUE THREAD

**Issue by low-batt** [iina/iina#3977]
**What you want IINA to do:**
Provide a way to view information that identifies a development build in the UI.

**What IINA does currently:**
Depending upon the nature of changes in a development build it may be very difficult to tell from the UI that you are not running the official release.

**Why you think this should be added:**
Some developers take development builds to other Macs in order to:
- Test under a different version of macOS
- Test for a long time under normal use

When doing such testing it is desirable to have a way to easily identify development builds.

One way to address this would be to add the build date and the git branch from which the build was done to the `About` window. As this information is only needed by developers it would be hidden by default. To reveal it a developer would option-click between the mpv version and the `License` button.

This proposal builds upon the logging of such information proposed by issue #3970.

**Examples of other projects that have something similar:**
I looked, but did not find a standard convention for identifying developer builds of Mac applications.

[Semantic Versioning](https://semver.org/#semantic-versioning-200) specifies a way to include [build metadata](https://semver.org/#spec-item-10) in a version number. But such techniques can not be used in an Apple version number.

Revealing hidden information in an about window can be seen in the `About This Mac` window. Clicking on the macOS version reveals the build number as discussed in [Find out which macOS your Mac is using](https://support.apple.com/en-us/HT201260)

Using option-click to reveal additional information is also used in macOS. If you option-click the Wi-Fi icon in the menu bar additional details about the connection are shown.

As this build information is not useful to the user using the released version of IINA revealing should require more than a simple click.

I have changes that add this to IINA's `About` window. As this builds upon the changes in PR #3971 I will prepare a PR once that PR has been merged (assuming it is approved).

**Comment by low-batt** [comment]
This is what the `About` window would look like with the changes I will propose after revealing the hidden build information:
![issue-3977](https://user-images.githubusercontent.com/86170219/194932575-94fdbd49-5991-4974-a85b-230d9284041a.jpg)

**Comment by uiryuu** [comment]
What about adding FFmpeg version as well?

**Comment by low-batt** [comment]
Yes, I can add the FFmpeg version. I'm expecting the FFmpeg would not be a part of the hidden information but would be on the same line that has the mpv version?

I just rebased PR #3971 fixed the merge conflicts due to the build changes. Need to get that one merged so I can prepare a PR for this issue.

**Comment by low-batt** [comment]
See the PR for updated screenshots of what the About window looks like with the proposed change.

**Comment by low-batt** [comment]
IINA 1.3.2 includes this enhancement. A decision was made to not hide the information, so the additional information is always visible.
