### ISSUE TITLE
Import Playlist? How?

### ISSUE THREAD

**Issue by hawkiboy** [iina/iina#3978]
I noticed another request for 'maintaining imported playlist order'.... Well can you even import a playlist? I find it strange that you can export a playlist but there doesn't seem to be any option for importing it again....

**Comment by low-batt** [comment]
Open the playlist `.m3u8` file with IINA like you would other media files.

**Comment by hawkiboy** [comment]
Thanks. Under file menu use 'open in new window'. Got it. thanks. Not sure why it is in a 'new window' and not in the current window. Pretty non-intuitive. Every other way of opening a file will not recognize the .m3u8. Seems like you should be able to add the playlist to the current playlist using 'add file.
Of course I can set finder to always open with and do it from there too.
