### ISSUE TITLE
Plugin menu key equivalents do not take effect until Plugin menu is clicked on

### ISSUE THREAD

**Issue by svobs** [iina/iina#3994]
**System and IINA version:**

- macOS 12.6
- IINA 1.3.0 `develop` branch, commit d0ef0d41232b4e07892b13449f3165c897edfa7c

**Expected behavior:**
Key bindings in the Plugin menu should take effect as soon as they are applicable.

**Actual behavior:**
After opening IINA, the user must open the Plugin menu at least once in order for any plugin key bindings to work.

**Steps to reproduce:**

1. Download latest code from the `develop` branch, build with XCode, enable plugins
2. Open IINA, go to `Preferences` > `Plugins` > `Install from Github...`, and install demo plugin: https://github.com/lhc70000/iina-plugin-demo
3. Quit and reopen IINA.
4. Without touching the Plugin menu, begin playing a video.
5. Press `Option`+`d`. See that nothing new is displayed over the video.
6. Click on Plugin menu and then close it.
7. Then press `Option`+`d` again. See that an overlay is displayed. 

**How often does this happen?**
Always

**Comment by svobs** [comment]
Some observations from digging through the code. Looks like this feature maybe wasn't 100% completed.

- The Plugin menu is populated by `MenuController::updatePluginMenu()`, which is where the key equivalent is set.
- This is either called by `JavascriptAPIMenu::forceUpdate()` (which isn't automatically called by anything), or by `menuWillOpen()`, which explains the current behavior.
- And `MenuController` has a boolean variable, `pluginMenuNeedsUpdate`, which is set in several places but is never consulted for anything.
- The other menu items are set either by `bindMenuItems()` at startup, by `updateKeyEquivalentsFrom()` when key bindings change, or both.
- Menu items from plugins might be a little different though, because it looks like they can be attached to a specific player, which can have its own unique set of plugin instances. So it might also be necessary to re-evaluate the Plugin menu contents each time a player window gains focus, if just to guarantee that the bindings will be updated.

**Comment by low-batt** [comment]
This is fixed in the released version of IINA.
