### ISSUE TITLE
Possible improvements to sidebar organization

### ISSUE THREAD

**Issue by svobs** [iina/iina#4000]
**What you want IINA to do:**

Change wording in UI to reflect that there is only one side panel, and things take up space inside it.
Instead of "Quick Settings Panel", use "Sidebar" or "Side Panel".
Instead of "Show X Panel", say "Show X in Sidebar", or simply "Show in Sidebar".
Make it smoother to switch between all the settings panes when the sidebar is already open.

Consider referring to the side panel generically as "Side Panel" or "Sidebar". Change names of each tab to "Show X in Sidebar", e.g., "Show Playlist in Sidebar", "Show Video Settings in Sidebar", or "Video" > "Show in Sidebar"
Decided to file this as its own enhancement request rather than reply to the discussion for PR #3980. There was some discussion about how to name each of the various panels which open from the right of the window. 

**What IINA does currently:**

Right now it looks like there are two panels, which each contain a set of tabs, for 5 in total:
- "Video", "Audio", and "Subtitles" (currently collectively referred to as "Quick Settings Panel")
- "Playlist" and "Chapters" (no collective name...?)
<img width="351" alt="Screen Shot 2022-10-16 at 20 28 18" src="https://user-images.githubusercontent.com/2213815/196083674-276433c1-5d01-4806-959e-366d9cd3d2a4.png">  <img width="353" alt="Screen Shot 2022-10-16 at 20 28 34" src="https://user-images.githubusercontent.com/2213815/196083737-d5387273-f156-4ad7-ab08-c8daf58af8a3.png">

Also (and I know this is starting to reach) what are opinions on including:

1. A button or something inside the sidebar to close it. Having to press the `ESC` key or dig into the menu again to close it feels a little but un-Mac-like.
2. Having a way to access all 5 of the tabs from within the sidebar? It could take one of several forms and wouldn't have to involve grouping all the tabs together. Maybe there could be a small icon to the right of the Quick Settings tabs which would change to the Playlist view (which would then allow access to Chapters) or something like that.

**Why you think this should be added:**

This was in response to @low-batt and @uiryuu's comments in #3980, which got the ideas flowing, but also based on my recent experience as a new IINA user trying to figure out how to navigate all this stuff. And this is stuff I'd volunteer to help develop, so long as there is consensus.

**Examples of other projects that have something similar:**

* Apple uses the term "Sidebar" consistently in Finder, Pages, Mail (although not XCode), and has [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/components/navigation-and-search/sidebars/) for it
* Google Chrome recently added a "Side Panel", with a toolbar button to toggle hiding/showing it.

**Comment by low-batt** [comment]
Late here. So my post may not be coherent....

Some quick thoughts...

> 3. User selects Playback > Show Chapters Panel. Nothing happens.

Not when I tried it. The panel changes to the `PLAYLIST`/`CHAPTERS` panel with `CHAPTERS` selected.

> 1. A button or something inside the sidebar to close it. Having to press the ESC key or dig into the menu again to close it feels a little but un-Mac-like.

Clicking on the window away from the panel closes it.

This is not a [Sidebar](https://developer.apple.com/design/human-interface-guidelines/components/navigation-and-search/sidebars/)? I believe something like the left side of the `Preferences` panel is what the HIG is referring to.

The menu items are being changed to:
- `Show Video Panel`
- `Show Audio Panel`
- `Show Subtitles Panel`

To match up with:
- `Show Playlist Panel`
- `Show Chapters Panel`

And all of them will switch to `Hide` instead of `Show` if the panel is being shown with the corresponding tab selected.

It seems the current German `MainMenu.strings` localization file does not contain a translation of `Show Quick Settings Panel`. It contains:
- `Videoeinstellungen`
- `Audioeinstellungen`
- `Untertiteleinstellungen`

"Video settings", "Audio settings" and "Subtitle settings"

The term `Panel` does bother me. It is more of a developer term than "settings".

Questioning naming brings up issue #2098. My thoughts on this issue is that it is more important that naming in IINA be consistent with mpv. So I am not in favor of a change that would cause IINA to not match up with mpv.

On the panel itself, there are lots of issues requesting the ability to move it outside of the window.

**Comment by svobs** [comment]
> This is not a [Sidebar](https://developer.apple.com/design/human-interface-guidelines/components/navigation-and-search/sidebars/)? I believe something like the left side of the Preferences panel is what the HIG is referring to.

OK, I dug a little deeper, and to be fair it does look like Apple is kind of specific about the styling of what it considers a "sidebar" - and that seems to limit it to a list of items which are hierarchically related to the "main" contents of the window. So `Playlist` and `Chapters` would qualify, but not the others.

My point wasn't that we should necessarily surrender and let Apple decide what a "side panel" is, any more than we should reject a toolbar which includes buttons and text fields and other "non-tool" items. It's a useful name because of the the "side" part - it gives you a strong hint about where it is. I don't really like `Panel` either, and `Bar` is appealing because it's compact.

But I suppose all of my arguments for `Sidebar` go away if we make the assumption that the locations of these settings tabs will be configurable. Having a playlist which is either a separate window or (preferred) embedded in the window but not overlapping the video is a feature high on my list of wants. But what might that look like? Seems like the most flexible solution would  be to allow the user to choose the location of each tab by itself, so that if they wanted, they could have the `Video`, `Audio`, and "Subtitle" settings side by side in a separate window, or have all 5 settings in separate windows, or all in the same sidebar, and any combination in between. But maybe a more sane approach would be to just to start with one allowed selection for each of the two sets of tabs.... Will investigate how difficult that might be.

> Questioning naming brings up issue https://github.com/iina/iina/issues/2098. My thoughts on this issue is that it is more important that naming in IINA be consistent with mpv. So I am not in favor of a change that would cause IINA to not match up with mpv.

Interesting. I'll bite. I generally agree with your point. But for the issue highlighted my opinion is for IINA's "queue" to actually try harder to be more like a playlist. For example, I agree with the requestor of #3951, that the shuffle setting should persist across launches. More than that, I'd like to see that if a user opens a file, and has `Add files in the same folder automatically` checked (so that a dynamic playlist is created from the items in that folder), then hits the `Shuffle` button, then quits and re-launches IINA, that same playlist in the same shuffled order should still be there. In other words, in the interest of maintaining application state across launches, the "queue" should be treated more like a playlist - just one that can get easily overwritten.

> > User selects Playback > Show Chapters Panel. Nothing happens.

> Not when I tried it. The panel changes to the PLAYLIST/CHAPTERS panel with CHAPTERS selected.

> > A button or something inside the sidebar to close it. Having to press the ESC key or dig into the menu again to close it feels a little but un-Mac-like.

> Clicking on the window away from the panel closes it.

Interesting... I just confirmed you're right - about 1.3.0 Build 131 (the last release) - but I'm getting said behavior on the `develop` branch. In addition to that, over half of the time it takes more than one click to dismiss the panel.

Can you let me know if you see the correct behavior in `develop`? I will try to see if I can isolate it. I've deleted my comments from the above but will enter them into a new issue if warranted.

**Comment by svobs** [comment]
Update: @low-batt take a look at #4001

**Comment by low-batt** [comment]
This is proof that I was sleepy when I replied last night.
I had encountered the problem and knew about the fix from @uiryuu.
Totally forgot about it when replying.
Sorry!

Preserving playlist state sounds like a useful feature.

**Comment by svobs** [comment]
No problem, it happens when things move fast! I'm happy that it's already fixed :)

...Kind of like this issue. I don't think there's enough meat left in it to merit keeping it open, but I got what I needed out of it.
