### ISSUE TITLE
Regression: toggling between side panels doesn't always work

### ISSUE THREAD

**Issue by svobs** [iina/iina#4001]
**System and IINA version:**

- macOS 12.6
- IINA `develop` branch, 6da6a3f410d8733119aa29303fad306552575f31

**Expected behavior:**

Of these 5 menu items:

1. `Playback` > `Show Playlist Panel`
2. `Playback` > `Show Chapters Panel`
3. `Video` > `Show Quick Settings Panel`
4. `Audio` > `Show Quick Settings Panel`
5. `Subtitles` > `Show Quick Settings Panel`

The following behavior is expected:

1. If no panels are shown and the user selects one of the actions above, the side panel should open and show that tab.
2. If the panel is open and showing the tab for action X, and action X is chosen, the panel should close.
3. If the panel is open and showing the tab for action X, and some action Y above (which is not action X) is chosen, the panel should show the tab for action Y.

**Actual behavior:**
See below.

**Steps to reproduce:**
1. Open IINA and begin playing a video.
2. Select `Video` > `Show Quick Settings Panel`. _The sidebar correctly opens to the `Video` tab._
3. Select `Audio` > `Show Quick Settings Panel`. _The sidebar correctly changes to the `Audio` tab._
4. Select `Playback` > `Show Chapters Panel`. _Nothing happens._

Repeating step 4 again sometimes closes the panel, and then repeating it one more time succeeds and shows `Chapters`. Although not always. Sometimes it continues to do nothing after several tries.

**How often does this happen?**

For me, following the steps above always resulted in incorrect results, although seems like there's some randomness to the results.

It seems to have problems when opening one of the `Playback` items when one of the `Quick Settings` items is showing, or vice versa. Moving between tabs which are displayed seems to work ok.

Changing from `Audio` to `Playlist` seems more reliable than from `Audio` to `Chapters`. Didn't try every combo.

It looks like the regression happened as part of the plugin system. I did some builds and confirmed it's present in 
6b09227d153a7a78a55f320e5e9a9cbbe30bd1ed, but not in 2a024281b64c6f52c84aec8e4c5c01978422514c, so it looks like the refactoring for the plugin system broke something, and the problem occurs even with `iinaEnablePluginSystem=no`.

I'm not at all familiar with this section of the code and will be busy with other things for a few days, if someone wants to investigate. Otherwise I'll take a look later in the week.

**Comment by uiryuu** [comment]
I've pushed a fix related to this on https://github.com/iina/iina/pull/3980, can you try on this branch?

**Comment by svobs** [comment]
> I've pushed a fix related to this on https://github.com/iina/iina/pull/3980, can you try on this branch?

Confirmed - looks like it is fixed. Thanks.
