### ISSUE TITLE
Make the second subtitle position adjustable

### ISSUE THREAD

**Issue by weiweihuanghuang** [iina/iina#4009]
Make the second subtitle position adjustable.

IINA currently defaults the second subtitle position to the top.

This feature should be added so that the second subtitle can be adjusted to a more readable position. Currently the second subtitle isn't useful if it defaults to the top.

Daum PotPlayer has the functionality to adjust the second subtitle position.

**Comment by low-batt** [comment]
IINA is a graphical user interface for the [mpv player](https://mpv.io/).  The mpv player is intended to primarily be used from the command line. It has a small controller on top of the video for basic control. The mpv project provides a library that can be embedded in other applications for video/audio playback. Using that library, IINA provides a full GUI for mpv as well as some of its own features such as downloading subtitles.

Rendering subtitles is a part of video playback. When it comes to how subtitles are embedded in the video IINA can only provide the features mpv provides for controlling subtitles. The available features can be found in the [subtitles](https://mpv.io/manual/stable/#subtitles) section of the [mpv manual](https://mpv.io/manual/stable/).

IINA is using mpv's [secondary-sid](https://mpv.io/manual/stable/#options-secondary-sid) option:
> -**-secondary-sid=<ID|auto|no>**
>
>  Select a secondary subtitle stream. This is similar to --sid. If a secondary subtitle is selected, it will be rendered as toptitle (i.e. on the top of the screen) alongside the normal subtitle, and provides a way to render two subtitles at once.

As this mpv issue [#3022](https://github.com/mpv-player/mpv/issues/3022) "support for secondary subtitle streams not forced to top" is still open, I don't think there is a way yet to control the position of the secondary subtitle.

For IINA this a an "upstream" issue. This feature must be added to mpv. Then mpv would have to include the new feature in a release. At that point IINA could upgrade the mpv library it embeds, gaining support for the new issue.

**Comment by low-batt** [comment]
The `master` branch of `mpv` now supports a [secondary-sub-pos](https://mpv.io/manual/master/#options-secondary-sub-pos) option. This is an important step in adding this functionality to IINA.

**Comment by Kyvrel** [comment]
+1

**Comment by low-batt** [comment]
I try not to talk about future releases because they are not set in concrete and definitely subject to change. What I can say is that the next IINA release will be a bug fix release where IINA's dependencies will not be updated. After that we should start work on the long planned feature release. No promises but that _might_ include a user interface for the new controls `mpv` has added for secondary subtitles.

**Comment by low-batt** [comment]
Support for adusting the position of the secondary subtitle has been added to IINA in the `develop` branch and is expected to be included in the upcoming feature release.

**Comment by saintyoseph** [comment]
Is there any news here? I just installed and started to use IINA, it is an awesome player. I quit VLC now. I wanted to use second subtitle but their position with first subtitle are so close to each other, I want to change position of second subtitle but I couldn't see any option in the settings. I hope this feature will be added soon. Thanks for everyone who helped this app to develop.

**Comment by low-batt** [comment]
Support is present in IINA 1.4.0 which was just released.
