### ISSUE TITLE
全屏看视频会变暗

### ISSUE THREAD

**Issue by smartes0** [iina/iina#4013]
#一些视频全屏以后不动鼠标就会突然屏幕变暗怎么办

**Comment by singh-jagjot** [comment]
Similar to issue 4014 [https://github.com/iina/iina/issues/4014](url)

**Comment by low-batt** [comment]
以英语为母语的人使用在线翻译器回答......

正如@singh-jagjot所指出的，描述的行为与macOS Ventura下全屏播放HDR视频时出现的问题相吻合。这个问题已经在多个问题中被报告，包括#4014。

我们目前正在努力为IINA增加一个解决这个问题的方法。

As @singh-jagjot indicated the described behavior matches a problem seen under macOS Ventura when playing HDR videos in full screen. This has been reported in multiple issues including #4014.

We are currently working on adding a workaround to IINA for this problem.

**Comment by lty2008one** [comment]
暂时可以通过

**Comment by uiryuu** [comment]
See #4014, closing
