### ISSUE TITLE
Layout errors in Settings > UI tab

### ISSUE THREAD

**Issue by svobs** [iina/iina#4033]
**System and IINA version:**

- macOS 13.0
- IINA `develop` branch f047d5b411a56ea87eab06f9b43fc3b705d7c998

**Steps to reproduce:**

1. Run a debug build of IINA, then open up its Settings window and go to the UI tab.
2. Check the log in XCode to find the errors (they will not appear in iina.log).

However, it's more useful to enable the purple visualizer thing. Run this in a terminal window:
```
defaults write com.colliderli.iina NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints true
```

Then follow the steps above again, and you'll see this:
![OSC-toolbar-bad-main](https://user-images.githubusercontent.com/2213815/199644584-bef7ef72-824d-453b-8dbd-7c0a878288a2.png)

Also, click the `Customize...` button to open the OSC Toolbar customization dialog and you'll see another one:
![OSC-toolbar-bad-popup](https://user-images.githubusercontent.com/2213815/199644710-90a4d99e-9de3-404d-8507-bc96e50e0878.png)

**How often does this happen?**
Always

**Comment by low-batt** [comment]
Fix has been merged into the develop branch.

**Comment by low-batt** [comment]
IINA 1.3.2 contains the fix for this issue.
