### ISSUE TITLE
With dark mode enabled, scroll bar in Release Notes is white

### ISSUE THREAD

**Issue by rakleed** [iina/iina#4046]
**System and IINA version:**

- macOS 13.0
- IINA 1.3.1 Build 133

**Expected behavior:**

The scroll bar is dark in Release Notes when using the dark theme.

**Actual behavior:**

The scroll bar is light in Release Notes when using the dark theme.

**Steps to reproduce:**

1. Make sure dark theme is selected in macOS Appearance settings
2. Install IINA 1.3.0
3. Open IINA
4. Click on IINA app menu
5. Choose Check for Updates...

- [x] MPV does not have this problem.

**How often does this happen?**

Every time.

-----

<details><summary>Screenshot</summary>

![Screenshot 2022-11-07 at 18 11 19](https://user-images.githubusercontent.com/19418601/200348389-5165364c-9e99-45ce-86f2-b19621731776.png)

</details>

You most likely need to update [Sparkle](https://github.com/sparkle-project/Sparkle) dependence to the latest version. Specifically, in version [2.2.1](https://github.com/sparkle-project/Sparkle/releases/tag/2.2.1) this problem was fixed.

**Comment by uiryuu** [comment]
Before:
![telegram-cloud-photo-size-5-6289511840560034692-y](https://user-images.githubusercontent.com/20237141/200459022-1acb55e3-2e21-490c-a308-a7d89d872423.jpg)

After:
![telegram-cloud-photo-size-5-6289511840560034694-y](https://user-images.githubusercontent.com/20237141/200459033-04ddbcdc-ee52-4676-aed9-2a293c8b2428.jpg)
