### ISSUE TITLE
File matching in playlist is wrong when video/audio mixed.

### ISSUE THREAD

**Issue by scegg** [iina/iina#4061]
**System and IINA version:**

- macOS 13.0.1 (x64)
- IINA 1.3.1 Build 133

**Expected behavior:**
When right click the item in playlist, select "Move to Trash", the file should be removed.

**Actual behavior:**
The selected menu item and another file is removed.

**Steps to reproduce:**
1 Place one video and some audio file in the same folder. Make sure the audio files are sorted before the video -- names are "smaller" than the video file.
2 Double click the video file to play.
3 Wait for the video playing to finished.
4 The audio file is started to play automatically. Note: The UI is changed, playlist is not visible like the previous version.
5 Change UI back to full mode. Open the play list.
6 Right click the video item (the 1st one), select "Move to Trash".
7 The selected menu item and the video file specified should be removed. BUT the 1st audio file is removed instead of the video file.

**How often does this happen?**
Always.

**Comment by scegg** [comment]
Update: When multiple video files are in the list, removing one to trash will delete the next file instead as the test scenario above.

**Comment by matt-fury** [comment]
I’m having the same issue, sending one video file from the list results in the next one down getting trashed instead. Clicking “show file in finder” brings up the correct file, however. glad i have a habit of double checking the trash,lol.

**Comment by svobs** [comment]
This sounds like a serious problem. I've got a couple other issues I'm trying to wrap up, but will investigate this in a few days if no one else does.

**Comment by svobs** [comment]
Reproduced. I also found that choosing `Move to Trash` for the last item in the playlist will result in IINA crashing.

**Comment by scegg** [comment]
> This sounds like a serious problem. I've got a couple other issues I'm trying to wrap up, but will investigate this in a few days if no one else does.

Yes. New version introduced many UI related issues. For another not related (maybe), the UI for audio only (I dunno the name of that, which has no video window frame) never update the played time nor the seek bar while playing. Have to switch to video UI.

**Comment by svobs** [comment]
> Yes. New version introduced many UI related issues. For another not related (maybe), the UI for audio only (I dunno the name of that, which has no video window frame) never update the played time nor the seek bar while playing. Have to switch to video UI.

@scegg Are you referring to Music Mode? There are a few open issues for that. Does it sound like the description for #4051? If not, you should create a new issue for it.

**Comment by scegg** [comment]
> > Yes. New version introduced many UI related issues. For another not related (maybe), the UI for audio only (I dunno the name of that, which has no video window frame) never update the played time nor the seek bar while playing. Have to switch to video UI.
> 
> @scegg Are you referring to Music Mode? There are a few open issues for that. Does it sound like the description for #4051? If not, you should create a new issue for it.

Yep. The issue is reported like #4051.

**Comment by low-batt** [comment]
IINA 1.3.2 contains the fix for this issue.
