### ISSUE TITLE
Unable to hide Quick Panel with On Screen Controller

### ISSUE THREAD

**Issue by karb0f0s** [iina/iina#4071]
**System and IINA version:**

- macOS 13.0.1
- IINA 1.3.1 Build 133

**Expected behavior:**

Pressing Playlist and Quick Settings buttons should show and hide panel.

**Actual behavior:**

I have to use shortcuts or menu to hide side panel.

**Comment by low-batt** [comment]
Reproduced. Confirmed regression. This must be fixed. Investigating...

In addition to shortcuts and menu you can click in the window outside of the panel to hide it.

**Comment by low-batt** [comment]
Fix has been merged into develop.

**Comment by low-batt** [comment]
IINA 1.3.2 contains the fix for this issue.
