### ISSUE TITLE
Playlist song name display garbled code

### ISSUE THREAD

**Issue by PiFrancis** [iina/iina#4097]
**System and IINA version:**

- macOS
  - 13.0.1 (22A400)
- IINA
  - 1.3.1 Build 133

**Expected behavior:**

```tex
loading local music folder, playlist song name display garbled code
```

**Actual behavior:**
<img width="442" alt="Snipaste_2022-11-26_11-53-48" src="https://user-images.githubusercontent.com/38675709/204074288-22eb4005-68b7-4e53-8f31-d46226dd81a3.png">
<img width="474" alt="Snipaste_2022-11-26_11-55-44" src="https://user-images.githubusercontent.com/38675709/204074293-75072634-4b12-4d46-abdf-c57248eeb06b.png">

**Comment by J-Liu** [comment]
Your mp3 file's metadata might not be UTF-8.
You can edit the metadata of your mp3 file in iTunes.

**Comment by PCoeur** [comment]
> 

How do I modify iTunes? Please inform the operation steps. Thanks

**Comment by PiFrancis** [comment]
> 

How do I modify iTunes? Please inform the operation steps. Thanks

**Comment by J-Liu** [comment]
> How do I modify iTunes? Please inform the operation steps. Thanks
Sorry, in Music

![1](https://user-images.githubusercontent.com/1065112/204135506-88a253bd-8af9-4280-ab72-eccbc99b313f.jpg)

![2](https://user-images.githubusercontent.com/1065112/204135533-0817d9ed-432c-47e2-a0f5-35c020e79107.jpg)

**Comment by PiFrancis** [comment]
> > How do I modify iTunes? Please inform the operation steps. Thanks
> > Sorry, in Music
> 
> ![1](https://user-images.githubusercontent.com/1065112/204135506-88a253bd-8af9-4280-ab72-eccbc99b313f.jpg)
> 
> ![2](https://user-images.githubusercontent.com/1065112/204135533-0817d9ed-432c-47e2-a0f5-35c020e79107.jpg)

Do modify file's metadata character encoding?
<img width="601" alt="Snipaste_2022-12-07_21-36-45" src="https://user-images.githubusercontent.com/38675709/206195838-729cc6ae-2a2d-48c0-8647-47c461866c48.png">
There is no character encoding column in the music details of iTunes, and there is no description of character encoding information for other options in the current window.
