### ISSUE TITLE
[Solution Report]: Cmd+Shift+S shortcut does not work on macOS Ventura (13.0.1)

### ISSUE THREAD

**Issue by qrohlf** [iina/iina#4098]
This is both a bug & solution report, I'm putting it here because I figure this is the place where people are most likely to search if they encounter the issue on their own.

The default hotkey of <kbd>⌘ + Shift + S</kbd> for "Open Subtitle Panel" fails to work on macOS Ventura (13.0.1). 

I went down a whole rabbit hole figuring out what was causing this, it turns out that there is a new system level "Live Captions" utility present in Ventura with a conflicting keyboard shortcut. When checked, this box in `Settings > Keyboard > Keyboard Shortcuts... > Accessibility` will cause the `universalaccessd` process to receive events for <kbd>⌘ + Shift + S</kbd> instead of IINA. Unchecking the box will resolve the issue. 

For some reason, the shortcut was not actually triggering the Live Captions OSD, not sure why - this is what made diagnosing the issue so tricky, as there wasn't any visual indication of _what_ the new shortcut was doing at the system level. I'm guessing it was because by default the shortcut seems to be enabled, but the speech model used by the device for speech recognition doesn't get downloaded from the internet until you enable the beta feature in a different preference pane?

In any case, if you're experiencing the same issue, just uncheck this box in `Settings > Keyboard > Keyboard Shortcuts... > Accessibility` and you're good to go:

<img width="687" alt="Screenshot 2022-11-26 at 8 42 18 AM" src="https://user-images.githubusercontent.com/347189/204097254-07cf9fc9-3560-49af-9cab-f07ebb761f25.png">

Shout out to [Shortcut Detective](https://www.irradiatedsoftware.com/labs/) for helping me figure out what process was intercepting the input, there is no way I'd have figured it out without that util.

**Comment by low-batt** [comment]
Did not reproduce for me.

To reproduce it I did the following:
- I upgraded to macOS 13.0.1. 
- I opened `System Settings`/`Accessibility`
- I selected `Live Captions (Beta)` 
- I changed the `Live Captions` toggle button to be on (blue)
- I waited for macOS to download languages
- I then opened IINA 1.3.1 and started playing a video
- I pressed ⇧⌘S on the keyboard
- IINA showed the quick settings panel with the subtitles tab selected

I then checked the keyboard shortcuts for live captions: 
- I opened `System Settings`/`Keyboard`
- I clicked on `Keyboard Shortcuts…`
- I clicked on `Accessibility`
- I clicked on the `Live Captions` disclosure triangle

This showed no keyboard shortcuts assigned by default:

![issue-4098](https://user-images.githubusercontent.com/86170219/204106364-d1ac3740-3b85-4eb1-8b8d-106e19b06b6b.jpg)


I'm confused as to why macOS assigned a shortcut by default in your case. Did you initially enable live captions under macOS 13.0?

**Comment by qrohlf** [comment]
I honestly have no idea what happened here - I wasn't even aware the feature existed until it started messing with my IINA settings, I most definitely did not enable the feature intentionally at any point.

Closest thing I can come up with is that this is on my work laptop that's part of a MDM deployment, so maybe somehow that keyboard shortcut crept into the settings somehow?

**Comment by qrohlf** [comment]
Appreciate you taking the time to attempt a repro though! In light of that info, I'm going to close this issue as resolved since it seems like the behavior I'm seeing isn't a default so there aren't any changes required on the IINA side of things. Hopefully anybody else who runs into a similar issue will be able to find this fix via the issue search!

**Comment by low-batt** [comment]
Yes, could be it was configured your companies's IT department.

I appreciate the excellent clear report. Good for the IINA project to know this feature will capture key press events before they are delivered to an app.
