### ISSUE TITLE
It can be played, but the color of the video is completely wrong

### ISSUE THREAD

**Issue by tlerbao** [iina/iina#4104]
As shown in the figure, I downloaded three of the same videos

-  normal：Black.Adam.2022.1080p.WEBRip.x265-RARBG
- It can be played but the color is completely wrong as shown below：Black.Adam.2022.2160p.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-WHITEMICHAEL 
- Can't play, black screen, but there is sound：Black.Adam.2022.2160p.WEB-DL.DDP5.1.Atmos.DV.MP4.x265-DVSUX

<img width="1971" alt="image" src="https://user-images.githubusercontent.com/20442232/204175848-3d3f1d93-d019-442d-bd07-d5be1c04ecf7.png">

**Comment by hooke007** [comment]
dovi vision profile 5 is currently not supported.

**Comment by hooke007** [comment]
dup
https://github.com/iina/iina/issues/3313
https://github.com/iina/iina/issues/3573

**Comment by majedmj** [comment]
is there a way to fix it
