### ISSUE TITLE
Increase border radius of the pip window to match the system defaults

### ISSUE THREAD

**Issue by Wiredframe** [iina/iina#4131]
**What you want IINA to do:**
Increase border radius of the pip window to match the system defaults

**What IINA does currently:**
The border radius is too small, making the pip window not as sleek as the native pip windows in ios and macos.

**Why you think this should be added:**
For general improvement

**Examples of other projects that have something similar:**
Firefox

**Comment by saagarjha** [comment]
We use the system PIP window already.
