### ISSUE TITLE
Crash report pops out after Cmd+Q every time

### ISSUE THREAD

**Issue by SeikilosLin** [iina/iina#4136]
M1 MacBook Air, Ventura 13.0.1 (latest), IINA 1.3.1 Biuld 133

A crash report appears every time after I use cmd+Q to quit the app. Occurred since latest IINA update.

**Comment by icpz** [comment]
Same issue here.

**Comment by svobs** [comment]
Can you post the crash report here? It's not very easy to track down problems without any info.

Are you in fullscreen mode when you're quitting? If so, it's probably #4020. (If you search the report and find the text `windowDidExitFullScreen` in it, that's almost certainly the culprit). A fix has been proposed but is waiting to be reviewed.

**Comment by icpz** [comment]
> Can you post the crash report here? It's not very easy to track down problems without any info.
> 
> Are you in fullscreen mode when you're quitting? If so, it's probably #4020. (If you search the report and find the text `windowDidExitFullScreen` in it, that's almost certainly the culprit). A fix has been proposed but is waiting to be reviewed.

Hi, I did find `windowDidExitFullScreen` in the crash report, so it's highly likely the same issue as #4020 
Thanks!

**Comment by SeikilosLin** [comment]
> Can you post the crash report here? It's not very easy to track down problems without any info.
> 
> Are you in fullscreen mode when you're quitting? If so, it's probably #4020. (If you search the report and find the text `windowDidExitFullScreen` in it, that's almost certainly the culprit). A fix has been proposed but is waiting to be reviewed.

Yes it occurs only when using fullscreen. Now I know how to avoid it. Thank you!

**Comment by Jolopu** [comment]
A small update fixing this issue would be highly appreciated! :-)

**Comment by edphan** [comment]
Issue is being addressed in this PR: https://github.com/iina/iina/pull/4068
