### ISSUE TITLE
Open In IINA Fails to launch IINA if links contain an apostrophe

### ISSUE THREAD

**Issue by NikkSaan** [iina/iina#4186]
I've noticed that some links fail to launch IINA using OpenInIINA because of a quotation issue in the extension. 
The problem seems to be in [this file](https://github.com/iina/iina/blob/develop/browser/Chrome_Open_In_IINA/common.js) on line 62. 

This is an example of such link:
[https://odysee.com/@TheLinuxExperiment:e/no,-arch-isn't-n%C2%B01,-x-org-is-dying,:9](https://odysee.com/@TheLinuxExperiment:e/no,-arch-isn't-n%C2%B01,-x-org-is-dying,:9)

To reproduce, try using the extension to open the link and observe the console.

--- Edit ---
It seems that the problem is caused by `encodeURIComponent()` on line 62 not escaping the single quote! 
Appending `.replace(/'/g, '%27')` after the encode does the trick.

I don't do pull requests for personal reasons. Don't ask!

MacOS 10.13
Vivaldi 5.6.2867.58
Open In IINA 2.0.0

**Comment by low-batt** [comment]
This is fixed in the released version of IINA.
