### ISSUE TITLE
mac上spv4安装好了确无法运行

### ISSUE THREAD

**Issue by seasideblue** [iina/iina#4188]
**System and IINA version:**
13.0.1 - macOS 
- IINA 
1.3.1
**Expected behavior:**

**Actual behavior:**按照官网教程安装了svp，但是却无法开启补帧，无论是用mpv还是iina，有没有大佬能帮我啊，我给钱，可以的话发邮件给我zcycold@gmail.com

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by low-batt** [comment]
母语为英语的人使用在线翻译器回答......

我想 "spv "是个错字，这是在说[SVP](https://www.svp-team.com/get/)？如果是这样，那么这就是SVP团队的问题，而不是IINA的问题。我建议把这个问题发到[SVP  Support Forum](https://www.svp-team.com/forum/)上。

最近在第#4099号问题中出现了SVP的主题。从我对该问题的回复中可以看出，我认为该问题与mpv发布0.35.0使得SVP对配置IINA的说明过时有关。在那个问题被发布后，SVP团队更新了他们的[Setting up IINA](https://www.svp-team.com/wiki/SVP:IINA) 说明。请确保你使用的是SVP的最新说明。
