### ISSUE TITLE
怎样通过homebrew安装vapoursynth

### ISSUE THREAD

**Issue by seasideblue** [iina/iina#4190]
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**
svp4要求安装python3和vapoursynth，我已经安装好python3了，但是通过homebrew安装vpoursynth就报错，
显示
Warning: No available formula with the name "vapoursynth".
==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for vapoursynth.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by low-batt** [comment]
以英语为母语的人使用在线翻译器回答...

根据问题#4188，我猜测你是按照[SVP](https://www.svp-team.com/get/)的说明[Setting up IINA](https://www.svp-team.com/wiki/SVP:IINA)具体操作。
> 需要。
>
> - 通过Homebrew安装支持Vapoursynth的mpv

我相信该说明只是指出SVP需要mpv建立在Vapoursynth支持下。为了满足这一要求，你只需要用[Homebrew](https://brew.sh/)安装mpv。这是因为 
[mpv Homebrew Formulae](https://formulae.brew.sh/formula/mpv) 包括对Vapoursynth的支持。
> 依赖于。
> ...
> vapoursynth 61 视频处理框架，考虑到了简单性

你所需要做的就是用brew安装mpv。

一定要在[SVP Support Forum](https://www.svp-team.com/forum/)上发表此类问题。SVP团队更有能力协助让SVP运作起来。

**Comment by Bein777** [comment]
这个问题解决了吗？

**Comment by low-batt** [comment]
从 IINA 项目的角度来看，没有什么问题需要解决。这是关于配置[SVP](https://www.svp-team.com/get/)以使用 IINA 的问题，最好在[SVP 支持论坛](https://www.svp-team.com/forum/)上讨论。

至少我们认为这就是问题所在。该问题的作者并未确认情况是否如此。
