### ISSUE TITLE
IINA播放大疆无人机拍摄的HLG视频卡顿 severe lag while playing HLG videos shot by DJI

### ISSUE THREAD

**Issue by monzetsushonen** [iina/iina#4194]
IINA
1.3.1 Build 133
mpv 0.34.1

播放大疆无人机拍摄的HDR HLG视频有严重卡顿
虽正常能解码和显示HDR视频

请协助解决

Severe lag occurs while playing HDR HLG video shot by DJI Drone.
Decode and display is OK.

Please help to improve.

**Comment by uiryuu** [comment]
Can you provide a such a file?

**Comment by monzetsushonen** [comment]
> 

How to upload large file to this thread?

**Comment by monzetsushonen** [comment]
https://www.icloud.com/iclouddrive/0faLVL8J5bye5fdTU7aFz1bpg#dji%5Ffly%5F20230122%5F123240%5F287%5F1674447762424%5Fvideo%5Fhlg

**Comment by HarukaMa** [comment]
![image](https://user-images.githubusercontent.com/861659/230708115-c5f0f3a8-1199-45ec-abdf-0a6fafa24ead.png)

At this resolution / bitrate you would definitely need hardware decoding; make sure it's enabled. Don't have HDR displays right now so not sure if it would still work though.

**Comment by monzetsushonen** [comment]
> ![image](https://user-images.githubusercontent.com/861659/230708115-c5f0f3a8-1199-45ec-abdf-0a6fafa24ead.png)
> 
> At this resolution / bitrate you would definitely need hardware decoding; make sure it's enabled. Don't have HDR displays right now so not sure if it would still work though.

I am sure that I enabled hardware decoding and HDR

Device : MBP 14 with M1 Pro, file is in internal storage.

**Comment by low-batt** [comment]
母语为英语的人使用在线翻译器回答...

检查员窗口的屏幕截图显示：

> 硬件解码器： videotoolbox


因此，硬件解码正在被使用。


在macOS Ventura 13.3.1下，我在装有M1芯片的MacBookPro18,2上用IINA 1.3.1播放这段视频时没有遇到滞后。正在使用硬件解码。而且播放似乎很顺利。


IINA 1.3.1中有一些与线程有关的问题，由于某些原因，在我的机器上没有造成问题，但对其他人来说却造成滞后。可能这就是你所遇到的滞后的原因。


如果你知道什么是未签名的夜间构建，并想测试一下最新开发版本的IINA是否能够播放这个视频而不卡顿，夜间构建是可用的[这里](https://nightly.iina.io/)。


最新的开发版本包含许多修正，以及对[mpv](https://mpv.io/)、[FFmpeg](https://ffmpeg.org/)和其他依赖项的升级。对HDR的处理已经改变。在设置面板的 "视频/音频 "标签里有一个新的HDR相关设置。


如果你测试了夜间构建并发现了一个回归，请报告它。我们离另一个IINA的发布越来越近了。

---

The screen shot of the inspector window shows:
> Hw Decoder: videotoolbox

So hardware decoding is being used.

I did not experience lagging while playing this video with IINA 1.3.1 on my MacBookPro18,2 with the M1 chip under macOS Ventura 13.3.1. Hardware decoding was being used. And playback seemed smooth.

There are some thread related problems in IINA 1.3.1 that for some reason do not cause problems on my machine, but cause lagging for others. Could be that is what is causing the lagging you are experiencing.

If you know what an _unsigned_ nightly build is and want to test to see if the latest development version of IINA is able to play this video without lagging, nightly builds are available [here](https://nightly.iina.io/).

The latest development build contains many fixes as well as upgrades to [mpv](https://mpv.io/), [FFmpeg](https://ffmpeg.org/) and other dependencies. Handling of HDR has changed. There is a new HDR related setting in the `Video/Audio` tab of the settings panel.

If you do test a nightly build and find a regression, please report it. We are getting closer to another release of IINA.

**Comment by monzetsushonen** [comment]
This issue was solved in version 1.3.2
Thanks for all developers.

此问题在1.3.2版本中得到解决
感谢所有开发者
