### ISSUE TITLE
HIDE FILE NAME IN UPPER LEFT WHEN OPENED IN FULLSCREEN

### ISSUE THREAD

**Issue by Seels** [iina/iina#4197]
Hello!
 
How do I turn off the file name that appears in the upper left corner when I launch a new video using IINA movie player?
 
I am using the full screen option and would like it to be a seamless change from one video to the next in the same window in full screen without seeing file names appear in the upper left.  Similarly, when the open file loops, how do I turn the time reset of the length of the file from appearing?

**Comment by low-batt** [comment]
These are On Screen Display messages. IINA currently does not have settings to enable/disable individual OSD messages, but you can completely disable the OSD. Follow these instructions:
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `UI`
- On the right side of the panel scroll to the `On Screen Display` section
- Uncheck the `Enable OSD` setting
- **Restart IINA** to activate the new settings

For audio/video playback support IINA uses a library from the [mpv](https://mpv.io/) project. Many of the features of the mpv player are also available in IINA using advanced settings. IINA supports using the [mpv OSD](https://mpv.io/manual/stable/#osd) in place of IINA's OSD. Should you wish to enable mpv's OSD follow these instructions:
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Advanced`
- Slide the `Enable advanced settings` toggle button to be on (blue)
- Check the `Use mpv's OSD` setting
- **Restart IINA** to activate the new settings

By default the mpv OSD does not display a message when playback starts. That message must be enabled using the [osd-playing-msg](https://mpv.io/manual/stable/#options-osd-playing-msg) option.

**Comment by Seels** [comment]
low-batt,

Amazing. Exactly what I needed. Thanks for pointing me towards OSD settings.  Really appreciate it!

**Comment by low-batt** [comment]
I'll mark this issue as a feature request to be able to individually disable some of IINA's OSD messages, in particular the two mentioned messages.

**Comment by low-batt** [comment]
Support was added in IINA 1.4.0-beta1.
