### ISSUE TITLE
speed up 1.25x and 1.5x

### ISSUE THREAD

**Issue by emperorjoker** [iina/iina#4199]
Now there is only 2x speed up, hopefully there will be 1.25x and 1.5x speed up/

thanks.

**Comment by low-batt** [comment]
With IINA playing a video click on `Show Video Panel` under the `Video` menu. The quick settings panel will appear on the right side of the main window with the `Video` tab selected. This panel can also be opened using a button on the on screen controller. The panel contains a `Speed` section with a slider to adjust playback speed. There is also a text box at the end of the slider that allows you to specify the speed directly:
![issue-4199](https://user-images.githubusercontent.com/86170219/215286762-3b8ce565-def0-48a1-9a66-91150539b621.jpg)

It is also possible to bind keys to the mpv commands `multiply speed 1.25` and `multiply speed 1.5`. See the `Key Bindings` tab of IINA `Settings`.
