### ISSUE TITLE
When wearing airpodspro headphones, the positioning progress bar will get stuck.

### ISSUE THREAD

**Issue by Xingxyc** [iina/iina#4209]
When wearing airpodspro headphones, the positioning progress bar will get stuck.
But when using other players, there will be no jam.
When I disconnect the earphone, it will return to normal.

- macOS 
- IINA

**Comment by low-batt** [comment]
Based on the indication that the progress bar functions normally when the AirPods are disconnected I believe this is a duplicate of issue #3805. See that issue for details.
