### ISSUE TITLE
 在macOS13.2 中 IINA 1.3.1播放音乐WAV文件进度条经常停止不动。1.3.0版本正常。

### ISSUE THREAD

**Issue by newhuajun** [iina/iina#4213]
在macOS13.2 中 IINA 1.3.1播放音乐WAV文件进度条经常停止不动。1.3.0版本正常。

**Comment by low-batt** [comment]
母语为英语的人使用在线翻译器回答...


谢谢你的报告。我确定这就是问题 #4051 中的问题。这是一个回归问题，被认为是在下一个版本的IINA中需要修复的高度优先事项。在 #4087 号拉动请求中已经提出了一个修复方案。该请求正在审查中。


我将把这个问题标记为与问题 #4051 重复的内容。
