### ISSUE TITLE
Scrubbing Using Arrow Keys Small Lag

### ISSUE THREAD

**Issue by CubingSoda** [iina/iina#4215]
**System and IINA version:**

- macOS 13.1
- IINA 1.3.1

**Expected behavior:**

Should go forward/back 5 seconds without delay using arrow keys.

**Actual behavior:**

Takes about a half second for it to start again.

**Steps to reproduce:**

Go to settings and change the right arrow keyboard shortcut to "seek 5 relative+exact" and left to "seek -5 relative+exact" 

**How often does this happen?**

100% of the time.

**Comment by low-batt** [comment]
Are you using any external audio devices? AirPods or Bluetooth speakers?

**Comment by CubingSoda** [comment]
No, just the built in speakers.

**Comment by low-batt** [comment]
I was making sure this did not involve a known issue with wireless audio.

The [mpv](https://mpv.io/) manual entry for the [seek](https://mpv.io/manual/stable/#command-interface-seek-%3Ctarget%3E-[%3Cflags%3E]) command says:

> **seek \<target> [\<flags>]**
>    Change the playback position. By default, seeks by a relative amount of seconds.
>
>    The second argument consists of flags controlling the seek mode:
>
>    **relative (default)**
>        Seek relative to current position (a negative value seeks backwards).
> …
> **exact**
>    Always do exact/hr/precise seeks (slow).

Note the `(slow)` in the last line. By adding `exact` mpv must do precise seeks which can be slow. The mpv manual entry for the [--hr-seek](https://mpv.io/manual/stable/#options-hr-seek) option explains a bit more:
> **--hr-seek=<no|absolute|yes|default>**
> Select when to use precise seeks that are not limited to keyframes. Such seeks require decoding video from the previous keyframe up to the target position and so can take some time depending on decoding performance. 

That means the time to seek is dependent upon the keyframe interval. The larger the time between keyframes the more decoding mpv has to do to find the frame at the exact position to seek to. There is no industry standard keyframe interval. Whoever encoded the video can choose the interval to use. Shorter intervals increase the size of the video. So the time it takes for a precise seek will depend upon how the video was encoded.

In the test I ran I did notice a very slight lag to the seek. I think this is expected.

Does this sound like it could be what you are experiencing, or do you think there is something else going on?

**Comment by CubingSoda** [comment]
Thank you. I think that is why it caused the delays. Is this preventable, or do I have to use a different media player?

**Comment by low-batt** [comment]
Any player will have to deal with the problems the keyframe interval poses if you force that player to seek to an **exact** spot.

What you really want is for the video have been encoded with a short keyframe interval to make exact seeking faster. But a short interval will make the video file larger, so if the person that encoded the video was concerned about the file size they are more likely to have chosen a longer interval.

If we are talking about seeking relative to the current playback position particular players may be able to seek faster due to how they cache data. So you may find a player that is faster at exact seeking. 

With respects to IINA you may be able to improve IINA's seeking speed using mpv options which can be specified in `Advanced` settings. For example most players are configured to be optimized for forward playback so caching is less likely to retain frames that have already been displayed. Setting the [demuxer-max-back-bytes](https://mpv.io/manual/stable/#options-demuxer-max-back-bytes) option might speed up reverse seeking:
> **--demuxer-max-back-bytes=\<bytesize>**
>
>    This controls how much past data the demuxer is allowed to preserve. This is useful only if the cache is enabled.

**Comment by CubingSoda** [comment]
I set `demuxer-max-back-bytes` to `1000000000` in the table. It didn't make a difference. Am I doing this correctly?

I quit IINA via command + q

**Comment by low-batt** [comment]
Be sure `Enable advanced settings` at the top is blue, enabled.

A reply to the StackExchange post [video player which can step forward and backward frame by frame smoothly](https://unix.stackexchange.com/questions/418395/video-player-which-can-step-forward-and-backward-frame-by-frame-smoothly) lists a number of mpv options:

> Enable lots of caching with some options like these: --demuxer-seekable-cache=yes --cache=yes --demuxer-max-back-bytes=100M --hr-seek=yes --demuxer-cache-wait=yes (not a well researched or exhaustive list)

Possibly some of them are needed as well. I've not explored this area of mpv.

**Comment by CubingSoda** [comment]
Thank you.

https://github.com/mpv-player/mpv/issues/4019#issuecomment-271869860

> That’s because MJPEG is an intra-only codec. Most common video codecs (H.264 etc.) can only be decoded efficiently in forward direction. Without keeping all frames since the last keyframe in memory (which is an indefinite number), you cannot framestep backward smoothly.

**Comment by low-batt** [comment]
Good find, mpv issue [#4019](https://github.com/mpv-player/mpv/issues/4019) is about this same issue.

The IBM tutorial [Keyframes, InterFrame & Video Compression](https://blog.video.ibm.com/streaming-video-tips/keyframes-interframe-video-compression/) is a good introduction to video compression.

When I get a chance I will look into this area of IINA and see if there is some overhead that can be eliminated.
