### ISSUE TITLE
[Bug] External disk locked after playing

### ISSUE THREAD

**Issue by goodman-capu** [iina/iina#423]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Expected behavior:**

Disk ejected successfully

**Actual behavior:**

Finder warns that "The disk is being used by some app, can't eject it". After I quit IINA, the disk can be ejected.

**Steps to reproduce:**

1. Play a video file on an external disk
2. Play another video on my local disk (Without quitting IINA in the meantime)
3. Try to eject the external disk

**How often does this happen?**

I don't know

**Comment by KuangLei** [comment]
Same problem here on my M1 MacBook, but not on my previous Intel one.

<hr />

**System and IINA version:**

* macOS 11.2.3
* IINA 1.1.2 Build 128 (Rosetta)
* VL716
* WD40EZRZ

**Comment by uiryuu** [comment]
Cannot reproduce this issue using the latest IINA. If the issue still exists, please reopen the issue and provide more information, thanks!
