### ISSUE TITLE
Support subtitle visibility

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4235]
**What you want IINA to do:**
This is a request for IINA to directly support the mpv options [sub-visibility](https://mpv.io/manual/stable/#options-no-sub-visibility) and [secondary-sub-visibility](https://mpv.io/manual/stable/#options-no-secondary-sub-visibility). These options disable/enable the rendering of subtitles, similar to muting audio.

Support must include menu items to toggle the state. The menu items must adhere to Apple's Human Interface Guidelines on [Menus](https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/menus), specifically the section on `Toggled items`.

IINA already has a `Subtitles` menu so new menu items must be under that menu. The current convention in the menu is to use the prefix `Second` for items that pertain to secondary subtitles. I suggest using `Visible` and `Second Visible` for the names of the items with checkmarks to indicate the state.

The menu items must include associated keyboard shortcuts. The key bindings used by mpv are:

| Key | Command |
| --- | --- |
| v | cycle sub-visibility |
| Alt+v | cycle secondary-sub-visibility |

IINA does not currently contain bindings for these keys so IINA should use the same bindings as mpv.

When subtitle visibility changes an OSD message must be shown so the user knows if subtitle rendering is enabled or disabled.

This request originates out of discussions concerning issue #4234.

**What IINA does currently:**
Currently this mpv feature is only available through custom key bindings, which does not provide feedback to the user as to the current state of subtitle visibility.

**Why you think this should be added:**
Subtitles is one area where IINA has a feature not found in mpv (without plugins), the ability to download from web sites that provide subtitles. IINA should insure other subtitle functions are supported. The mpv subtitle visibility feature is a convenience feature similar to being able to quickly mute audio.

**Examples of other projects that have something similar:**
This is a mpv feature.

**Comment by shelbyKiraM** [comment]
AHHH this feature had been driving me crazy... I accidentally hid the subs but FINALLY found the fix here. Even when I used J to go between the subs they weren't reappearing. I'm sure there's some reason for this but why not just go to None with J?

**Comment by low-batt** [comment]
Thanks for commenting. Sorry you were tripped up by this [mpv](https://mpv.io/) feature. I was unaware of this particular feature and I too would have been very confused if I had accidentally enabled it.

Your experience provides another justification as to why this feature is needed. If you are using the mpv key bindings and accidentally type a "v" subtitles disappear and there is currently no indication in IINA that it is due to this feature.

And if the IINA setting `Resume last playback position` is enabled restarting IINA will not make subtitles visible again as this is one of the settings that is remembered and restored on a per file basis. This [Terminal](https://support.apple.com/guide/terminal/welcome/mac) session shows me checking the attributes that were saved for a particular video:
```bash
low-batt@gag ~$ md5 -qs '/Users/low-batt/Movies/resume-failure.mp4' | xargs -I % cat ~/Library/Application\ Support/com.colliderli.iina/watch_later/%
start=46.450000
pause=yes
sub-visibility=no
low-batt@gag ~$
```

That the setting may be sticky across a restart of IINA makes accidentally enabling this feature a confusion situation.

As to why this feature does not change the subtitle selection to `None`…

This is a [mpv](https://mpv.io/) feature so I have to guess what the designers of this feature were thinking. Imagine if muting audio changed the speaker selection to `None`. If you have more than one set of speakers you can't the just quickly unmute, you have to select the speakers you want to use again.

So think of this feature like muting for subtitles. You want to quickly temporarily stop displaying subtitles and then be able to quickly enable displaying them again.

**Comment by homocomputeris** [comment]
> Currently this mpv feature is only available through custom key bindings

It's also in the mpv preset:
<img width="566" alt="mpv_v" src="https://user-images.githubusercontent.com/7422433/221071024-aab56b89-799d-4df0-923d-8597ba06db0f.png">

**Comment by low-batt** [comment]
Thanks for having my back and checking my work. Yes, my first post was incorrect. In my second post I do indicate if you are using the mpv key bindings you can run into this. This adds to the importance of providing a GUI for this mpv feature. More news on that shortly…

**Comment by low-batt** [comment]
The commit in the pull request will:
- Add a `Hide Subtitles`/`Show Subtitles`  item to the `Subtitles` menu
- Add a `Hide Second Subtitles`/`Show Second Subtitles`  item to the `Subtitles` menu
- Add a key binding mapping `v` to `cycle sub-visibility`
- Add a key binding mapping `⌥v` to `cycle secondary-sub-visibility`
- Add a new OSD message `Subtitle Visibility: On/Off`
- Add a new OSD message `Second Subtitle Visibility: On/Off`
- Add `secondary-sub-visibility` to `watch-later-options`
- Add logging of `watch-later-options`

With these changes the `Subtitles` menu looks like:
![issue-4235-menu](https://user-images.githubusercontent.com/86170219/221078128-275ea39d-9bfa-4152-8611-817135c39e78.jpg)


The new OSD message looks like:
![issue-4235-OSD](https://user-images.githubusercontent.com/86170219/221078154-0ecc2c74-56c4-4a54-9e51-1748b3650aa5.jpg)

As always critical review comments welcome.

**Comment by low-batt** [comment]
Based on review feedback the new OSD messages now look like:
![issue-4235-OSD-Hidden](https://user-images.githubusercontent.com/86170219/221379805-b7d7510e-1e7d-424c-9958-874a3abad088.jpg)
![issue-4235-ODS-visible](https://user-images.githubusercontent.com/86170219/221379806-61ec42b9-c64d-4cc3-a731-74bee0cf0ba0.jpg)

**Comment by low-batt** [comment]
The latest proposed changes add switches to the `SUBTITLES` tab of the quick settings panel as seen here:
![issue-4235-panel](https://github.com/iina/iina/assets/86170219/71a2d3cf-befe-4d09-baac-2d30fdf479f9)

**Comment by lhc70000** [comment]
![image](https://github.com/iina/iina/assets/8478049/b2d0c77a-0fa7-4f85-9a72-4a81596d1e80)
I think we can just put a switch here to indicate whether the subtitle is shown.
