### ISSUE TITLE
Playback History window: no confirmation when Backspace key used

### ISSUE THREAD

**Issue by svobs** [iina/iina#4255]
**System and IINA version:**

- macOS 13.1
- IINA 1.3.1 Build 133

**Expected behavior:**

Because right-click on an entry in this window puts up a confirmation dialog before deleting, one would expect the same if using the Backspace key.

**Actual behavior:**
No confirmation. Item(s) immediately deleted.

Also, using `Ctrl`+`Backspace`, or `Shift`+`Backspace`, `Option`+`Backspace` (i.e. any modifier other than `Command`) also deletes the entry, when they probably shouldn't. Also one would expect the `Delete` key to work also, but it does not.

**How often does this happen?**
Always

**Comment by low-batt** [comment]
Reproduced for me. As there is no "undo" to recover the history entry if you accidentally pressed the delete key I consider not prompting for a confirmation a high priority defect.

**Comment by low-batt** [comment]
This is fixed in the released version of IINA.
