### ISSUE TITLE
从全屏按q退出时每次都会出现iina意外退出弹窗

### ISSUE THREAD

**Issue by terryyyyyyi** [iina/iina#4277]
- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by low-batt** [comment]
母语为英语的人使用在线翻译器回答...


谢谢你的报告。从描述中，我确定这就是问题#4020（和其他问题）中报告的问题。这是一个回归问题，被认为是IINA下一个版本中需要修复的高度优先事项。在#4068 号请求中已经提出了一个修复方案。该请求正在审查中。


我将把这个问题标记为与问题#4020 重复的内容。

**Comment by uiryuu** [comment]
Please track this issue @ https://github.com/iina/iina/issues/4020
