### ISSUE TITLE
Non-existing menu item pops up when searching in the help menu

### ISSUE THREAD

**Issue by uiryuu** [iina/iina#4298]
**System and IINA version:**

- macOS 13.2.1
- IINA 1.3.1

**Expected behavior:**
Show existing menu items when searching in the help menu.

**Actual behavior:**
The results contains "placeholder" items which will be changed based on the current keybinding profile.

![image](https://user-images.githubusercontent.com/20237141/227857618-0364441b-a4a6-4b6c-8522-ee12153b0321.png)

**Steps to reproduce:**
- Make sure the keybinding configuration is set to "IINA default"
- Open a video
- Search "frame" in the help menu
- There are "Next Frame" and "Previous Frame" in the results in the playback menu
- However if you go into the playback menu directly, there are no "Next Frame" and "Previous Frame", instead, "Step Forward 5s" and "Stop Backward 5s" are in the place.
- If you hover over the results, "Step Forward" and "Step Backward" will be changed into "Next Frame" and "Previous Frame"; and that will change back when the menu is refreshed again.

- [x] MPV does not have this problem.

**How often does this happen?**
Always

**Comment by svobs** [comment]
Hmm. When I set the config to "IINA default", I see that there is indeed a keybinding for `Next Frame`:

![SCR-20230327-mmbt](https://user-images.githubusercontent.com/2213815/228065537-a80028ae-d11e-4e40-8857-0b9494ae830b.png)

When I hold the Option key down, I can see it in the menu:

![Screenshot 2023-03-27 at 14 05 24](https://user-images.githubusercontent.com/2213815/228066547-4a1ad8c7-badb-4ac6-8aba-08768eaca5c8.png)

Tested on the last major release: IINA 1.3.1 Build 133

**Comment by uiryuu** [comment]
So it's intended behavior. My bad didn't search frame in the IINA default conf.
