### ISSUE TITLE
Custom crop view resize issues

### ISSUE THREAD

**Issue by yuxiqian** [iina/iina#4299]
**System and IINA version:**

- macOS Ventura 13.3
- IINA 1.3.1

Start IINA and play a video, open "Quick Settings" panel and select Crop - "Custom...". Drag the right edge over the left boundary and release.

**Expected behavior:**

Drag the left edge of the box, should be able to resize the box again.

**Actual behavior:**

Unable to resize by drag the left edge, and its hit-box stays on the right side.

<img width="389" alt="screenshot" src="https://user-images.githubusercontent.com/34335406/227893506-25132460-556c-4f9b-b2aa-de8ea50330ee.png">

</details>

<br>

</details>

<br>

**Steps to reproduce:**

https://user-images.githubusercontent.com/34335406/227890268-c57467a0-158d-4b8f-b46c-81bb3dd3020f.mov

- [x] MPV does not have this problem.

**How often does this happen?**

Every time.

**Comment by low-batt** [comment]
This is fixed in the released version of IINA.
