### ISSUE TITLE
IINA stopped responding after quit clicked

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4310]
**System and IINA version:**

- macOS 13.3
- IINA 1.3.1

**Expected behavior:**
After clicking on `Quit IINA` under the `IINA` menu the application terminates.

**Actual behavior:**
Rarely after clicking on `Quit IINA` IINA does not terminate and becomes unresponsive.

[quit-hang-process-sample.txt](https://github.com/iina/iina/files/11125442/quit-hang-process-sample.txt)

**Steps to reproduce:**
Click on  `Quit IINA` under the `IINA` menu while a video is playing.

- [ ] MPV does not have this problem.

Unknown.

**How often does this happen?**
Rarely. Very difficult to reproduce. First time I have seen this.

**Comment by svobs** [comment]
I have seen this happen a couple of times too, but only while running via XCode, so wasn't sure whether it was caused by XCode or its debugger.

**Comment by low-batt** [comment]
Catching me before I have fully analyzed this one, but I suspect it is due to an issue you pointed out, that mpv sends a bunch of events when stopping that we should not be processing. I will be looking into whether this is a delayed forced drawing in reaction to one of those events.
