### ISSUE TITLE
Unable to adjust alpha with new NSColorWell style

### ISSUE THREAD

**Issue by yuxiqian** [iina/iina#4322]
**System and IINA version:**

- macOS 13.3
- IINA develop branch
- Xcode 14.3

PR #4039 brought a new `.minimal` look for `NSColorWell` which looks nice. However it doesn't support colors with alpha channel.

**Expected behavior:**

Clone and build IINA locally, open "IINA Settings" -> "Subtitle" and click any color well.

User should be able to select the first "transparent" option (it's common to set subtitle background transparent).

Click "Show Colors..." button should open an `NSColorPanel` with alpha slider.

**Actual behavior:**

The "transparent" color button in the pop-up view is disabled.

<img width="198" alt="color pop-up" src="https://user-images.githubusercontent.com/34335406/230295473-fb0771f7-e9f1-4f9d-b64f-1eb46f057c39.png">

"Show Colors..." window doesn't have alpha slider, either.

<img width="263" alt="color panel without alpha slider" src="https://user-images.githubusercontent.com/34335406/230295913-d1450768-605e-4e18-8b4a-21856d442a2b.png">

**How often does this happen?**

Every time

**Comment by low-batt** [comment]
@yuxiqian Thanks for reporting this.
