### ISSUE TITLE
iina URL scheme query lose

### ISSUE THREAD

**Issue by bluebabes** [iina/iina#4325]
**System and IINA version:**

- macOS 12.4
- IINA 1.3.1 Build 133

**Expected behavior:**

Keep all parameters

**Actual behavior:**

open demo url:

```
iina://open?url=http://cpats01.115.com/c617c1d17614fca6d4a8caf522fcbd37/642FB68D/8F78958624C09002B6952ACB35E1A4597DEA70D8/8F78958624C09002B6952ACB35E1A4597DEA70D8_1920.m3u8?u=132362861&se=u,ua&s=157286400&ck=&ua=TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwOC4wLjAuMCBTYWZhcmkvNTM3LjM2
```

and i found player url is 
<img width="805" alt="image" src="https://user-images.githubusercontent.com/3329261/230569140-bb806528-255a-4f21-8c0c-20958899352e.png">

only one query "u" exist, everything else is lost.

**Comment by xjbeta** [comment]
encode the url after "url="

`iina://open?url=http%3A%2F%2Fcpats01.115.com%2Fc617c1d17614fca6d4a8caf522fcbd37%2F642FB68D%2F8F78958624C09002B6952ACB35E1A4597DEA70D8%2F8F78958624C09002B6952ACB35E1A4597DEA70D8_1920.m3u8%3Fu%3D132362861%26se%3Du%2Cua%26s%3D157286400%26ck%3D%26ua%3DTW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwOC4wLjAuMCBTYWZhcmkvNTM3LjM2%0A`
