### ISSUE TITLE
Sidebar active tab button colors for do not match

### ISSUE THREAD

**Issue by svobs** [iina/iina#4332]
**System and IINA version:**

- macOS 13.1
- IINA `develop` f6f0eb727678ab6679280f73695bd64b38701734

**Expected behavior:**

The highlight color of the "active" tab in the [Quick] Settings tab group should be the same as the Playlist/Chapters tab group (preferably solid black?)

**Actual behavior:**

Settings tabs are #000000, but Playlist/Chapters tabs are #61554B.

<img width="836" alt="SCR-20230409-bqzg" src="https://user-images.githubusercontent.com/2213815/230761189-26c64fa5-396e-4131-900b-e76820380a42.png">

<img width="833" alt="SCR-20230409-bqvt" src="https://user-images.githubusercontent.com/2213815/230761192-c3ffaf0b-607b-4383-9d35-869dbbf2d303.png">

**Steps to reproduce:**

I highly recommend the amazing app [Shottr](https://shottr.cc/) which is an excellent tool for taking screenshots, analyzing them and annotating them. The shots above are screenshots of it viewing screenshots from IINA, showing the output of its color analyzer.

**How often does this happen?**

Always

**Comment by low-batt** [comment]
This is fixed in the released version of IINA.
