### ISSUE TITLE
按文件夹导入音频，播放列表中的音频无法按子文件夹进行分层级展示

### ISSUE THREAD

**Issue by poutous** [iina/iina#4338]
按文件夹导入音频，播放列表中的音频无法按子文件夹进行分层级展示，致使播放列表中的音频文件十分的杂乱，并且不清楚播放列表中的章节有何用？是否鸡肋？可否设置关闭章节功能？希望iina能通过一次选择打开最外层的文件夹，导入其下的所有子文件夹及文件。在播放列表，可以对导入的最外层文件夹点击展开/收起子文件夹的方式进行播放。

**Comment by poutous** [comment]
the same as #4348 , can you help me delete this ? @low-batt

**Comment by low-batt** [comment]
母语为英语的人使用在线翻译器回答...

我正在关闭这个与 #4348 重复的问题。

I am closing this one as a duplicate of #4348.
