### ISSUE TITLE
Subtitles panel shows "..." for subtitle number

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4341]
**System and IINA version:**

- macOS 13.3.1
- IINA develop branch

**Expected behavior:**
The subtitles panel is able to properly display the subtitle number for more than 9 subtitle files.

**Actual behavior:**
The subtitles panel displays `#9` for the ninth subtitle file, but only `...` for the 10th subtitle file. The panel should at least be able to accommodate 2 digits. Also when the panel first opens it displays the subtitle files starting with `<none>`, even if subtitle `#8` is selected, forcing the user to scroll to see the selected subtitle file.

![missing-subtitle-number](https://user-images.githubusercontent.com/86170219/231003357-20a81ce8-18d2-47b6-8ac2-6da68d214de3.jpg)

**Steps to reproduce:**
Play a video with many subtitle files. Open the subtitles panel. Scroll down past the ninth subtitle file.

- [x] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by svobs** [comment]
I can take a look this one. May be a good idea to revisit `Video track`, `Audio track`, and `Secondary sub` tables too.

**Comment by low-batt** [comment]
Yes. `Secondary sub` definitely exhibits this problem as well. I did not check the other tables. Instead of subtitles a video might have a number of different audio tracks.

**Comment by low-batt** [comment]
This is fixed in the released version of IINA.
