### ISSUE TITLE
Option request

### ISSUE THREAD

**Issue by cagatay00** [iina/iina#4366]
**What you want IINA to do:** I want permanent osd controller option

**What IINA does currently:**When mouse goes out of inna app window, osd controller disappears.

**Why you think this should be added:**I am doing a job that i have to see the time always. when osd controller disappear, my job gets harder to handle

**Examples of other projects that have something similar:**

**Comment by smishralm10** [comment]
We can add an option in "On Screen Controller" settings to enable this behaviour and disable "Auto hide after" option when enabled. 
I'd be happy to implement this feature.

**Comment by cagatay00** [comment]
@smishralm10 that would be super, thank you

**Comment by thesla13** [comment]
Hello!

I'm sorry if this the wrong place to ask, but I have downloaded the 1.4.0 beta the other day and have been glad to find the option to keep the OSC always displayed. Some two years ago I also had a similar suggestion, #4401. So thank you so much!

But, what I would very much like to be able to do — is to be able to switch auto-hide on and off with a shortcut. Is there any way to assign a shortcut to this setting? Maybe some sort of script (I've no idea what I'm talking about, I've never used scripts in IINA)?

Again, thank you very much!

**Comment by low-batt** [comment]
This was added in IINA 1.4.0.
