### ISSUE TITLE
Scroll views do not respect reduce motion

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4374]
**System and IINA version:**

- macOS 13.3.1
- IINA 1.3.1

**Expected behavior:**
IINA reduces animations if the user has enabled the macOS [Reduce motion](https://support.apple.com/guide/mac-help/reduce-screen-motion-mchlc03f57a1/mac) setting. From Apple's Human Interface Guidelines section [Color and effects](https://developer.apple.com/design/human-interface-guidelines/foundations/accessibility#color-and-effects):
> **Play tightened animations when Reduce Motion is on.** People can turn on Reduce Motion if they tend to get distracted or experience dizziness or nausea when viewing animations that include effects such as zooming, scaling, spinning, or peripheral motion. In response to this setting, you need to turn off or reduce animations that are known to cause problems (to learn more, see [Responsive Design for Motion](https://webkit.org/blog/7551/responsive-design-for-motion/)).

**Actual behavior:**
Scroll views have [horizontalScrollElasticity](https://developer.apple.com/documentation/appkit/nsscrollview/1403540-horizontalscrollelasticity) and [verticalScrollElasticity](https://developer.apple.com/documentation/appkit/nsscrollview/1403475-verticalscrollelasticity) set to [automatic](https://developer.apple.com/documentation/appkit/nsscrollview/elasticity/automatic). This intensifies the rubber band scrolling animation effect which can be a problem for users with vestibular disorders.

<br>

**Steps to reproduce:**
- Open IINA
- Play a video
- Show the quick settings panel
- Shrink the window so a scroll bar appears in the panel
- In the quick settings panel scroll to the end of the panel
- The quick settings panel stretches and bounces

- [ ] MPV does not have this problem.

This is an IINA issue.

**How often does this happen?**
Every time.

**Comment by saagarjha** [comment]
…this seems like it works as intended? We are using the default scroll view behavior, no?

**Comment by low-batt** [comment]
Apple intends that the application, not AppKit, change animations based `Reduce motion` being enabled. AppKit provides settings on controls that applications can use to reduce animation. But doesn't help you use them, such as providing a setting that tells AppKit to choose the best behavior based on `Reduce motion`. Apple has left that to the application to implement.

I the case at hand that means we have to override the elasticity setting (which we have set to enable animations in the XIB) at runtime if the user has enabled this macOS setting.

**Comment by saagarjha** [comment]
Apple does not intend for applications to do this. This is not something we should implement.
