### ISSUE TITLE
Loading subtitles menu action should open containing directory of current video file instead of last opened directory

### ISSUE THREAD

**Issue by Blanen** [iina/iina#4382]
**What you want IINA to do:**

I would like IINA "load external subtitles..." to open the directory containing the current video file
<img width="359" alt="image" src="https://user-images.githubusercontent.com/7236824/234271937-e8ccc2a9-6b88-4e39-bdeb-0ad33e00f825.png">

Maybe even auto-detect subtitle files by extension or by subfolder(subs folder for example).

**What IINA does currently:**
Opens the last opened directory opened with this action. For me it just means it opens a different movie folder, sometimes in the "subs" directory of that directory. Before I knew this was the behavior I opened the english subtitles in the to only have loaded the subs for a different video.

**Why you think this should be added:**
Less annoying and confusion.

**Examples of other projects that have something similar:**
VLC

**Comment by Blanen** [comment]
Editing sorry...

**Comment by Blanen** [comment]
I could try it myself and make a PR if this feature is wanted by the maintainer(s).

**Comment by saagarjha** [comment]
Seems like a reasonable feature to add. Anyone else willing to weigh in?

**Comment by smishralm10** [comment]
I can look into this.

**Comment by low-batt** [comment]
This has been implemented in the released version of IINA.
