### ISSUE TITLE
Enhance identification of IINA build

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4383]
**What you want IINA to do:**
Make it very easy to determine what kind of IINA build you are running.

**What IINA does currently:**
There are four kinds of IINA builds:
- Beta
- Debug
- Nightly
- Release

Currently Beta builds can be identified by the orange `BETA` button on the welcome window:

![welcome-window-beta](https://user-images.githubusercontent.com/86170219/234702224-498b9643-4e8a-4732-99f1-aeea9ba20175.jpg)

However that window will not be shown unless the `At launch` setting is set to `Show welcome window`. In the `develop` branch the about window has been enhanced to show the build date and the git branch from which the build was generated. This is also logged:

```text
15:24:23.697 [iina][d] Built Apr 26, 2023 at 12:22:21 AM from branch develop, commit bea84bb41b43daa4d84587a6b3ff5def6fe214d5
```

However this information does not explicitly identify the kind of build.

**Why you think this should be added:**
To avoid any confusion over what kind of build is being run. This is especially important when reporting problems.

**Examples of other projects that have something similar:**
The GNOME Human Interface Guidlines for [App Icons](https://developer.gnome.org/hig/guidelines/app-icons.html) says:
> **Nightly Variant**
> If you provide a nightly or beta build of your app, it is recommended to create a specific version of the app icon for it so it is possible to tell them apart.

That convention can be seen on [this](https://www.mozilla.org/en-US/firefox/channel/desktop/) page which shows the Beta, Developer and Nightly icons used by Firefox. IINA should adopt this convention of using different icons to clearly distinguish between the different kinds of builds.

As there already is an IINA convention of identifying a Beta build on the welcome window, that should be extended to identify Nightly and Debug builds. Might want to make these buttons like is done for BETA. The NIGHTLY button would identify the build date a provide a link to the commit the build was generated from. Not as critical for DEBUG but might as well do the same for that kind of build.

The about window should be enhanced as follows:
- Beta: Instead of the branch name show the orange `BETA` label
- Debug: Show branch name and clickable commit `fix-4279 bea84bb`
- Nightly: Instead of the branch name show Nightly and clickable commit `NIGHTLY bea84bb`
- Release: Similar to welcome window, don't call out that this is the release build, suppress showing the branch name

At the start of the log file append BETA, DEBUG or NIGHTLY after the build number:
```text
00:25:13.792 [iina][d] IINA 1.3.1 Build 133 NIGHTLY
```
As the build date, branch and commit are already logged, that the only change needed to the log file.

**Comment by svobs** [comment]
What exactly is an IINA "beta" build? Is this something new?

Pretty clear on "release" and "nightly". Not so clear on "debug" either...sounds like this will be only seen by developers?

**Comment by uiryuu** [comment]
@svobs Beta is not new. We have beta releases for before x.0.0 or x.x.0 releases. It's a way to test newly added features and find out bugs before the stable release. Beta builds can auto update via Sparkle as well.

So we will have three release channel:
- Release
- Beta
- Nightly

As for debug build, that is in comparison to release build: debug build is unoptimized, every time we hit run in Xcode, a debug build is generated; whereas a release build is optimized and ready to be distributed to end users. So all builds we distribute should be release build. When dev want to let a user to test one specific issue, the dev can send a debug build to the user.

**Comment by low-batt** [comment]
Although we don't send debug builds to users, I feel it is still useful to make it clear that this is a debug build as some developers (me) take debug builds to their non-development machines for long term testing and need to distinguish those builds from official releases. No need for a special icon, but useful to call it out in the welcome and about windows.

**Comment by uiryuu** [comment]
We can add a special label in the welcome window to indicate a debug build, regardless the release type of the build.

**Comment by low-batt** [comment]
That sounds good.

**Comment by anohren** [comment]
Sounds useful, and like it'd lend itself nicely to color coding, with a matching colored border around the icon. Beta orange (like the TestFlight indicator), Nightly purple (same as Firefox), Debug...yellow?

**Comment by low-batt** [comment]
@anohren See the mockups and comments at the end of discussion #3670.

**Comment by anohren** [comment]
Already done, I see. Thanks.

**Comment by Mikasa-san** [comment]
When I tried to build in Release I got this error 

The following build commands failed:
	SwiftEmitModule normal x86_64 Emitting\ module\ for\ iina_plugin (in target 'iina-plugin' from project 'iina')
(1 failure)
note: Run script build phase 'Copy Dylib Symlinks' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'iina' from project 'iina')
Error: Process completed with exit code 65.

but in Debug It works fine

**Comment by low-batt** [comment]
I've created issue #4717 for the build issue. Lets continue the discussion in that issue.

**Comment by Mikasa-san** [comment]
It worked fine after this commit https://github.com/iina/iina/commit/79cd70c6197eeb0efd599c5c60e7c208292e3193 and also I used xcode 15 and latest macos and its works fine now

**Comment by low-batt** [comment]
Glad to hear the build is now working.
