### ISSUE TITLE
IINA Player Will Not Work 

### ISSUE THREAD

**Issue by GaiusMiliusMaximus** [iina/iina#4384]
I'm running IOS 12.6.5 and IINA will crash every time I try to play any video. It'll open the video and IINA will crash immediately after opening it. I've uninstalled IINA and installed it again several times and it keeps doing the same thing: not working. VLC is running fine and plays all the videos IINA won't open, that is, every and any video. I liked IINA better than VLC, but the fact that IINA just won't work makes me wonder if I should uninstall it, delete it, forget about it and wait for a better, reliable player for Mac.

**Comment by low-batt** [comment]
Is this a typo?: IOS 12.6.5

If you are running IINA under iOS on your iPhone then that is **VERY CONCERNING**. See the FAQ question: [Will there be a Windows/Linux/iOS version?](https://github.com/iina/iina/wiki/FAQ#will-there-be-a-windowslinuxios-version) The short answer is that IINA is only available for macOS. If you are running something called IINA on your iPhone, it isn't actually IINA. Be worried.

If that was a typo and you are running IINA under macOS Monterey 12.6.5 then it is unexpected that IINA would crash immediately after opening. macOS should be generating a crash report. The entire crash report is needed to be able to tell you what has gone wrong. My best guess is that one of the files IINA stores information in, such as the history database, is corrupted. The crash report will tell us if that guess is correct or not.

**Comment by GaiusMiliusMaximus** [comment]
I never said iPhone. Where in the heck did you get that? So yeah, my Apple Macbook Pro Laptop Computer keeps crashing when using IINA, and of course, when it crashes, it'll send a report to Apple, but since it keeps crashing and there's nothing to do about it apparently, I'm looking for a better player that will work and that is reliable, and that isn't VLC or Quicktime.

**Comment by low-batt** [comment]
The first line of the issue says **IOS**:
> I'm running IOS 12.6.5

When the crash report window pops up select all of the text in the window, copy and paste it to `TextEdit`, save the file and post it here by drag-n-drop to the `Leave a comment` box and click `Comment` and I will see what the crash report tells us.

If in that report you see a line that refers to `HistoryController` like this:
```text
16  IINA                                0x000000010dda3d23 $s4IINA17HistoryControllerC4read33_0B71AAD2BB36342BF577C90551905D8DLLyyF + 163
```

Then it is likely this is issue #3656. We did not figure out how the user got into that bad state because they deleted the file, which cleared the problem, but also erased the evidence needed to investigate further.

**Comment by GaiusMiliusMaximus** [comment]
Yes, it was the same issue as #3656. I already fixed it. Thank you very much; I really appreciate your help!

**Comment by low-batt** [comment]
Sorry you encountered #3656. Thanks for letting us know you were able to resolve the problem!

I'm going to have to walk through the history code and see if can I spot what could be going wrong.

**Comment by low-batt** [comment]
And by the way you will see crashes if you exit directly from full screen mode. That problem will be fixed in the next release of IINA.
