### ISSUE TITLE
播放杜比视界视频BUG

### ISSUE THREAD

**Issue by OyJohny** [iina/iina#4390]
播放杜比视界视频出现颜色显示错误问题，如下图，望作者改进。

**Comment by OyJohny** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/50914611/235868717-d8349f6d-7635-4238-a75c-d1d063aa6b4e.png">

**Comment by hooke007** [comment]
善用搜索 dup https://github.com/iina/iina/issues/3313 https://github.com/iina/iina/issues/3573
