### ISSUE TITLE
IINA crash

### ISSUE THREAD

**Issue by vadikgo** [iina/iina#4428]
IINA quit unexpectedly
-------------------------------------
Translated Report
-------------------------------------

Process:               IINA [49335]
Path:                  /Applications/IINA.app/Contents/MacOS/IINA
Identifier:            com.colliderli.iina
Version:               1.3.1 (133)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-05-21 18:55:19.4675 +0300
OS Version:            macOS 13.3.1 (22E772610a)
Report Version:        12
Anonymous UUID:        C0B0C6A2-25F1-1263-16D7-782CC81B79FD

Time Awake Since Boot: 1200000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000048
Exception Codes:       0x0000000000000001, 0x0000000000000048

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [49335]

VM Region Info: 0x48 is not in any region.  Bytes before following region: 105553518919608
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)

Kernel Triage:
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libmpv.1.dylib                	       0x101a05418 mpv_get_property + 16
1   IINA                          	       0x100ae77b0 PlayerCore.syncUI(_:) + 560
2   IINA                          	       0x100ae747c PlayerCore.syncUITime() + 56
3   IINA                          	       0x1009f466c MainWindowController.showUI() + 372
4   IINA                          	       0x1009f0470 MainWindowController.windowDidExitFullScreen(_:) + 504
5   IINA                          	       0x1009f3f1c @objc MainWindowController.windowWillClose(_:) + 120
6   CoreFoundation                	       0x1a85cf254 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
7   CoreFoundation                	       0x1a866af30 ___CFXRegistrationPost_block_invoke + 88
8   CoreFoundation                	       0x1a866ae78 _CFXRegistrationPost + 440
9   CoreFoundation                	       0x1a85a0580 _CFXNotificationPost + 704
10  Foundation                    	       0x1a94fd9e4 -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
11  AppKit                        	       0x1ac2676d0 -[NSWindow(NSFullScreen) _didExitFullScreen] + 336
12  AppKit                        	       0x1ac06c94c -[_NSExitFullScreenTransitionController _doAfterExitFullScreen] + 304
13  AppKit                        	       0x1ac06d1a8 -[_NSExitFullScreenTransitionController _doSucceededToExitFullScreen] + 712
14  AppKit                        	       0x1ac06d9e0 __63-[_NSExitFullScreenTransitionController _performExitFullScreen]_block_invoke + 236
15  libxpc.dylib                  	       0x1a8241650 _xpc_connection_reply_callout + 124
16  libxpc.dylib                  	       0x1a8241540 _xpc_connection_call_reply_async + 88
17  libdispatch.dylib             	       0x1a834c480 _dispatch_client_callout3 + 20
18  libdispatch.dylib             	       0x1a836a624 _dispatch_mach_msg_async_reply_invoke + 344
19  libdispatch.dylib             	       0x1a835ab4c _dispatch_main_queue_drain + 756
20  libdispatch.dylib             	       0x1a835a848 _dispatch_main_queue_callback_4CF + 44
21  CoreFoundation                	       0x1a861bc88 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
22  CoreFoundation                	       0x1a85d94a8 __CFRunLoopRun + 1992
23  CoreFoundation                	       0x1a85d858c CFRunLoopRunSpecific + 612
24  HIToolbox                     	       0x1b1e0ddf4 RunCurrentEventLoopInMode + 292
25  HIToolbox                     	       0x1b1e0dc30 ReceiveNextEventCommon + 648
26  HIToolbox                     	       0x1b1e0d988 _BlockUntilNextEventMatchingListInModeWithFilter + 76
27  AppKit                        	       0x1ab7f7f58 _DPSNextEvent + 636
28  AppKit                        	       0x1ab7f70f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
29  AppKit                        	       0x1aba18764 -[NSApplication _shouldTerminate] + 700
30  AppKit                        	       0x1aba0b450 -[NSApplication terminate:] + 612
31  AppKit                        	       0x1abb2f024 -[NSApplication _terminateFromSender:askIfShouldTerminate:saveWindows:] + 124
32  AppKit                        	       0x1abaf22a0 __79-[NSApplication(NSWindowCache) _scheduleCheckForTerminateAfterLastWindowClosed]_block_invoke + 56
33  AppKit                        	       0x1ac009828 ___NSRunLoopTimerCreateWithHandler_block_invoke + 56
34  CoreFoundation                	       0x1a85f448c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
35  CoreFoundation                	       0x1a85f4134 __CFRunLoopDoTimer + 940
36  CoreFoundation                	       0x1a85f3c8c __CFRunLoopDoTimers + 356
37  CoreFoundation                	       0x1a85d941c __CFRunLoopRun + 1852
38  CoreFoundation                	       0x1a85d858c CFRunLoopRunSpecific + 612
39  HIToolbox                     	       0x1b1e0ddf4 RunCurrentEventLoopInMode + 292
40  HIToolbox                     	       0x1b1e0dc30 ReceiveNextEventCommon + 648
41  HIToolbox                     	       0x1b1e0d988 _BlockUntilNextEventMatchingListInModeWithFilter + 76
42  AppKit                        	       0x1ab7f7f58 _DPSNextEvent + 636
43  AppKit                        	       0x1ab7f70f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
44  AppKit                        	       0x1ab7eb558 -[NSApplication run] + 464
45  AppKit                        	       0x1ab7c29a8 NSApplicationMain + 880
46  IINA                          	       0x100962428 main + 12
47  dyld                          	       0x1a81a3f28 start + 2236

Thread 1:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	       0x1a84bbe90 semaphore_wait_trap + 8
1   caulk                         	       0x1b1b1a024 caulk::semaphore::timed_wait(double) + 212
2   caulk                         	       0x1b1b19ed8 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	       0x1b1b19bc8 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x1a84fbfa8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1a84f6da0 thread_start + 8

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1a84bbf14 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1a84ce240 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1a84c4b78 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x1a84bc290 mach_msg + 24
4   CoreFoundation                	       0x1a85da8b8 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a85d9198 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a85d858c CFRunLoopRunSpecific + 612
7   AppKit                        	       0x1ab922508 _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x1a84fbfa8 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x1a84f6da0 thread_start + 8

Thread 3:
0   libsystem_pthread.dylib       	       0x1a84f6d8c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1a84f6d8c start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x1a84f6d8c start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x1a84f6d8c start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x1a84f6d8c start_wqthread + 0

Thread 8:: com.apple.coremedia.rootQueue.47
0   libsystem_kernel.dylib        	       0x1a84bbea8 semaphore_timedwait_trap + 8
1   libdispatch.dylib             	       0x1a834ca18 _dispatch_sema4_timedwait + 64
2   libdispatch.dylib             	       0x1a834d018 _dispatch_semaphore_wait_slow + 76
3   libdispatch.dylib             	       0x1a835dc6c _dispatch_worker_thread + 324
4   libsystem_pthread.dylib       	       0x1a84fbfa8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1a84f6da0 thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000100bdfc61   x2: 0x0000000000000005   x3: 0x000000016f49e940
    x4: 0xe700000000000000   x5: 0x0000000000000001   x6: 0x0000000204a3ac48   x7: 0x0000000000000000
    x8: 0x0000000000000008   x9: 0x0000000200000003  x10: 0x0000000000000003  x11: 0x0000000000000074
   x12: 0x00000000a4042847  x13: 0x00000000000007fd  x14: 0x00000000a4243033  x15: 0x00000000a4042847
   x16: 0x0000000101a05408  x17: 0x0300000100c4e631  x18: 0x0000000000000000  x19: 0x0000000206303908
   x20: 0x0000600001119120  x21: 0x0000000000000000  x22: 0x000000016f49e8d0  x23: 0x0000000000000008
   x24: 0x000000016f49e8c0  x25: 0x0000600002e913b0  x26: 0x000060000238a6d0  x27: 0x0000000100c67d10
   x28: 0x0000000204a49430   fp: 0x000000016f49e8b0   lr: 0x0000000100ae77b0
    sp: 0x000000016f49e860   pc: 0x0000000101a05418 cpsr: 0x60001000
   far: 0x0000000000000048  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x10095c000 -        0x100c0bfff com.colliderli.iina (1.3.1) <da58f4cc-7901-3bca-a111-34e5236b0261> /Applications/IINA.app/Contents/MacOS/IINA
       0x101218000 -        0x10125ffff org.sparkle-project.Sparkle (1.27.1) <03b93eb2-1724-361d-afeb-cbf423fec740> /Applications/IINA.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x101994000 -        0x101c6ffff libmpv.1.dylib (*) <e8089b8a-8ba0-3583-a8f2-e724a48fa25f> /Applications/IINA.app/Contents/Frameworks/libmpv.1.dylib
       0x10309c000 -        0x1038dffff libavcodec.58.dylib (*) <d57b6ac3-69bb-3fe4-80ba-a0c2fd9e8485> /Applications/IINA.app/Contents/Frameworks/libavcodec.58.dylib
       0x10169c000 -        0x10184ffff libavformat.58.dylib (*) <d1bc3fb0-0eb0-3e6b-8c17-8582e563a15a> /Applications/IINA.app/Contents/Frameworks/libavformat.58.dylib
       0x10129c000 -        0x1012ebfff libavutil.56.dylib (*) <3852e24c-7a21-3e15-8711-c0582b0d5087> /Applications/IINA.app/Contents/Frameworks/libavutil.56.dylib
       0x101518000 -        0x101583fff libswscale.5.dylib (*) <9882cdd7-7479-353c-9a71-9a3123a02ece> /Applications/IINA.app/Contents/Frameworks/libswscale.5.dylib
       0x1022a4000 -        0x1024b3fff libavfilter.7.dylib (*) <191a9776-cb43-31fa-b4b1-d40bf48a34be> /Applications/IINA.app/Contents/Frameworks/libavfilter.7.dylib
       0x101150000 -        0x101163fff libswresample.3.dylib (*) <299a030f-ebf4-3005-9495-befd7ef14116> /Applications/IINA.app/Contents/Frameworks/libswresample.3.dylib
       0x101104000 -        0x10113bfff libmujs.dylib (*) <4ceaa680-f85a-3dc0-826c-754b81075293> /Applications/IINA.app/Contents/Frameworks/libmujs.dylib
       0x10159c000 -        0x1015c7fff libjpeg.9.dylib (*) <32ed69ed-cc93-3bdf-9e5a-87e41188edbe> /Applications/IINA.app/Contents/Frameworks/libjpeg.9.dylib
       0x101174000 -        0x1011affff liblcms2.2.dylib (*) <926ba1ff-0db6-3716-980c-1a8a62125854> /Applications/IINA.app/Contents/Frameworks/liblcms2.2.dylib
       0x1015dc000 -        0x10165ffff libarchive.13.dylib (*) <f683cd6d-54d6-35ae-895c-1bc9eaba7e07> /Applications/IINA.app/Contents/Frameworks/libarchive.13.dylib
       0x1011d0000 -        0x1011f3fff libass.9.dylib (*) <a0213f3d-edf5-35f3-b2f8-5db30417f876> /Applications/IINA.app/Contents/Frameworks/libass.9.dylib
       0x101900000 -        0x101917fff libavdevice.58.dylib (*) <9b1fb29b-3747-38c0-8cbb-18e31df63968> /Applications/IINA.app/Contents/Frameworks/libavdevice.58.dylib
       0x1018a8000 -        0x1018e7fff libbluray.2.dylib (*) <10625fed-b446-33f5-9212-e5336f628e43> /Applications/IINA.app/Contents/Frameworks/libbluray.2.dylib
       0x101e1c000 -        0x101e8ffff libluajit-5.1.2.dylib (*) <c08d77bb-69f3-3500-9f10-4ed3807b985f> /Applications/IINA.app/Contents/Frameworks/libluajit-5.1.2.dylib
       0x10192c000 -        0x10194ffff librubberband.2.dylib (*) <ecb2d79c-64a7-375a-a506-93c547ed998e> /Applications/IINA.app/Contents/Frameworks/librubberband.2.dylib
       0x101d78000 -        0x101d9ffff libuchardet.0.dylib (*) <9992fb01-32bb-3bc3-b6f0-2ac441cce12e> /Applications/IINA.app/Contents/Frameworks/libuchardet.0.dylib
       0x101d00000 -        0x101d37fff libzimg.2.dylib (*) <770682a8-0582-3211-9045-c96b73b41892> /Applications/IINA.app/Contents/Frameworks/libzimg.2.dylib
       0x101eb0000 -        0x101ecbfff liblzma.5.dylib (*) <67ff2ab8-3d81-346e-b1a7-f5831df75bd9> /Applications/IINA.app/Contents/Frameworks/liblzma.5.dylib
       0x102168000 -        0x10220bfff libdav1d.5.dylib (*) <9d804697-0f0c-376f-a59b-a9e36f5a991f> /Applications/IINA.app/Contents/Frameworks/libdav1d.5.dylib
       0x101970000 -        0x101977fff libsnappy.1.dylib (*) <4022c0b2-738d-32c7-9895-bafe4192d0c1> /Applications/IINA.app/Contents/Frameworks/libsnappy.1.dylib
       0x101ee0000 -        0x101ef3fff libspeex.1.dylib (*) <8f494ccd-0fd4-3875-bd07-cf4fb579c655> /Applications/IINA.app/Contents/Frameworks/libspeex.1.dylib
       0x101db4000 -        0x101dd3fff libsoxr.0.dylib (*) <f48b27a0-7d51-38b4-98cd-a0781ded7ca3> /Applications/IINA.app/Contents/Frameworks/libsoxr.0.dylib
       0x101f04000 -        0x10206ffff libgnutls.30.dylib (*) <41415c3d-03b5-31cf-9136-b1e5b722fd91> /Applications/IINA.app/Contents/Frameworks/libgnutls.30.dylib
       0x1026a0000 -        0x1026fbfff libzmq.5.dylib (*) <17f2999e-c97c-3ecf-b500-0a4083af07f1> /Applications/IINA.app/Contents/Frameworks/libzmq.5.dylib
       0x102560000 -        0x102593fff libfontconfig.1.dylib (*) <b8c13902-50e3-3042-b871-605de89bde7b> /Applications/IINA.app/Contents/Frameworks/libfontconfig.1.dylib
       0x1025ac000 -        0x102627fff libfreetype.6.dylib (*) <a2888acb-1683-342f-976c-ffd3a3038b28> /Applications/IINA.app/Contents/Frameworks/libfreetype.6.dylib
       0x102104000 -        0x10210ffff libintl.8.dylib (*) <dfef0cad-a017-3020-88b9-649bf110c914> /Applications/IINA.app/Contents/Frameworks/libintl.8.dylib
       0x1020cc000 -        0x1020effff libpng16.16.dylib (*) <ae1a915e-6edd-32bf-8b0e-2334eb801cb8> /Applications/IINA.app/Contents/Frameworks/libpng16.16.dylib
       0x102958000 -        0x102a1bfff libp11-kit.0.dylib (*) <34cb5c74-6da5-341d-8138-6418de3f9b1e> /Applications/IINA.app/Contents/Frameworks/libp11-kit.0.dylib
       0x102120000 -        0x10213ffff libidn2.0.dylib (*) <0a447085-73e1-39b6-b809-5b0292cb5046> /Applications/IINA.app/Contents/Frameworks/libidn2.0.dylib
       0x102740000 -        0x1028d7fff libunistring.2.dylib (*) <70baa370-d7dd-3b8f-8212-3d30eaede2b6> /Applications/IINA.app/Contents/Frameworks/libunistring.2.dylib
       0x102274000 -        0x10227ffff libtasn1.6.dylib (*) <45126420-cf0f-3837-a7a3-9afedfdbfd91> /Applications/IINA.app/Contents/Frameworks/libtasn1.6.dylib
       0x102650000 -        0x10267ffff libnettle.8.dylib (*) <81edfeb2-5678-313b-a2eb-0b6e3d25c374> /Applications/IINA.app/Contents/Frameworks/libnettle.8.dylib
       0x1028fc000 -        0x102933fff libhogweed.6.dylib (*) <d91d481a-5c1f-3f08-8f17-03a194d1031a> /Applications/IINA.app/Contents/Frameworks/libhogweed.6.dylib
       0x102b5c000 -        0x102bb3fff libgmp.10.dylib (*) <1b0ed021-d966-3812-b59a-7e98e2afee4e> /Applications/IINA.app/Contents/Frameworks/libgmp.10.dylib
       0x102ab0000 -        0x102ac3fff libffi.8.dylib (*) <1408e6fd-aa3e-3510-b809-24b912ff8c15> /Applications/IINA.app/Contents/Frameworks/libffi.8.dylib
       0x102ad4000 -        0x102af7fff libsodium.23.dylib (*) <70bc45ff-75e2-36ff-a0f5-00b4b5343b73> /Applications/IINA.app/Contents/Frameworks/libsodium.23.dylib
       0x102150000 -        0x102157fff libpostproc.55.dylib (*) <7b34b610-f825-3ce4-8b32-c05e036b370e> /Applications/IINA.app/Contents/Frameworks/libpostproc.55.dylib
       0x102bcc000 -        0x102dabfff libtesseract.5.dylib (*) <3ed5e74a-556d-3b47-ab5c-c2e955ade3fa> /Applications/IINA.app/Contents/Frameworks/libtesseract.5.dylib
       0x102b14000 -        0x102b1ffff libvidstab.1.1.dylib (*) <5b96389e-ddb8-3449-9286-8e3b57de022d> /Applications/IINA.app/Contents/Frameworks/libvidstab.1.1.dylib
       0x1043d0000 -        0x1045a7fff liblept.5.dylib (*) <b5e35649-26f3-3aca-8f55-edab92e1d688> /Applications/IINA.app/Contents/Frameworks/liblept.5.dylib
       0x102b30000 -        0x102b37fff libgif.dylib (*) <4ef5081c-c168-3954-b838-433ea072537d> /Applications/IINA.app/Contents/Frameworks/libgif.dylib
       0x102f70000 -        0x102fcbfff libtiff.5.dylib (*) <ba7ee282-2ae6-3000-9a8d-46c1ecc6e2b1> /Applications/IINA.app/Contents/Frameworks/libtiff.5.dylib
       0x102e7c000 -        0x102e83fff libwebpmux.3.dylib (*) <861e3f81-9adb-3859-be62-080376c89edb> /Applications/IINA.app/Contents/Frameworks/libwebpmux.3.dylib
       0x102fe8000 -        0x103027fff libwebp.7.dylib (*) <9665a603-e243-3562-bc03-cc56a384f9fb> /Applications/IINA.app/Contents/Frameworks/libwebp.7.dylib
       0x103040000 -        0x103083fff libopenjp2.7.dylib (*) <da0c73e0-b72a-34a5-bf6f-89286a4739d2> /Applications/IINA.app/Contents/Frameworks/libopenjp2.7.dylib
       0x102e94000 -        0x102f33fff libzstd.1.dylib (*) <ed895779-5b03-35f8-9cb8-68a1a918da44> /Applications/IINA.app/Contents/Frameworks/libzstd.1.dylib
       0x102a74000 -        0x102a8ffff liblz4.1.dylib (*) <0521a050-d6d8-3c9c-8a9b-cdc866861a3e> /Applications/IINA.app/Contents/Frameworks/liblz4.1.dylib
       0x102f54000 -        0x102f5bfff libb2.1.dylib (*) <b6ac4e59-bd35-3097-babe-ec3405d6ce05> /Applications/IINA.app/Contents/Frameworks/libb2.1.dylib
       0x103fb4000 -        0x103fcffff libfribidi.0.dylib (*) <afdb3cad-9eb8-37f7-ab72-61809d585e17> /Applications/IINA.app/Contents/Frameworks/libfribidi.0.dylib
       0x104204000 -        0x1042bbfff libharfbuzz.0.dylib (*) <e782c8f4-ed89-3a53-b848-c9739beffd23> /Applications/IINA.app/Contents/Frameworks/libharfbuzz.0.dylib
       0x103fe0000 -        0x103ff3fff libgraphite2.3.dylib (*) <bfe3b8b5-90eb-3141-8e25-a4be70288195> /Applications/IINA.app/Contents/Frameworks/libgraphite2.3.dylib
       0x104008000 -        0x1040ebfff libglib-2.0.0.dylib (*) <54f55c8f-62c5-30cd-ac35-3a878691461a> /Applications/IINA.app/Contents/Frameworks/libglib-2.0.0.dylib
       0x103f5c000 -        0x103f93fff libpcre.1.dylib (*) <b8393e5b-bf7b-351e-8165-e6f44723e782> /Applications/IINA.app/Contents/Frameworks/libpcre.1.dylib
       0x104188000 -        0x10419bfff libxcb.1.dylib (*) <34bfcd18-46bb-35aa-83a0-ccf404d1ec99> /Applications/IINA.app/Contents/Frameworks/libxcb.1.dylib
       0x101688000 -        0x10168bfff libxcb-shm.0.dylib (*) <9ed523d8-0f98-3167-a239-007defcfa561> /Applications/IINA.app/Contents/Frameworks/libxcb-shm.0.dylib
       0x101d64000 -        0x101d67fff libxcb-shape.0.dylib (*) <694aea2c-595c-331b-969a-0217f21da21e> /Applications/IINA.app/Contents/Frameworks/libxcb-shape.0.dylib
       0x104154000 -        0x10415bfff libxcb-xfixes.0.dylib (*) <98d401da-ddc4-3ff0-b1b3-1d5b22489d27> /Applications/IINA.app/Contents/Frameworks/libxcb-xfixes.0.dylib
       0x102290000 -        0x102293fff libXau.6.dylib (*) <8a30dcf0-a4e2-3459-82c3-cdd3e5b83943> /Applications/IINA.app/Contents/Frameworks/libXau.6.dylib
       0x102b48000 -        0x102b4bfff libXdmcp.6.dylib (*) <aa177442-5712-3e92-92b3-34e8096d36b4> /Applications/IINA.app/Contents/Frameworks/libXdmcp.6.dylib
       0x10e5d8000 -        0x10e5e3fff libobjc-trampolines.dylib (*) <80f14f3d-d099-3693-a8e0-eb9a526b1790> /usr/lib/libobjc-trampolines.dylib
       0x118900000 -        0x11891ffff com.apple.security.csparser (3.0) <862735d9-d84d-31b0-bfa8-d75e2271af1a> /System/Library/Frameworks/Security.framework/Versions/A/PlugIns/csparser.bundle/Contents/MacOS/csparser
       0x11bc5c000 -        0x11bc63fff com.apple.CloudDocsFileProvider (1.0) <26e33c5a-f76f-3570-8782-d0dc2d61ff00> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/CloudDocsFileProvider.bundle/Contents/MacOS/CloudDocsFileProvider
       0x11bc74000 -        0x11bc7bfff com.apple.FileProviderOverride (855.100.378) <782f062d-b9d5-3e62-9ce7-b68d197712a2> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/FileProviderOverride.bundle/Contents/MacOS/FileProviderOverride
       0x11bd14000 -        0x11bd33fff com.apple.findersync.fileprovideroverride.FinderSyncCollaborationFileProviderOverride (13.3) <99856966-e77f-3294-a16a-e59a7e494572> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride
       0x11d13c000 -        0x11d1a7fff com.apple.AppleMetalOpenGLRenderer (1.0) <7651840d-f268-3dea-ab6e-979cd46d3b2b> /System/Library/Extensions/AppleMetalOpenGLRenderer.bundle/Contents/MacOS/AppleMetalOpenGLRenderer
       0x1282e8000 -        0x12841bfff com.apple.audio.units.Components (1.14) <3318bd64-e64f-3e69-991d-605d1bc10d7d> /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
       0x1a855b000 -        0x1a8a34fff com.apple.CoreFoundation (6.9) <b4fdaece-9727-3969-b014-27f7f24c8e01> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1a94f4000 -        0x1a9eb9fff com.apple.Foundation (6.9) <b7d67e5a-dce2-3f6b-b2b8-895a3669e3ec> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x1ab7bf000 -        0x1ac6cdfff com.apple.AppKit (6.9) <cc3e5215-4cd7-364c-8750-6eb7002720ce> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1a8232000 -        0x1a8275fff libxpc.dylib (*) <f94bdfc7-9955-30c0-b092-19d4fb410ae1> /usr/lib/system/libxpc.dylib
       0x1a8348000 -        0x1a838ffff libdispatch.dylib (*) <8e87dc0e-a570-3933-b37d-5e05ad516206> /usr/lib/system/libdispatch.dylib
       0x1b1ddd000 -        0x1b2110fff com.apple.HIToolbox (2.1.1) <5f34bbf5-653a-31a5-b4b3-0a02c91ab488> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x1a819e000 -        0x1a822c53b dyld (*) <ac277a36-1808-327a-8761-cca585421212> /usr/lib/dyld
       0x1a84bb000 -        0x1a84f4fe7 libsystem_kernel.dylib (*) <7acbd9bc-d056-310e-858d-81b116cf6d28> /usr/lib/system/libsystem_kernel.dylib
       0x1b1b18000 -        0x1b1b40fff com.apple.audio.caulk (1.0) <06456788-36d4-3e9d-ab9a-eab934756fe4> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x1a84f5000 -        0x1a8501fff libsystem_pthread.dylib (*) <b401cfb3-8dfe-32db-92b3-ba8af0f8ca6e> /usr/lib/system/libsystem_pthread.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)
Writable regions: Total=2.0G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=2.0G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG backing stores                 6400K        8 
CG image                          1744K       30 
CG raster data                    12.6M      101 
ColorSync                          624K       29 
CoreAnimation                     10.5M      358 
CoreGraphics                        48K        3 
CoreGraphics (reserved)             16K        1         reserved VM address space (unallocated)
CoreImage                           16K        1 
CoreUI image data                 5680K       44 
Foundation                          16K        1 
Foundation (reserved)               16K        1         reserved VM address space (unallocated)
Kernel Alloc Once                   32K        1 
MALLOC                           554.4M       97 
MALLOC guard page                  288K       14 
MALLOC_MEDIUM (reserved)           1.0G       10         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        384K        5 
SQLite page cache                  128K        1 
STACK GUARD                       56.1M        9 
Stack                             12.2M        9 
VM_ALLOCATE                       1568K       34 
__AUTH                            1682K      351 
__AUTH_CONST                      27.9M      575 
__CTF                               824        1 
__DATA                            21.8M      637 
__DATA_CONST                      30.2M      648 
__DATA_DIRTY                      1958K      220 
__FONT_DATA                        2352        1 
__GLSLBUILTINS                    5174K        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       811.4M       71 
__OBJC_RO                         66.2M        1 
__OBJC_RW                         2011K        1 
__TEXT                           643.5M      669 
dyld private memory                272K        2 
libnetwork                         128K        8 
mapped file                      203.8M       43 
shared memory                      976K       19 
===========                     =======  ======= 
TOTAL                              3.8G     4009 
TOTAL, minus reserved VM space     2.4G     4009

**Comment by low-batt** [comment]
Thank you for reporting this crash.

The crash report shows this is the problem described in issue #4020. That problem has been fixed in the development version of IINA. That fix will be included in the next release of IINA. See the pinned issue for status of the next release.
