### ISSUE TITLE
Identify generated sources

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4429]
**What you want IINA to do:**
The swift classes `MPVCommand`, `MPVOption` and `MPVProperty` are all generated and **must not** be modified by developers. These files are generated from mpv documentation by the script `other/parse_doc.rb` and then checked into git. This is done whenever IINA upgrades to a newer version of the mpv library.

Normally generated files should not be checked into source control. They should be regenerated as a part of the build. This is the proper way to ensure that developers do not accidentally modify the generated source instead of the true source or the generator. This also ensures that anything that breaks the source generation process is noticed early.

However, this issue is not about changing the IINA build process to always generate these files. This issue proposes several changes to make it less likely that a new developer modifies the generated source.

The following changes are suggested:
- Change `parse_doc.rb` to include a comment at the top of the generated source that makes it very clear that the source file has been generated and **must not** be directly modified by developers
- Add a new group `Generated` to the Xcode project and move the generated sources into that group
- Update the [Current structure](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md#current-structure) section of the [Contributing](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md) document to warn contributors about the generated sources

**What IINA does currently:**
It is not at all obvious to a new contributor that these sources should not be modified.

**Why you think this should be added:**
A pull request was submitted containing changes to these sources.

**Comment by saagarjha** [comment]
+1 to this and +1 to generating the files on-demand fwiw

**Comment by low-batt** [comment]
Incorporating generation into the build is more involved. An issue for another day. I figured the changes proposed in this issue could be done quickly and should be effective in communicating to new collaborators the special nature of these three sources.
