### ISSUE TITLE
Second ASS Subtitle keep its own style.

### ISSUE THREAD

**Issue by doumeem** [iina/iina#4433]
**What you want IINA to do:**
Keep the style of second subtitle if it's ass

**What IINA does currently:**
Changes the style and position of the second subtitle to just normal font and puts in the top

**Why you think this should be added:**
When comparing 2 different ass subtitles

**Examples of other projects that have something similar:**

**Comment by low-batt** [comment]
Similar to many open source projects IINA is layered on top of other projects. For audio/video playback IINA is using a library from the [mpv](https://mpv.io/) project.

Rendering subtitles is a part of video playback. When it comes to how subtitles are embedded in the video IINA can only provide the features mpv provides for controlling subtitles. The available features can be found in the [subtitles](https://mpv.io/manual/stable/#subtitles) section of the [mpv manual](https://mpv.io/manual/stable/).

As the mpv issue [#3022](https://github.com/mpv-player/mpv/issues/3022) is still open, I don't think there is a way yet to control the style of the secondary subtitle.

For IINA this a an "upstream" issue. This feature must be added to mpv. Then mpv would have to include the new feature in a release. At that point IINA could upgrade the mpv library it embeds, gaining support for the new feature.

**Comment by hooke007** [comment]
Now you can update libmpv to test.
`secondary-sub-ass-override=scale`

**Comment by low-batt** [comment]
@hooke007 Thanks for pointing out the new `mpv` option. I'm currently overloaded and have not been keeping an eye on what `mpv` has been merging. Normally I'd immediately test this, but at the moment I need to focus on other tasks.

I see [secondary-sub-delay](https://mpv.io/manual/master/#options-secondary-sub-delay) and [secondary-sub-pos](https://mpv.io/manual/master/#options-secondary-sub-pos) have been added as well.

There are multiple open IINA issues requesting better secondary subtitle support. Now that support has been added to `mpv` I am going to label this issue as a high priority to add support for these settings.

**Comment by low-batt** [comment]
Re-opening as PR #5050 does not close this issue, it is related in that it changed the override level slider.

**Comment by low-batt** [comment]
Support was added in IINA 1.4.0-beta1.
