### ISSUE TITLE
Crash when quitting with Inspector window open

### ISSUE THREAD

**Issue by svobs** [iina/iina#4456]
**System and IINA version:**

- macOS 13.4
- IINA develop branch 39801567ac3c836e655f37041bf2af5f277cad69

**Expected behavior:**
IINA exits cleanly

**Actual behavior:**
IINA crashes with a "bad access" exception.

First encountered this on my recent PR branch, but then was able to reproduce it on `develop`. This was while running from XCode, and though I disabled all the breakpoints, I was unable to prevent it from breaking on the exception and I couldn't get past it - so no fancy crash report I can post here. Feeling a bit lazy to build an archive and try to reproduce it yet again. It looks like a familiar problem though.
<img width="1967" alt="SCR-20230607-oolb" src="https://github.com/iina/iina/assets/2213815/19bd55ab-5570-4fa3-b16d-8756111305bf">

**Steps to reproduce:**
1. Assemble at least 2 videos in a directory.
2. Open IINA. Make sure `Settings` > `General` > `Playlist` > `Add files in the same folder automatically` is checked.
3. In IINA, open the first video in the directory.
4. Show the Inspector window.
5. Skip to the next video.
6. Wait about 1 second and then use `Command`+`Q` to quit IINA.
7. See if IINA crashes.

**How often does this happen?**
Between 1/5 and 1/10 of the time.

**Comment by low-batt** [comment]
With the mpv IPC interface enabled by setting `input-ipc-server` to `/tmp/mpv-socket` the following bash script will reproduce the problem:
<details>
<summary><b>startQuitLoop.sh:</b></summary>

```bash
#!/bin/bash

while true; do

    echo Starting IINA
    
    open -a /Users/low-batt/Library/Developer/Xcode/DerivedData/iina-gwhhvjgxybcchtdcwvmukizbfeip/Build/Products/Debug/IINA.app  ~/Movies/Airplaneski.mp4

    sleep 1

    osascript -e 'activate application "IINA"' \
              -e 'tell application "System Events" to keystroke "i" using command down'

    sleep 1
    
    
    echo Instructing  IINA to Quit
    osascript -e 'activate application "IINA"' \
              -e 'tell application "System Events" to keystroke "q" using command down'

    echo '{ "command": ["playlist-next", "weak"] }' | socat - /tmp/mpv-socket | jq

    sleep 2
    
done
```
</details>

**Comment by low-batt** [comment]
IINA 1.3.2 contains the fix for this issue.
