### ISSUE TITLE
Add customizable playback controls to Picture-in-Picture mode

### ISSUE THREAD

**Issue by CacheStacks** [iina/iina#4466]
**What you want IINA to do:**
Have a customizable Picture-in-Picture playback panel accessible through settings.

**What IINA does currently:**
Simply has exit Picture-in-Picture mode button (also a close "X" button which does the same action) and play/pause button.

**Why you think this should be added:**
Sometimes I watch very long video streams and miss a word or two and would like to flit back a few seconds or forward some to skip by breaks, etc. It would be great to have a subset of control buttons to choose from that could let a user customize their style of playback (for instance the seek bar, jump X amount of seconds forward or back, skip to end/beginning, etc.).

**Comment by saagarjha** [comment]
IINA uses the system PIP window, which doesn't support this as far as I can tell.

**Comment by uiryuu** [comment]
If you want richer playback control than the system-provided PIP, please use float on top feature and you can use all the controls in the main window.
