### ISSUE TITLE
upgraded to 1.3.2 and IINA hangs opening webm files. 1.3.1 is OK

### ISSUE THREAD

**Issue by jwasilko** [iina/iina#4485]
1.3.2 opens a webm file and just shows a black window and the spinning beach ball. 1.3.1 opens the same file correctly. Same behavior on multiple macs running OS 13.4.1

Here's the stack trace from killing IINA with force quit:

Heaviest stack for the main thread of the target process:
  19  start + 1903 (dyld + 25631) [0x7ff81056441f]
  19  main + 9 (IINA + 31945) [0x10a905cc9]
  19  NSApplicationMain + 817 (AppKit + 15618) [0x7ff8139f1d02]
  19  -[NSApplication run] + 586 (AppKit + 195304) [0x7ff813a1dae8]
  19  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214 (AppKit + 251002) [0x7ff813a2b47a]
  19  _DPSNextEvent + 858 (AppKit + 255440) [0x7ff813a2c5d0]
  19  _BlockUntilNextEventMatchingListInModeWithFilter + 64 (HIToolbox + 190744) [0x7ff81a413918]
  19  ReceiveNextEventCommon + 657 (HIToolbox + 191422) [0x7ff81a413bbe]
  19  RunCurrentEventLoopInMode + 292 (HIToolbox + 191917) [0x7ff81a413dad]
  19  CFRunLoopRunSpecific + 560 (CoreFoundation + 503601) [0x7ff810997f31]
  19  __CFRunLoopRun + 2206 (CoreFoundation + 507449) [0x7ff810998e39]
  19  __CFRunLoopDoTimers + 285 (CoreFoundation + 613113) [0x7ff8109b2af9]
  19  __CFRunLoopDoTimer + 807 (CoreFoundation + 614099) [0x7ff8109b2ed3]
  19  __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20 (CoreFoundation + 615256) [0x7ff8109b3358]
  19  __NSFireTimer + 67 (Foundation + 649062) [0x7ff811863766]
  19  @objc PlayerCore.syncUITime() + 24 (IINA + 1918504) [0x10aad2628]
  19  PlayerCore.syncUITime() + 51 (IINA + 1918259) [0x10aad2533]
  19  PlayerCore.syncUI(_:) + 971 (IINA + 1919499) [0x10aad2a0b]
  19  mpv_get_property + 92 (libmpv.2.dylib + 521388) [0x10c02b4ac]
  19  mp_dispatch_lock + 221 (libmpv.2.dylib + 414909) [0x10c0114bd]
  19  __psynch_cvwait + 10 (libsystem_kernel.dylib + 16622) [0x7ff8108820ee]
 *19  psynch_cvcontinue + 0 (com.apple.kec.pthread + 20884) [0xffffff8003766194]

**Comment by lhc70000** [comment]
Please see this discussion thread: https://github.com/iina/iina/discussions/4479#discussioncomment-6393427


> Chiming in to say this is likely caused by [VideoToolbox VP9 hwaccel freezes ffmpeg](https://trac.ffmpeg.org/ticket/9599). A workaround is adding the `mpv` option `hwdec-codecs` and setting it to `h264,vc1,hevc,vp8,av1` (removing VP9) in the Advanced menu in the settings.

**Comment by jwasilko** [comment]
Thanks!

**Comment by uiryuu** [comment]
Closed as duplicate
