### ISSUE TITLE
No Audio in over-4x speedup 

### ISSUE THREAD

**Issue by hshsilver** [iina/iina#4492]
No Audio in over-4x speedup.

Is this a feature or a bug?

As I know many Chrome extensions could keep sound when videos is in 16x speed up.

**Comment by low-batt** [comment]
This is a configurable feature. 

For audio/video playback IINA is using a library from the [mpv](https://mpv.io/) project. Many mpv configuration settings not exposed in the IINA GUI can still be used by setting them in IINA's `Advanced` settings.

From the mpv manual's entry for the [speed](https://mpv.io/manual/stable/#options-speed) option:
> **--speed=<0.01-100>**
>    Slow down or speed up playback by the factor given as parameter.
>
>    If --audio-pitch-correction (on by default) is used, playing with a speed higher than normal automatically inserts the scaletempo2 audio filter.

So by default when IINA changes the speed the mpv library is adding an audio filter. From the mpv manual's entry for [scaletempo2](https://mpv.io/manual/stable/#audio-filters-scaletempo2[):
> **scaletempo2\[=option1:option2:...]**
>
>    Scales audio tempo without altering pitch. The algorithm is ported from chromium and uses the Waveform Similarity Overlap-and-add (WSOLA) method. It seems to achieve a higher audio quality than scaletempo and rubberband.
> …
> **max-speed=\<speed>**
>    Mute audio if the playback speed is above <speed> and <speed> != 0. (default: 4.0)

Note: "(default: 4.0)" This explains why audio is muted above 4x.

To permanently change this configuration follow these instructions.

- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Advanced`
- Slide the `Enable advanced settings` toggle button to be on (blue)
- In the `Additional mpv options` section click on `+`
- A new entry appears in the table
- Double click on `name` and replace it with `af`
- Double click on `value` and replace it with `scaletempo2=max-speed=16`
- Confirm the settings panel looks like the screenshot below
- **Restart IINA** to activate the new settings

![issue-4492](https://github.com/iina/iina/assets/86170219/e0b5aeb6-f39b-4982-b576-c2fbe069e970)
It is also possible to add audio filters directly. Click on `Audio Filters…` under the `Audio` menu.

For more details on this read the linked mpv manual sections.

**Comment by hshsilver** [comment]
Problem Solved!😊
Thanks for your well-stylized and detailed instructions!
