### ISSUE TITLE
Inspector pallet: entries in the Status/Watch section are truncated 

### ISSUE THREAD

**Issue by scrutinizer11** [iina/iina#4521]
**What you want IINA to do:**

The _Watch_ list of the _Inspector_ has

(1) Resizable columns (2) lines wrap 

**What IINA does currently:**

In the Watch list, key identifiers and values are truncated without an option to resize the columns by dragging the separator.

![Screenshot 2023-07-21 at 21 11 26](https://github.com/iina/iina/assets/45983734/ee46dfa4-d8de-4dc9-9663-3b9b63bd289b)

**Comment by svobs** [comment]
Will submit a PR for this one soon

**Comment by low-batt** [comment]
This was fixed in IINA 1.4.0-beta1.
