### ISSUE TITLE
Separate control for secondary subtitle delay

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4524]
**What you want IINA to do:**
Provide a way to separately control the delay for the primary and secondary subtitles. This should include a way to keep the delays in sync to avoid forcing users to change two sliders when both subtitles need the same delay applied.

This feature request comes from a Telegram user in the IINA group chat.

**What IINA does currently:**
A single slider on the subtitles panel controls the delay for both the primary and secondary subtitles.

**Why you think this should be added:**
This ability has been requested in mpv issue https://github.com/mpv-player/mpv/issues/2629. There is a pending implementation in mpv PR https://github.com/mpv-player/mpv/pull/11689.

This IINA issue tracks the need to update IINA once mpv has added this feature.

**Comment by sorae42** [comment]
It would be nice for this feature to be implemented since some subtitle I had sometime get desynced from the primary subtitle and the video itself.

**Comment by low-batt** [comment]
Good to know there is interest in this feature. I just checked and the `mpv` issue referenced above is still open. So IINA is still blocked waiting for `mpv` to implement this.

**Comment by low-batt** [comment]
The `master` branch of `mpv` now supports a [secondary-sub-delay](https://mpv.io/manual/master/#options-secondary-sub-delay) option. This is an important step in adding this functionality to IINA.

**Comment by VanyaTheSpark** [comment]
Oh my god please add this feature, I need it so much right now! Also it would be really realy cool if we had an option to add 3rd subtitle track!

**Comment by sorae42** [comment]
> Oh my god please add this feature, I need it so much right now! Also it would be really realy cool if we had an option to add 3rd subtitle track!

3rd subtitle track isn't possible until mpv support it. You may need to create an issue on mpv.

**Comment by low-batt** [comment]
It is `libmpv` that adds subtitles into the video frame. IINA can only control subtitle rendering by altering the `mpv` configuration using the subtitle related options `mpv` provides. Thus when it comes to displaying a 3<sup>rd</sup> subtitle, that should be requested of `mpv` as @sorae42 correctly indicated.

The recent change `mpv` made was the addition of the following options for controlling the rendering of the secondary subtitle:

- [secondary-sub-ass-override](https://mpv.io/manual/master/#options-secondary-sub-ass-override)
- [secondary-sub-delay](https://mpv.io/manual/master/#options-secondary-sub-delay)
- [secondary-sub-pos](https://mpv.io/manual/master/#options-secondary-sub-pos)

At this time these new features are only available by building the `mpv` `master` branch. We are hoping a new version of `mpv` will be released in time for IINA's upcoming feature release.

As I am a junior developer I can't say much about IINA's future release plans, but I am aware that there have been lots of requests for the ability to control the rendering of the secondary subtitle.

The next release of IINA is likely to be a bug fix release containing the fixes that did not get done in time to make it into 1.3.4. Once that release is out the focus will be on the long planned feature release.
