### ISSUE TITLE
Media key event response not scoped to active user

### ISSUE THREAD

**Issue by vbrinnel** [iina/iina#4526]
- macOS 12.6.7
- IINA 1.3.2 Build 135

**Expected behavior:**
Media key events fired under a specific OSX user should not affect the opened IINA player of another user.  

**Actual behavior:**
Pressing play / pause under `User1` affects the opened IINA player of `User2`.

**Steps to reproduce:**
Under `User1`, open IINA and play a video. Pause the video.
Switch to `User2`. Press the 'play/pause' media key. Wait a few seconds.
Switch back to `User1`. Video is playing (or has ended depending how much you've waited)

**How often does this happen?**
always

Thanks

**Comment by low-batt** [comment]
Reproduced!
With [Quicktime Player](https://support.apple.com/guide/quicktime-player/welcome/mac)!!!!
As well as IINA…

I ran this test on my MacBookPro18,2 under macOS 13.4. When I switched to user 2 the [Control Center](https://support.apple.com/guide/mac-help/quickly-change-settings-mchl50f94f8f/mac) `Now Playing` section showed the default application, that Apple refuses to let us configure, the `Music` app. And yet if I clicked on the play key the `Music` app does not startup as it normally does. If I click on the play button in `Now Playing` it does. Switching back to user 1 and `Quicktime`, which was paused, starts playing.

I found this report in the Apple support community: ["Now Playing" in Control Center show media from another Mac OS user](https://discussions.apple.com/thread/252301449). That was reported against macOS 10.14. Seems Apple half fixed that defect.

There is a known problem with IINA not properly releasing the media keys, issue #4331. That needs to be fixed. But it is not related to this issue.

My conclusion is that Apple needs to fix macOS.

**Comment by vbrinnel** [comment]
Hi, thanks for your response. You are absolutely right, the same happens with VLC as well. That's unfortunate. I'm going to close this issue now, my conclusion being the same as yours. Sorry for the noise.

**Comment by low-batt** [comment]
Reporting IINA problems where it turns out the root cause is outside of the IINA project is common. If IINA is malfunctioning it is a valid issue. Glad you reported this. Now other people encountering this behavior may find this issue in a search and not have to do their own investigation.

**Comment by svobs** [comment]
What I'd done is disable IINA's media key integration by unchecking `Settings` > `Key Bindings` > `Use system media control`. You will lose prev/next/pause media keys (although you can still mute the audio). But also, doing allows me to circumvent an even worse MacOS media keys problem, where [pausing one app causes all Bluetooth audio to mute](https://www.reddit.com/r/mac/comments/bgz0xm/bluetooth_headphones_pausing_music_mutes_all_audio/).
