### ISSUE TITLE
When online video is opened with the player, it will crash, and the video cannot be loaded normally

### ISSUE THREAD

**Issue by kaige-cai** [iina/iina#4537]
When online video is opened with the player, it will crash, and the video cannot be loaded normally
The most common is the video of the pikpak network disk, the online link cannot be opened

**Comment by low-batt** [comment]
When you say crash, do you mean IINA disappeared and was replaced by a macOS crash report?

If that is the case, then we really need the crash report to explain the failure. The report may still be available. Crash reports can be viewed in the macOS console utility as discussed [here](https://support.apple.com/guide/console/reports-cnsl664be99a/mac). If the report is still around then please drag and drop the `.ips` file to the comment section and attach the file to this issue.

**Comment by kaige-cai** [comment]
In fact, it’s not that it crashed, it’s that the player is unresponsive when playing online videos. Like below
https://pic.imgdb.cn/item/64efe4e1661c6c8e54dc095c.png

**Comment by LangLangBart** [comment]
- can you post the link to the online video?

---

- I encountered a similar issue couple of weeks ago and could solve it by adjusting the `Raw options` for `youtube-dl` under the `Network` options in the settings.

```sh
# copied from 'man yt-dlp'
format="(bv*[height<=?1080][vcodec~='^((he|a)vc|h26[45])']+ba)/(bv*+ba/b)"

man yt-dlp
# Download the best video with either h264 or h265 codec,
# or the best video if there is no such video
$ yt-dlp -f "(bv*[vcodec~='^((he|a)vc|h26[45])']+ba) / (bv*+ba/b)"
```

**Comment by kaige-cai** [comment]
> * can you post the link to the online video?
> 
> * I encountered a similar issue couple of weeks ago and could solve it by adjusting the `Raw options` for `youtube-dl` under the `Network` options in the settings.
> 
> ```shell
> # copied from 'man yt-dlp'
> format="(bv*[height<=?1080][vcodec~='^((he|a)vc|h26[45])']+ba)/(bv*+ba/b)"
> 
> man yt-dlp
> # Download the best video with either h264 or h265 codec,
> # or the best video if there is no such video
> $ yt-dlp -f "(bv*[vcodec~='^((he|a)vc|h26[45])']+ba) / (bv*+ba/b)"
> ```

link below
https://dl-a10b-0470.mypikpak.com/download/?fid=JeEfufegU7DtYcMVFrlSGBZQ5ISlIPaczMj_3oGIbJv25X92rk0pfV6Ty8cQ8Q6_YA8-8Ci24lLzonbrKVi8FGDoZzT-vUu_tJ2oJhKlEDU=&from=5&verno=3&prod=1104&expire=1693627539&g=E956B0090BEDFAD3ACB7B4B6308AC012502F1E97&ui=Yt09w_75YBqU0JzE&t=0&ms=10400000&th=10400000&f=13750275313&alt=0&fileid=VNd8KknYMiZjnBU575_2-F34o1&userid=Yt09w_75YBqU0JzE&pr=XQPkPvr9WWiIuMvELmrVerqJVMEQmxUkwzj1ZoUMehNu_xItnnxOp3hIAnHdF9cGxSIM0eCcyUy0Awp0rTa4I3UnmXSkuXWWWX38s_PC1CJ81XtYHeb6y5oz06BPvNwLs2crKy2ZTGT_ICLZk0_YtxVFjFGGRMnAhBYN7Pd5rKzauVMf7n1PRtOcATsB5G9EAEqQ_wWDz7aF9kqgkRJ4nxm0VduTvta0qtGcOe7B1CwGyV92EeGV2lV7Gsa0nMl2RlzM4lb44cI-JlMsN0V80F9CcX57wb2DPj5oBAr0OyV-jtmvA8KMoDetC5BlYW2fMAz2NSsSbgIJrXge41NS2ySAYk-VWP6PHfdwvcFoupg=&sign=E603BA0E4E3A9BCFB96C8370243ECC00

**Comment by kaige-cai** [comment]
.
