### ISSUE TITLE
DnD file format filtering not working since 1.3.3

### ISSUE THREAD

**Issue by receyuki** [iina/iina#4556]
**System and IINA version:**

- macOS 13.4.1 
- IINA 1.3.3

**Expected behavior:**
If the user drags a folder containing files in multiple formats into iina, the iina playlist should load only the video files.
<img width="118" alt="image" src="https://github.com/iina/iina/assets/28808141/0264c10c-e589-4c57-a8cd-71d252a997f0">
<img width="98" alt="image" src="https://github.com/iina/iina/assets/28808141/57fdb707-25ad-4d1e-ad83-b125624e07fe">
iina v1.3.2 works fine 

**Actual behavior:**
<img width="100" alt="image" src="https://github.com/iina/iina/assets/28808141/8bc39202-730a-4cf3-8f76-0e764be4a648">
iina v1.3.3 will load all files

**Comment by low-batt** [comment]
I believe this is the problem discussed in issue #4548.

**Comment by receyuki** [comment]
duplicate

**Comment by low-batt** [comment]
Thanks for closing. I've marked this as a duplicate. It is considered a regression that must be fixed. Watch #4548 for progress.

**Comment by receyuki** [comment]
Got it, thx.
