### ISSUE TITLE
The video screen appears slightly jittery when fast-forwarding or rewinding.

### ISSUE THREAD

**Issue by hugepower** [iina/iina#4580]
**System and IINA version:**

- macOS 13.5 (22G74)
- IINA 1.3.3 Build 138

**Expected behavior:**

IINA should play the video smoothly without any jitter when fast-forwarding or switching video scenes.

**Actual behavior:**

IINA often has left and right jitter when fast-forwarding or switching video scenes in playback mode. There is no problem in pause mode.

**Steps to reproduce:**

- Open a video file with IINA.
- Fast-forward or switch video scenes using the keyboard shortcuts or the mouse.
- Observe the jitter on the screen.

**How often does this happen?**

Every time I fast-forward or switch video scenes.

**Additional information:**

I opened the log Log viewer to check and found that sometimes when I fast-forwarded once, there would be two or three **Playback restarted** in the log. I suspect there is a problem here.
~~(I’m sorry, English is not my primary language, so I might not be very precise.)~~

<img width="1137" alt="20230814064703" src="https://github.com/iina/iina/assets/46076022/91c14a7f-d26e-4bc5-bd79-5b4a349a7e3c">

**Comment by hugepower** [comment]
I was playing a video and quickly dragging the progress bar to find the scene I wanted to watch.Then, I found this issue.

**Comment by low-batt** [comment]
Video files consumers encounter use codecs that compress the file. The compression techniques prioritize normal forward playback over random seeking. How much this affects the performance of seeking depends upon exactly how the video was encoded and the hardware capabilities of the Mac the video is being played on.

Perform the following test:
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Video/Audio`
- For the `Hardware decoder` setting select `Disabled`
- Confirm the settings panel looks like the screenshot below
- **Restart IINA**

![issue-4580](https://github.com/iina/iina/assets/86170219/5cae36a9-7372-4f11-bed8-2ca0456a6902)

With hardware decoding disabled test performance of seeking again. Report the results of this test.

**Comment by hugepower** [comment]
I am MacBook Air M1 2020, I followed your steps, and set the Hardware decoder to Disabled, but the problem still exists.

I recorded a video. In the last few seconds of the video, the character’s limbs were shaking. For example, when the man bent down to pick up something, and when he was sitting in the car, his head was shaking. 

https://github.com/iina/iina/assets/46076022/22104d22-0820-49e8-be9b-e304124856de

**Comment by low-batt** [comment]
The MacBook Air M1 should be plenty powerful.

Similar to many open source projects IINA is layered on top of other projects. For audio/video playback IINA is using a library from the [mpv](https://github.com/mpv-player/mpv) project. For this reason the issue template contains the following checkbox:
> \
> - [ ] MPV does not have this problem.

Does this problem reproduce when playing using the [mpv player](https://mpv.io/)?

In my own testing seeking was showing more intermediate results with hardware decoding disabled. The mpv player exhibited that same behavior.

To look for jitter I played a video that shows the earth rotating. The earth remains centered in the frame, so I could seek and focus on whether the earth was shifting around. I wasn't able to see any jittering in that test.

**Comment by hugepower** [comment]
> MacBook Air M1 应该足够强大。
> 
> 与许多开源项目类似，IINA 位于其他项目之上。[对于音频/视频播放，IINA 使用mpv](https://github.com/mpv-player/mpv)项目中的库。因此，问题模板包含以下复选框：
> 
> > 
> > 
> > * [ ] MPV则不存在这个问题。
> 
> [使用mpv 播放器](https://mpv.io/)播放时是否会重现此问题？
> 
> 在我自己的测试中，寻求的是在禁用硬件解码的情况下显示更多中间结果。mpv 播放器也表现出相同的行为。
> 
> 为了寻找抖动，我播放了一段显示地球旋转的视频。地球仍然位于框架的中心，因此我可以寻找并关注地球是否在移动。我在那次测试中没有看到任何抖动。

I don’t have this problem when testing with other players like MPV. I think there is some reason that causes the **player.playbackRestarted()** method to be called repeatedly. This leads to multiple Playback restarted records in the log when there is a shake.

https://github.com/iina/iina/blob/1af17dbc795f602c268afccc8599906ca25a6a9f/iina/MPVController.swift#L944

**Comment by hugepower** [comment]
I tested three versions of IINA, and only the 1.3.1 version had no problem.

1.3.3 released on 2023-07-20
1.3.2 released on 2023-07-07
1.3.1 released on 2022-11-06

https://www.iina.io/download/

**Comment by hugepower** [comment]
I asked Bing Chat, and it told me the following information. 

> Your question is about the code difference between IINA 1.3.1 and 1.3.2 versions, on line 944 of the MPVController.swift file. According to the information I searched from the Internet, here are the main changes:
>- In version 1.3.1, this line is `mpv_set_property_string(mpv, MPVOption.Video.deinterlace, "auto")`, which means setting the video deinterlacing mode to automatic¹.
>- In version 1.3.2, this line was deleted, because mpv 0.35.0 version has removed the deinterlacing option².

I followed these tips, and the problem was solved after I turned on **deinterlace** in the IINA v1.3.3 player.

<img width="532" alt="2023-08-14 14 16 41" src="https://github.com/iina/iina/assets/46076022/9f8364ef-b2ef-407e-a3ff-e423966fc738">


Thank you for your help, I will now close this issue.

**Comment by low-batt** [comment]
Thank you so much for your investigation. I really appreciate you identifying what was causing the behavior. That the video being played is interlaced explains why I was having trouble reproducing the problem.

Glad Bing Chat pointed you in the right direction, but I'm thinking that AI has been drinking or using drugs.

On this from Bing Chat:
> … because mpv 0.35.0 version has removed the deinterlacing option

The mpv manual entry for the [deinterlace](https://mpv.io/manual/stable/#options-deinterlace) option contains this note:
> …
> (Since mpv 0.27.0, even the hardware deinterlace filters will conflict. Also since that version, --deinterlace=auto was removed, which used to mean that the default interlacing option of possibly inserted video filters was used.)

Bing Chat is right about mpv having removed `auto` as a supported setting, but that happened a long time ago.

I'm sure that explains why I'm not finding the given source line `mpv_set_property_string(mpv, MPVOption.Video.deinterlace, "auto")` in the IINA 1.3.1 sources:

```text
low-batt@gag iina (release/1.3.1 $%=)$ grep -inr --include \*.swift 'MPVOption.Video.deinterlace' *
iina/PlayerCore.swift:833:    mpv.setFlag(MPVOption.Video.deinterlace, enable)
iina/MPVController.swift:115:    MPVOption.Video.deinterlace: MPV_FORMAT_FLAG,
iina/MPVController.swift:1068:    case MPVOption.Video.deinterlace:
low-batt@gag iina (release/1.3.1 $%=)$ 
```

I guess the good news is that Bing Chat did provide some useful information.
