### ISSUE TITLE
Playing mov can't fast forward normally.

### ISSUE THREAD

**Issue by songyizhang** [iina/iina#4622]
**System and IINA version:**

- macOS 11.7.1
- IINA 1.3.3

**Expected behavior:** Playing mov can fast forward normally.

**Actual behavior:** Playing mov can't fast forward normally.

**Steps to reproduce:** When play mov, pressing the right arrow, the video will play from the beginning.

**How often does this happen?**Every time.

**Comment by low-batt** [comment]
How does this differ from issue #4620?

**Comment by songyizhang** [comment]
I don't describe the essential information in this issue, so I open one new issue, and I can't delete it. You can delete one of them if you want.

**Comment by low-batt** [comment]
Thanks for adding the additional information. I've copied that information to #4020. I will close this issue as a duplicate.
