### ISSUE TITLE
Giant unwanted Easter egg in Subtitles sidebar

### ISSUE THREAD

**Issue by svobs** [iina/iina#4638]
**System and IINA version:**

- macOS 14.0 Sonoma
- IINA dev 655dbf81794491ddd87b699cec867edf3e3624cb

**Steps to reproduce:**

Start playing a video, then open Subtitles sidebar.

**Expected behavior:**

Regular old settings.

**Actual behavior:**

Giant egg blocking most settings.
<img width="784" alt="Screenshot 2023-10-04 at 19 08 14" src="https://github.com/iina/iina/assets/2213815/1534f70e-a7c0-4fe6-bdf3-eed0bd361fe3">

- [x] MPV does not have this problem.

**How often does this happen?**
Always

Not present in IINA 1.3.3, so looks like a regression on the `develop` branch.

**Comment by low-batt** [comment]
Yikes! I downloaded the latest [nightly](https://nightly.iina.io/) build from that commit. Played a video with that version of IINA, opened the quick settings panel and clicked on the `SUBTITLES` tab. No easter egg for me.

I'm still using macOS 13.5.2. I was holding off on upgrading to macOS 14 after reading about some issues.

I will play around some more and see if I can trigger this. It is almost like the circle representing the font color has turned into this. If you click on it does anything happen?

**Comment by low-batt** [comment]
Does the nightly build seem messed up to you? If I bring up the about window it shows:
> Jul 8, 2023 at 12:26:51 PM
> NIGHTLY bc4c084

Wrong time. Wrong commit.

Are you seeing this?

**Comment by svobs** [comment]
Tried the nightly build. It doesn't exhibit the defect.

Although you're right. It shows a commit from July, corresponding to Build 135. But then About also shows Build 138. So that sounds like a problem which I trust you will report to the right person(s)? But looks like the nightly build is not going to provide the final answer for this bug...

Back in my local dev environment, I tried the following. All failed to clear The Egg.

- Checked out & built various commits on `develop` all the way back to 1.3.2 or so before I stopped trying.
- Rebooted MacOS
- Cleared the build folder, XCode cache
- Cloned into a fresh directory, downloaded dependencies via script.

So it's looking like this was introduced when I upgraded to Sonoma. It would be good to know if anyone else is seeing this.

> It is almost like the circle representing the font color has turned into this. If you click on it does anything happen?

Looks like you are right. It's not really clickable, and in fact it doesn't block clicks on the controls behind it. But by clicking around i was able click on its button and change the font color to orange:

<img width="912" alt="Screenshot 2023-10-04 at 23 33 54" src="https://github.com/iina/iina/assets/2213815/1ee23db8-e87b-4912-98ac-ca939751ba96">

**Comment by low-batt** [comment]
I have reported the nightly build problem.

I checked the nightly build and it does seem to contain the changes associated with the commit that triggered it. Looking like that problem may be isolated to the special processing to embed that information in the Info.plist. I tested building the nightly configuration myself and the about window was correct, so it seems to be something to do with the official nightly build process.

The trouble with asking users running macOS Sonoma if they have seen this is that it is not reproducing with the released version of IINA or the IINA nightly build. Seems like building under macOS Sonoma causes the problem? Rather odd that this seems to only fail if built under macOS Sonoma.

I am using Xcode 15.0. I'm assuming you are using that version as well and not the Xcode 15.1 Beta?

The offending control is a [RoundedColorWell](https://github.com/iina/iina/blob/develop/iina/RoundedColorWell.swift), an IINA customized [NSColorWell](https://developer.apple.com/documentation/appkit/nscolorwell).

Might want to set a breakpoint on the `draw` method and see what AppKit is supplying for `dirtyRect`.

I am going to have to upgrade to macOS Sonoma soon. Currently been working on very time consuming changes and problems. Been hoping to finish those before potentially destabilizing my development system.

**Comment by low-batt** [comment]
I'm troubled that we can't explain why this problem only appears when you build under macOS Sonoma. Maybe there is a change in the macOS 14.0 SDK that comes with Xcode 15 which only causes a problem under Sonoma?

**Comment by svobs** [comment]
> I'm troubled that we can't explain why this problem only appears when you build under macOS Sonoma. Maybe there is a change in the macOS 14.0 SDK that comes with Xcode 15 which only causes a problem under Sonoma?

I'm not super familiar with AppKit's `draw()` mechanism, but by its name, `dirtyRect` suggests that it is an area that has been marked "dirty" and needs to be redrawn , sort of like a cache determines which items are stale. It's not safe to assume that the whole view will be marked "dirty" at the same time rather than some portion of it, because doing so makes assumptions about the internal mechanisms of the cache/draw functionality which can easily change for every release without notice. This is why using `bounds` is safer.

That said, being delivered a `dirtyRect` which is the size of the `TabViewItem`'s content view definitely looks like a bug introduced by Sonoma. We shouldn't expect any reason for it to go outside the color well's bounds. In general, AppKit controls are not supposed not go outside their bounding box [EDIT: not true. See below], although it's definitely not a law which is enforced. "Round rect" buttons are one annoying example as they typically draw 1px outside their bounds which I've had to account for in past PRs. 

A bit off topic, but I think I see another small regression introduced by Sonoma. If the `videoView` is resized while the video is playing, it "wobbles" inside the window which looks ugly. It looks like this only shows up in `develop` when using the "pinch to zoom" feature to resize the window while playing, although is a lot more evident in my fork because i had previously been able to do lots of animations smoothly while playing the video, including toggling full screen. I'm presently investigating possible workarounds.

**Comment by low-batt** [comment]
The one other place I found that uses `dirtyRect` is in `PreferenceWindowController.draw`. Check and see if anything is amiss with the settings window,

What bothers me is that the problem isn't seen with the released version of IINA. There is a second factor besides just running under macOS Sonoma.

It sure seems like `AppKit` is broken and passing the rect for a superview instead of for the control's view.

**Comment by svobs** [comment]
> The one other place I found that uses dirtyRect is in PreferenceWindowController.draw. Check and see if anything is amiss with the settings window

Good thinking. Took a look at `PrefSearchResultMaskView.draw()`, and it seems to be working okay. I then tried replacing `dirtyRect` with `bounds`, and saw no difference. But I would recommend replacing it for future safety.

> What bothers me is that the problem isn't seen with the released version of IINA. There is a second factor besides just running under macOS Sonoma.

Not necessarily. Remember that the released version of in IINA was compiled with an older version of XCode. It may be calling older APIs behind the scenes. There are also all kinds of version markers in the project (and presumably the compiled code) which the AppKit render engine can see and then respond with the expected logic for that version. Microsoft is known to do this in Windows Compatibility Mode by using "shims" which even trick the older programs into thinking they are talking to older versions of Windows.

Anyway, hopefully the nightly builds can be fixed and remove all doubt.

Wouldn't recommend upgrading to Sonoma. No new useful features, but some new bugs. Seeing lots of [this error](https://developer.apple.com/forums/thread/738589) in the logs now. Not hard to speculate they are working on refactoring their display code as they transition to Metal... Hopefully they won't break OpenGL too quickly!

**Comment by saagarjha** [comment]
You're probably hitting https://developer.apple.com/documentation/appkit/nsview/4236466-clipstobounds

**Comment by low-batt** [comment]
I've been overloaded with other stuff and have not been paying attention to macOS Sonoma. I'm going to have to find time to investigate and upgrade. The [AppKit Release Notes for macOS 14](https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14#NSView) contains an extensive discussion of this change. Part of it says:
> Filling the dirty rect of a view inside of -`drawRect`. A fairly common pattern is to simply rect fill the dirty rect passed into an override of `NSView.draw()`. The dirty rect can now extend outside of your view’s bounds. This pattern can be adjusted by filling the bounds instead of the dirty rect, or by setting `clipsToBounds = true`.

So, yes indeed this matches up with the behavior seen. The release notes also say:
> For applications linked against the macOS 14 SDK, the default value of this property is `false`. Apps linked against older SDKs default to `true`.

I'm using Xcode 15 and building and linking against the macOS 14 SDK under macOS Ventura:
```text
low-batt@gag ~$ xcodebuild -showsdks
…
macOS SDKs:
	macOS 14.0                    	-sdk macosx14.0
```

And have not encountered this behavior. Building with Xcode 15 allows use of a newer version of AppKit:

IINA 1.3.3:
```
/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2299.50.120)
```

Xcode 15 build:
```text
/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2483.0.0)
```

It seems it is not merely building against the new macOS 14 SDK, but also running under macOS Sonoma which has a newer version of AppKit.

**Comment by svobs** [comment]
> You're probably hitting https://developer.apple.com/documentation/appkit/nsview/4236466-clipstobounds

Thank you @saagarjha! I need to keep better track AppKit changes.
