### ISSUE TITLE
Quitting IINA without closing windows causes Finder to malfunction

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4656]
**System and IINA version:**

- macOS 14.0
- IINA 1.3.3

**Expected behavior:**
Quitting IINA without closing windows does not affect Finder behavior.

**Actual behavior:**
@Whizzbizz reports:
If you quit Iina without closing its windows beforehand, the Finder (M1 iMac, Sonoma) will not do anything with files opened by Iina before you open them again and close them "properly", and only then quit Iina.

**Steps to reproduce:**
- Open a file with IINA
- Quit IINA without closing the window
- Attempt to access the file in Finder

- [ ] MPV does not have this problem.

Unknown.

**How often does this happen?**
Unknown.

**Comment by low-batt** [comment]
This report is very concerning.

When an application terminates it is the responsibility of macOS to close any files that application opened and did not close. If that is not happening then that is a defect in macOS 14.0.

There was a severe error introduced in macOS Ventura 13.3 where Finder failed to open files if the filename contained certain characters (issue #4308). That was fixed in macOS 13.4. I only bring this up as an example of recent macOS Finder problems.

Can you say some more about the erroneous Finder behavior. What is it that Finder refuses to do?

**Comment by Whizzbizz** [comment]
I had it in Ventura, too: you try to send a file to the trash, a dialog (notification) will appear, saying: "Preparing…" or something, and this dialog will last forever if you don't interrupt in one way or another. Any change of path (moving the file) on the same volume will result in the same behaviour. Copying is no problem.

I had it with files edited in ff-works, too. So Iina was only the video player, but independently from ff-works, the same Finder behaviour came up with Iina.

Only after I quit one or all of these apps, sometimes even after a complete user logout, normal behaviour came back.

**Comment by low-batt** [comment]
To read a file an application asks macOS to "open" the file. The file will be "closed" either when that application asks macOS to "close" the file, or when the user quits that application, macOS will automatically "close" any files still open by the application.

When you instruct macOS to eject a disk, such as a USB stick, it looks to see if any files are currently "open".  If any are, macOS will refuse to eject the disk and put up an alert:
![issue-4656](https://github.com/iina/iina/assets/86170219/ed322a60-8389-428b-a5b7-21c56174274e)

As for when an application asks macOS to "close" a file, that is a grey area. In general it is highly desirable that with respects to this an application matches the expectations of a user. With applications where a file is associated with a window, users will expect that when that window is closed the application will close the file. However applications where it is common for a user to open the same file again may choose to keep the file open to be able to quickly "reopen" the file.

With the IINA setting `Quit after all windows are closed` disabled and the setting `Keep window open after playback finishes` enabled I played a video on a USB stick until playback stopped at the end of the video. The window remained open. I tried ejecting the USB stick and macOS put up the alert shown above. I then closed the IINA window. IINA remained running in the dock. I tried ejecting the stick again and macOS successfully ejected the disk.

As IINA may also open the file in order to generate thumbnails, it might keep the file open while performing that operation. I did not test that.

Similar behavior will occur when you try and move a file to the trash. If an application has a file open macOS will not allow you to throw it away.

**However**, the initial report indicates Finder had trouble _after_ IINA had quit. And that restarting IINA and closing the windows cleared that problem. That definitely should not be happening. Double check that is what is occurring.

**Comment by Whizzbizz** [comment]
My concerns about Iina (or ffmpeg) not closing files seem to be solved: today, I found that Apple's QuickLook service seems to be the culprit and that files can be moved properly after quitting the 'QuickLookUIservice (Finder)' in 'Activity Monitor'.

**Comment by low-batt** [comment]
Thank you so much for reporting this problem was traced to the `QuickLookUIService` for `Finder`. I was wondering what could be causing this problem.

A typical programming error is to fail to close an open file. Usually it is caused by someone adding new code that fails to account for the need to close the file. Or it is due to an alternative code path that was not covered by testing.

I wonder if this problem is new to macOS Sonoma.

Now that the root cause has been identified I am going to go ahead and close this issue. If you do find that there is a problem with how IINA handles this, please feel free to reopen this issue or open a new one.
