### ISSUE TITLE
Use System Media Control Not Working

### ISSUE THREAD

**Issue by TomG1230** [iina/iina#4660]
Hi,

I've recently downloaded IINA and I've been trying to prevent my F8 key (which is the Play/Pause) button from starting and pausing media in the player. I tried to untick Use System Media Control, as well as deleting the keys from Configuration menu, but no matter what when I press it, it always starts / pauses the media. Is there any way to prevent this happening?

**Comment by low-batt** [comment]
Did not reproduce for me.

After unchecking the `Use system media control` setting did you restart IINA? For many settings, IINA will dynamically update its behavior when the setting is changed. But some settings require IINA to be restarted for the change to be noticed. This is one of those.

The test I ran was as follows:
- I started IINA and unchecked  `Use system media control`
- I then restarted IINA playing a video
- I pressed F8
- macOS started the Music app
- IINA did not pause playback

If you open Control Center you can see which application the media keys are currently assigned to.

This test was run with IINA 1.3.3 under macOS 13.5.2.

Are you running macOS 14.0?

**Comment by TomG1230** [comment]
Hi,

I did initially restart IINA a number of times with no luck, but after logging back into my Mac today the issue seems to have resolved itself! Maybe I just needed a mac restart for it to stick. Thanks for providing a full list of instructions though!

**Comment by low-batt** [comment]
@TomG1230 Thank you for following up and reporting it started working after logging out and logging back in.

Was this with macOS 14.0?

I've not had time to upgrade to macOS Sonoma. Under Ventura macOS support for media keys is definitely defective. I reproduced a problem another user reported where a media key press event was delivered to the _wrong user_. I plan on checking to see if Apple has fixed that for Sonoma once I find the time to upgrade. I was unaware of the problem reported in this issue. Disturbing that macOS has these reliability problems.

**Comment by TomG1230** [comment]
@low-batt Hi! This was with Ventura 13.5. At least I'm not going crazy! Hope it manages to get fixed soon.
