### ISSUE TITLE
default video resolution

### ISSUE THREAD

**Issue by zamkara** [iina/iina#4677]
where can I find the option to change the resolution of my streaming video to 720p or other to default/fixed without changing individually each time I play the video?

![image](https://github.com/iina/iina/assets/70899024/42920df5-856d-404c-9810-1a87441906c3)

**Comment by low-batt** [comment]
For audio/video support IINA uses a library from the [mpv](https://github.com/mpv-player/mpv) project. In turn `mpv` uses [yt-dlp](https://github.com/yt-dlp/yt-dlp) for streaming. The answer to this question has to do with what controls `yt-dlp` provides. What their defaults are. And how you can configure `yt-dlp` in IINA.

From the [FORMAT SELECTION](https://github.com/yt-dlp/yt-dlp#format-selection) section of the `yt-dlp` README:
> By default, yt-dlp tries to download the best available quality if you **don't** pass any options.

What resolution that is depends upon the resolutions offered by the streaming site for the video in question.

To limit the resolution of streaming follow these instructions:
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Network`
- In the `youtube-dl` section look for the `Raw options` setting
- Set `Raw Options` to `format=bestvideo[height<=720]+bestaudio`
- Confirm the settings panel looks like the screenshot below
- **Restart IINA** to activate the new settings

![issue-4677](https://github.com/iina/iina/assets/86170219/b1420bcb-314f-4d89-8236-27774cf9fcd8)
