### ISSUE TITLE
Open Recent menu cleared with each new build

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4688]
**System and IINA version:**

- macOS 14.1.1
- IINA `develop`

**Expected behavior:**
The list of recent files in the `Open Recent` menu item under the `File` menu is only cleared when the user clicks on `Clear Menu`.

**Actual behavior:**
Running an IINA executable built with Xcode 15.0.1 under macOS 14.1.1 clears the list of recent files. After that the `Open Recent` menu item works as expected. However if a source is modified and IINA is rebuilt, then the list will be cleared again when the new executable is run.

**Steps to reproduce:**
Under macOS Sonoma 14.1.1 and using Xcode 15.0.1 follow these instructions:
- Start the released version of IINA
- Play a video
- Open the `File` menu and move the cursor over the `Open Recent` menu item
- Notice the video is listed in the `Open Recent` menu item
- Quit the released version of IINA
- Run IINA from Xcode
- Open the `File` menu and move the cursor over the `Open Recent` menu item
- Notice the list is _empty_
- Play a video
- Open the `File` menu and move the cursor over the `Open Recent` menu item
- Notice the video is listed in the `Open Recent` menu item
- Quit the develop version of IINA
- Modify a source
- Run IINA from Xcode
- Open the `File` menu and move the cursor over the `Open Recent` menu item
- Notice the list is _empty again_

- [x] MPV does not have this problem.

It does not support `Open Recent`.

**How often does this happen?**
Every time a new executable is run.

**Comment by low-batt** [comment]
Searching for others reporting this problem I found the Apple developer forum post: [Document controller's recent files list cleared between versions](https://developer.apple.com/forums/thread/703694). That post reports this occurring after building on Monterey. Unfortunately the post provides no clue to the problem.

I confirmed that [recentDocumentURLs](https://developer.apple.com/documentation/appkit/nsdocumentcontroller/1514976-recentdocumenturls) is indeed returning an empty list.

**Comment by low-batt** [comment]
I ran a test where I built the develop branch of IINA using Xcode 15.0.1 under macOS Ventura 13.6.1 and brought that executable to my Mac running macOS Sonoma 14.1.1. Under Ventura that executable does not clear the list of previously opened files shown in the `Open Recent` menu item. Running that same executable under Sonoma clears the list and  `Open Recent` only shows a dimmed `Clear Menu`.

Xcode 15 links the macOS 14 SDK which uses a newer version of AppKit as shown by `otool`.

IINA 1.3.3:
```bash
low-batt@urp MacOS$ otool -L IINA | grep AppKit.framework
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2299.50.120)
```

IINA built with Xcode 15:
```bash
low-batt@urp MacOS$ otool -L IINA | grep AppKit.framework
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2483.0.0)
```

The working theory is that this issue has something to do with the new version of AppKit.

Checking the [macOS Sonoma 14.2 Beta 4 Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-14_2-release-notes) and the [Xcode 15.1 Beta 3 Release Notes](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-15_1-release-notes) I did not find any mention of such a problem.

**NOTE** the following from the [Xcode 15.1 Beta 3 Release Notes](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-15_1-release-notes):
> - Fixed: Swift apps built with Xcode 15.0 crash on launch on macOS 10.13. (114820860)

Therefore at this time the lastest released version of Xcode (15.0.1) **must not** be used to build IINA for a release. 

Some links to information:
- [macOS Sonoma 14.2 Beta 4 Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-14_2-release-notes)
- [Xcode 15.1 Beta 3 Release Notes](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-15_1-release-notes)
- [Xcode 15.0.1 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_0_1-release-notes)
- [Xcode 15 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes)
- [Xcode updates](https://developer.apple.com/documentation/updates/xcode)
- [AppKit Release Notes for macOS 14](https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14#NSView)
- [AppKit updates](https://developer.apple.com/documentation/updates/appkit)
- [WWDC 2023 What’s new in AppKit](https://developer.apple.com/videos/play/wwdc2023/10054/)
- [WWDC NOTES What's new in AppKit](https://www.wwdcnotes.com/notes/wwdc23/10054/)

**Comment by low-batt** [comment]
I have upgraded to macOS 14.1.2. The menu is still being cleared and macOS has already crashed once on me.

**Comment by low-batt** [comment]
I have upgraded to macOS 14.2 and Xcode 15.1. The menu is still being cleared.

In the Apple Developer Forums I found the post [Document controller's recent files list cleared between versions](https://developer.apple.com/forums/thread/703694) which describes this exact behavior, except this developer encountered it when upgrading to Monterey:
> I have a document-based app. Whenever I'm publishing a new version on App Store, and even when setting a new build number, my app completely loses the recent files list.
>
> I'm accessing the list using `recentDocumentURLs`, but the recent documents are also lost from the File -> Recent files menu.
>
> This started happening when I started building my app on Monterey. When built in Big Sur, this doesn't happen. I'm guessing this is not a feature, because other apps don't seem to behave this way when downloading a new update.
>
> I'm guessing something has changed in sandboxing or somewhere else, and I'm missing it?

Unfortunately there are no replies to that post.

The man page for `sharedfilelistd` lists the files involved in storing the `Open Recent` entries.
<details>
<summary><b>man sharedfilelistd:</b></summary>

```text
sharedfilelistd(8)          System Manager's Manual         sharedfilelistd(8)

NAME
     sharedfilelistd – User agent which manages lists of file system items

DESCRIPTION
     sharedfilelistd is a per-user agent that manages lists of recent and
     favorite documents, applications, and volumes.  It stores the lists for
     global Apple Menu > Recent Items, the per-application File > Open Recent,
     and some of the content in the Finder sidebar.

FILES
     /System/Library/CoreServices/sharedfilelistd
     /System/Library/LaunchAgents/com.apple.coreservices.sharedfilelistd.plist
     ~/Library/Application Support/com.apple.sharedfilelist/*

SEE ALSO
     sfltool
```
</details>

The property list file containing the `Open Recent` entries is `com.colliderli.iina.sfl3`:
```bash
low-batt@urp com.apple.LSSharedFileList.ApplicationRecentDocuments$ pwd
/Users/low-batt/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments
low-batt@urp com.apple.LSSharedFileList.ApplicationRecentDocuments$ ls -la com.colliderli.iina.sfl3
-rw-r--r--  1 low-batt  staff  2561 Dec 16 17:54 com.colliderli.iina.sfl3
low-batt@urp com.apple.LSSharedFileList.ApplicationRecentDocuments$ 
```

I captured 5 copies of the property list:
- Two files in list populated by IINA 1.3.3 
- Empty list right after running a development build of IINA
- Populated list after running that same build again
- Empty list after running a new development build
- Two files in list populated by IINA 1.3.0

I converted the binary property list to XML using this comment:
```text
plutil -convert xml1 com.colliderli.iina.sfl3
```

I have not been able to find any information about how to interpret the contents of this property file. I am suspicious of the following portion of the file. This is from IINA 1.3.3:
```xml
<string>com.apple.LSSharedFileList.DesignatedRequirement</string>
<string>com.apple.LSSharedFileList.MaxAmount</string>
<string>com.apple.LSSharedFileList.AppIdentifier</string>
<data>
+t4MAAAAAMAAAAABAAAABgAAAAYAAAAPAAAAAgAAABNjb20uY29sbGlkZXJs
aS5paW5hAAAAAAcAAAAOAAAAAAAAAAoqhkiG92NkBgEJAAAAAAAAAAAABgAA
AAYAAAAOAAAAAQAAAAoqhkiG92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZI
hvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1YmplY3QuT1UAAAAAAAEAAAAK
NjdDUTc3VjI3UgAA
</data>
<integer>15</integer>
<string>67CQ77V27R.com.colliderli.iina</string>
```

This is with the development build:
```xml
<string>com.apple.LSSharedFileList.DesignatedRequirement</string>
<string>com.apple.LSSharedFileList.MaxAmount</string>
<string>com.apple.LSSharedFileList.AppIdentifier</string>
<data>
+t4MAAAAACgAAAABAAAACAAAABSAgfWhyl5i8Cuk1GEDluhzkQ8A9A==
</data>
<integer>15</integer>
<string>com.colliderli.iina</string>
```

Those values do not change while I continue to use that same development build. When a create a new build the values change:
```xml
<string>com.apple.LSSharedFileList.DesignatedRequirement</string>
<string>com.apple.LSSharedFileList.MaxAmount</string>
<string>com.apple.LSSharedFileList.AppIdentifier</string>
<data>
+t4MAAAAACgAAAABAAAACAAAABSF+q1xyKWGL8WA93f0Zy71HZ/kkQ==
</data>
<integer>15</integer>
<string>com.colliderli.iina</string>
```

When then run IINA 1.3.0 these values change back to the values IINA 1.3.3 produces.

I re-read the [AppKit Release Notes for macOS 14](https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14) and did not find anything that would explain this behavior.

**Comment by saagarjha** [comment]
Ok so if we decode that data we get this:

```console
$ pbpaste | base64 -d | xxd
00000000: fade 0c00 0000 0028 0000 0001 0000 0008  .......(........
00000010: 0000 0014 85fa ad71 c8a5 862f c580 f777  .......q.../...w
00000020: f467 2ef5 1d9f e491                      .g......
```

That's `CSMAGIC_REQUIREMENT` which is presumably coming from the executable's code signature.

**Comment by low-batt** [comment]
Based on advice from @saagarjha I ran some experiments. I created an app based on Xcode's Document App template. That template creates an app with a `Open Recent` menu item. That app displayed the same behavior of erasing the list of recent documents when the app was changed and a new build was created.

The app is signed with an ad hoc certificate as the output of `codesign` shows.

<details>
<summary><b>codesign output:</b></summary>

```text
low-batt@urp Debug$ codesign -dv --verbose=4 OpenRecent.app
Executable=/Users/low-batt/Library/Developer/Xcode/DerivedData/OpenRecent-gafvtaaoryvjfxblrqablilsvowf/Build/Products/Debug/OpenRecent.app/Contents/MacOS/OpenRecent
Identifier=com.bcs.OpenRecent
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=1291 flags=0x2(adhoc) hashes=30+7 location=embedded
VersionPlatform=1
VersionMin=853248
VersionSDK=918016
Hash type=sha256 size=32
CandidateCDHash sha256=681b7e47bbf14381c7542ad5c975726f0cb15e3c
CandidateCDHashFull sha256=681b7e47bbf14381c7542ad5c975726f0cb15e3c939ed4cb59d10f9a3e3322ff
Hash choices=sha256
CMSDigest=681b7e47bbf14381c7542ad5c975726f0cb15e3c939ed4cb59d10f9a3e3322ff
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=32768
Executable Segment flags=0x1
Page size=4096
CDHash=681b7e47bbf14381c7542ad5c975726f0cb15e3c
Signature=adhoc
Info.plist entries=26
TeamIdentifier=not set
Sealed Resources version=2 rules=13 files=0
Internal requirements count=0 size=12
low-batt@urp Debug$ 
```
</details>

I then tested again this time using `codesign` to sign the app with my own certificate. With the app signed with that certificate the list of recent documents was not cleared.

I also looked into the `com.colliderli.iina.sfl3` property list on my Mac running macOS Ventura. The keys `AppIdentifier` and `DesignatedRequirement` were not present in the property list.

Seems like `sharedfilelistd` was changed in macOS Sonoma to tie the list of recent documents to the app based on its certificate. Maybe a privacy/security enhancement?

For IINA this means uses using the release version of IINA will not have their list of recent documents cleared. However I have confirmed that executing an IINA nightly build will clear the list of recent documents. And of course developers will have their list cleared as well.

**Comment by low-batt** [comment]
This problem does not occur with the officially released version of IINA that is signed with IINA's certificate. PR #4730 is a workaround that improves the situation for developers running their own build which is signed with an ad hoc certificate causing the `Open Recent` list to be cleared.

**Comment by low-batt** [comment]
Backing up the above analysis the Apple Technote [TN3127: Inside Code Signing: Requirements](https://developer.apple.com/documentation/technotes/tn3127-inside-code-signing-requirements) in the [Designated requirement](https://developer.apple.com/documentation/technotes/tn3127-inside-code-signing-requirements#Designated-requirement) section says:
> Unsigned code has no DR. Ad hoc signed code, called Sign to Run Locally by Xcode, has a DR but it’s tied to that specific version of the code. In both cases macOS can’t reliably track the identity of the code.

This agrees with the behavior seen. When developing if the code changes then its DR changes and `sharedfilelistd` clears the list of recent documents.

**Comment by LeoNatan** [comment]
The "workaround" for this issue causes IINA to hang on launch.

https://github.com/iina/iina/issues/5299

No other player or app has this issue. Whatever issues you have with signing, restoring that recents list synchronously on main thread is not a good idea.

**Comment by low-batt** [comment]
You are correct. The workaround is faulty and responsible for #5299. We were unable to find a fix for the workaround and in the development version of IINA the workaround has been disabled. We are stuck with this new macOS behavior of clearing the recent documents list.

This new macOS behavior of clearing the list is not specific to IINA. The problem was reproduced using the Xcode template for a documents based app. IINA probably differs in that this is the list that is shown in IINA's welcome window, so it is immediately obvious when the list has been lost. Other apps may only only provide the list in a `Open Recent` menu item where you won't know the list has been cleared unless you open that menu. See my comments in #5299.
