### ISSUE TITLE
Youtube video keep buffering 

### ISSUE THREAD

**Issue by KOTHX** [iina/iina#4701]
**System and IINA version:**

- macOS Sonoma 14.1.1
- IINA 1.3.3 Build 138 

**Expected behavior:**

Playing youtube video 

**Actual behavior:**

When i try to play youtube video its keep in buffering state 

this is my current network config 

![CleanShot 2023-11-27 at 18 58 28@2x](https://github.com/iina/iina/assets/13770732/d64b1e96-5a39-4976-82aa-f095a9272c24)

**Comment by low-batt** [comment]
I tried streaming the YouTube video [The World in HDR in 4K (ULTRA HD)](https://www.youtube.com/watch?v=tO01J-M3g0U) and it played without buffering for me.

Have you used `brew upgrade` to ensure you are using the latest version of `yt-dlp`? The following [Terminal](https://support.apple.com/guide/terminal/welcome/mac) session shows the `yt-dlp` version I used for the above test:
```text
low-batt@gag ~$ which yt-dlp
/opt/homebrew/bin/yt-dlp
low-batt@gag ~$ yt-dlp --version
2023.11.16
low-batt@gag ~$ 
```

Are you using verison `2023.11.16`? Assuming the latest verison of `yt-dlp` exhibits buffering for you then you may be experiencing traffic throttling, either by your ISP, or by YouTube. This is more likely to happen if you are sharing a public IP address with other users.

If this is a case of throttling then you might be able to improve the situation by changing the `yt-dlp` configuration. From the [FORMAT SELECTION](https://github.com/yt-dlp/yt-dlp#format-selection) section of the `yt-dlp` README:
> By default, yt-dlp tries to download the best available quality if you **don't** pass any options.

What resolution that is depends upon the resolutions offered by the streaming site for the video in question.

If you are streaming videos for which YouTube provides high resolutions, such as the above referenced 4K video, then you can try reducing the resolution to see if that helps. To limit the resolution of streaming follow these instructions:
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Network`
- In the `youtube-dl` section look for the `Raw options` setting
- Set `Raw Options` to `format=bestvideo[height<=720]+bestaudio`
- Confirm the settings panel looks like the screenshot below
- **Restart IINA** to activate the new settings

![reduce-resolution](https://github.com/iina/iina/assets/86170219/397902c0-455c-4d58-8f5e-12c79547f05d)

**Comment by KOTHX** [comment]
Thanks it work however changing the resolution to 1080p format=bestvideo[height<=1080]+bestaudio cause the problem again as when i run it with format=bestvideo[height<=720]+bestaudio it play the video at 720 at max

**Comment by low-batt** [comment]
Setting that `yt-dlp` option is a workaround and yes, it has some undesirable side effects. For example, I suspect that if you try and stream from a site that only provides 4K resolutions then `yt-dlp` with that configuration will fail.

For advice regarding throttling I suggest asking the [yt-dlp](https://github.com/yt-dlp/yt-dlp) project. [This comment](https://github.com/yt-dlp/yt-dlp/issues/985#issuecomment-944839974) from `yt-dlp` issue https://github.com/yt-dlp/yt-dlp/issues/985 provides some specific steps to take when investigating throttling.

**Comment by KOTHX** [comment]
Thanks
