### ISSUE TITLE
Release build fails with exit code 65

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4717]
**System and IINA version:**

- macOS unknown
- IINA `develop` branch?

**Expected behavior:**
A release build of IINA completes successfully.

**Actual behavior:**
The following was reported by @Mikasa-san in issue #4383:

When I tried to build in Release I got this error:
```text
The following build commands failed:
SwiftEmitModule normal x86_64 Emitting\ module\ for\ iina_plugin (in target 'iina-plugin' from project 'iina')
(1 failure)
note: Run script build phase 'Copy Dylib Symlinks' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'iina' from project 'iina')
Error: Process completed with exit code 65.
```

but in Debug It works fine

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
Only with the release build, the debug build works.

**Comment by low-batt** [comment]
Hi @Mikasa-san!

I tried and I was able to successfully build a release version of IINA. Read through what I did below and look for what differs from your setup.

I tried building a release version for any Mac from the `develop` branch on my MacBookPro16,1 with a 6-Core Intel Core i7 chip running macOS 14.2 using Xcode 15.1. I built the release version in two ways. In Xcode I clicked on `Archive` under the `Product` menu. Took a while, but that successfully generated a release archive. I also tried building a release version by clicking on `Edit Scheme…` under the `Product` menu and changing the `Run` `Build Configuration` to `Release` and then building IINA. That too worked for me.

I repeated this process on my MacBookPro18,2 with an Apple M1 Max chip running macOS 13.6.1 using Xcode 15.0.1. Building under this Mac also worked.

In the output above it is the `exit code 65` that is of concern.

I too see this note in the Xcode build log:
```text
note: Run script build phase 'Copy Dylib Symlinks' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'iina' from project 'iina')
```

That is expected. It has to do with this build phase:
![copy-dylib-symlinks](https://github.com/iina/iina/assets/86170219/f408aff5-9b41-4e57-a410-172f3a645fc7)

That phase uses a bash script to copy any libraries in `deps/lib` that are symbolic links into the build directory. This is not a significant part of the build time so it has not been changed to support Xcode's dependency analysis.

At what point does your Xcode build log show the build failed? This is what the end of the log of my working build looks like:
![build-log](https://github.com/iina/iina/assets/86170219/d7448c6a-32a9-45b4-ad98-0ec267302bb8)

**Comment by Mikasa-san** [comment]
I used Github workflow to build it and I get that error says "Copy Dylib Symlinks"

**Comment by low-batt** [comment]
The IINA GitHub action that performs continuous integration builds is working. Check your workflow definition against IINA's CI workflow: [ci.yml](https://github.com/iina/iina/blob/develop/.github/workflows/ci.yml)

Make certain your workflow downloads the dependencies:
```text
      - name: Install dependencies
        run: ./other/download_libs.sh
```

**Comment by low-batt** [comment]
As @Mikasa-san has reported the build is now working I'm closing this issue.
