### ISSUE TITLE
Version Numbering Borked

### ISSUE THREAD

**Issue by thoran** [iina/iina#4744]
**System and IINA version:**

- macOS 13
- IINA 1.3.4

**Expected behavior:**

Perhaps there's no intention for IINA to use SemVer, but even so...

The latest release notes for 1.3.4 were confusing. It states that 1.4.0 will be "the next major release". Usually a major release is indicated by incrementing the first number, hence I expected that the next major release would be 2.0 not 1.4.0.

So, I would call 1.4.0 a "minor release", since incrementing the second number is how that is known.

Additionally, when adding new features such as "Added a new "Take Screenshot" button on the OSC ([pull/4648](https://github.com/iina/iina/pull/4648))" or "Download from Open Subtitles using the new REST API ([issues/3920])", then a minor release is warranted for that, assuming that there are no backwards compatible breakages, which for non-library code is a bit more flexible I admit.

Usually bug fixes are included in a tiny release, whereby the third number is incremented. Sometimes a fourth number is employed and I don't mind that style, even if it isn't strictly SemVer, but might rather be considered a SemVer superset.

So, I would consider 1.3.4 to be sufficient for all the fixes, which are able to optionally be rolled out with 1.4.0, but given the new features this should be release 1.4.0 and what you're calling "the next major release", assuming it really does warrant being called that should be 2.0.

**Actual behavior:**

See above or not relevant.

**Steps to reproduce:**

Read the release notes.

**How often does this happen?**

I'm not sure as I haven't reviewed other release notes to see if this is a consistent pattern.

**Comment by saagarjha** [comment]
Yes, IINA does not use semver. The version numbers are purely for marketing and decided on in an ad-hoc fashion.
