### ISSUE TITLE
Clean Uninstallation

### ISSUE THREAD

**Issue by herry23xet** [iina/iina#4747]
It would be nice if it's shown where all the files and folders of this app are located so that it can be uninstalled without leaving any residue.
Unfortunately, I couldn't find anything like that described.
I don't want to uninstall the app, but I think it's useful just in case.
Could you please add this?

**Comment by hugepower** [comment]
I found a solution using AppCleaner, a free tool that can remove any app and its associated files from your Mac. You can download it from [https://freemacsoft.net/appcleaner/](https://freemacsoft.net/appcleaner/.) It also supports uninstalling other apps that are not listed in the Applications folder. Just drag and drop the app icon to AppCleaner and it will do the rest. Hope this helps!
<img width="1005" alt="截屏2024-01-03 14 55 35" src="https://github.com/iina/iina/assets/46076022/81f9c848-4885-4f70-a27e-a0366db56362">

**Comment by herry23xet** [comment]
@hugepower Thx! But does AppCleaner really delete everything? I've often read that AppCleaner still leaves remnants behind.

**Comment by low-batt** [comment]
Thanks @hugepower for posting the screen shot showing those directories. 

If IINA logging was ever enabled in IINA's settings under the `Advanced` tab then there will be log files in the directory `/Library/Logs/com.colliderli.iina`. My guess is that `AppCleaner` would have found that directory if @hugepower had enabled logging.

I'm expecting you will also have this file:
`~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.colliderli.iina.sfl2`

With this file we are now into a "grey" area. This file does not "belong" to IINA. This file belongs to `sharedfilelistd`, a macOS daemon. This is where macOS stores the list of recently opened documents on behalf of IINA. This is the list you see in IINA's welcome window and in the `Open Recent` menu item. Possibly macOS will cleanup this file when an application is deleted.

There are many more places like this where macOS stores knowledge of an application. I'm not sure how fast macOS cleans up all of its databases that "know" about an application.

**Comment by herry23xet** [comment]
Thank you, then I can really assume that AppCleaner finds everything that only explicitly belongs to IINA and is not "shared" or is in the "grey" area. That's good to know!

**Comment by low-batt** [comment]
Yes, I believe so.

Another directory I forgot to mention is `~/.config/mpv/`. That is the default directory for [mpv](https://github.com/mpv-player/mpv) configuration. Use of this directory can be enabled on the IINA setting's `Advanced` tab. IINA does not create this directory. It is up to you to create it if you want IINA to use `mpv` configuration files.

**Comment by saagarjha** [comment]
This list is likely to also be helpful: https://github.com/Homebrew/homebrew-cask/blob/25896209b81aa56dd28d93c57180b28e36c15f42/Casks/i/iina.rb#L23

**Comment by hugepower** [comment]
I am using PNG format for my screenshots, and each one occupies approximately 2MB of space. Surprisingly, in the `~/Library/Caches/com.colliderli.iina/screenshot_cache` directory, IINA has stored nearly 10GB of past screenshot images. I am puzzled by this as I don't understand the need to retain so many screenshots, which seem to be taking up a significant amount of unnecessary storage space.

**Comment by low-batt** [comment]
I have created issue #4899 for the large screenshot cache problem.
