### ISSUE TITLE
Overlapping Subtitles when displaying dual subtitles

### ISSUE THREAD

**Issue by minimapletinytools** [iina/iina#4752]
- macOS 14.2.1
- IINA 1.3.4

**Expected behavior:**
Both subtitles should be clearly visible 

**Actual behavior:**
Sometimes subtitles will overlap each other overhead. 
I'm guess some subtitles display overhead. Suggest overriding these to simply display in the usual position.
<img width="941" alt="Screenshot 2024-01-05 at 10 36 13 AM" src="https://github.com/iina/iina/assets/108157/be51ccf2-8d95-4ad4-bb77-43c78d23635f">

**How often does this happen?**
happens quite often in the video files I'm watching

**Comment by minimapletinytools** [comment]
Thanks for the awesome software BTW! The dual subtitle feature is amazing for language learning.

**Comment by low-batt** [comment]
For audio/video and subtitle rendering support IINA uses a library from the [mpv](https://github.com/mpv-player/mpv) project. This is why the issue template contains this checkbox:
> - [ ] MPV does not have this problem.

If the problem is reproducible with the [mpv](https://mpv.io/) player then the root cause is in code IINA does not control and the problem must be reported to that project. In the case of subtitles it is `mpv` that renders the subtitle text into the video frame.

If you can provide the subtitle files that exhibit this problem I can test if this is reproducible with the [mpv](https://mpv.io/) player.

To post files you can just drag-n-drop them to the `Add a comment` box below and then click the `Comment` button.

**Comment by minimapletinytools** [comment]
I should have clarified in the description. This issue happens only when enabling secondary subtitles. It doesn't seem like mpv supports dual subtitle so the issue is not reproducible in mpv. This issue happens whenever subtitles, which would normally display at the bottom of the screen as a "primary subtitle" have their position set to the top of the screen, which may conflict with the "secondary subtitle" positionining at the top of the screen.

Here is a screenshot of the same scene from above in mpv with only english subtitles displaying at the top (most of the time, the subtitles display at the bottom of the screen)

<img width="700" alt="Screenshot 2024-01-05 at 8 04 03 PM" src="https://github.com/iina/iina/assets/108157/ae2d6654-4c9d-4039-b1c0-6c9e39258cb1">

I will try and extract the subs from the mkv file with ffmpeg, not sure if that will work or if the extracted subs will preserve the positioning args though. I think this issue could probably be easily reproduced with any subtitle file that repositions to the top of the screen though.

**Comment by minimapletinytools** [comment]
I was able to extract the subs. I can see that the subs corresponding to the screenshot above has the `{\an8}` which is an ASS tag which sets the position to the top. 

```
136
00:07:30,366 --> 00:07:33,369
{\an8}<i>it was once a sacred place
where villagers slept in peace.</i>
```

```
156
00:07:30,242 --> 00:07:33,370
{\an8}村人らの眠る
静かな聖域であったが
```

I've also attached the two .srt files for the english and japanese subs I extracted. 

[subs.zip](https://github.com/iina/iina/files/13848374/subs.zip)

**Comment by minimapletinytools** [comment]
Just for clarity, here is a screenshot of how the dual subtitles look when there is no position tag 

<img width="959" alt="Screenshot 2024-01-05 at 8 22 15 PM" src="https://github.com/iina/iina/assets/108157/23e78361-feb4-43d0-a46a-fdda0d0c42f2">

**Comment by low-batt** [comment]
Thanks for the excellent analysis!

On this:
> It doesn't seem like mpv supports dual subtitle so the issue is not reproducible in mpv. 

From the mpv manual entry for the [sub-files](https://mpv.io/manual/stable/#options-sub-file) option:
> It's possible to show two subtitles at once: use `--sid` to select the first subtitle index, and `--secondary-sid` to select the second index.

The [secondary-sid](https://mpv.io/manual/stable/#options-secondary-sid) option is the key to getting `mpv` to display a second subtitle.

I believe the [sub-ass-style-overrides](https://mpv.io/manual/stable/#options-sub-ass-style-overrides) option can be used to just override the specific alignment tag, but I could not figure out the proper syntax to get that option to work.

Instead I set the option [sub-ass-override](https://mpv.io/manual/stable/#options-sub-ass-override) to `strip`. Not ideal as this strips all tags.

To set this in IINA follow these instructions:

- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Advanced`
- Slide the `Enable advanced settings` toggle button to be on (blue)
- In the `Additional mpv options` section click on `+`
- A new entry appears in the table
- Double click on `name` and replace it with `sub-ass-override`
- Double click on `value` and replace it with `strip`
- **Restart IINA** to activate the new settings

See if that works.

**Comment by minimapletinytools** [comment]
Thanks for the detailed instructions. That totally worked for me!

![Screenshot 2024-01-06 at 8 47 38 PM](https://github.com/iina/iina/assets/108157/36f34972-0f1c-46ab-a712-405d99ee1083)

I suggest, as a feature, having this `sub-ass-override: strip` set by default when displaying dual subtitles and perhaps adding a toggle in the subtitle menu to opt-out of it. position tags in subtitles seem to be pretty common, at least in anime.

**Comment by minimapletinytools** [comment]
So glad to finally having working dual subs. This has been fantastic for learning Japanese. I'm surprised this feature isn't supported in more places / more in demand. 

Was the one of the main intents of dual subtitles for language learners?

Just floating an idea here. I find myself frequently typing the Japanese subs in chatGPT and asking "can you please break down this japanese sentence for me".  I've found this learning flow much more useful than just looking up words in the dictionary. I'd love to be able to just click the subs and deep link to chatGPT with a prewritten prompt. The ability to highlight words and have a dictionary popup would be nice too of course.
 
Well, if I find myself wanting this enough, I may open a new feature request ticket and/or look into implementing it myself. I thought I'd ask here if such an idea would be in line with iina's design space.

**Comment by uiryuu** [comment]
> I'd love to be able to just click the subs and deep link to chatGPT with a prewritten prompt. The ability to highlight words and have a dictionary popup would be nice too of course.

I think this is a perfect idea to be implemented though our recent plugin system. If you are interested, please refer to the documentation of the plugin system: https://docs.iina.io/pages/creating-plugins.

**Comment by cgarvie** [comment]
This worked for me and I just want to thank you guys for building such fantastic software. You are building such a general piece of software (a media player) that you may not know of all the little niches in which it is useful, but it is perhaps the best media player for those learning foreign languages or needing double subtitles. Thanks so much, it's really a lifesaver!
