### ISSUE TITLE
Drag&drop stops work after the video starts playing

### ISSUE THREAD

**Issue by tywtyw2002** [iina/iina#4756]
**System and IINA version:**

- macOS 12.6.3
- IINA IINA 1.3.4 Build 140

**Expected behavior:**
When dragging and dropping a video or subtitle onto the IINA player, it should automatically load the subtitle or start playing the new video.

**Actual behavior:**

The IINA ignores drag and drop events once the video starts playing.

https://github.com/iina/iina/assets/576954/02a03546-2b06-475a-b57c-185fc7f5eff0

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

[iina.log](https://github.com/iina/iina/files/13855338/iina.log)

</details>

**Comment by uiryuu** [comment]
I wasn't able to reproduce this problem. It seems that you enabled plugins based on the log you provided. Can you try to disable all the plugins and retry to see wether this issue still exists? Thanks.

**Comment by tywtyw2002** [comment]
Yes, that plugin add an overlay over the player and blocked the drag&drop events.
