### ISSUE TITLE
About Picture in Picture

### ISSUE THREAD

**Issue by JiangZhou1** [iina/iina#4760]
The picture-in-picture mode can only be attached to the four corners of the screen. Can the picture-in-picture be used at any position?

**Comment by uiryuu** [comment]
Unfortunately, no. The Picture-in-Picture functionality are completely provided by macOS, which we can do little to nothing with. If you want to put a floating player where ever you want, try use "Float on top" feature.

**Comment by saagarjha** [comment]
You can move the window to an arbitrary location by holding down the ⌘ key while dragging
