### ISSUE TITLE
Play next item automatically preference not respected

### ISSUE THREAD

**Issue by kevinwan9** [iina/iina#4764]
**System and IINA version:**

- macOS  Sonoma 14.2.1
- IINA  1.3.4

**Expected behavior:**
Disabling "Play next item automatically" for playlist won't automatically play the next video after the current video is done, and will pause at the end of the current video.

**Actual behavior:**
Disabling the option has no effect on behavior; the next item in a playlist will play automatically once the current video is complete regardless of whether the setting is actually toggled on or not.

**Steps to reproduce:**
1. Disable "Play next item automatically"
2. Load in a playlist
3. Watch to the end of the video
4. The next item in the playlist automatically plays

**How often does this happen?**
Every time.

**Comment by svobs** [comment]
@Terannosaurus why did you close this? I've been looking at the code and I think there may actually be a bug here.
