### ISSUE TITLE
Bluetooth keyboard causes video to pause?

### ISSUE THREAD

**Issue by ballo** [iina/iina#4787]
I apologize if this isn't IINA specific; I honestly don't know if it is or isn't but I'm hoping to diagnose the problem in any case.

I have a cheap Rii Bluetooth keyboard which I bought to control video and other things when I have my Mac connected to the TV. It works as expected when connected, but leave it be for a few minutes it will sleep and IINA will pause the video. If I wake the keyboard it will quickly reconnect and I'll press space bar to resume playing, but then it'll sleep and the video pauses again. 

I would understand the video pausing if the Bluetooth device was an audio device, but not a keyboard. If I turn off the keyboard it doesn't pause the video; only it going into sleep mode does it pause.

Any suggestions?

**Comment by low-batt** [comment]
I don't remember reading a similar issue. Scratching my head as to what is happening. Here is an experiment to try to rule out a few of IINA's settings…

- Start IINA
- Under the IINA menu click on `Settings…`
- In the `Behavior` section of the settings panel look for the `Pause/resume when` disclosure triangle
- Expand that section
- Uncheck any checked settings in this group
- **Restart IINA**
- Test keyboard sleeping and see if behavior changes

If you have never changed this section of settings then I think only the `Pause when machine goes to sleep` will be checked. To implement that IINA is listening for the [willSleepNotification](https://developer.apple.com/documentation/appkit/nsworkspace/1530075-willsleepnotification). That should only occur if the Mac is going to sleep.

I'm not expecting any of these settings are causing playback to pause, but good to rule them out.

**Comment by ballo** [comment]
Thanks for getting back to me. I was confused for a second when I didn't see a "Behavior" tab, but I eventually found it and I'll keep them in mind. Unfortunately, this doesn't happen every time it sleeps but only some of the times, which means I can't make it happen on demand (the worst kind of bug). 

If I find a way to make it happen more deliberately I'll mention it. Unfortunately, I have to let the device sleep which takes a while and then wake it which also takes a half minute. It definitely happened without touching the device, however. 

Edit: I'm closing this until it reappears. There is a possibility that a right click caused it as it's very easy to hit on this keyboard.

**Comment by low-batt** [comment]
Thanks for reporting back and closing the issue. If you continue to encounter trouble please feel free to reopen this issue.

Another possibility is that the keyboard is glitching while entering sleep and sending a space character which would also cause IINA to pause the video.
