### ISSUE TITLE
About SPDIF digital output support

### ISSUE THREAD

**Issue by tombloon** [iina/iina#48]
This is a great project!
I suggest to add through the built-in optical fiber direct output DTS AC3 support.
This is very useful for playing HD audio and video. 
Thank you for all the work you've done!

**Comment by lhc70000** [comment]
Thanks for feedback.

I'll try to add this feature and update you when made some progress.

**Comment by lhc70000** [comment]
Added in [0.0.4](https://github.com/lhc70000/iina/releases/tag/v0.0.4).

**Comment by swrobel** [comment]
I can't get my Macbook to output DTS HD bitstream over HDMI. Should this feature allow that? I have all S/PDIF settings checked:
<img width="329" alt="screen shot 2017-03-06 at 5 01 31 pm" src="https://cloud.githubusercontent.com/assets/157270/23637183/021d12ae-028f-11e7-8f21-f717bb6d12dd.png">

**Comment by lhc70000** [comment]
@swrobel Seems that we need to compile FFmpeg with libdcadec…… Hopefully will add in next version.

**Comment by mb21** [comment]
Can confirm that this isn't working for me either in IINA 0.0.12 Build 37, mpv 0.25.0 on macOS Sierra. Would be great to have it added!

Currently, the only GUI player I can get this to work in is `MPlayer OSX Extended` with the binary `Official MPlayer SVN r36986`...

**Comment by macdavis** [comment]
> I can't get my Macbook to output DTS HD bitstream over HDMI. Should this feature allow that? I have all S/PDIF settings checked:
> <img alt="screen shot 2017-03-06 at 5 01 31 pm" width="329" src="https://cloud.githubusercontent.com/assets/157270/23637183/021d12ae-028f-11e7-8f21-f717bb6d12dd.png">

It's a limitation of macOS itself. There is nothing IINA, mpv, or any other media player can do.

**Comment by macdavis** [comment]
> Can confirm that this isn't working for me either in IINA 0.0.12 Build 37, mpv 0.25.0 on macOS Sierra. Would be great to have it added!
> 
> Currently, the only GUI player I can get this to work in is `MPlayer OSX Extended` with the binary `Official MPlayer SVN r36986`...

For AC3, E-AC3, DTS, you could try add `coreaudio-spdif-hack=yes` in advanced settings.
