### ISSUE TITLE
希望有剪辑视频的功能，把视频裁掉一部分

### ISSUE THREAD

**Issue by olafchou** [iina/iina#4816]
**What you want IINA to do:**

**What IINA does currently:**

**Why you think this should be added:**

**Examples of other projects that have something similar:**

**Comment by low-batt** [comment]
母语为英语的人使用在线翻译器进行回复...

这与 #1989 问题重复。

有开源视频编辑器。Shotcut 就是其中之一：
https://www.shotcut.org/
