### ISSUE TITLE
Add a key binding to bind the R key to sub-pos +1

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4823]
**What you want IINA to do:**
Provide a key binding from the `R` key to the `add sub-pos +1` command in the default IINA key bindings.

**What IINA does currently:**
IINA currently provides the following subtitle position related key bindings in `IINA Default`:
| Key | Command |
| --- | --- |
| `r` | `add sub-pos -1` |
| `t` | `add sub-pos +1` |

**Why you think this should be added:**
It appears this portion of the IINA key bindings were designed to match `mpv`. But in `mpv` commit https://github.com/mpv-player/mpv/commit/496b13227b7f4b47a660bbf4e314f9a55b7e8867 a binding to the `R` key was added.

From the [Keyboard Control](https://mpv.io/manual/stable/#keyboard-control) section of the `mpv` manual:
> **r and R**
>    Move subtitles up/down. The t key does the same as R currently, but use is discouraged.

This change is correctly reflected in IINA's `mpv Default` key bindings:
| Key | Command |
| --- | --- |
| `r` | `add sub-pos -1` |
| `R` | `add sub-pos +1` |
| `t` | `add sub-pos +1` |

As `IINA Default` does not currently contain a key binding for the `R` key a binding can be added to match the `mpv` bindings.

**Comment by svobs** [comment]
@low-batt I can take ownership of this if you'd like.

**Comment by low-batt** [comment]
Thanks, I will assign it to you.

**Comment by low-batt** [comment]
This was added in IINA 1.3.5.
