### ISSUE TITLE
Add key bindings for changing subtitle font size

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4824]
**What you want IINA to do:**
Provide key bindings for changing subtitle font size.

**What IINA does currently:**
IINA does not provide any bindings for this in the `IINA Default` key bindings. The `mpv Default` key bindings contains the following entries:
| Key | Command |
| --- | --- |
| ⇧g | `add sub-scale +0.1` |
| ⇧f | `add sub-scale -0.1` |

These keys have not been assigned in the  `IINA Default` key bindings. IINA should consider adding bindings that match the `mpv Default` key bindings.

**Why you think this should be added:**
This was requested in [this comment](https://github.com/iina/iina/issues/4457#issuecomment-1948034554) on issue #4457.

**Examples of other projects that have something similar:**
`mpv`

**Comment by svobs** [comment]
Seems like the `IINA Default` config should strive to be a superset of the `mpv Default` config?

**Comment by low-batt** [comment]
Maybe. For now just address this specific case as if we keep the change simple the reviewers should approve it for the upcoming bug fix release.

Lets see what the reviewers say about adding more `mpv` bindings. If they think that is a good idea then such a change can go into the feature release.

We are getting closer to having all the PRs ready for the bug fix release, but are behind on merging.

**Comment by low-batt** [comment]
This was added in IINA 1.3.5.
