### ISSUE TITLE
Sreenshots with timecode in the file name

### ISSUE THREAD

**Issue by curbyourenthusiasm** [iina/iina#4858]
MPC has the timecode in the file name of all saved screenshots. It would be cool to have this at IINA.

**Comment by low-batt** [comment]
IINA uses a library from the [mpv project](https://github.com/mpv-player/mpv) for audio/video support. Many mpv features not exposed by the IINA user interface are still available by directly setting `mpv` options. This is the case for the name generated for a screenshot filename. See issue #4177 for an example of how to alter the generated filename.

I'm going to label this issue as a duplicate of #4177. If you think that is incorrect reply to this issue and indicate what is different. If the instructions in #4177 for altering the generated filename do not work, reply to that issue and I will try and help.

**Comment by curbyourenthusiasm** [comment]
> IINA uses a library from the [mpv project](https://github.com/mpv-player/mpv) for audio/video support. Many mpv features not exposed by the IINA user interface are still available by directly setting `mpv` options. This is the case for the name generated for a screenshot filename. See issue #4177 for an example of how to alter the generated filename.
> 
> I'm going to label this issue as a duplicate of #4177. If you think that is incorrect reply to this issue and indicate what is different. If the instructions in #4177 for altering the generated filename do not work, reply to that issue and I will try and help.

Thank you very much. Worked like a charm!

**Comment by low-batt** [comment]
Great! Glad to hear it worked. I'm closing this issue as a duplicate of #4177.
