### ISSUE TITLE
Automatically stop when not in foreground

### ISSUE THREAD

**Issue by StepanPazderka** [iina/iina#4868]
**What you want IINA to do:**
I want IINA to be able to automatically stop whenever I switch to another app. I am using IINA to quickly browse through videos and its an annoyance to always have to pause playing video before I switch to another app.

**What IINA does currently:**
nothing

**Why you think this should be added:**

**Examples of other projects that have something similar:**

**Comment by low-batt** [comment]
Follow these instructions:
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- In the `Behavior` section click on the `Pause/resume when` disclosure triangle
- Check the `Window becomes inactive/active`

Does that provide the feature you are looking for?

**Comment by StepanPazderka** [comment]
My apologies!! yes absolutely

**Comment by low-batt** [comment]
Glad to hear it is working for you. 

No need to apologize. The disclosure triangles that hide these settings are easy to miss. Do not be afraid to ask questions about IINA if you have trouble.

I will go ahead and close this issue.
