### ISSUE TITLE
Incorrect directionality in RTL OSD

### ISSUE THREAD

**Issue by ShlomoCode** [iina/iina#4884]
**System and IINA version:**

macOS 14.4.1
IINA 1.3.4 + PR #4922

**Expected behavior:**
The audio progress indicator in the OSD should always be from left to right (see https://github.com/iina/iina/issues/4878#issuecomment-2054149270).
The OSD itself should be on the left side of the screen in RTL mode.

**Actual behavior:**
- The OSD (on screen display) has a playback progress slider while changing the position, and it should be like the slider in the OSC (from left to right, like a tape).
- The numbers in the OSD are also not in the right direction, meaning it should be
`{current_time} / {remaining_time}` (as in the OSC slider)
and not `{remaining_time} / {current_time}`
- In addition, the OSD should be on the left side of the window and not on the right side

**Screenshort:**
<details>
  <summary>Video</summary>

  https://github.com/iina/iina/assets/78599753/415277e8-ea4f-4abb-bd98-429bd9ab66d6

</details>

**Steps to reproduce:**

- Open the IINA project in Xcode
- Under the Product menu open the Scheme menu and select Edit Scheme…
- Click on the Options tab
- Scroll down to the App Language setting
- In the pull down select Right-to-Left Pseudolanguage near the end of the list
- Start IINA running under Xcode
- Start playing a video
- Change playback position (for example by tapping on a position in the progress slider)

Or you can build with PR #4922 and set your language to Hebrew.

[x] MPV does not have this problem.

mpv does not support localization.

_Originally posted by @ShlomoCode in https://github.com/iina/iina/issues/4878#issuecomment-2065450058_

**Comment by ShlomoCode** [comment]
WIP

**Comment by low-batt** [comment]
This is the part I don't understand:
> In addition, the OSD should be on the left side of the window and not on the right side

Why would the OSD not flip location like other components?

The OSD is "interesting" since it needs to not flip when showing playback progress, but needs to flip when showing other information such as volume, yes?

**Comment by ShlomoCode** [comment]
> Why would the OSD not flip location like other components?

Mmm... I forgot that in the LTR version it's already on the left side of the screen, I'm used to notifications (toasts) appearing at the "end" of the screen, that is, in English it's usually on the right side. It's like that in macos notifications, in English it's on the right and in Hebrew it's on the left.
But iina is the opposite of normal in English... you know why?

> The OSD is "interesting" since it needs to not flip when showing playback progress, but needs to flip when showing other information such as volume, yes?

Yes

**Comment by low-batt** [comment]
Caught me working on this. There are a number of OSD messages that need to be corrected. Juggling multiple tasks. I may not finish this one today.

On this:
> But iina is the opposite of normal in English... you know why?

I'm a newbie (relative to others) junior IINA developer. I wasn't around when IINA was initially developed and still don't have any knowledge about such design decisions. My _guess_ is that IINA matched  `mpv` whose OSD is also on the left side. As you can disable IINA's OSD and switch to the `mpv` OSD it makes sense that they are both in the same part of the window. I believe the attraction of the `mpv` OSD is that it can be customized.

**Comment by low-batt** [comment]
Proposed fix posted in PR #4886.

**Comment by ShlomoCode** [comment]
i pulled the pr, build and checked the abLoop, pause, resume, volume and progress messages
Looks good!

**Comment by low-batt** [comment]
Great! Next up is the remaining problems in issue #4776.

In [IINA's instance of Crowdin](https://translate.iina.io/) Hebrew is 99% translated. There are still a few missing translations. Are you able to bring it to 100%?

**Comment by ShlomoCode** [comment]
@low-batt There were [5 strings left](https://crowdin.com/editor/iina/all/en-he?view=comfortable&filter=basic&value=2) that I couldn't understand the context/meaning of. If you comment on them it will help!

p.s. still the location of the OSD toast on the right side of the screen seems illogical to me

**Comment by low-batt** [comment]
As I don't normally work on localization I don't have a Crowdin account yet. I'm trying to create one now. Having some trouble. I will help with the translations once I gain access.

For something like the OSD location it is best to comment on the PR so when I get a senior developer to review the proposed changes they may be able to comment on why things are the way they are, or suggest a change.

**Comment by low-batt** [comment]
I am now on Crowdin. I answered the questions I found. Crowdin wouldn't let me use my normal email, so I will be very slow to notice messages posted there.

**Comment by ShlomoCode** [comment]
Thank you, now Hebrew is 100% complete
