### ISSUE TITLE
RTL language causes overlapping in subtitle settings

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4888]
**System and IINA version:**

- macOS 13.6.3
- IINA 1.3.4 + PR #4922

**Expected behavior:**
UI components do not overlap with right to left languages such as Arabic and Hebrew.

**Actual behavior:**
Currently IINA does not support any right to left languages. However PR #4922 enables Hebrew. If you build IINA with that pull request and set Hebrew as the language then the color wells on the `Subtitle` tab of IINA's settings overlap the labels for the control. Also, if on the `UI` tab in the `On Screen Display` section the  `Display time and battery info when in full screen` setting is enabled then the text giving the battery state overlaps with the battery icon.

These problems were reported by @ShlomoCode in issue #4776. As that issue reports quite a few RTL related problems I have created this issue to focus just on these two problems.

**Steps to reproduce:**
- Open the IINA project in Xcode
- Under the `Product` menu open the `Scheme` menu and select `Edit Scheme…`  
- Click on the `Options` tab
- Scroll down to the `App Language` setting
- In the pull down select `Right-to-Left Pseudolanguage` near the end of the list
- Start IINA running under Xcode
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Subtitle`
- Notice in the `Text Subtitles` section the labels overlapping with the color wells.

Or you can build with PR #4922 and set your language to Hebrew.

- [x] MPV does not have this problem.

mpv does not support localization.

**How often does this happen?**
Every time.

**Comment by ShlomoCode** [comment]
The battery icon is now in the right direction, but now its boundary line looks blurry
![CleanShot 2024-04-23 at 20 49 56@2x](https://github.com/iina/iina/assets/78599753/d5ae2813-f56a-4c0f-8575-e47b211ad94b)
When I change the language specific to the application in the system settings to English, the icon is sharp (MBP 2021 built-in screen)
Is it the same for you?

**Comment by ShlomoCode** [comment]
The orientation of the right half of the color picker button should be reversed, so that the two halves together form an ellipse (like [group-toggle](https://getbootstrap.com/docs/5.0/components/button-group/))
![CleanShot 2024-04-23 at 20 47 10@2x](https://github.com/iina/iina/assets/78599753/6d71eaf8-4a53-41ae-9a55-fd88f6c6999c)

**Comment by ShlomoCode** [comment]
There also seems to be some overlap in the video and audio tabs (in the sidebar)
![CleanShot 2024-04-23 at 21 13 49@2x](https://github.com/iina/iina/assets/78599753/0958e6d2-bfeb-491d-ac5f-b41e1f839fb8)

**Comment by low-batt** [comment]
Tuesday is a busy day for me, but I will be responding to these problems.

There is definitely something wrong with the quick settings sidebar as I get constraint warning when I open it. The labels for the icons do look too close together.

A noticed another problem in the subtitle panel. Look for the word `force` in the Hebrew screenshot in my comment [here](https://github.com/iina/iina/pull/4889#issuecomment-2071380392). That is not a translation error, that is an IINA localization defect. I will be fixing that as well.

**Comment by ShlomoCode** [comment]
I dived into the color picker again and I think that the 2 parts of the button should also be replaced, i.e. "mirror" of the English version -
If in LTR it is like this and the flow is from left to right
 
![CleanShot 2024-04-25 at 01 41 45@2x](https://github.com/iina/iina/assets/78599753/22de7bf4-1df2-4f5f-9380-a59adbbdf18e)


In RTL it should simply be a mirror - like the "valid" in this image:

![CleanShot 2024-04-25 at 01 33 53@2x](https://github.com/iina/iina/assets/78599753/cff1df87-4440-44a7-98de-dbbc6088b2f5)

**Comment by ShlomoCode** [comment]
i updated the image

**Comment by low-batt** [comment]
Yes. I agree. The entire color well should be flipped as shown in the one labled "valid".

IINA uses a [NSColorWell](https://developer.apple.com/documentation/appkit/nscolorwell) and when running under macOS Ventura or later the [expanded](https://developer.apple.com/documentation/appkit/nscolorwell/style/expanded) style is used. I'm still trying to track down what is causing it to not flip as expected. I wrote a tiny test program and that worked fine. So it is something about how it is used in IINA that is causing it to malfunction. I will continue to investigate.

**Comment by ShlomoCode** [comment]
> There is definitely something wrong with the quick settings sidebar as I get constraint warning when I open it. The labels for the icons do look too close together.

Just a little reminder. I worry this small detail may have slipped through the cracks with everything going on :)

**Comment by low-batt** [comment]
The constraint warnings seen with the quick settings panel when the layout is reversed proved to be due to the problems with the speed slider labels. The fix for that problem corrected the constraint warnings.

**Comment by ShlomoCode** [comment]
> The constraint warnings seen with the quick settings panel when the layout is reversed proved to be due to the problems with the speed slider labels. The fix for that problem corrected the constraint warnings.

I built now with https://github.com/iina/iina/pull/4919 + #4922, and still the labels are too close to the icons. 
I don't know how to check if there is a constraint warning, but the problem is still there.
I opened an issue https://github.com/iina/iina/issues/4925 for it.

**Comment by low-batt** [comment]
I will have a look at #4925 tomorrow. Thanks for entering the issue.

Constraint warnings happen when constraints conflict so badly that layout is forced to intentionally break constraints. When that happens there will rather large warnings in the Xcode console. Of course objects can be miss-aligned without any constraint warnings.

To make it very obvious when constraint warnings occur run this command in terminal:
```bash
defaults write com.colliderli.iina NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints true
```

With that setting you will get a purple box around the window as seen here:
![purple](https://github.com/iina/iina/assets/86170219/c61a6c88-3c7c-4716-bf02-d4305a71d180)


To turn this debugging tool off delete the setting or set it to `false`.
