### ISSUE TITLE
Screenshot cache contains many large files

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4899]
**System and IINA version:**

- macOS 14.4.1
- IINA 1.3.4

**Expected behavior:**
Disk caches are bounded in size.

**Actual behavior:**
@hugepower reports in [this comment](https://github.com/iina/iina/issues/4747#issuecomment-2081105353):
> I am using PNG format for my screenshots, and each one occupies approximately 2MB of space. Surprisingly, in the `~/Library/Caches/com.colliderli.iina/screenshot_cache` directory, IINA has stored nearly 10GB of past screenshot images. I am puzzled by this as I don't understand the need to retain so many screenshots, which seem to be taking up a significant amount of unnecessary storage space.

**Steps to reproduce:**
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- Scroll down to the `Screenshots` section
- Uncheck the `Save to` setting
- Uncheck the `Show previews after taking screenshots`
- Start playing a video
- Take a screenshot
- Notice a file still remains in the `~/Library/Caches/com.colliderli.iina/screenshot_cache` directory

- [x] MPV does not have this problem.

**How often does this happen?**
Every time with the settings shown above.

**Comment by hugepower** [comment]
**System and IINA version**:

macOS Sonoma 14.4.1
IINA 1.3.4

In IINA's screenshot settings, when only the "Copy to Clipboard" function is enabled, each screenshot taken will be automatically saved to the designated directory.

<img width="630" alt="image" src="https://github.com/iina/iina/assets/46076022/a934e088-e4b4-4750-8bce-8ded0ecaaa49">

**Comment by low-batt** [comment]
Reproduced for me. This is a defect.

When the `Save to` screenshot setting is disabled IINA uses the `~/Library/Caches/com.colliderli.iina/screenshot_cache` cache directory. That is expected. The defect is that the code that removes the temporary file is not executed if the `Show previews after taking screenshots` setting is disabled.

At least that is my analysis after a quick investigation. Do you have `Show previews after taking screenshots` unchecked?

**Comment by hugepower** [comment]
> Reproduced for me. This is a defect.
> 
> When the `Save to` screenshot setting is disabled IINA uses the `~/Library/Caches/com.colliderli.iina/screenshot_cache` cache directory. That is expected. The defect is that the code that removes the temporary file is not executed if the `Show previews after taking screenshots` setting is disabled.
> 
> At least that is my analysis after a quick investigation. Do you have `Show previews after taking screenshots` unchecked?

Yes. I did not enable this feature.

<img width="932" alt="image" src="https://github.com/iina/iina/assets/46076022/bab21cbd-2b26-46f0-83fc-f192e2ca8ec5">

**Comment by low-batt** [comment]
Thank you so much for reporting this problem and providing the additional information. I was initially confused by this report as I didn't know IINA had a screenshot cache. Wasting disk space is a critical problem that must be fixed. I have added this issue as a high priority fix for the next release.
