### ISSUE TITLE
视频内置的软字幕切换到一下一句台词很多时候无效

### ISSUE THREAD

**Issue by JeseYe** [iina/iina#4900]
观察到的现象大概如此：如果两句台词的时间间隔很短切换下一句就可以，如果相距时间比较长，那么切换下一句台词就无效。这个现象是不是后面的流还没读取，切换下一句没找到内容？

**Comment by low-batt** [comment]
母语为英语的用户正在使用在线翻译...


我想这是关于使用 ⇧→ 键查找下一个字幕？当与嵌入式字幕一起使用时，该功能有其局限性。只有在短预取范围内才能找到下一个字幕。这听起来像是您描述的行为。如果到下一个字幕的时间间隔太长，就无法找到它。


问题 #4882 正在讨论这个问题。可以通过扩大缓存来改善这种行为。

**Comment by JeseYe** [comment]
> 母语为英语的用户正在使用的翻译...
> 
> 我想这是关于使用 ⇧→ 键查找下一个字幕？当与嵌入式字幕一起使用时，该功能有其局限性。只有在短预取范围内才能找到下一个字幕。这听起来听起来像您所描述的的行为。如果到下一个字幕的时间间隔太长，就无法找到它。
> 
> 问题#4882正在讨论这个问题。可以通过扩大缓存来改善这种行为。

如何在IINA中设置扩大缓存呢？我在ui上没有看到设置缓存的选项。谢谢！

**Comment by low-batt** [comment]
缓存设置可在 IINA 设置的 "网络 "选项卡中找到：

![cache-settings](https://github.com/iina/iina/assets/86170219/18b6d272-3dde-4de2-a63e-9b755f784be2)



您可能还需要在 IINA 的 "高级 "设置中设置 [demuxer-readahead-secs](https://mpv.io/manual/stable/#options-demuxer-readahead-secs)，如[本评论](https://github.com/iina/iina/issues/4709#issuecomment-1846500937)底部所示。


另一种解决方法是使用 "加载外部字幕... "菜单项将包含嵌入式字幕文件的文件加载为外部字幕文件。

**Comment by JeseYe** [comment]
> 缓存设置可在 IINA 设置的 "网络 "选项卡中找到：
> 
> ![cache-settings](https://private-user-images.githubusercontent.com/86170219/326659209-18b6d272-3dde-4de2-a63e-9b755f784be2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODM0NjQsIm5iZiI6MTcxNTU4MzE2NCwicGF0aCI6Ii84NjE3MDIxOS8zMjY2NTkyMDktMThiNmQyNzItM2RkZS00ZGUyLWE2M2UtOWI3NTVmNzg0YmUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA2NTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMGNjZGZiMTY0NDFjYTUxNDRhMDg4MGJlZDUyMmI1NGUyMjNhNWQ4NDlmZDk3OTZlNTZiMzVjNmQ3ZTYyZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nkp9jfZ8XSiV7fXwB6D-VTkuWQE0i96Dyg1U3fxjcFs)
> 
> 您可能还需要在 IINA 的 "高级 "设置中设置 [demuxer-readahead-secs](https://mpv.io/manual/stable/#options-demuxer-readahead-secs)，如[本评论](https://github.com/iina/iina/issues/4709#issuecomment-1846500937)底部所示。
> 
> 另一种解决方法是使用 "加载外部字幕... "菜单项将包含嵌入式字幕文件的文件加载为外部字幕文件

**Comment by JeseYe** [comment]
> > 缓存设置可在 IINA 设置的 "网络 "选项卡中找到：
> > ![cache-settings](https://private-user-images.githubusercontent.com/86170219/326659209-18b6d272-3dde-4de2-a63e-9b755f784be2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODM0NjQsIm5iZiI6MTcxNTU4MzE2NCwicGF0aCI6Ii84NjE3MDIxOS8zMjY2NTkyMDktMThiNmQyNzItM2RkZS00ZGUyLWE2M2UtOWI3NTVmNzg0YmUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA2NTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMGNjZGZiMTY0NDFjYTUxNDRhMDg4MGJlZDUyMmI1NGUyMjNhNWQ4NDlmZDk3OTZlNTZiMzVjNmQ3ZTYyZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nkp9jfZ8XSiV7fXwB6D-VTkuWQE0i96Dyg1U3fxjcFs)
> > 您可能还需要在 IINA 的 "高级 "设置中设置 [demuxer-readahead-secs](https://mpv.io/manual/stable/#options-demuxer-readahead-secs)，如[本评论](https://github.com/iina/iina/issues/4709#issuecomment-1846500937)底部所示。
> > 另一种解决方法是使用 "加载外部字幕... "菜单项将包含嵌入式字幕文件的文件加载为外部字幕文件

感谢，我已经在高级中设置缓存解决了

**Comment by low-batt** [comment]
很高兴听到它奏效了
