### ISSUE TITLE
ReplayGain support

### ISSUE THREAD

**Issue by MrSimmo** [iina/iina#4915]
**What you want IINA to do:**

Would be great to be able to add ReplayGain support natively to the UI (I know we can set values using MPV advanced settings but it would be nice to be able to set and alter ReplayGain settings in the audio settings).

**Why you think this should be added:**

It would allow libraries of music which have ReplayGain tags added to music files to be able to be played at the intended gain levels.

**Examples of other projects that have something similar:**

Foobar2000 Mac has an excellent ReplayGain implementation, with clipping support etc. Note, I'm not suggesting Iina supports creation of ReplayGain tags, only reading and using existing tags.

**Comment by low-batt** [comment]
Really nice writeup of the requested feature.

The request is to add UI support for the `mpv` [replaygain](https://mpv.io/manual/stable/#options-replaygain) option:
> **--replaygain=<no|track|album>**
>    Adjust volume gain according to replaygain values stored in the file metadata. With `--replaygain=no` (the default), perform no adjustment. With `--replaygain=track`, apply track gain. With `--replaygain=album`, apply album gain if present and fall back to track gain otherwise.

I'm assuming it is desirable to also include support for the associated options:
- [replaygain-preamp](https://mpv.io/manual/stable/#options-replaygain-preamp)
- [replaygain-clip](https://mpv.io/manual/stable/#options-replaygain-clip)
- [replaygain-fallback](https://mpv.io/manual/stable/#options-replaygain-fallback)

**Comment by low-batt** [comment]
Please have a look at the screenshots of the proposed implementation in PR #4932. Does that look like what you were expecting? Does the `mpv` behavior I show look like ReplayGain is working?

**Comment by MrSimmo** [comment]
> Please have a look at the screenshots of the proposed implementation in PR #4932. Does that look like what you were expecting? Does the `mpv` behavior I show look like ReplayGain is working?

This is brilliant - looks great! Yup, looks like its working fine. Thank you again

**Comment by low-batt** [comment]
Very helpful that you entered this issue. I was unaware of this `mpv` feature.

I'm a junior IINA developer so the proposed changes still need to be reviewed by the other developers. Future release plans are always subject to change, but last I heard the next release will be a bug fix release, so unlikely this change will make it into that release. As soon as possible after that release will be the first beta release for the long planned feature release. I'm expecting this change will make it into that release.

**Comment by MrSimmo** [comment]
Thanks low-batt; sounds good! and thanks again

**Comment by low-batt** [comment]
Support was added in IINA 1.4.0-beta1.

**Comment by MrSimmo** [comment]
Awesome thanks :)
