### ISSUE TITLE
Spatial Audio-Like Multi-channel Audio Output In IINA?

### ISSUE THREAD

**Issue by April-June-August** [iina/iina#4916]
When playing videos with multichannel audio tracks, IINA plays it normally, but that is not acknowledged by macOS so the option to use Spatial Audio is disabled. 

<img width="325" alt="Screenshot 2024-05-05 at 8 28 03 PM" src="https://github.com/iina/iina/assets/33798984/1315acf2-436f-4d3a-864f-a04f6966545f">

The same file can be recognized and played in 'Multichannel' or 'Dolby Atmos' by Infuse. The output can be recognized by macOS and the option to use Spatial Audio is available, which makes the sound more vivid. 
<img width="321" alt="Screenshot 2024-05-05 at 7 49 49 PM" src="https://github.com/iina/iina/assets/33798984/0ad63c81-9266-483d-b812-d883444abfa8">
<img width="323" alt="Screenshot 2024-05-05 at 8 23 01 PM" src="https://github.com/iina/iina/assets/33798984/198b2b3a-0efd-4da7-8823-2ef90c91472b">

Can this be implemented in IINA in the future?

**Comment by low-batt** [comment]
Interesting timing. This is currently being heavily discussed in issue #3444. I will be closing this issue as a duplicate.

Briefly, IINA has been waiting for the [mpv](https://github.com/mpv-player/mpv) project to implement the required changes. That is done. Thank you mpv project! IINA needs to update the `libmpv` and enable the support. Likely that will occur in the upcoming feature release. Likely there will be one more bug fix release before that happens. See #3444 for more discussion. [This comment](https://github.com/iina/iina/issues/3444#issuecomment-2093954801) contains a similar screenshot of a development version of IINA showing spatial audio enabled.

**Comment by April-June-August** [comment]
Got it. Thanks for the reply and the work! 👍
