### ISSUE TITLE
`iina-cli` doesn't work when stdin is /dev/null

### ISSUE THREAD

**Issue by zmwangx** [iina/iina#4936]
`iina-cli` doesn't work when stdin is not a tty, or when stdin EOFs early — not sure which. Trying to play anything with e.g.

    /usr/local/bin/iina <file> </dev/null

or

    echo | /usr/local/bin/iina <file>

causes an error dialog saying "Cannot open file or stream!". Directly calling `/Applications/IINA.app/Contents/MacOS/IINA` doesn't exhibit this problem.

Problem is I sometimes invoke `iina` from another program, e.g. from a Go or Swift application, where stdin of a subprocess by default is attached to the null device, so I end up getting these very unhelpful error messages. The fix is simple, just invoke the `IINA` binary directly, or if it's possible, attach stdin of the subprocess to a tty. I'm filing this bug because maybe it's fixable, and even if it's intended, maybe the error message can be made more helpful. Btw, `mpv` doesn't have this problem either.

**System and IINA version:**

- macOS 14.5
- IINA 1.3.4 Build 140

**Expected behavior:**

Invoking `/usr/local/bin/iina` (which is a symlink to `/Applications/IINA.app/Contents/MacOS/iina-cli`) should work regardless of whether stdin is attached to a tty.

**Actual behavior:**

There's always an error dialog "Cannot open file or stream!"

<details>
<summary><b>Crash report:</b></summary>

N/A
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

N/A
</details>

<br>

**Steps to reproduce:**

Run

    /usr/local/bin/iina <file> </dev/null
    echo hi | /usr/local/bin/iina <file>

etc.

- [x] MPV does not have this problem.

**How often does this happen?**

Reliably reproducible.

**Comment by yuxiqian** [comment]
Seems `iina-cli` has an option called `--no-stdin` and
```shell
iina <file> --no-stdin < /dev/null
echo hi | iina <file> --no-stdin
```
works for me.

**Comment by zmwangx** [comment]
Ah yes, somehow I didn't see that, thanks. The default behavior and generic error message is still rather confusing, but it's a smaller issue when there's already an option.
