### ISSUE TITLE
RTL: Incorrect arrow icon direction in browser extensions reference

### ISSUE THREAD

**Issue by ShlomoCode** [iina/iina#4950]
**System and IINA version:**

- macOS 14.4.1
- IINA 1.3.4 + PR #4922

**Expected behavior:**

The icon will always point to the text, even in RTL languages such as Hebrew and Arabic.

**Actual behavior:**

Currently IINA does not support any right-to-left languages. However PR #4922 allows Hebrew. If you build IINA with this pull request and set Hebrew as the language, you will notice that the arrows in the browser extension buttons (under the Utils tab in the settings) do not point in the direction of the text (the direction is hard-coded to the right)

![CleanShot 2024-05-23 at 06 21 53@2x](https://github.com/iina/iina/assets/78599753/b11f4265-3b74-4f23-9d9d-2a099762ea09)
![CleanShot 2024-05-23 at 07 03 48@2x](https://github.com/iina/iina/assets/78599753/02c0ba59-3921-430b-a558-7557736ad3b6)

**Steps to reproduce:**

- Open the IINA project in Xcode
- Under the `Product` menu open the Scheme menu and select `Edit Scheme…`
- Click on the `Options` tab
- Scroll down to the `App Language` setting
- In the pull down select `Right-to-Left Pseudolanguage` near the end of the list
- Start IINA running under Xcode
- Open Settings and go to Utils section
- Notice that the arrows are not facing the text

- [x] MPV does not have this problem.

mpv does not support localization.

**How often does this happen?**

Every time.

**Comment by low-batt** [comment]
@ShlomoCode Does it look the same when the system language is Hebrew?

**Comment by ShlomoCode** [comment]
> @ShlomoCode Does it look the same when the system language is Hebrew?

Yes (even after restart)
![CleanShot 2024-05-26 at 06 35 59@2x](https://github.com/iina/iina/assets/78599753/6cdf263f-e805-4418-aa8b-3bd22229b117)

**Comment by low-batt** [comment]
Thanks for checking. I see the problem. I was confused by the terminology. Working on a fix.

**Comment by ShlomoCode** [comment]
![CleanShot 2024-05-26 at 16 03 49@2x](https://github.com/iina/iina/assets/78599753/8fd46d84-fabe-4437-a9f3-f87ce3d5a92b)
The arrows should stay on the right side of the button, just point towards the text and not out. See also https://github.com/iina/iina/pull/4937

**Comment by uiryuu** [comment]
So you mean (Chrome <-) (Firefox <-), am I correct?
![image](https://github.com/iina/iina/assets/20237141/39966855-88a2-49a5-8e41-8507b6882266)
Like this?

**Comment by ShlomoCode** [comment]
Yes

**Comment by ShlomoCode** [comment]
It depends on whether in the particular language the word is translated or left in English... a bit problematic, I agree
If there is no solution to this, forcing the use of the English version will always be a reasonable compromise in my opinion
![a](https://github.com/iina/iina/assets/78599753/db0150af-402d-41ce-a91a-58fdf489071e)

**Comment by ShlomoCode** [comment]
It depends on whether in the particular language the word is translated or left in English... a bit problematic, I agree
If there is no solution to this, forcing the use of the English version will always be a reasonable compromise in my opinion
![a](https://github.com/iina/iina/assets/78599753/cf03ee8d-c910-42aa-ba40-c14b779a44be)

**Comment by ShlomoCode** [comment]
Should this issue be reopened? Otherwise we might miss it...
