### ISSUE TITLE
Text clipping in the audio delay slider

### ISSUE THREAD

**Issue by uiryuu** [iina/iina#4951]
**System and IINA version:**

- macOS 14.5
- IINA 1.3.4

**Expected behavior:**
No text clipping

**Actual behavior:**
Text clipping in the audio delay slider in Chinese localization.

![image](https://github.com/iina/iina/assets/20237141/6aa575a0-7e68-4323-b9a8-b6b375ccb7a3)

**Steps to reproduce:**
Navigate to QuickSettingsPanel -> Audio, observe the slider.

- [x] MPV does not have this problem.

**How often does this happen?**
Always

**Comment by low-batt** [comment]
This was fixed in IINA 1.4.0-beta1.
