### ISSUE TITLE
Incorrect text alignment in the battery icon of the OSD in RTL

### ISSUE THREAD

**Issue by ShlomoCode** [iina/iina#4957]
**System and IINA version:**

- macOS 14.4.1
- IINA 1.3.4 + PR #4922 + PR #4889 or #develop (https://github.com/iina/iina/commit/13d16eb223d50575d931ef68e9561b3730f7163b)

The text inside the battery icon (OSD) should be aligned to the right in RTL 

![CleanShot 2024-05-29 at 03 07 51@2x](https://github.com/iina/iina/assets/78599753/9ec0e12b-07fd-40fd-8cb1-2bc24514de79)

**Expected behavior:**

The text is right aligned

**Actual behavior:**

The text is aligned to the left

**Alternatives I considered:**

Always align to the center

**Steps to reproduce:**

- Open the IINA project in Xcode
- Under the `Product` menu open the Scheme menu and select `Edit Scheme…`
- Click on the `Options` tab
- Scroll down to the `App Language` setting
- In the pull down select `Right-to-Left Pseudolanguage` near the end of the list
- Start IINA running under Xcode
- Enable OSD and "Display time and battery info when in full screen" in setings > UI
- Open some video and go to full screen

- [x] MPV does not have this problem.

mpv does not support localization.

**How often does this happen?**

Every time.

**Comment by ShlomoCode** [comment]
ping @low-batt

**Comment by low-batt** [comment]
The intent is that the text is centered. The constraint that centers the label holding the text in the battery icon has to be offset a bit due to the icon being bigger on one side. That offset was chosen to make 100% look good. But for lower values it was a bit off. I had to change the code to take into account the value and adjust the constraint accordingly. See if you think the result is acceptable.

**Comment by ShlomoCode** [comment]
Looks good now in RTL (and with [this](https://github.com/iina/iina/pull/4971/files/d288305e7d0ef87fb330d5f1cd7b030383635ab7#diff-b8312c82bcc6d0df5f9959c5c375f7c74d2e7acaee358d60841f2c39ad2008a5) looks even more good), but in LTR it's not centered
![CleanShot 2024-06-03 at 17 44 30@2x](https://github.com/iina/iina/assets/78599753/2f265d7d-71dc-4ca7-a0d4-25381d10ea3d)
