### ISSUE TITLE
"Check for update" does not detect new version

### ISSUE THREAD

**Issue by simonbcn** [iina/iina#4968]
**System and IINA version:**

- macOS 14.5 (23F79)
- IINA 1.3.4

I opened IINA today and clicked on `Check for update` but it tells me that there is no new version, even though you released version 1.3.5:

![Captura de pantalla 2024-06-01 a las 8 50 00](https://github.com/iina/iina/assets/428231/e7b4cab9-8781-4061-85d1-2b63a7164143)

**Comment by Moulick** [comment]
Looks like https://iina.io/appcast.xml has not been updated yet.
