### ISSUE TITLE
The compilation date in the debug build in RTL languages seems not rendered correctly

### ISSUE THREAD

**Issue by uiryuu** [iina/iina#4969]
**System and IINA version:**

- macOS 14.5
- IINA 1.3.5

**Expected behavior:**
Correctly rendered

**Actual behavior:**
![image](https://github.com/iina/iina/assets/20237141/7b83d4fd-e9b0-43a1-ab14-5cf35ec63861)

**Steps to reproduce:**
- Use a debug (or nightly) build in Hebrew
- Click "About IINA" in the menu
- Observe the date field

- [x] MPV does not have this problem.

**How often does this happen?**
Always

**Comment by uiryuu** [comment]
We might want to use a time & date formatter to match the system region settings.

**Comment by low-batt** [comment]
I will investigate.

**Comment by low-batt** [comment]
@ShlomoCode This is how the build date looks when formatted by [DateFormatter](https://developer.apple.com/documentation/foundation/dateformatter):
![date](https://github.com/iina/iina/assets/86170219/2b6a76f4-720a-4ebd-95b1-fc6d31125024)

That looks odd to me. How should that date look in Hebrew?

The code that produced that string looks like:
```swift
let toString = DateFormatter()
toString.dateStyle = .medium
toString.timeStyle = .medium
toString.string(from: buildDate)
```

**Comment by ShlomoCode** [comment]
> @ShlomoCode This is how the build date looks when formatted by [DateFormatter](https://developer.apple.com/documentation/foundation/dateformatter): ![date](https://private-user-images.githubusercontent.com/86170219/335826390-2b6a76f4-720a-4ebd-95b1-fc6d31125024.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTIwMDAsIm5iZiI6MTcxNzI5MTcwMCwicGF0aCI6Ii84NjE3MDIxOS8zMzU4MjYzOTAtMmI2YTc2ZjQtNzIwYS00ZWJkLTk1YjEtZmM2ZDMxMTI1MDI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDAxMjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYjQwMmI4NTkwN2U0MjkzZDc2N2RiNDA4MmQzOTMyY2EyNzlkMDIyY2FjZjQyN2JmNWYxZjcyNjVmMzNhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HCz0v7f9XMrCvhWpOtw5t5Va4lMT5FFIXL-XiEt8WwI)
> 
> That looks odd to me. How should that date look in Hebrew?


It's just a lack of RTL
Is it according to the format defined in system settings?

**Comment by ShlomoCode** [comment]
Additional issues in the About window in the "Contributors" tab (the arrows should be reversed like in https://github.com/iina/iina/pull/4958, and the line "powered by Crowdin" should be localizable):
![CleanShot 2024-06-02 at 04 19 12@2x](https://github.com/iina/iina/assets/78599753/a501486c-1450-49c2-abfa-8497c41b6308)

**Comment by ShlomoCode** [comment]
> @ShlomoCode This is how the build date looks when formatted by [DateFormatter](https://developer.apple.com/documentation/foundation/dateformatter): ![date](https://private-user-images.githubusercontent.com/86170219/335826390-2b6a76f4-720a-4ebd-95b1-fc6d31125024.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTIwMDAsIm5iZiI6MTcxNzI5MTcwMCwicGF0aCI6Ii84NjE3MDIxOS8zMzU4MjYzOTAtMmI2YTc2ZjQtNzIwYS00ZWJkLTk1YjEtZmM2ZDMxMTI1MDI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDAxMjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYjQwMmI4NTkwN2U0MjkzZDc2N2RiNDA4MmQzOTMyY2EyNzlkMDIyY2FjZjQyN2JmNWYxZjcyNjVmMzNhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HCz0v7f9XMrCvhWpOtw5t5Va4lMT5FFIXL-XiEt8WwI)
> 
> That looks odd to me. How should that date look in Hebrew?


It's just a lack of RTL
Is it according to the format defined in system settings?

**Comment by low-batt** [comment]
No. It is picking up the `App Language` setting in the Xcode `Scheme`.

How should it look?

**Comment by ShlomoCode** [comment]
> How should it look?

![CleanShot 2024-06-03 at 16 34 35@2x](https://github.com/iina/iina/assets/78599753/5bcf3147-586a-4fee-ae83-e056c0791471)
it's just change back the Text Direction to Natural:
![CleanShot 2024-06-03 at 16 36 24@2x](https://github.com/iina/iina/assets/78599753/b4a3bea9-62fc-4314-ab47-2c72b619cb33)

BTW, I think that a `short` date is more suitable here than the `medium` one. But it is no longer specifically related to language.

**Comment by low-batt** [comment]
I believe the date is correct now in the latest commit.
