### ISSUE TITLE
Unauthorized link to crowdin contributors in IINA's About window

### ISSUE THREAD

**Issue by ShlomoCode** [iina/iina#4972]
In IINA's About window there is a link to https://crowdin.com/project/iina/members 
![CleanShot 2024-06-02 at 04 50 26@2x](https://github.com/iina/iina/assets/78599753/90790ebb-0292-4762-82c2-ce06c097cf24)
That returns a 403 error
![CleanShot 2024-06-02 at 04 52 35@2x](https://github.com/iina/iina/assets/78599753/02effb24-7751-4fd4-a945-b330cf951d13)
Even though I'm logged in to crowdin account.

**System and IINA version:**

- macOS 14.5
- IINA 1.3.5

**Comment by ShlomoCode** [comment]
ping @uiryuu

**Comment by uiryuu** [comment]
It seems Crowdin only lets user see the contributors once they are logged in. So maybe we can change this link to the dashboard page of IINA on Corwdin. Thoughts @lhc70000 ?

**Comment by ShlomoCode** [comment]
> It seems Crowdin only lets user see the contributors once they are logged in.

I'm logged into a Crowdin account, and I contributed to the iina project there, and I don't have access. It appears that only the project menagers (@uiryuu and @lhc70000) have access to this page.

**Comment by uiryuu** [comment]
That makes more sense now. We must change the link.
