### ISSUE TITLE
Feature: Copy current timestamp + keybind

### ISSUE THREAD

**Issue by treiber** [iina/iina#4974]
**Summary:**

Quite simply, have a menu option and optional keybind to copy the current timestamp of any video playing. Could be useful for automation; my needs are video annotations where I often note down the current timestamp as a marker.

**Comment by low-batt** [comment]
It requires a bit of configuration, but you can accomplish this with the current version of IINA. See the discussion in issue #3370. Read through the comments. By the end you can press a key and the time will be in the paste buffer.

**Comment by hugepower** [comment]
To use the `copy_playback_position.lua` script:


1. Place `copy_playback_position.lua` in `~/.config/mpv/scripts/`.
2. Ensure that IINA is configured to use `~/.config/mpv/` as the configuration directory.
3. In IINA’s key binding settings, bind the `n` key to `script-binding copy_position`.
4. Restart IINA to activate the script and the key binding.

Below is the script code. You need to create a `copy_playback_position.lua` file and paste the following content into it.

Once you’ve done this, follow the steps provided to set up the script in IINA. After setting it up, pressing N will copy the playback position to the clipboard.

```lua
-- copy_playback_position.lua
-- Lua script for MPV/IINA to get the current playback position in a customizable format, copy it to the clipboard, and show an OSD message if successful

-- Global variable for time format
-- 全局变量，用于时间格式
local time_format = "[%02d:%02d:%02d]" -- Default format: [HH:MM:SS]

-- Function to format time based on the global format
-- 根据全局格式格式化时间的函数
function format_time(seconds)
    local hours = math.floor(seconds / 3600)
    local minutes = math.floor((seconds % 3600) / 60)
    local secs = math.floor(seconds % 60)
    return string.format(time_format, hours, minutes, secs)
end

-- Get the current playback position
-- 获取当前播放位置
function get_playback_position()
    local position = mp.get_property_number("time-pos") -- Get the playback position in seconds
    if position then
        return format_time(position)
    else
        return "[--:--:--]"
    end
end

-- Copy the playback position to the clipboard and show an OSD message if successful
-- 将播放位置复制到剪贴板，如果成功则显示OSD消息
function copy_to_clipboard()
    -- Get the current playback position
    -- 获取当前播放位置
    local position = get_playback_position()
    
    -- Use echo and pbcopy to copy to clipboard on Unix-based systems
    -- 使用 echo 和 pbcopy 命令在 Unix 系统上复制到剪贴板
    local clipboard_command = "echo '" .. position .. "' | pbcopy"
    local check_command = "pbpaste"
    
    -- Execute the clipboard command
    -- 执行复制到剪贴板的命令
    os.execute(clipboard_command)
    
    -- Check if the clipboard content matches the position
    -- 检查剪贴板内容是否与播放位置匹配
    local handle = io.popen(check_command)
    local clipboard_content = handle:read("*a"):gsub("\n", "")
    handle:close()
    
    -- Show OSD message based on the check
    -- 根据检查结果显示OSD消息
    if clipboard_content == position then
        mp.osd_message("Copied to clipboard: " .. position, 2) -- Display message for 2 seconds
        -- 显示成功复制的消息，持续2秒
    else
        mp.osd_message("Failed to copy to clipboard", 2) -- Display failure message for 2 seconds
        -- 显示复制失败的消息，持续2秒
    end
end

-- Bind the `n` key to copy the playback position and show an OSD message if successful
-- 将`n`键绑定到复制播放位置并显示OSD消息（如果成功）的函数
mp.add_key_binding("n", "copy_position", copy_to_clipboard)
```

<img width="958" alt="Screenshot 2024-08-26 at 10 38 06" src="https://github.com/user-attachments/assets/3b62ed9c-ed90-4678-9b59-58b3653803e4">

**Comment by hugepower** [comment]
After pressing the N key, the playback position timestamp will be copied to the clipboard in the format [HH:MM:SS], and an on-screen display (OSD) notification will show the copied timestamp.

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/ece8ab8f-4f1d-44bb-a471-3c20c4a72d18">

**Comment by low-batt** [comment]
Nice and self contained. Significantly better than the solution in #3370.

**Comment by treiber** [comment]
This works like a charm, thank you so much @hugepower!

I've adjust my script to output [MM:SS] only, if the timestamp is below one hour by checking for it in the `format_time` function.
```lua
-- Function to format time based on the global format
function format_time(seconds)
    local hours = math.floor(seconds / 3600)
    local minutes = math.floor((seconds % 3600) / 60)
    local secs = math.floor(seconds % 60)

    if hours > 0 then
        -- Format as HH:MM:SS for timestamps greater than 1 hour
        return string.format(time_format, hours, minutes, secs)
    else
        -- Format as MM:SS for timestamps less than 1 hour
        return string.format("[%02d:%02d]", minutes, secs)
    end
end
```
