### ISSUE TITLE
IINA displays malformed quick settings panel

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4980]
**System and IINA version:**

- macOS 13.6.3
- IINA `develop` @ 6ad1d323eb9d10afd3b159b78db7d32b345d1353

**Expected behavior:**
Quick settings panel is displayed correctly.

**Actual behavior:**
IINA initially displays this for the quick settings panel:
![panel](https://github.com/iina/iina/assets/86170219/c87f0708-38a3-4ff4-a407-41d2f29bfe9a)

If I then close the panel and reopen it the panel displays normally.

This is a regression in the `develop` branch, not in a released version of IINA.

**Steps to reproduce:**

- Start IINA playing a video
- Click on the OSC button to show the quick settings panel
- The panel is displayed incorrectly
- Click outside of the panel to close the panel
- Click on the OSC button to show the quick settings panel
- The panel is displayed correctly

- [x] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by svobs** [comment]
Can't seem to reproduce this using develop @ 8a716a7a096ca4ef2430f15d9d4f629c35bcc95b, MacOS 14.4.1. Everything looks fine. Tried with `Reduce Motion` on too, and with "floating" and "bottom" OSCs, respectively.

**Comment by low-batt** [comment]
I can reproduce, so I'll take this one.

**Comment by low-batt** [comment]
As you warned me, there are problems lurking with respects to fading transitions.
