### ISSUE TITLE
OSD battery and time message displayed without information

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4985]
**System and IINA version:**

- macOS 13.6.3
- IINA `develop` at cb85732ae830fa8698820527fab2b686c2b38e6a

**Expected behavior:**
OSD battery and time message is not malformed.

**Actual behavior:**
The OSD is displayed missing information:
![battery](https://github.com/iina/iina/assets/86170219/0f6b3086-b4d7-4fcc-b618-7ff85ee59108)

If you start the video playing the OSD will be updated with the information.

This does not occur with IINA 1.3.5. The OSD is displayed with the information before playback is started.

<br>

**Steps to reproduce:**
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- Click on the `When media is opened` disclosure triangle
- Enable the `Pause` setting
- On the left side of the panel click on `UI`
- In the `On Screen Display` section enable the `Display time and battery info when in full screen`
- Open a video
- Under the `Video` menu click on `Enter Full Screen`
- Observe the OSD is shown missing information

- [x] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by low-batt** [comment]
This regression was introduced by commit 95966df8790a90b800e56f2234781c560935a5df.
@svobs Can you take this one?

**Comment by svobs** [comment]
> @svobs Can you take this one?

Ah, sorry! Did not notice this one until now. Will try to actively check my "mentions" list going forward…

When I cherry-picked the changes from my fork, I forgot to account for this project having separate windows for both normal windowed mode & for music mode, instead of the single window used by my project. @uiryuu thanks for picking up the fix.

**Comment by low-batt** [comment]
@svobs No problem. I would have eventually noticed and reminded you.

I remember you working on a PR that would add an `Enable OSC` similar to the setting we have for the OSD? I remember there were concerns about it being tied into the title bar. I think it is fine if the disabling the OSC also disables the title bar. The use case is people running a loop in a kiosk. They don't want any controls or notifications to pop up.

Anyway, `develop` now has a setting to disable hiding the OSC. Would be nice to also have the opposite setting in this release and be able to disable the OSC.

**Comment by svobs** [comment]
@low-batt I remember `Enable OSC`. I'll work on it next. Will shoot for getting it done by July 15. I think I might split it into 2 [stacked](https://newsletter.pragmaticengineer.com/p/stacked-diffs) PRs: 1 for the actual feature + 1 to add support for it in the Settings UI. I'm still pondering some things about the latter's implementation which might be best addressed independently.

**Comment by low-batt** [comment]
This was fixed in IINA 1.4.0-beta1.
