### ISSUE TITLE
Make current Magic Mouse seekbar control work everywhere

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [iina/iina#4987]
**What you want IINA to do:**

When one gestures an horizontal slide on the Magic Mouse when cursoring over the seekbar, the video begins to seek. However, the native behaviour of macOS is that this works at all times when hovering over the video, and not just when one hovers over the seekbar.

**Examples of other projects that have something similar:**

If one previews a video on Finder with the spacebar it works as I suggest.

**Comment by svobs** [comment]
I don't own a Magic Mouse, but based on Apple's docs it sounds like the behavior should be similar to the Magic Trackpad. Can you confirm that `Settings…` > `Control` > `Scroll horizontally to:` is set to `Seek`, yet it's not possible to horizontally scroll when hovering inside the window?

**Comment by 2V3EvG4LMJFdRe** [comment]
Wow. How long has that been there for? I must've gone through settings a number of times on an admittedly much older iteration of IINA. Yes, you're right, that setting does what the ticket asks for, and it even includes further settings for the speed. I will mark this issue as solved!
