### ISSUE TITLE
add Show in Finder menu command

### ISSUE THREAD

**Issue by vassudanagunta** [iina/iina#5001]
**What you want IINA to do:**

- Conveniently show the currently playing media's file in the Finder via menu command.
 
- Even more conveniently do so with a keyboard shortcut. 

Of the two, I think the keyboard shortcut is more important, so I'd be happy with that without the menu item. I vote for a default keyboard shortcut of `⌘R`.

**What IINA does currently:**

The only way that I can find to do this is by showing the playlist, right-click the item, and choose `Show in Finder`. It is a pain, and  it is not keyboard-shortcut-able.

One can right-click on the filename in the titlebar, then click on the containing folder in the dropdown that appears, but this is also inconvenient and not keyboard-shortcut-able.

**Why you think this should be added:**

It's a common need. 

IINA has a `File:Delete Current File` command, so it seems odd that the more general ability to do whatever you want with the file via the Finder is missing.

**Examples of other projects that have something similar:**

Many apps have such a menu command, though named differently:

`Show in Finder`: XCode, macOS Dock, BBEdit
`Reveal in Finder`: Sublime, Transmission, VLC
`Open in Finder`:  Jetbrains IDEs
`Open File Location`: Typora

**Comment by low-batt** [comment]
Nice clear writeup of requested feature!

**Comment by vassudanagunta** [comment]
It's the very least i can do for all the good work y'all do. I'd contribute directly if I was a Swift/C programmer.

**Comment by ShlomoCode** [comment]
I'm not a Swift developer (developer in other languages) but this seems like an easy task. I will try to work on it :)

**Comment by low-batt** [comment]
Support was added in IINA 1.4.0-beta1.
