### ISSUE TITLE
HistoryController uses deprecated methods

### ISSUE THREAD

**Issue by low-batt** [iina/iina#5004]
**System and IINA version:**

- macOS 13.6.3
- IINA `develop` at 2ed5d72568eac27aba57685686b48b8c88dd1834

**Expected behavior:**
As much as possible building IINA does not generate compiler warnings.

**Actual behavior:**
Building with Xcode 15.2 generates a number of new warnings since the `MACOSX_DEPLOYMENT_TARGET` setting was raised to 10.15. This issue is only about the following two warnings:
```text
/Users/low-batt/Documents/builds/iina-official/iina/iina/HistoryController.swift:27:34 'unarchiveObject(withFile:)' was deprecated in macOS 10.14: Use +unarchivedObjectOfClass:fromData:error: instead

/Users/low-batt/Documents/builds/iina-official/iina/iina/HistoryController.swift:31:34 'archiveRootObject(_:toFile:)' was deprecated in macOS 10.14: Use +archivedDataWithRootObject:requiringSecureCoding:error: and -writeToURL:options:error: instead
```

The compiler is flagging use of the deprecated methods [NSKeyedUnarchiver.unarchiveObject(withFile:)](https://developer.apple.com/documentation/foundation/nskeyedunarchiver/1417153-unarchiveobject) and [NSKeyedArchiver.archiveRootObject(_:toFile:)](https://developer.apple.com/documentation/foundation/nskeyedarchiver/1410621-archiverootobject). Apple has deprecated these methods in order to encourage conformance to [NSSecureCoding](https://developer.apple.com/documentation/foundation/nssecurecoding) which protects against object substitution attacks.

Correcting these warnings requires changing `PlaybackHistory` to implement [NSSecureCoding](https://developer.apple.com/documentation/foundation/nssecurecoding) and then changing the methods in `HistoryController` that read and save history. I believe this will require the history database to be migrated.

**Steps to reproduce:**
Perform a full clean build of the `develop` branch.

- [x] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by svobs** [comment]
> Correcting these warnings requires changing PlaybackHistory to implement [NSSecureCoding](https://developer.apple.com/documentation/foundation/nssecurecoding) and then changing the methods in HistoryController that read and save history. I believe this will require the history database to be migrated.

Is the goal to migrate to secure coding, or just to get rid of the warnings? Here are the changes I made to do the latter: 8e11e11355850b852418a35d44924fea907ddccd

**Comment by low-batt** [comment]
Since we are being forced to touch it I think we should adhere to secure coding as that is a good thing to do. The changes in that commit are part of what is needed. I have some of the changes needed for secure coding. It is looking like that won't require database migration and should not be hard to implement. I am doing some testing at the moment.

**Comment by low-batt** [comment]
@svobs By the way, the big `mpv` / FFmpeg upgrade was just merged. You will need to download new libs once you pull `develop`.

**Comment by low-batt** [comment]
@svobs Please have a look at the proposed fix. I used some of the changes from your commit and added code to support secure coding.
