### ISSUE TITLE
IINA stucks if some recently played items are on disconnected network drives

### ISSUE THREAD

**Issue by vinhtq115** [iina/iina#5043]
**System and IINA version:**

- macOS 14.5
- IINA 1.3.5

**Expected behavior:**
IINA starts normally.

**Actual behavior:**
IINA hangs when starting (Application not responding). It also attempts to access the disconnected network drives. (I saw Finder popped up some error dialogue about unable to access the disconnected network drives as it is unavailable).

<img width="372" alt="Screenshot 2024-07-03 at 14 16 53" src="https://github.com/iina/iina/assets/34190240/66815267-f25e-4484-8f70-364d6c50b0ce">

**Steps to reproduce:**
1. Open some files on network drives.
2. Exit IINA.
3. Disconnect the network drives.
4. Open IINA.

**How often does this happen?**
Frequently when network drives are disconnected. Perhaps the network drives are not on the same LAN network too? (This happens to me most of the time when I'm not at home, where my network drives are located)

**Notes**
This can be fixed by mounting the network drives, open IINA (which will start normally), delete all the history. After doing this and disconnecting the drives, IINA works perfectly fine when being opened.

**Comment by uiryuu** [comment]
Duplicated of https://github.com/iina/iina/issues/4973
