### ISSUE TITLE
Disabling pitch correction when slowing down a video

### ISSUE THREAD

**Issue by supahfox** [iina/iina#5052]
Is this already a feature? Because I couldn't really get it to work, even in the advanced settings tab

IINA 1.3.5 Build 141
macOS Sonoma 14.5

**Comment by low-batt** [comment]
I believe this is doable with advanced advance configuration…

The behavior in question comes from the [mpv](https://github.com/mpv-player/mpv) [audio-pitch-correction](https://mpv.io/manual/stable/#options-audio-pitch-correction) option:
> **--audio-pitch-correction=<yes|no>**
>    If this is enabled (default), playing with a speed different from normal automatically inserts the `scaletempo2` audio filter. You can insert filters besides scaletempo2 and modify their params using _Conditional auto profiles:_

Using conditional auto profiles requires using a mpv config file. Look for the `Use config directory` setting at the bottom of the `Advanced` tab in IINA's settings.

Follow that link to the mpv manual for an example of a conditional auto profile. If you have trouble getting that to work search the net for mpv and conditional auto profile and I'm sure you will find examples.

**Comment by supahfox** [comment]
Worked, tysm! 

[af_insert]
profile-cond=speed ~= 1
profile-restore=copy
af-add=scaletempo2=search-interval=50
audio-pitch-correction=no

**Comment by low-batt** [comment]
Glad you were able to get it to work. Thanks for checking back in, posting results and closing the issue. Very helpful.
