### ISSUE TITLE
Inconsistent grammar of "music mode"

### ISSUE THREAD

**Issue by svobs** [iina/iina#5076]
**System and IINA version:**

- macOS 14.5
- IINA post-1.3.5 develop, 9f14c3c468c12ff84d1655bf5ea7b6c69d2a8161

**Expected behavior:**

Use `"music mode"` everywhere to refer to the feature.

**Actual behavior:**
`Not while in Music Mode or only playing audio`
<img width="1041" alt="SCR-20240716-cdyu" src="https://github.com/user-attachments/assets/26f47108-6be8-4462-bcd4-8ad50ac57e99">

Maybe `Music Mode` would be better than `"music mode"`? But the pattern has already been set.

Also, while playing the role of grammar police: the text would be "more correct" if it maintained parallel structure between clauses, e.g.: `Not while in "music mode" or when only playing audio`. But that's arguably less important than keeping a consistent naming scheme.

**Comment by low-batt** [comment]
An embarrassingly obvious mistake by me. I will change the new text to use lowercase in double quotes. Thanks for catching this.
