### ISSUE TITLE
Settings window is still called "Preferences" in some strings

### ISSUE THREAD

**Issue by svobs** [iina/iina#5092]
**System and IINA version:**

- macOS 14.5
- IINA post-1.3.5 `develop` branch, 108c93c3860be882546ea8c95cfa668aa5b565b4

**Expected behavior:**

Preferences window is referred to as `Settings` in all user-facing text.

**Actual behavior:**

<img width="759" alt="SCR-20240726-sykn" src="https://github.com/user-attachments/assets/e65dbe5c-a16e-4640-ad61-2936a8c90b41">

In Localizable.strings:
1. ❌ `"preference.title" = "Preferences";` (see screenshot above). Also see base string in `MainMenu.xib`.
2. ❌ `"alert.sub_lang_not_set" = "Please set preferred subtitle languages in preferences before using OpenSubtitles. English(eng) will be used this time."` (also not uppercase here)
3. ❌ `"alert.duplicated_plugin_id" = "Duplicated plugin identifiers detected. Two or more plugins have the same identifier \"%@\". This may cause abnormal behaviors. Please find them in Preferences - Plugins and report to their authors. If a plugin is installed locally, you can also manually change its identifier in the plugin's Info.json file.";`

**Comment by low-batt** [comment]
Duplicate of #4038, although this issue lists specific instances not mentioned in that issue. Issue #4038 is on the schedule for beta 2. Fine to address it in beta 1. This should be fixed such that "Preferences" is still used on the old macOS versions.

**Comment by svobs** [comment]
> Duplicate of https://github.com/iina/iina/issues/4038, although this issue lists specific instances not mentioned in that issue. Issue https://github.com/iina/iina/issues/4038 is on the schedule for beta 2. Fine to address it in beta 1. This should be fixed such that "Preferences" is still used on the old macOS versions.

Oh yes, I do remember that issue, but did not see your [latest comment](https://github.com/iina/iina/issues/4038#issuecomment-2155787122). I did a quick search for that issue before filing this but did not search hard enough. I'll close this issue and just leave a comment in #4038.
