### ISSUE TITLE
Playback menu mostly disabled

### ISSUE THREAD

**Issue by low-batt** [iina/iina#5093]
**System and IINA version:**

- macOS 13.6.3
- IINA `develop` @ 108c93c3860be882546ea8c95cfa668aa5b565b4

**Expected behavior:**
The `Playback` menu functions properly.

**Actual behavior:**
Many items on the `Playback` menu are disabled:
![playback](https://github.com/user-attachments/assets/bd6882af-ee9b-4b1b-a0ee-da0a79db0844)

**Steps to reproduce:**
- Start a copy of IINA built from `develop`
- The `Welcome` window appears
- Do not start playing a video
- Open the `Playback` menu
- Most of the menu items are disabled, as expected
- Start playing a video
- Open the `Playback` menu
- Most of the menu items are still disabled

From a quick investigation this does not reproduce when IINA is built from `develop` @ b9d8ca4d9db3e182946e7c649617b0e043e76168. It is reproducible starting with commit c59d75090588460e4acca21376cceb91cbeede4c.

- [x] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by uiryuu** [comment]
Bisected and confirmed this bug was due to #5005 by @ShlomoCode. `validateMenuItem` should return true instead of preserving their previous states. Fixed in https://github.com/iina/iina/commit/bbb17c24ca3053a82ded2e30c7cc43cf781fac5b
