### ISSUE TITLE
RTL language causes audio equalizer knobs to disappear

### ISSUE THREAD

**Issue by low-batt** [iina/iina#5110]
**System and IINA version:**

- macOS 13.6.3
- IINA `develop` @ 3cde0e11a07ea9f266692be48d1933f640a214c6

**Expected behavior:**
Audio equalizer knobs are equally spaced and are not partially drawn.

**Actual behavior:**
When the language is set to Hebrew spacing between the knobs is not equal and some knobs are partially drawn:
![eq](https://github.com/user-attachments/assets/66f0c88f-b975-492e-a1c7-ad279d57a428)

**Steps to reproduce:**
- Open the IINA project in Xcode 
- Under the `Product` menu open the `Scheme` menu and select `Edit Scheme…`  
- Click on the `Options` tab
- Scroll down to the `App Language` setting
- In the pull down select `Hebrew`
- Start IINA running under Xcode
- Start playing a video
- Press ⇧⌘A to show the audio panel
- Notice the sliders are not equally spaced and some knobs are partially drawn in the `Equalizer` section

- [x] MPV does not have this problem.

mpv does not support localization.

**How often does this happen?**
Every time.

**Comment by svobs** [comment]
Try selecting all the vertical sliders & add Equal Width constraints between them all.
Then change the Content Hugging Priority of `+12 dB Text Field` to 1000.

**Comment by uiryuu** [comment]
@svobs Tried your solution, and it works, thanks!
