### ISSUE TITLE
IINA freezes randomly during video playback

### ISSUE THREAD

**Issue by AndDevDE** [iina/iina#5115]
**System and IINA version:**

- macOS 15.0 Beta (24A5298h)
- IINA 1.3.5 Build 141

**Expected behavior:**

Video plays until it ends.

**Actual behavior:**

After a few minutes of playback, the video freezes, program doesn't respond and you have to force quit.
Audio playback still continues while program is frozen!

<br>

**Steps to reproduce:**

Open .mp4 file and watch for a few minutes with same IINA and MacOS version.

- [ ] MPV does not have this problem.

**How often does this happen?**

Every video I tried to watch showed this issue.

**Comment by subhashhhhhh** [comment]
happening same with me ever since i updated to sequoia developer beta

**Comment by low-batt** [comment]
24A5298h identifies this as [macOS 15 beta 4](https://developer.apple.com/news/releases/?id=07232024j). Apple has introduced a regression in Beta 4 that is causing trouble for various players. This is being discussed in issue #5088.
