### ISSUE TITLE
Audio EQ loses a decimal of precision

### ISSUE THREAD

**Issue by svobs** [iina/iina#5120]
**System and IINA version:**

- macOS 14.6
- IINA develop 3cde0e11a07ea9f266692be48d1933f640a214c6

**Expected behavior:**

2 decimals of precision for each audio EQ slider.

**Actual behavior:**

Discovered this while debugging. The "lavfi" filter params are incorrectly parsed and don't account for the `]` in the last filterchain. But the code uses `dropLast()` on all the filterchains which causes each `g` filter (except the last) to lose one digit of precision.

<img width="656" alt="SCR-20240808-baqi" src="https://github.com/user-attachments/assets/1c4d77b0-63d7-4355-8057-a4c0eb5fde72">

Adding the following logging revealed the bad outcome:

<img width="742" alt="SCR-20240808-bbtj" src="https://github.com/user-attachments/assets/53d7790e-4e29-470c-81b8-eeb35a621b17">

**How often does this happen?**

Always

**Comment by svobs** [comment]
It looks like one solution might be not to use `filter.stringFormat` but instead use `filter.params["graph"]` and then strip the brackets. It looks like the "graph" param is a pseudo-param introduced by IINA as a kludge ("special tweak for lavfi filters") to add support for ordered params with the same name, which weren't otherwise possible with the existing `params` dictionary, but the kludge was also not well documented. (Ideally the parsing code should be entirely rewritten...)

**Comment by uiryuu** [comment]
I pushed a fix, it should fix the issue, please try out

**Comment by svobs** [comment]
> I pushed a fix, it should fix the issue, please try out

I tested 04c619311644f9f0a69d2a07e6edfbfdb67cb4a9 and it looks fixed. Great!

At first I tried out 58af397b5597580a6795605f4667dc523d131341 but I think something is wrong with it. When I drag & drop a media file into the Welcome window, it usually (but not always) quits the app.

> It looks like the "graph" param is a pseudo-param introduced by IINA as a kludge

I dug into this more deeply and learned that `graph` is actually an mpv kludge, not an IINA kludge 😂 my apologies to whoever wrote that part of the code.

**Comment by uiryuu** [comment]
Thank you for testing out these rusty commits. https://github.com/iina/iina/commit/58af397b5597580a6795605f4667dc523d131341 is indeed pretty risky since it touches the logic when loading windows.

> When I drag & drop a media file into the Welcome window, it usually (but not always) quits the app.

I couldn't reproduce this issue. Can you give more detailed steps to reproduce? And is that a crash? What did the logs say?

**Comment by svobs** [comment]
> I couldn't reproduce this issue. Can you give more detailed steps to reproduce? And is that a crash? What did the logs say?

@uiryuu I filed a new issue for it. See #5122.

**Comment by svobs** [comment]
Also looks like you left a line of test code in the commit (`print(gain)`) which you probably want to remove. I'm closing this issue though as it's now fixed.
