### ISSUE TITLE
IINA sometimes quits when video file dropped onto Welcome window

### ISSUE THREAD

**Issue by svobs** [iina/iina#5122]
**System and IINA version:**

- macOS 14.6
- IINA develop 950b8bc809f174b35a42ce720ed318ccd8b6c1fe

- [x] MPV does not have this problem.

**Expected behavior:**
Dropping a video file onto the Welcome window should open the file.

**Actual behavior:**
Sometimes IINA quits instead of opening the file.

[iina.log](https://github.com/user-attachments/files/16571067/iina.log)
[mpv.log](https://github.com/user-attachments/files/16571068/mpv.log)

**Steps to reproduce:**

1. Configure IINA to "Show welcome window at launch" and "Quit after all windows are closed" as shown. <img width="626" alt="SCR-20240810-nyak" src="https://github.com/user-attachments/assets/aefa2e8b-2660-4e9d-829d-8630f2c920de">
3. Reopen IINA so that the Welcome window is shown.
4. Drag a video file from the Finder into the list in the Welcome window.
5. See if IINA quits instead of opening the file. If it opens successfully, quit manually and then repeat the above steps.

<br>

**How often does this happen?**
More than half the time.

**Comment by low-batt** [comment]
Reproduced for me. This is the code that is deciding to terminate IINA:
```swift
func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    guard PlayerCore.active.mainWindow.loaded || PlayerCore.active.initialWindow.loaded else { return false }
    guard !PlayerCore.active.mainWindow.isWindowHidden else { return false }
    return Preference.bool(for: .quitWhenNoOpenedWindow)
  }
```

This code thinks neither the initial window nor the active window are loaded.

**Comment by low-batt** [comment]
I see what the problem is. Working on a fix.
