### ISSUE TITLE
Simplified Chinese subtitles

### ISSUE THREAD

**Issue by JEafjopa** [iina/iina#5126]
Why are the simplified Chinese subtitles in square shape, but other subtitles are fine? I downloaded the latest inna version again, but it's still the same. My macos is version 15beta

**Comment by JEafjopa** [comment]
like this
![Uploading 截屏2024-08-12 01.23.00.png…]()

**Comment by uiryuu** [comment]
See https://github.com/iina/iina/issues/5072: try to update to the latest beta.
