### ISSUE TITLE
Chinese subtitles error

### ISSUE THREAD

**Issue by elsword50716** [iina/iina#5164]
As the pic shows, it became squares.
The subtitle is Chinese Traditional (SUBRIP), also error in Chinese Simplified

**System and IINA version:**

- macOS 15.0 Beta（24A5331b）
- IINA 1.3.5 Build 141 

![Xnip2024-09-03_23-05-36](https://github.com/user-attachments/assets/c9db480e-92b0-4af1-9e99-0645d22fba67)

**Comment by the-eric-kwok** [comment]
Workaround: Change the subtitle font to a Chinese font other than PingFang, and it will render normally.

**Comment by elsword50716** [comment]
> Workaround: Change the subtitle font to a Chinese font other than PingFang, and it will render normally.

But my font  is Helvetica Neue, I think it's something wrong with the OS version.
After I update to 15.1 beta, the problem solved.

**Comment by low-batt** [comment]
I was going to suggest checking the font using [Font Book](https://support.apple.com/guide/font-book/install-and-validate-fonts-fntbk1000/mac). Too late now that it is working.

If the subtitle is an external file and you can post it in this issue I will see how it reacts on my Mac.

**Comment by elsword50716** [comment]
> I was going to suggest checking the font using [Font Book](https://support.apple.com/guide/font-book/install-and-validate-fonts-fntbk1000/mac). Too late now that it is working.
> 
> If the subtitle is an external file and you can post it in this issue I will see how it reacts on my Mac.

It’s soft subtitles in the MKV file. I think it should be the same subtitles as in #5072, but in Traditional Chinese.
The app “Fileball” has this bug, and it was also fixed by updating the OS.
#5072 was also resolved by updating the OS version.
Thanks for your help! 👍

**Comment by low-batt** [comment]
I had vaguely remembered there was some similar issue and had gone looking for it with no luck. It was #5072 I was thinking of. I missed it because it was not labeled. Glad you found it.

Sorry for all the trouble! I will close this issue as a macOS defect.

**Comment by 930727fre** [comment]
Fix:
▎ 1. Open Font Book (⌘+Space → "Font Book")
▎ 2. Search for PingFang or Heiti
▎ 3. If shown as disabled (greyed out), right-click → Enable
▎ 4. No app restart needed — IINA / VLC pick it up immediately
