### ISSUE TITLE
playlist-shuffle doesn't shufle playlist

### ISSUE THREAD

**Issue by julesallen** [iina/iina#5165]
**System and IINA version:**

- macOS 14.5 (23F79)
- IINA 1.3.5 Build 141

**Expected behavior:**
`playlist-shuffle` should re-sort playlist in a random order from within the app. Invoking `iina-cli --mpv-shuffle .` works fine.

**Actual behavior:**
Doesn't do this in the app.

**Steps to reproduce:**
Attempt to shuffle playlist with a keystroke.

**How often does this happen?**
Always

**Comment by julesallen** [comment]
Looks like this is underway!

https://github.com/iina/iina/pull/5024

**Comment by low-batt** [comment]
Thanks for tracking that down and closing this issue. Very appreciated.

**Comment by julesallen** [comment]
Sorry I didn't catch it before opening a new ticket. Really enjoying the
snappiness of this wonderful project, thanks to all!
