### ISSUE TITLE
Missing controls to adjust secondary subtitles

### ISSUE THREAD

**Issue by ronliu** [iina/iina#5181]
There were controls to adjust secondary subtitles added in https://github.com/iina/iina/pull/5020 to address issue https://github.com/iina/iina/issues/4009, but for some reason those controls seem to have gone missing.

**Comment by low-batt** [comment]
Are you using IINA 1.3.5?  The changes have been merged to the `develop` branch. They are not in a released version of IINA.

GitHub views issues as tasks for developers and will automatically close an issue when an associated pull request is merged.  Last I looked GitHub did not allow you to override this behavior. If I am involved I will usually re-open an issue as an indication that the change in not yet in a released version of IINA.

**Comment by ronliu** [comment]
Oh I am on 1.3.5 — did not realize this feature was not released yet. That explains it thank you!

**Comment by low-batt** [comment]
Sorry about the confusion! I will go ahead and close this issue.

IINA is currently working on towards the first Beta release of the long discussed "feature" release. Part of that involves upgrading the version of `libmpv` to 0.38.0. That upgrade adds the backend support for additional secondary subtitle control options. So IINA is adding UI for these new controls.

A lot of the work planned for the first Beta release has been completed, but there is still work to do to finish the changes planned for Beta 1.
