### ISSUE TITLE
Option to Disable Media Control for IINA

### ISSUE THREAD

**Issue by 612aidan** [iina/iina#5193]
**What you want IINA to do:**
I would like IINA to have an option in settings to disable it from using media controls on the keyboard. 

**Why you think this should be added:**
I listen to music as I work. But when I need to reference a video file, I pause my music to listen to the video. To do so, I pause the music using the pause button on my keyboard. When I'm done with the video file, I hit the x to close and try to press the play button on my keyboard to resume the music. But IINA is still registered as the main audio, so it tries to pause and unpause the media that was previously played on IINA.

**Examples of other projects that have something similar:**
In Google Chrome, there is the option to remove media control for YouTube and other media. I have that setting, so my play/pause button only works on my music.

**Comment by svobs** [comment]
Try un-checking this checkbox in `Settings…`, then restarting IINA.
<img width="932" alt="System Media Control checkbox" src="https://github.com/user-attachments/assets/e60b325c-dbdd-4dde-859e-43bcfd63632b">

**Comment by 612aidan** [comment]
Welp, I am just dumb haha

When I looked in the key binds menu I was looking through the configuration and completely overlooked that check box. Sorry for wasting your time with this!

And thanks for your help!

**Comment by svobs** [comment]
No problem :)
