### ISSUE TITLE
Video is paused after open the video file when the audio settings checked S/PDIF output "DTS" or "DTS-HD"

### ISSUE THREAD

**Issue by yangwudong** [iina/iina#5196]
**System and IINA version:**

- macOS: 14.7
- IINA: 1.3.5 Build 141

**Expected behavior:**
Given a video file (e.g. mkv or mp4), IINA has the audio settings checked S/PDIF output "DTS" or "DTS-HD" and IINA is not open,
When open this video file,
Then this video can start play directly with correct display and sound output.

**Actual behavior:**
The video can't play, the window can show the first frame of the video and the player state is "playing" as below, but the display and sound are both paused.

<img width="462" alt="image" src="https://github.com/user-attachments/assets/a520462b-878b-4e0d-b654-271090fbb746">

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
When check on the audio settings for S/PDIF output is "DTS" or "DTS-HD" and then quit the app, and then open a video file, this bug can be reproduced.

Pass settings:
<img width="1212" alt="pass" src="https://github.com/user-attachments/assets/00b8afc7-cdde-4874-860c-1a6d759f898b">

Failure settings:
<img width="1239" alt="failure" src="https://github.com/user-attachments/assets/d37ede8f-0b6b-4639-80c9-08931fcafc77">

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by low-batt** [comment]
Thank you for the excellent clear report.

Please have a look at issue #5161. I think that is the issue you are encountering. See if you agree.

The root cause of #5161 is mpv issue https://github.com/mpv-player/mpv/issues/8403. IINA has to wait for the mpv project to fix that regression.

**Comment by yangwudong** [comment]
yes, I believe they are same and thanks for sharing the progress.
