### ISSUE TITLE
Incorrect percent encoding under Sequioa

### ISSUE THREAD

**Issue by koitococo** [iina/iina#5205]
**System and IINA version:**

- macOS 15.0.1
- IINA 1.3.5

**Actual behavior:**

As described in issue #4861, the url may be encoded twice. PR #4860 was supposed to fix this, and it worked well in Sonoma. However, the issue has regressed in Sequoia.

**Steps to reproduce:**

- Enable logging in IINA
- Open `/[lorem] ipsum.mp4` for example
- Check logs of above actions, and get incorrectly encoded url

- [x] MPV does not have this problem.

**How often does this happen?**

Occurs consistently in Sequoia.

**Comment by low-batt** [comment]
Didn't reproduce for me.

I tried opening `iina://weblink?url=https://example.com/[lorem] ipsum.mp4` in Firefox.

IINA 1.3.5 under macOS 15.0:
```text
22:34:18.050 [iina][d] Parsing URL iina://weblink?url=https://example.com/%5Blorem%5D%20ipsum.mp4
22:34:18.050 [player0][d] Open URL: https://example.com/%5Blorem%5D%20ipsum.mp4
22:34:18.051 [player0][d] Opening https://example.com/%5Blorem%5D%20ipsum.mp4 in main window
```

IINA 1.3.5 under macOS 13.6.9:
```text
22:26:33.619 [iina][d] Parsing URL iina://weblink?url=https://example.com/%5Blorem%5D%20ipsum.mp4
22:26:33.619 [player0][d] Open URL: https://example.com/%5Blorem%5D%20ipsum.mp4
22:26:33.619 [player0][d] Opening https://example.com/%5Blorem%5D%20ipsum.mp4 in main window
```

Can you provide some more details about how you are triggering the problem and what you are seeing in the log file?

I notice you are running macOS 15.0.1. I've been busy and have not upgraded to 15.0.1. I'll try and find time to update my Sequoia machine.

**Comment by koitococo** [comment]
When use opening link `iina://weblink?url=https://example.com/[lorem] ipsum.mp4` in chromium, the encoding is correct:

```
13:02:06.671 [iina][d] Parsing URL iina://weblink?url=https://example.com/%5Blorem%5D%20ipsum.mp4
13:02:06.671 [player0][d] Open URL: https://example.com/%5Blorem%5D%20ipsum.mp4
13:02:06.671 [player0][d] Opening https://example.com/%5Blorem%5D%20ipsum.mp4 in main window
```

But when open url `https://example.com/[lorem] ipsum.mp4` in IINA UI `Open URL` , the bug did reproduce:

```
13:02:44.336 [iina][d] Menu - Open URL
13:02:51.740 [player0][d] Open URL: https://example.com/%5Blorem%5D%2520ipsum.mp4
13:02:51.740 [player0][d] Opening https://example.com/%5Blorem%5D%2520ipsum.mp4 in main window
```

**Comment by low-batt** [comment]
Thanks! Reproduced using `https://example.com/[lorem] ipsum.mp4` and opening directly in IINA using `Open URL…`.

Broken in IINA 1.3.5 under macOS 15.0:
```text
03:02:58.695 [iina][d] Menu - Open URL
03:03:12.311 [player0][d] Open URL: https://example.com/%5Blorem%5D%2520ipsum.mp4
03:03:12.311 [player0][d] Opening https://example.com/%5Blorem%5D%2520ipsum.mp4 in main window
```

Correct in IINA 1.3.5 under macOS 13.6.9:
```text
03:08:50.934 [iina][d] Menu - Open URL
03:09:01.781 [player0][d] Open URL: https://example.com/%5Blorem%5D%20ipsum.mp4
03:09:01.782 [player0][d] Opening https://example.com/%5Blorem%5D%20ipsum.mp4 in main window
```
