### ISSUE TITLE
IINA crashes when saving audio equalizer presets got cancelled

### ISSUE THREAD

**Issue by yuxiqian** [iina/iina#5210]
### IINA Version

IINA Nightly 50f4aab

### Release Channel

Release

### macOS Version

macOS Sequoia 15.1

### Steps to Reproduce

1. Launch IINA and play a random video
2. Open "Quick Settings" Panel and switch to "Audio" Tab
3. Adjust the Equalizer sliders and click "Save the current EQ as a preset" command in the pop-up menu, but click "Cancel" in the prompt window (not to create a new preset)

Now the equalizer pop-up menu will go blank. Clicking it will cause IINA to crash.

<img width="261" alt="截屏2024-10-13 22 36 45" src="https://github.com/user-attachments/assets/9f29ce43-6bc0-48b1-8cfb-083b2618e1fe">

### Expected Behavior

IINA should not crash.

### Actual Behavior

IINA crashed.

### Crash Report

https://pastebin.com/RFed9rFJ

### How often can you reproduce the issue

Always.

### Required actions

- [X] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional actions

- [X] I tested with the Nightly build and confirmed the issue is not fixed.
- [X] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

**Comment by yuxiqian** [comment]
My guess is when preset saving dialog got interrupted [here](https://github.com/iina/iina/blob/50f4aaba099fec1d9c3a16d4b51b64618b45fad0/iina/QuickSettingViewController.swift#L1127C8-L1129C8), the pop-up menu selected state has to be restored manually to avoid accidentally selecting the "Save Preset" menu item. However the `lastUsedProfileName` would be "Custom" in this case, and `findItem(_ name: String, _ tag: Int)` was not able to find it (since the "Custom" menu item is not of `eqUserDefinedProfileMenuItemTag` type.)

**Comment by low-batt** [comment]
Nice writeup. Reproduced for me. Glad you reported this as we are getting close to a beta release.

The crash occurs on this line:
https://github.com/iina/iina/blob/50f4aaba099fec1d9c3a16d4b51b64618b45fad0/iina/QuickSettingViewController.swift#L1164

<details>
<summary><b>Crashing Thread:</b></summary>

```text
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   IINA                          	       0x10055de6c QuickSettingViewController.menuNeedsUpdate(_:) + 2172
1   IINA                          	       0x10055deb4 @objc QuickSettingViewController.menuNeedsUpdate(_:) + 52
2   AppKit                        	       0x188e2b120 -[NSMenu _populateFromDelegateWithEventProvider:] + 352
3   AppKit                        	       0x188e2baec -[NSMenu _populateWithEventProvider:] + 236
4   AppKit                        	       0x1887c55f4 -[NSMenu _populateWithEventRef:] + 96
5   AppKit                        	       0x188e2bd2c -[NSMenu _populateWithFlags:eventRef:] + 200
6   AppKit                        	       0x188fbfd90 -[NSCocoaMenuImpl _send1MenuPopulate] + 128
7   AppKit                        	       0x188fbfcdc __36-[NSCocoaMenuImpl _sendMenuPopulate]_block_invoke + 40
8   AppKit                        	       0x188fbf9a0 -[NSCocoaMenuImpl forEachLinkedMenuDo:includingSelf:] + 176
9   AppKit                        	       0x188fbed90 -[NSCocoaMenuImpl viewWillAppear] + 48
10  AppKit                        	       0x188d8012c -[NSContextMenuImpl viewWillAppear] + 60
11  AppKit                        	       0x188ea1738 -[NSPopupMenuWindow _orderFrontWithParentWindow:screenFrame:] + 320
12  AppKit                        	       0x188ea14c4 -[NSPopupMenuWindow _commonPresentFromView:animated:] + 564
13  AppKit                        	       0x188ea1258 -[NSPopupMenuWindow presentAsPopUpRelativeToView:animated:] + 88
14  AppKit                        	       0x188d7f884 +[NSContextMenuImpl presentPopup:fromView:withContext:animated:] + 500
15  AppKit                        	       0x188fcc188 _NSPopUpMenu + 2128
16  AppKit                        	       0x188fcb864 -[NSCocoaMenuImpl popUpMenu:atLocation:width:view:selectedItemIndexProvider:font:positioningRect:flags:options:] + 432
17  AppKit                        	       0x18892ee08 -[NSPopUpButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 644
18  AppKit                        	       0x188801b54 -[NSControl mouseDown:] + 448
19  AppKit                        	       0x1888009f4 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 3672
20  AppKit                        	       0x18878c2d0 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 384
21  AppKit                        	       0x18878bf80 -[NSWindow(NSEventRouting) sendEvent:] + 284
22  AppKit                        	       0x188f9dc10 -[NSApplication(NSEventRouting) sendEvent:] + 1656
23  AppKit                        	       0x188bacefc -[NSApplication _handleEvent:] + 60
24  AppKit                        	       0x188657ea8 -[NSApplication run] + 520
25  AppKit                        	       0x18862e750 NSApplicationMain + 888
26  IINA                          	       0x1005c6084 main + 12
27  dyld                          	       0x1846bc274 start + 2840
```
</details>

**Comment by uiryuu** [comment]
Thanks for reporting this issue. https://github.com/iina/iina/commit/704484d8a2ddcfd4106157ef518a318706caf26a should fix this, and also fix an additional bug where newly created/renamed custom profile cannot be deleted.
