### ISSUE TITLE
Wrong colors when hardware decoding a 4K DV HDR10

### ISSUE THREAD

**Issue by burgerga** [iina/iina#5236]
### IINA Version

Nightly 9913cf7

### Release Channel

Nightly

### macOS Version

15.0.1

### Steps to Reproduce

1. Start video (with HW decoding on)
2. Observe weird colors
3. Turn off HW decoding
4. Observe better colors (similar to released IINA, which works with and without HW decoding)

https://github.com/user-attachments/assets/0f363e82-b23e-458a-a983-d63a9e415974

### Expected Behavior

1. Start video (with HW decoding on)
2. Observe good colors

### Actual Behavior

1. Start video (with HW decoding on)
2. Observe bad colors

### Logs

[iina.log](https://github.com/user-attachments/files/17548168/iina.log)
[mpv.log](https://github.com/user-attachments/files/17548169/mpv.log)

### Sample Files

Mediainfo
[MediaInfo_penguin_S01E01.json](https://github.com/user-attachments/files/17548156/MediaInfo_penguin_S01E01.json)

I'm on the IINA telegram, if needed I can probable send you a sample

### How often can you reproduce the issue

Always

### Required Actions

- [X] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [X] I tested with the Nightly build and confirmed the issue is not fixed.
- [X] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

**Comment by burgerga** [comment]
Suggestion by @lhc70000 to switch HW decoder from auto-copy to auto solved this.

**Comment by low-batt** [comment]
Reproduced for me. The video attached to [this comment](https://github.com/iina/iina/discussions/5109#discussioncomment-10333123) reproduces the problem. I also reproduced it with mpv 0.39.0. Will be testing with mpv built from `master`.

**Comment by burgerga** [comment]
@low-batt Can you share your mpv arguments? For me mpv 0.39.0 seems to play it fine with hwdec=auto-copy (which results in hwdec=videotoolbox-copy)

**Comment by low-batt** [comment]
If you play a HDR video using mpv without any arguments it does not enable [Extended Dynamic Range](https://developer.apple.com/documentation/metal/hdr_content/displaying_hdr_content_in_a_metal_layer#3335505). HDR videos have a greater range of brightness. The XDR displays on the MacBook Pros with Apple Silicon chips have a peak brightness of 1,600 nits. To make full use of the range of brightness of an XDR display an application must enable EDR.

Using mpv 0.39.0 on your MacBook Pro use these options:
```text
mpv --cocoa-cb-output-csp=bt.2100-pq --target-prim=bt.2020 --target-trc=pq
```

Probably best to run this test while plugged in and without the screen set to maximum brightness. Then repeat the test adding `--hwdec=auto-copy`. Depending upon how much the video uses the full the dynamic range the difference should be noticeable.

I will be writing this up in detail in a report to mpv.

**Comment by low-batt** [comment]
Oops. Got me working too fast. I forgot the `--vo=libmpv`

**Comment by low-batt** [comment]
@burgerga Thank you very much for reporting this problem. As you can see I've entered an issue with mpv. Hopefully we will heard from them soon.

**Comment by burgerga** [comment]
> If you play a HDR video using mpv without any arguments it does not enable [Extended Dynamic Range](https://developer.apple.com/documentation/metal/hdr_content/displaying_hdr_content_in_a_metal_layer#3335505). 
>...

Ah, I was still using `target-colorspace-hint` but that was not enough, results are indeed better with `cocoa-cb-output-csp`. Why not `display-p3-pq` by the way? (I see P3 all over the display settings in Mac, so I'm just wondering)

**Comment by low-batt** [comment]
We obtained a fix from the mpv project. Many thanks to the mpv project for the quick fix! IINA's `libmpv` has been rebuilt with the fix. I tested and the picture with `Hardware decoder` set to `Auto (Copy)` and it now looks the same as with the other settings.

When playing HDR videos encoded with Dolby Vision using mpv the best picture should be seen with `--target-colorspace-hint --vo=gpu-next`. GPU Next has fixes related to color and better support for Dolby Vision. Of course as GPU Next is still considered experimental you may run into problems such as the crash that occurs when you exit mpv when `-target-colorspace-hint` is used.

This set of options `--cocoa-cb-output-csp=bt.2100-pq --target-prim=bt.2020 --target-trc=pq --vo=libmpv` is the closest to matching what IINA is doing when playing the video in [this comment](https://github.com/iina/iina/discussions/5109#discussioncomment-10333123). At this time it is not possible for clients using `libmpv` to use GPU Next.

On why not `display-p3-pq`, the values used are chosen to match up with the color space of the video I was testing with. A different video could very well require different values. The current version of [BT.2100](https://en.wikipedia.org/wiki/Rec._2100) was approved in 2018. [Display P3](https://en.wikipedia.org/wiki/DCI-P3) is an earlier standard.

I'm going to close this issue as the current Nightly builds should be working.

THANK YOU so much for reporting this problem. We were not aware of this regression. You prevented this problem from making it into the upcoming beta release.

**Comment by burgerga** [comment]
Perfect, thanks for your elaborate response, very helpful 👍
