### ISSUE TITLE
Pause/Play Controls for IINA Nightly do not work after updating Nightly build

### ISSUE THREAD

**Issue by LightningRocks** [iina/iina#5264]
### IINA Version

1.3.5

### Release Channel

Nightly

### macOS Version

15.2

### Steps to Reproduce

- Open a video in IINA
- Close IINA
- Upgrade/Change Version of IINA being used from Nightly
- Open IINA and click resume for the video you were playing previously in IINA

Was also able to make this occur when enabling additional MPV options in IINA settings, so it seems to be tied to video playback while changing something in IINA. The issue is fixed as well if you click somewhere else on the progress bar compared to where video playback originally continues from.

### Expected Behavior

IINA pause/play control playback of previously in progress video works normally even between/after updates

### Actual Behavior

IINA pause/play controls during playback of video do not work at all both with keybinds and in player controls upon resuming previously in progress video

### Sample Files

https://drive.google.com/file/d/14NMC3wYzpVcXVxZrtsSLUyvujHgzFT0K/view?usp=sharing

I was able to also replicate this with .mp4 files I had on hand as well with the same results

### How often can you reproduce the issue

Every time

### Required Actions

- [X] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [X] I tested with the Nightly build and confirmed the issue is not fixed.
- [X] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

**Comment by LightningRocks** [comment]
@low-batt The more I think about this, the more I think this is related to the play/pause button regression that you were talking about in my other report

**Comment by low-batt** [comment]
Thanks for creating this issue. It is helpful for tracking.

I definitely encountered this yesterday. I'm struggling to reproduce it today. Been looking at the code and didn't spot anything obvious. I'm going to have to think on this one and take another look tomorrow.
