### ISSUE TITLE
Unable to display Chinese plug-in subtitles

### ISSUE THREAD

**Issue by NoirSe7en** [iina/iina#5265]
### IINA Version

1.3.5

### Release Channel

Release

### macOS Version

15.1 (24B83)

### Steps to Reproduce

- First step...
- Second step...
- ...

### Expected Behavior

Unable to display the external subtitles in Chinese. It used to be able to display it.

### Actual Behavior

Now the Chinese subtitles are all just squares.

### Sample Files

<img width="652" alt="截屏2024-11-13 12 52 13" src="https://github.com/user-attachments/assets/a1942a41-b51c-48b4-8f11-134755128384">

### How often can you reproduce the issue

every time i put in the subtitles

### Required Actions

- [X] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [ ] I tested with the Nightly build and confirmed the issue is not fixed.
- [ ] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

**Comment by low-batt** [comment]
See [this comment](https://github.com/iina/iina/issues/5176#issuecomment-2380401632) on issue #5176. Try using [Font Book](https://support.apple.com/guide/font-book/welcome/mac) to download the PingFang fonts as described in that comment.

**Comment by NoirSe7en** [comment]
Thanks a bunch for your advice. It worked!

**Comment by low-batt** [comment]
Thank you very much for reporting that worked and for closing the issue. Very helpful!

I still have not found any information about why Apple made such a disruptive change and did not mention it in the Sequoia release notes.
