### ISSUE TITLE
Disable subtitile animation

### ISSUE THREAD

**Issue by kmatheussen** [iina/iina#5267]
### IINA Version

1.3.5

### Release Channel

Release

### macOS Version

14.7

### Steps to Reproduce

1. Start Iina
2. Open a movie with subtitiles
3. Subtitiles -> Subtitile -> Select one
4. Play movie
5. When the first subtitile appears, it's animated, the characters pops up quickly one by one when people speek.
6. This might be very good I'm sure it's a good feature in many situation.
7. But not always. When I'm watching a movie I don't want to be distracted animations not related to the movie. An event like this catches my attention, and then my brain pop out of the move world, a distraction. So I don't want sutitiles to be a distraction,  What want is subtitiles to be a crutch in case I am not able to hear the words their speeking, and if that happens I can look at the bottom of the screen for a brief moment to read the word I wasn't able to hear.
8. Currently, I'm destracted all the time because of the subtitle animations, since they are updated character by caracter, and takes away focus from the move, I"m sure everyone's not equal, and that many people won't find this distrcticting, and that's fine. But I'm also pretty sure quite a lot of people find this so distracting that they rather turn the subtitles off.
9. My proposal is an option disable animation of subtitile E.g. just draw the text and be done.

I've tried many video players, and all the programs I havre tried have switched to this animation style of presenting subttitiles, so you're not the only one, buy I would be extremely happy if you could have an option to disable the animation.

(Note: I've only tried one move, so in theory it could be that it;s the subtitile which is doing the animation, and not iina, but for me it looks like it's IIna that's doing the animation.)

Anyway, thanks for a great program. I won't be using your program if you animiate the subutitiles, but apart from that the program is great.

### Expected Behavior

An option to turn off subtitiles animation

### Actual Behavior

No option to turn off subtitiles animation

### How often can you reproduce the issue

Always

### Required Actions

- [X] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [X] I tested with the Nightly build and confirmed the issue is not fixed.
- [X] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

**Comment by kmatheussen** [comment]
Here's a video-example of what I mean. http://users.notam02.no/~kjetism/IMG_0.MOV

**Comment by low-batt** [comment]
I'm feeling sick after watching those animated subtitles.

The animation is not being added by the player. The author of the subtitles has added the animation. Without a video sample that exhibits the problem I can't say if it is possible to suppress the animation. 

Subtitles can be "burned" into the video frame. Players have no control over such subtitles.

To provide the users the ability to show or hide subtitles and allow them to choose from several different languages, subtitles can be included as separate streams in the video file. Or in external files. For such subtitles the player has to render the subtitle into the video frame. Depending upon the [subtitle format](https://en.wikipedia.org/wiki/Subtitles#Subtitle_formats) the player may be able to alter how the subtitles are shown. As can be seen from that Wikipedia table, there are a lot of subtitle formats.

While playing the video, under the `Subtitles` menu, does the `Subtitle` menu item show any subtitle tracks or do you only see `<none>` listed? If no subtitle tracks are listed then the subtitles are a part of the video and can't be altered. IINA subtitle settings will have no effect for such subtitles.

If a subtitle track is listed then under the `Window` menu click on the `Inspector` menu item. The `Inspector` panel appears. Click on the `Tracks` tab. In the `Track` pull down select a subtitle track. The entry for `Codec` should indicate what kind of subtitle format is being used.

If the entry for `Codec` is `ass` as shown here:

![inspector](https://github.com/user-attachments/assets/a64add20-6378-43ac-bdb8-7c5877b72972)

Then try the following:
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Subtitle`
- In the `ASS Subtitles` section click on `Ignore ASS styles`
- Slide the `Override level` slider all the way to the right (`strip`)

See if that stops the subtitles from animating. I'm not sure if that will work or not, but worth a try.

**Comment by kmatheussen** [comment]
Thank you very much. I have to admit that this is a movie, or more specifically a tv-series, I've downloaded illegally, because it's not possible to it view it in my country in other ways (except messing with vpn and maye get a foreign creditcards, etc.). I intend to buy or rent it when it will, but I'm a fan and can't wait. Maybe it'll never be avaiilable, it's been 5 months already).

Anwyay, the codec days "subrip". (Maybe it's an automaticallly created subtitle?) I tried to slide the "override level" all the way to the right anwyay, and enabled "Ignore ASS styles", but it made no difference.

Thanks for your help! I guess there's nothing you can do if this is the subtitile itself that's doing this.

**Comment by kmatheussen** [comment]
It's great that you have keybinding for cycling through subtitiles, so at least I can turn it on only when I need it.

**Comment by kmatheussen** [comment]
(for the record, it's snowpiercer season 4 I'm trying to watch. It's not easy when youre not living in the U.S. :-))

**Comment by low-batt** [comment]
It is common that users can't post video samples due to copyright or privacy issues. Don't worry about not being able to post a sample. We do the best we can to figure out what is going on without being able to reproduce it ourselves.

As you deduced the settings I mentioned above only apply to subtitles in Advanced SubStation Alpha format (ASS). The [SubRip](https://en.wikipedia.org/wiki/Subrip) format is really simple. See that Wikipedia link. To get that to animate they must be outputting a subtitle multiple times in a row, adding characters over a short period of time. Something like that. I have never encountered such a subtitle file.

I suggest trying subtitles files from other authors for this show. You can download subtitles from [Open Subtitles](https://www.opensubtitles.com/en/home) from within IINA. Or open [Snowpiercer subtitles for episodes from season 4](https://www.opensubtitles.com/en/tvshows/2020-snowpiercer/seasons/4) in a browser, download the subtitle file and load it into IINA.

If you have trouble doing that, describe the problem and I will try and help.

**Comment by kmatheussen** [comment]
Thank you again! The support for this program is amazing, and so is the program. It's probably more than 10 or more years since I last downloaded tv series with sub titles, and IINA is for sure much better than the programs I used then. I didn't even think about just downloading subtitiles directly in the program. For episode 6, which I'm at now, opensubtitles had a couple of alternative to the one included with the .mkv-file, but strangely enough those were also animating. However, at assrt.net I finally found a normal subtitle, well, at least if you don't mind chinese subtitles above the english ones. :-) But that's not a big problem.

I also want to emphasize that I am not a cheap bastard, I am willing to pay to watch this tv series, the problem is that it's just not possible to pay for it. :-) But I am going to subscribe to whatever streaming service that is going to provide it in the future.

**Comment by low-batt** [comment]
Glad you found some subtitles that aren't animated. After searching the net I'm getting the impression animating subtitles might be the new "thing". I sure hope it does not catch on.

I found one of the animating subtitles on Open Subtitles. The clip below from the subtitle file shows what these subtitle authors are doing. To a player this just looks like a normal subtitle file that has a lot of subtitles that are displayed for an extremely short time: 
```text
8
00:00:06,839 --> 00:00:06,868
>» W

9
00:00:06,869 --> 00:00:06,898
>» Wil

10
00:00:06,899 --> 00:00:06,938
>» Wilfo

11
00:00:06,939 --> 00:00:06,968
>» Wilford

12
00:00:06,969 --> 00:00:06,998
>» Wilford:

13
00:00:06,999 --> 00:00:07,038
>» Wilford: Th
```

**Comment by kmatheussen** [comment]
Thanks for investigating. Looking at the pattern, it shouldn't be too much work writing a script that removes the animation though.

**Comment by kmatheussen** [comment]
IINA could possibly have an option to automatically remove those kinds of animation. I'll chip in 20$ for a feature like that, maybe others will chip in too.

**Comment by low-batt** [comment]
For audio/video and subtitle rendering IINA is using a library from the [mpv](https://mpv.io/)  project. It is `libmpv` that renders the subtitle into the video frame. IINA never "sees" subtitles that are embedded in the video file. IINA does not open/read external subtitle files, it merely passes them to `libmpv`. From a software engineering perspective, such a feature belongs in mpv.

Hopefully animated subtitles will not become a trend. It if does I'm sure we will start to see a lot of requests for such a feature.
