### ISSUE TITLE
[Question] how to get correct duration of .m3u8 with #EXTINF 

### ISSUE THREAD

**Issue by ErBWs** [iina/iina#5291]
So I'm developing a Flutter app with `media_kit`, a Flutter plugin also based on `mpv`, but with .m3u8 like this:

https://mycj-api.heimuer.app/play/1a2deecf5a764d4ba193c3dbeeb4aa80.m3u8

it cannot get correct duraion on macOS, instead it plays 10 seconds by 10 seconds.

But I found that iina is playing it normally, so I'm wondering if you guys did some work on it?

Huge Thanks!

**Comment by low-batt** [comment]
IINA uses [FFmpeg](https://ffmpeg.org/) to probe the video files for duration information and then adds the durations to get the total duration of the playlist. This code:
https://github.com/iina/iina/blob/3578fedf8ff0422c9281762b17945ae4c1d3b840/iina/FFmpegController.m#L346-L383

**Comment by ErBWs** [comment]
Thanks! This would be helpful
