### ISSUE TITLE
Document which URLs are supported

### ISSUE THREAD

**Issue by MagnusOxlund** [iina/iina#5308]
Currently it's hit and miss whether IINA can open a given URL.

**Comment by MagnusOxlund** [comment]
It would also be helpful to have (visual) feedback while waiting for a URL to load.

**Comment by low-batt** [comment]
IINA is built on top of code from other projects. When it comes to opening URLs the key component is [yt-dlp](https://github.com/yt-dlp/yt-dlp). The sites `yt-dlp` supports is documented [here](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md).

_However_, this:
> Currently it's hit and miss whether IINA can open a given URL.

Is pretty much always true. Web sites can change at any time, breaking compatibility with `yt-dlp`. For this reason `yt-dlp` is frequently updated. It is important to keep `yt-dlp` up to date. The version of `yt-dlp` shipped internally with IINA quickly becomes out of date. The next version of IINA will make it easier to keep `yt-dlp` up to date. On how to configure IINA 1.3.5 to use an external `yt-dlp` executable that you can keep up to date see [this comment](https://github.com/iina/iina/issues/4522#issuecomment-1646167332).

A [throbber](https://en.wikipedia.org/wiki/Throbber) has been added in the development version of IINA to indicate URL loading. This change will be in the next release version of IINA.

**Comment by MagnusOxlund** [comment]
> The sites yt-dlp supports is documented documented [here](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md)

Thank you.
