### ISSUE TITLE
Is it possible to set transparency to pip screen and make the windows under the pip windows clickable.

### ISSUE THREAD

**Issue by AlickH** [iina/iina#561]
请问能够实现为画中画功能设置透明度
并且能够透过画中画点击被遮挡的那部分底部窗口吗？
谢谢 = =

**Comment by lhc70000** [comment]
不能。这是系统的设定。

**Comment by SIDmao** [comment]
悲伤脸 = =
那iiNA主窗口能不能实现以上功能呢

**Comment by lhc70000** [comment]
透明是可以的，点击穿过不清楚。

但这些都不在计划内。如果有很多用户要求，会考虑。

**Comment by SIDmao** [comment]
要是能实现就好了 
小屏幕边看视频教程边跟着操作也能方便一点
谢谢您的回答
祝生活愉快

**Comment by saagarjha** [comment]
@lhc70000 This *might* be possible if we mess around with the PIP window controller APIs–though it would be very prone to breaking.

**Comment by alejx** [comment]
Did any media player on macOS did this? I don't think we are able to make the cursor click stuff that is under the view.

**Comment by saagarjha** [comment]
Well, no video player on macOS that I know of supports PIP :)
Anyways, `NSWindow` provides `ignoresMouseEvents` that should provide what we want; if this doesn't work out we could always try to capture the mouse events and pass them through manually.

**Comment by skynichols** [comment]
There is an app called Helium in the app store which can do transparency but some youtube videos will be unavailable for some reason. It's a great feature and I wish iina had it because its so much of a better player :(
