### ISSUE TITLE
[Feature Request] Add russian(maybe other languages) sites with subtitles for anime, TV shows and movies.

### ISSUE THREAD

**Issue by imKota** [iina/iina#680]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.9

**Expected behavior:**

Please add support for online download of subtitles from [fansubs.ru](http://www.fansubs.ru/) (This is the most popular Russian site with subtitles for anime. Total files: 10375) and [subs.com.ru](http://subs.com.ru/).

At **fansubs.ru** only russian subtitles to the anime. 
On **subs.com.ru** russian, english subtitles to anime, films and serials.

Or for this, I with a friend @mrslain can try to make a site where all these subtitles will be stored. Especially for subtitles requests that will be requested by the player, and given for download.
We can try to make the site not only for russian users, but for everyone.

How do you like the idea?

Thanks!

**Comment by imKota** [comment]
@mrslain What do you say?

**Comment by mrslain** [comment]
@imKota it's a very good idea ;) But I really want to sleep xD
