### ISSUE TITLE
Visual artefacts in playlist and quick settings panels while playing video

### ISSUE THREAD

**Issue by VKondakoff** [iina/iina#723]
There are visual artefacts in both playlist and quick settings panels while playing video. Here is a screenshot: http://take.ms/ReyNO . The artefacts are appearing only when video is playing.

**System and IINA version:**

- macOS 10.13 (17A264c)
- IINA 0.0.11

**Steps to reproduce:**

Just open playlist or quick settings panel while playing video.

**How often does this happen?**

Every time.

**Comment by saagarjha** [comment]
Would you mind telling us the specs of the system is occurring on? In particular, does it have a discrete GPU and was IINA using it?

**Comment by lhc70000** [comment]
@alejx encountered this on his MacBook Pro 15 with Touch Bar (and discrete GPU) on 10.12.4 beta, but never in stable releases.

**Comment by saagarjha** [comment]
If we can reliably reproduce it I'll file a radar; it's probably some issue that hasn't been worked out yet.

**Comment by VKondakoff** [comment]
My system specs: 

iMac (Retina 5K, 27-inch, Late 2014)
4 GHz Intel Core i7
32 ГБ 1600 MHz DDR3
AMD Radeon R9 M295X 4 ГБ

Please, let me know if you need additional info.

I noticed, that I can reproduce the visual artefacts when video is stopped by moving the On Screen controller under the Playlist/Settings panel. Here is a quick video: https://www.dropbox.com/s/42ssqqk2yf8oo6f/iina_visual_artefacts.mov?dl=0
