### ISSUE TITLE
No hardware accelerated decoding for MPEG2 bitstream

### ISSUE THREAD

**Issue by atomicsaiko** [iina/iina#794]
**System and IINA version:**

- Macbook Pro 13 (Late 2017)
- macOS 10.12.5 
- IINA 0.0.11

**Expected behavior:**

Low CPU usage and HW Decoder value set to _VideoToolbox_ (Inspector dialog) when playback MPEG2 TS source.

**Actual behavior:**

MPEG2 TS source is decoded using software instead of hardware. The Intel Core i5-7360U (Intel Iris™ Plus Graphics 640) has support for MPEG2 hardware accelerated decoding. It appears to be not utilized by IINA. Hardware accelerated decoding for H.264 bitstream works in IINA.

**Comment by uiryuu** [comment]
Please reopen if this issue still exists
