### ISSUE TITLE
Thumbnails not work well for black and white films

### ISSUE THREAD

**Issue by swj1442291549** [iina/iina#891]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.12 Build 37

**Expected behavior:**

The thumbnails should display the image of the files

**Actual behavior:**

<img width="1085" alt="touch bar shot 2017-07-20 at 08 50 19" src="https://user-images.githubusercontent.com/14990247/28395738-cb11e276-6d28-11e7-8bb3-03fc9fc70d10.png">

![screen shot 2017-07-20 at 08 50 35](https://user-images.githubusercontent.com/14990247/28395741-d3741880-6d28-11e7-9066-d89fe8464067.png)

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

Every time

**Comment by lhc70000** [comment]
Does clearing thumb cache and reopening the file works?

**Comment by swj1442291549** [comment]
Not working with either methods.

My guess is that algorithm generating thumbnail has some defects on dealing with black and white screen.
