### ISSUE TITLE
[Bug] Double clicking a group of files from Finder does not open all files

### ISSUE THREAD

**Issue by JohnClay** [iina/iina#908]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12 (build 37)

**Expected behavior:**

All of the videos should open separately, or the first is opened and the remainder are added to the playlist (preferably, this would be a user-selectable option).

**Actual behavior:**

Double clicking a group of selected items will result in only the first file opening. 

**Steps to reproduce:**

- Select a number of compatible files in Finder
- Double click said group of files
- Only the first file will be opened

**How often does this happen?**

100% of the time

**Comment by JohnClay** [comment]
It looks like as of 0.0.13, the remaining video files are added to a playlist. It would be ideal if this was user-selectable, as open files in separate windows/tabs is the expected behaviour when opening a group of files. However, adding them to a playlist is arguably more functional.

**Comment by lhc70000** [comment]
Indeed. @alejx Could you add such an option?

**Comment by uiryuu** [comment]
This feature has already been implemented in IINA
