### ISSUE TITLE
Title bar not fading away properly if 'reduce transparency' enabled

### ISSUE THREAD

**Issue by ATiGr** [iina/iina#938]
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12

**Expected behavior:**
the title bar should fade away smoothly.

**Actual behavior:**
If 'reduce transparency' in 'System Preferences - Accessibility - Display' is enabled, the title bar would flicker before completely disappear. (which is very annoying, especially when IINA excels at visual elements)

**How often does this happen?**
every time when you move away your cursor and the title bar tries to fade away.

**Comment by uiryuu** [comment]
I couldn't reproduce this issue. If the issue still exists for you, please reopen this issue and add more info about your system.
