### ISSUE TITLE
crashed when playing

### ISSUE THREAD

**Issue by KawhiZhuuu** [iina/iina#949]
The player crashed several times in playing.It crashed in the same position.
![qq20170809-113246 2x](https://user-images.githubusercontent.com/16774273/29104273-193f1c92-7cf7-11e7-8bbd-f75bd66384d3.jpg)
![qq20170809-113259 2x](https://user-images.githubusercontent.com/16774273/29104282-1eb05ab0-7cf7-11e7-8d89-f45ecbfcb09a.jpg)
![qq20170809-113746 2x](https://user-images.githubusercontent.com/16774273/29104294-3091258e-7cf7-11e7-8879-223aae8879bc.jpg)

**Comment by saagarjha** [comment]
Could you let the application crash and attach a crash log? What were you doing to trigger this?

**Comment by ZSwitch** [comment]
@saagarjha  I ran it in Xcode.There were no crash log but the stack.I watched movies when it crashed.I did not change movie and its progress.
