### ISSUE TITLE
welcome window doesn't save the position where it was opened last time

### ISSUE THREAD

**Issue by ghost** [iina/iina#991]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
When I center the window (e.g. witch Magnet) I want to have it centred when I close iina and open it up again 

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
every time

**Comment by lhc70000** [comment]
It'll be fixed in next version.
